[quote.epigraph, , Prov. 4:18]
____
The path of the just is as the shining light,
that shines more and more unto the perfect day.
____

== Preface.^
footnote:[Note by the Editors of the original _Friends Library:_
A few passages in the following Diary,
chiefly written during Mary Capper`'s visit to France, before she became a Friend,
and which appeared irrelevant to the object of the publication, have been omitted,
and several original letters addressed to correspondents in America,
have been added to this edition.]

The journals and other papers of Mary Capper,
were entrusted by herself to the care and revision of the editor,
with the understanding that any use might be made of them which, after her decease,
should appear to be right.
The present compilation is, in consequence, now offered to the public,
with the hope that the cause of truth and righteousness--that cause which
was so dear to the subject of this memoir through a long life,
may be served thereby.

The character of Mary Capper is pretty fully developed in the subsequent pages;
yet it may be allowed to the editor,
who had the privilege of near intimacy with her for almost half a century, to remark,
that in preparing this work for the press,
and consequently dwelling much on the life and conduct of this devotedly pious individual,
she has been particularly impressed with the cheerful contentment of spirit,
manifested under the varying circumstances of her life.
This is the more striking, when the feebleness of her bodily powers,
the enlarged liberality of her mind, and her deep feeling for human sorrows,
are taken into account,
together with her limited pecuniary resources and small personal accommodations.
It is true, she was often entrusted with the means of relieving those in distress,
which was to her a source of genuine delight;
but she steadfastly refused repeated offers of increased comforts for herself;
preferring to dwell in comparative obscurity,
and in the close vicinity of those dear friends whose
society and kindness had largely contributed,
for a long course of years, to her enjoyment.
Another object which she had in view was, to be so situated as to occasion,
to such friends as might be passing through the town,
little inconvenience in paying her a visit;
for such was her modest estimate of her own attainments,
that she could not suppose her friends would incline, or could suitably be expected,
to come far to make her a call.

Many, however, as will be seen in the following pages,
could bear their testimony to the solid satisfaction which such visits afforded them;
and this undoubtedly proceeded from the conviction,
that the chief pursuit of Mary Capper`'s life had been to honour her Lord and Master;
by this she gave the strongest proof of her gratitude for the love of God,
extended to her in Jesus Christ her Saviour;
whose peace was richly shed abroad in her heart,
and more especially so as she approached his heavenly kingdom,
where all is peace and love, and joy in the Holy Spirit, and that forever!

[.signed-section-signature]
Katharine Backhouse.

[.signed-section-context-close]
Darlington, 1847.
