== Chapter I.

Parentage, education, etc.

Mary Capper was born on the 11th of the fourth month, 1755.
She was the daughter of William and Rebecca Capper, of Rugeley, in Staffordshire.
They had a very numerous family, consisting of ten sons and four daughters;
some of whom lived to advanced age.

John, their first-born, was a merchant in London, where he died in 1835,
after completing his eighty-eighth year; James also died the same year in that city,
at the age of eighty-one; having been, during fifty years.
Rector of Wilmington, Sussex.

The whole family were brought up by their parents as members of the Episcopal Church,
to which they themselves were conscientiously attached.

Mary, the subject of the following Memoir, possessed a mind of no ordinary description;
energetic and contemplative, she seemed peculiarly prepared,
as Divine Grace was allowed to operate upon her gifted mind,
to throw aside the prejudices of education, and to stem the torrent of opposing opinion.

Her susceptible heart was, however, keenly alive to the sorrows of others,
and deep were her sufferings, when, for a time,
her religious views broke the harmony of the domestic circle;
but having taken up the cross of Christ,
she was mercifully enabled to follow her Lord in simple obedience,
and in full reliance upon his power to preserve and strengthen her through every trial.

Much of the account of her childhood was penned after
she had attained the age of eighty years;
and a more lively description cannot be given to the reader than in her own words.

* * *

My dear parents, +++[+++she writes,]
accustomed their children to read the Scriptures.
The religious instruction of my childhood was, I think, received from my dear mother.
She was a deeply tried Christian mother.

I think it was about my tenth year that I was sent to my aunt Langford,
at Macclesfield in Cheshire.
She was a serious member of the National Establishment, a very respectable,
widowed gentlewoman.
Under her kind care, I was instructed in the strict observance of religious forms;
to remember the text of every sermon that I heard; to write the Collects,
etc. but I do not recollect much serious impression being made on my mind.
About this time, there was a great talk about Methodism; our relations, the Rows,
of Macclesfield,^
footnote:[One of these was Hester Ann Rogers,
of whom an instructive little memoir is published.--Ed.]
were said to have turned Methodist, and were lightly spoken of and ridiculed.
I well remember that I felt sorry for this; because I thought, if they were good people,
and only differed from others in the way that they thought was right,
they ought to be loved.

I was allowed to go, with my young companions,
to the theatre and various other places of amusement;
and I do not recollect that any remark was made,
upon time being thus squandered and mis-spent.

On my return home, some domestic changes had taken place; my second brother, Samuel,
was settled in business at Birmingham; and as he was still young,
it was considered best for my father to be much with him;
so that my dear mother was frequently left with my eldest brother, John,
and the younger children, at Rugely.
Nursing and needlework were my proper employments, but I was fond of active play;
out-doing my companions at ball, jumping, sliding, etc.

+++[+++The following extracts from a diary kept by Mary Capper, about this period,
show the manner in which her time was chiefly occupied,
and the unfoldings of her youthful mind.]

9th. My friend K. Barbor drank tea with me.
How delightful and improving is the company of a good and worthy friend!
I think I have read that friendship is too noble a passion for female minds; but why so?
Have we not souls as well as men?
and as capable of the worthiest attainments!

15th. My brother prevailed upon mamma to stay till tomorrow.
I am grieved at the thoughts of leaving the country,
just now that everything is in perfection, to go and bury one`'s self in Birmingham,
where one does not feel a refreshing breeze, nor see a green leaf,
except a few nasty withered things in the church yard, once in the year.
I have not patience to think of it! but parents must be obeyed.

8th. Went to Church; we were very fortunate, as we got there before it was much crowded;
when we were confirmed.
I walked in a very grave and serious humour.

+++[+++Respecting this circumstance, she subsequently remarks:]
At a suitable age, with great seriousness, and heart contriting impressions,
I went through the ceremony of confirmation by the Bishop;
a ceremony of no small import in my view;
as what had been promised for me by my sponsors, I was,
in accordance with this outward rite, bound to perform,
as then of age to take the responsibility myself; namely, to deny all pomp and vanity;
to walk in God`'s holy will and commandments all the days of my life.
Knowing that I came very short of this, I was distressed, and mourned much in secret.
I was afraid to mention my feelings, as they seemed strange,
and I did not know of anyone who had the like.

14th. Mamma told me of a fault in my behaviour,
a repetition of which I will endeavour to avoid.

November 10th. Received a very polite invitation
from M. Capper to spend a few days at Castle Bromwich.

14th. Arrived there.

19th. I do not know the meaning of it,
but I never in my life wished more sincerely to be at home.
I shall be heartily glad when I get into Bull Street.

23rd. Set out for home with a joyful heart.
My father received a sensible and dutiful letter from brother Jasper.
O! how my father`'s eye glistened with true paternal tenderness!
That we may all unite, and strive to give joy to the hearts of our worthy parents,
is and shall be, my constant prayer.`"

+++[+++The following letter was addressed to Mary Capper by her mother,
when left on one occasion as housekeeper at Birmingham:]

April 17th, 1769.

My Dear Molly,

You are a good girl for writing, agreeable to promise, every week; pray continue to do so.
I observed what you said about the riding-dress; but, my dear child,
consider you are one of number twelve; therefore,
no superfluities can or ought to be expected.

I was much pleased with one of your letters, wherein you say,
'`I have been strongly solicited to go out this evening,
but have withstood the temptation.`' O! my dear girl,
may you have grace to withstand every temptation to evil, or imprudent things;
and that you may be able to say, '`Get you behind me, Satan! for I am resolved already;
and my Jesus, who vanquished you upon the cross, will assist my weakness,
and enable me to overcome your temptations!`' Assist and enable us He will,
whenever we call sincerely upon Him; and I doubt not, my dear child,
you have already experienced a pleasing satisfaction
whenever you have denied yourself any amusement,
though innocent, if it interfered with what was right and necessary to be done.

Your mother,

Rebecca Capper.

+++[+++In adverting to these days, Mary Capper writes]
"`I was, at times, and many times, in early life,
very thoughtful as to the genuine effect of religion on the mind.
My constitution was weak, which I have considered one among other favours;
for my nature was volatile, and I was much left as to outward restraints; and, indeed,
urged to go to public amusements, plays, dances, etc. which were considered innocent.
The first contrary impression that I distinctly remember was once, while on my knees,
at my accustomed evening prayers; my thoughts being confused and dissipated,
I lay down comfortless,
believing that whatever distracted and hindered prayer must be wrong.
This impression rested with me; and from time to time,
led to deep reflection and secret conflict.
The witness for truth left me not; and as little sacrifices,
such as declining gay parties, seemed to yield a peaceful calm,
I was favoured with resolution to persevere.
I wept over my dear mother`'s letter,
though she knew not all the temptations I was subjected to.
One occasion, I think I cannot forget,
because it is sealed by mercy and by experience to this day; though the thing was,
in itself, comparatively little, and I was then young.
Being tempted to take some fruit, in a garden where I was unobserved,
and being on the point of gathering it, a sudden check arrested me.
I cannot distinctly describe it,
but I walked from the spot with a sweetness of inward peace, indescribable,
such as I think I had never before known; and it arose in my heart,
and has remained in my understanding, this is the teaching of the grace of God; or,
in other words, of the Holy Spirit!
This, we had been taught to believe, would enable us to overcome evil;
but it is not sufficiently understood; and when gently developed in the still,
small voice, it is frequently not obeyed;
and the quick sense of its secret monitions becomes less discernible.

External objects, and the too general example of Christian professors,
entangle and allure the mind; the doctrine of the Cross of Christ,
or the self-denial thereby taught, is rarely brought into view; or possibly,
little understood, farther than as regards strictly moral conduct,
and a due observance of religious institutes.
This I write, not uncharitably, nor by way of censure.
I was favoured with a sense of good, under such restraints as these,
before I underwent the ceremony of confirmation; and for several years after this,
during many little fluctuations in the domestic arrangements, I continued serious,
and given to retirement.
O! how would the enemy of all good, sometimes come in like a flood,
and almost terrify me with evil thoughts and suggestions.
It would be vain to attempt setting forth the hidden striving
of nature with the light which manifests the evil,
separating the precious from the vile.
I was not obstinately rebellious, though my temper was naturally hasty and impatient.
On some occasions, my brother James was a gentle reprover, and was in example, kind.
In after years, he became my advocate, as a Christian brother;
for he believed me sincere, though his religious views were not in accordance with mine.

My brother John married and settled at Rugeley,
after which event the rest of the family went to reside at Birmingham with our parents.

+++[+++This brings us to a new era in the domestic circle,
to which Mary Capper makes some allusion in mentioning the
change which afterwards took place in her religious views;
and as this change of view and practice first became obvious in her brother Jasper,
a few particulars relating to him may here be acceptable to the reader, and useful,
as a connecting link in the history of Mary Capper.

He was about four years older than she was, and tenderly attached to her.
When quite young,
he was sensible of the quickening influence of the Holy Spirit visiting his soul,
and it became his practice reverently to read a portion of the
Holy Scriptures before he left his room "`in a morning.
On these occasions he frequently sat for a time in silence, in order to wait upon Him,
who, he felt persuaded, alone could open the sacred writings to his understanding.
While a young man,
he accompanied his brother James (who was about to take orders as a clergyman) to London;
and during their stay there, they called upon Mary Knowles,
who was an acquaintance of the family.^
footnote:[As there is frequent mention made of this individual in the narrative,
it may not be irrelevant to remark,
that she was eminent for her great intellectual powers,
and tor her taste and skill in painting and in needlework:
in which arts she excelled in her imitations of nature.
Her conversational powers were so great, and so peculiarly fascinating,
that her company was much sought, and she was thereby induced to mix unprofitably,
with many worldly-minded persons, to her own great loss.
She outlived her husband many years, and attained to advanced age.
As she drew near the close of life, she was, through mercy, permitted a long illness,
during which she was made to feel the burden of sin,
and to lament over her misspent time and mis-applied talents;
and there is reason to hope that the cry of her penitent spirit was heard,
and that she was made a partaker of the salvation which is in Christ.]
On being informed of James`'s prospects,
she gave them a description of the qualifications which
she deemed essential to a true minister of the gospel.
This address, while it produced little effect upon the mind of James,
sank deeply into that of Jasper, and he was, in consequence,
induced to go to a Friends`' meeting.
Farther reflection,
enquiry and conviction were the means of attracting
him very closely to this religious society;
but he had much suffering to pass through, in various ways,
before he became a member of it.

His parents,
who appear scarcely to have considered the Society of Friends to be Christians,
from partaking in an ignorance of their principles which was then very prevalent, were,
of course, much opposed to his being united to such a body;
and his father treated him with a severity which
was cause of great sorrow to his affectionate heart;
yet he was enabled to continue firm in what he saw to be required of him.
He obtained some employment in London, where he was kindly noticed by a few Friends,
and the house of John Fry, in Whitechapel, was always open to him.

One day, while he was in much distress, on account of his father`'s objecting to assist,
or even to see him, he went to J. Fry`'s and found several Friends assembled;
among whom was Barbara Drewry, who was engaged in religious testimony.
He quietly took his seat near the door of the room; when,
without knowing anything of his situation, she addressed him very remarkably;
expressing her apprehension that he was under great
conflict respecting some requiring of duty;
and her full belief that, if he became obedient to the will of the Lord therein,
though he might be called upon to give up all that was most dear to him,
and every prospect of outward advantage, yet the Lord would abundantly recompense him,
and would ultimately bless him, not only with spiritual, but with temporal increase.
This proved to him like a brook by the way,
and contributed to strengthen his resolution to make
a surrender of his all to Divine disposal.
Being fully convinced of the necessity of a truly religious life,
he soon became sensible of a sincere desire for the best welfare of his dear connections,
and he ventured to write to his sister Mary,
endeavouring to awaken in her mind a serious concern for her eternal salvation.
This letter, however, failed in producing the effect designed,
and he received from his sister an answer which was very unsatisfactory to him;
the following is extracted from his reply to it.]

To Mary Capper, Birmingham.

London, 28th September, 1776.

Dear Sister,--It is not my intention to enter into a religious controversy,
or to persuade you or anyone (for I have not myself been persuaded) into errors of judgment;
if, as you say, I have blindly and enthusiastically fallen into them;
but on the contrary,
would gladly acknowledge my weakness and be thankful to be set right.
I desire to ask you this question By what standard did you examine my letter?
Not by the doctrine of our Saviour and his apostles I am convinced,
or you could not have accused me of enthusiasm; for, as I understand the word,
enthusiasm is a mistaken zeal; but,
where zeal is directed by truths handed down to us for our direction,
it cannot be too fervent.
Our misfortune is, we cannot always maintain such a zeal.
If you call it a fit, because it is a frame of mind which I am likely to fall from,
I agree to it; but this is owing to my own weakness,
and for lack of steadfast faith and trust in Him who would support me;
but to prove that I was, at the time of writing to you, under proper impressions,
could I constantly maintain them,
they would not only warm my heart with a continual
sense of the gratitude due to my Redeemer,
but render it impossible for me to do anyone an injury, or fall into the least sin.
Ought then these impressions to be stifled?
or ought we not rather to press after them?

If I remember right, I addressed myself to your heart before,
but you have answered me in haste,
and I am sensible never asked your poor heart one question about it;
but in the strength of your own reason you have confided,
and I will endeavour to prove that you have trusted to a broken reed;
therefore answer me a question; and if your heart does not give it the negative,
then ask yourself, if you do not deny your Redeemer, by making the Gospel of none effect.
Did your heart assent to this assertion in your letter?
that you '`look upon a sincere,
humble and uniform adherence to the rules of moral duties as the substance
of our faith and doctrine.`' Surely not! for this excludes Christianity;
as it is possible to be a strict moralist without one grain of true religion;
for many of the Heathens were so, and even Atheists may be so.

Our blessed Saviour himself condemned the Scribes and Pharisees, who were strictly moral;
they carried themselves uprightly as to their moral characters,
and were looked upon by the world as the best of men; they fasted twice in the week,
and were not (as one of them said) extortioners, unjust,
etc. and they gave tithes of all that they possessed; yet what does the Lord,
who knew their hearts, call them?
Hypocrites, who prayed to God with their lips, but whose hearts were far from Him!
How is it frequently with us?
are not you and I like unto them?

If I have advanced anything in my letter which is unscriptural, point it out to me;
if not, how is it enthusiasm?

If we believe that we '`must one day give an account for every idle word;`' and that,
'`whether we eat or drink, or whatsoever we do,
we must do all for the glory of God,`' (which we must believe,
or deny our professed faith,) can we watch too narrowly over ourselves?
or endeavour, too carefully,
to avoid what may tend in the least to alienate our
affections from the things which are above?

'`To enjoy is to obey.`' Was our Saviour sent upon earth as a pattern for us?
Did He enjoy the good things of this life in the manner you speak of?
We are told to use the things of this life so as not to abuse them,
but never to rejoice in them, that I remember.
When the Apostles were beaten, and departed from the presence of the council rejoicing,
was it enjoying the good things of this life?
No! it was rejoicing in the Lord; and I believe, that to enjoy his presence,
we must obey his leadings.
Read the first chapter of John, and tell me what you can make of it without this belief.
In the Epistle to the Corinthians, the ministers of God are spoken of '`as sorrowful,
yet always rejoicing.`' Were not these, think you,
called by those who did not listen to them, a morose set of fellows?
Yet, were they not enjoying and obeying?
Thus it is with almost all religious people.

I shall not wish for quite so sudden an answer as to my last, but one more to the matter,
and honestly produced by serious judgment;
a little farther from the surface than your other.
My intention was, not to accuse nor to dictate,
but to warn you with a desire to enquire after these things.

In true brotherly love, being sensible of my own errors, from a very sinful neglect.

Your true friend and affectionate brother,

Jasper Capper.

+++[+++No remark is preserved respecting the effect of this letter on Mary Capper`'s mind,
but it appears to have induced her to reflect very seriously upon her own condition,
and to make some enquiry into the faith and practice of
the Society to which her brother had become so much attached.
She was, at that time, in very delicate health,
and her parents resolved (probably under the influence
of various motives) to place her in a family in France,
for a time.

On this account she was brought into new and trying circumstances;
and it is thought that extracts from her journal at that time,
will not be without interest in many ways; especially to those in early life,
who will see that she possessed a very lively imagination and warm feelings; and who may,
by the perusal,
be the better prepared to appreciate the sacrifices which she had afterwards to make,
in order to obtain peace of mind, and to become the humble disciple of a crucified Lord.]
