== Chapter II.

Sojourn in France.

Birmingham, October 19th, 1776.

Very busy making preparations to set out for London, in the Diligence, tomorrow morning,
with M. and M. Bingham; the latter purposing to accompany me to Paris,
or some other part of France, where I am going for the recovery of my health,
which has been upon the decline for some months.

London, 21st,--Just arrived at the Castle and Falcon; much fatigued,
having travelled all night without sleep.
We arrived at Stratford at ten o`'clock,
and there met with several of Bingham`'s friends, who were at the inn;
we supped together, after which we resumed our journey with fresh spirits;
indeed we then stood in need of our best courage, for it was very dark and the roads bad;
this, with the fears we had of being robbed, was dismal enough.
Just as morning began to dawn we reached Oxford;
the daylight advanced with all the beautiful attendants of a fine morn,
and it was most delightfully pleasant.
Breakfasted at Tetsworth; and heartily rejoiced we were, for we were really hungry,
I bore the journey better than I could have imagined;
after paying proper attention to the bread and butter, we once again set forward;
it was a glorious day, and the country appeared beautiful,
in spite of the rigorous season.
Immediately on my arrival at my journey`'s end, I wrote to my brother Jasper,
and he came half an hour after, I fainted several times, which is not surprising,
as I was much fatigued.

22nd, Was taken to bed last night very ill.
My affectionate brother, who had never seen me in that way before, was quite alarmed,
and sent for Dr, Knowles, I have slept tolerably.
Walked with my brother and my friend Bingham, into Cheapside.
Dined with my uncle Smallwood, and spent a rational, agreeable evening with Dr,
and M. Knowles, at their house in Ingram Court, I admire the doctor more, I think,
than any man I ever met with.
He strikes me as a man of learning and affability; polite without ceremony;
perfectly good humoured without the least tincture of levity; charitable to all,
in thought, word and deed.
It is easy to imagine that no one could possess all these qualities without being,
in the true sense of the word, a Christian.
Though the doctor is, by profession, a Quaker,
he is far from endeavouring to influence the judgment of others.
We had much serious conversation,
and my heart felt interested in every word that fell from the mouth of the worthy doctor,
I wish, if my stay in town permits, frequently to repeat these visits,
I do not wonder at my dear Jasper being impatient to introduce me into such company,
as he knew my inclinations too well to suppose that I should find it irksome.
I wish I could prevail upon all my acquaintance to
lay aside all their trivial ways of killing time,
by playing at cards and such diversions; and in their room to institute improving,
rational conversation; it would undoubtedly be better for society in general;
we should then enjoy ourselves in reality.
How far more praiseworthy those are who spend their time in searching
after and admiring the wonderful power and goodness of the Almighty,
than such as think of little but the gratification of the senses;
who scarcely know or consider how or wherefore this grand universe is supported,
or whether governed by a Supreme, All-powerful Being!

Nancy Fry, a very pleasing young person, drank tea with us;
I was struck with her appearance and wish to be better acquainted.

The doctor does not approve of my intention of going into a Convent,
as he thinks I shall be in great danger of having
my sentiments as to religion totally changed;
he remarked that the transition from our form of
worship to that of the Romish Church was very trifling,
and might possibly be brought about, almost imperceptibly,
as they spare no pains to gain a proselyte.

This has quite unsettled my designs,
as I would by no means throw myself into the midst of dangers,
the nature of which I am entirely unacquainted with.
We took our leave of these worthy Friends, with a promise willingly made on my part,
to dine with them on Friday, if nothing prevent.

23rd, My brother Jasper called and took us to dine with my brother William,
who lives at Holborn Bridge, He appears to be a sensible worthy character.
After we had coffee we called a coach,
intending to go and spend the evening with my uncle Capper, in Berkeley Square;
but an unaccountable whim entering the head of my brother William, (prompted,
I make no doubt,
by his wish to give us pleasure,) he asked if we
should have any objection to see the Opera,
to be performed that night, I was inclined to refuse;
but fancying that my friend had a desire to go, I accompanied her without reluctance.
My disappointment and disgust are not to be described;
I had heard much of the shining qualities of +++[+++the actress,]
and therefore expected something extraordinary; but of all the figures I ever saw,
she is the most miserable; and her impudence is inconceivable.
In the midst of my chagrin,
I could not help feeling emotions of pity for the poor unhappy wretch, who,
in her serious moments, must call to mind a life spent in such a manner;
how melancholy a retrospect!
I may truly say, my intended pleasure was turned into actual pain,
I was very ill afterwards.

24th, My brother Jasper called upon me;
he was not pleased at my last night`'s expedition;
in truth I was vexed at myself I could not help making a comparison between the
different feelings with which I retired to rest last evening and the night before;
one all hurry and confusion, without one rational idea; the other calm,
serene and pleasing; with a train of ideas, delightful, quiet and composed.
I very joyfully performed my promise of spending the day in Ingram Court,
and it was as agreeable as I expected.
The doctor was at home all the afternoon, and we had much serious conversation,
in which my heart was interested,
the doctor and his wife explained the benefit arising from silent meetings,
which I am convinced must be very great; we are then freed from all external objects,
and wait upon the Lord, in silent submission;
which must doubtless be a far more acceptable sacrifice than those forms
of prayer that are repeated by the lips when the spirit is far from God.
This silent meditation is certainty an excellent preparation for vocal prayer.

25th. Nancy Fry called, and went with us to M. Williamson`'s,
a person who keeps bees in a glass hive;
it is very entertaining to see these industrious little
creatures all busied in their various occupations.

26th. Went, with my brother Jasper, to the Quakers`' meeting,
and was exceedingly pleased with one of the female preachers.
There was silence nearly an hour and a half,
in which time I was prepared to receive instruction,
and I felt the force of what I heard.
Returned to our lodgings well satisfied with silent worship.

27th. Dined and spent a very agreeable day with Nancy Fry`'s parents in Whitechapel.
I admire the whole family exceedingly;
such marks of sincerity and friendly civility I scarcely ever received.
I shall actually venerate this society of people;
for among those that I am acquainted with,
there reigns such a universal spirit of affection, with a real desire to please,
that I cannot help being strongly attached to those
sentiments which are productive of these social delights;
to me far more engaging than the pompous parade that attends the proudly great.

29th. M. Bingham and my brother went with us to the Tower,
in order to look at the vessel in which we propose embarking;
the Captain is an elderly polite man;
he informed us that his daughter would accompany us to Boulogne,
where his family resides.
He could not say when he should sail; as there are Press Warrants out,
a Protection is necessary, or it is possible that all the men may be taken.
On expressing our desire to see the curiosities in the Tower,
our obliging conductors willingly complied;
and being informed that there were no beasts worth seeing, the old lion,
etc. being gone to the shades of their noble ancestors, we visited the Arsenal.
I was much pleased with the regular form in which all the arms are placed.
Could the mind be divested of the idea of destruction,
for which these weapons are designed, it would be possible to behold,
with pleasing astonishment, the perfection which has been arrived at in the manufacture.
On our return we had some conversation with two young girls
who had just come from the Ursuline Convent at Boulogne,
and were not discouraged by their account.
About five o`'clock I took leave of my friend,
as I had accepted of M. Morris`'s invitation to spend a few days with her at Tottenham.
She received me with that good nature and affability which characterise her.
I cannot but spend my time agreeably here, as in the company of M. Knowles and M. Morris,
it is impossible to be otherwise than happy.
Very poorly and retired to rest early; Mary Booth, an agreeable girl, was my companion.^
footnote:[Mary Booth was afterwards the wife of John Fell.]

31st. Poorly all day.
M+++.+++ Knowles was so obliging as to read in the life of William Penn, an eminent Quaker,
who suffered much from persecution,
being imprisoned and cruelly treated on account of his religious views and practices.
He bore all with fortitude; supported by the true spirit of Christianity,
he overcame all difficulties.

November 4th. In tolerable health and spirits; have fainted but twice since Saturday.
We had company to dinner--Friends, a new married couple!
The more I see of these people, the more I admire them;
they receive each other with such marks of sincere love and friendship,
that my heart partakes in their apparent satisfaction.
Spent the afternoon in serious conversation.

5th. Read part of the life of George Fox, and found myself interested in his sentiments,
which appear to me noble and full of weight.
I quit these kind friends tomorrow.

8th. We embarked on board the "`Four Friends,`" Captain Merriton,
accompanied by my brother Jasper.
Our fellow passengers appear tolerably agreeable.

11th. After a very tedious passage, landed at Boulogne,
surrounded by a number of strange creatures;
but my attention was fixed upon two delicate figures, dressed most fantastically,
'`far beneath that creature man,
who is so proud of being rational!`' Their coats were blue and purple,
and their hats covered with various coloured feathers; a delicate tincture of rouge,
and an enormously large muff completed the whole.
A polite Englishman stepped from amid the throng,
and we willingly permitted him to conduct us to the '`Ville de Londres,`' a poor,
dirty inn compared with English houses.
After dinner we walked in the town.
I admire the dress of the tradespeople, which has an air of decent simplicity,
but what appeared the most diverting and extraordinary, was that all men and women,
rich and poor, had each a muff;
it was very droll to see a miserable creature in rags and wooden clogs,
with a large muff.

12th. Between eight and nine o`'clock, we were surprised by the entrance of an old dame,
pale and meagre as an inhabitant of the grave, attended by two or three young girls.
After our astonishment had a little subsided, and they were seated,
we took the liberty of enquiring from what cause
proceeded the honour of this early visit;
which, in reality, gave us no satisfaction, as we were not dressed,
having only left our beds a few minutes before.
They, however, made no apology for throwing us into such consternation,
but informed us that they were come for two young ladies,
who came over with the intention of entering the Convent.
Poor Nicholls and Powell did not seem over pleased
with the appearance of their future companions;
however they agreed to wait upon them after dinner;
upon which they rose and took their leave.

A little after four o`'clock, we attended our fellow travellers to the Ursuline Convent,
and delivered them into the hands of six nuns, who were dressed perfectly neat and plain.
We were informed that the Pensioners rise at five o`'clock, all the year.
To breakfast is not the custom of the country; but at ten o`'clock, they dine upon soup,
with a morsel of coarse beef boiled to strings.
This is served in a manner by no means elegant.
After this frugal repast, they are occupied in studies till five o`'clock.
Their supper is roasted meat; with a salad, when the season permits.
The hour of rest is seven.
These particulars did not give my friend and me any strong desire to join them;
and what weighs, still more with us is,
that we should be under the necessity of submitting to all their customs and superstitions.
They have mostly fifteen prayers each day,
which would be a burden to those who do not imagine
that they shall be heard for their much speaking.
Returned to our Auberge, and gave up all thoughts of entering a Convent.

14th. Called on our friends in their prison, as it may justly be termed;
we were only allowed to speak to them through an iron grate;
poor Powell appeared dissatisfied with her situation,
though she was obliged to put on her best looks, and to say that she liked it very well,
as the governess who was with them understands English.
We returned to the inn by the ramparts, which command an extensive view of the sea,
and of distant hills, woods and villages.
I observed a large crucifix, placed on an eminence in the middle of the town,
and was informed that the people, on certain days, flock in great numbers,
to offer their prayers before this figure.
Surely this is a zealous blindness, which raises compassion in a thinking mind!

15th. M. Thomas conducted us to one of the best looking houses in Boulogne,
situated near the ramparts in the High Town.
We were introduced into a pretty parlour; and after a few minutes,
M+++.+++ Brunet made her appearance.
I was much pleased with her, and we soon fixed upon terms.

21st. Most tempestuous weather; many of the poor are great sufferers from the high winds,
some of their habitations being laid level with the earth;
indeed they are not calculated to stand against a storm,
being made of nothing but a sort of clay and sticks;
the lower sort of people live miserably in this country.
They are in general very idle, and consequently very poor;
and their religion rather encourages their natural antipathy to labour.

22nd. Fridays and Saturdays we have no flesh meat,
which they pretend is a mortification of the body; but for my own part,
I cannot consider it any merit to abstain from meat,
when the whole art of cookery is exerted to prepare fish, roots,
etc. in the nicest manner.

23rd. The whole family at Mass;
as the road to their place of worship is too bad for the coach,
my friend and I have not the opportunity of going with them.
I know not whether I ought to regret this,
for I should possibly be under the necessity of submitting to their ceremonies;
at the same time I feel a longing desire to join in the assemblies of the faithful.
From an idea of politeness, the family desisted from cards;
but what was more disagreeable to us, as it prevented our retiring,
an optic glass was produced, in order, as they said,
to amuse us without wounding our consciences; but they know not our real sentiments.

26th. A great feast; the family at Mass.
We walked out, but were glad to return, as it was insupportably cold;
we found an excellent fire in our chamber, at which we enjoyed ourselves till dinner.
M+++.+++ Brunet gave us some books to read,
telling us she should think it a favour if we would
conform to their custom of not working on their holidays.
This is disagreeable, as they are numerous,
and I cannot find that laziness promotes godliness.

27th. Rose very unwell.
Bingham is exceedingly kind and attentive;
and nothing can exceed the tender affection of my dear brother Jasper.
I think I can never be ungrateful to my indulgent friends.

December 3rd. Company to dinner; never was I so tired!
I hope it is not customary to give many dinnerings; if it is,
I must provide myself with a large stock of patience.
I really seem to pick like a sparrow among eating creatures; four hours at table,
eating all the time!
The dinner I thought extravagantly profuse;
served in three courses of nine or ten dishes each; and afterwards an elegant dessert;
then coffee, and to conclude, a glass of liquor.
There were four priests present,
and all the company ate and drank as if they thought
that was the chief end for which they are born.

6th. The morning alone in my chamber.
Experienced a calm satisfaction which I would not exchange for all the world can give.

14th. M. Dupont informs us that there is a great talk of war; in short,
I think we hear of little else than wars and rumours of wars.
I know not when they will follow the advice of the apostles,
and beat their swords into plough shares, etc.

17th. Called at the Convent.
My brother purposes setting out for London tomorrow.

19th. Took a tender and affectionate leave of my dear brother.

27th. When the card table appeared, retired to my chamber.

January 5th, 1777.
A deep snow.
My health has been so poor for some time past, that I am reduced to a very weak state;
but I think, if the happiness of my friends were not as dear to me as my own,
I should be far from regretting my present indisposition,
as it inclines my mind to a serious consideration
of those things that are necessary to salvation;
a consideration which I might have neglected, had I been in perfect health.

6th. What they call a jovial day! that is noisy mirth,
in which I found neither wit nor amusement, and therefore slipped out of the room.
During the month before Lent, they have no meagre days.

15th. Began the day, as usual, with our studies.
After dinner, spent two hours at our toilet, and four hours in visiting;
a pretty account this, to give of the manner of spending our time.
I am actually discontented with myself;
as so many hours employed to no purpose give me no satisfaction.

February 2nd. Went to Vespers for the first time.
I was very near the door, and could not see all the ceremonies,
but I saw enough to excite surprise.
'`My God,`' thought I, '`that such a number of persons, seemingly disposed to serve You,
should imagine that You are pleased with the burning of incense,
and the lifting up of hands!`' The sacrifice of a
humble spirit is far more acceptable to our God,
who designs that we should worship Him in spirit.
But, in answer to all the objections you make to their numerous forms and ceremonies,
they tell you that they were instituted by Moses, and commanded by God.

7th. Received a very serious letter; I must own, I think rather too serious; that is,
there is in it a kind of melancholy that I cannot make agree with my ideas of religion;
which, in my opinion, one should be careful to exhibit as both simple and pleasing.

10th. Company to dinner!
I do detest these dinnerings;
one loses more time than it is possible for any reasonable person to imagine.
It is really a melancholy consideration that so many beings,
with faculties sufficient to render them useful and happy,
should content themselves with eating, drinking and playing.
I hope these feastings will soon cease,
as I should suppose they pass Lent in a more serious and moderate manner.
I shall rejoice heartily when we return to the peaceful Herdinghen;
for the more I see of the world, the more I am enchanted with solitude,
and its lovely train of innocent amusements,
that prompt the mind to gratitude and contemplation.
Charles received a letter from Jasper containing excellent advice.

Am very undetermined about attending a large party to the play and a masked ball.
Had I only my inclination to consult, I should not hesitate a moment in refusing;
but my refusal is considered as a stubborn resolution to be singular;
this is a character that I am by no means desirous of, and many ideas rush into my mind,
to vindicate a compliance with the wishes of others; but on the other hand, I am,
from experience, convinced that these noisy diversions intoxicate the mind, enfeeble it,
and render it incapable of performing the duties for which we were born.
I presume not to judge for others; but for myself,
I find it necessary to guard against the tumultuous joys of the world.
Nine`' o`'clock.
Not at the ball, which is satisfactory, though the cause gives me pain,
as it is the illness of M. Brunet.

16th. Received a pleasing epistle from M. Knowles,
containing a few serious directions on the most important object of our lives.
My heart melts with the earnestness of my desires to become
one of those few that labour after the perfection of holiness.

20th. We are quite pleased with the progress we have made in learning the language,
etc. since M. has kept her room.
I am not sorry that Lent has begun, as there are no balls, etc.
They are not very strict in this family, as they eat meal once or twice a week; in short,
I think it is but a farce their pretending to fast; for though they do not eat flesh,
they feast upon delicate fish, swimming in butter, etc.
This, in reality, I prefer to their days of Gras;
and although they scruple to eat a morsel of meat,
they do not scruple to give way to their anger.

26th. Walked round the ramparts; the Castle is an ancient pile of building,
now made use of as a prison.
Two or three rooms, which look upon the ramparts,
are particularly reserved for the confinement of young gentlemen who are extravagant,
or any way disobedient to their parents.
Every father or mother has power to shut up their
children for any time they may think proper;
for life, if it is thought their crimes deserve it.

March 1st. Received an invitation from an English family, to a ball and concert.
Bingham, etc. went, but I was not well enough.
Employed the time in reading Thomas a Kempis,
and felt more satisfaction than I should have done in their splendid assembly.

11th. Was exceedingly shocked to hear of the death
of the young lady whose wedding we saw,
not many weeks since; she was taken ill on thursday, and died this morning,
leaving a distressed husband and mother.
Who, that has any consideration,
would be so anxious after the happiness which is so uncertain!
These daily instances of the instability of earthly joys
should certainly warn us against a reliance upon them.
What a melancholy change in this family! the other day, all gay,
and flattering themselves with the prospect of many succeeding years!
Happy is the mind whose dependence is not upon the fluctuating joys of this world,
who can contemplate all with the eye of a passenger that is seeking rest in another!

April 7th. A great feast-day.
At Vespers, could not be so attentive to myself as I wished,
for there were a number of ceremonies which I could not help observing.
It is strange to me that so many absurdities should
be considered an acceptable sacrifice to the Lord.
I think the priest does little but change his clothes;
but I must say that the whole congregation seem to attend with seriousness;
much more so than the protestants;
and I doubt not the sincere in heart reap the benefit arising from true devotion.

10th. A most delightful day!
We walked in the wood, and fixed upon a romantic spot, to build a grotto in.
Heard of the death of a near neighbour, who dined with us soon after our arrival.
I think it is remarkable that,
out of the families with whom we have dined since we came to this part,
three of the principals are dead.

16th. St. Omers is delightfully situated, and the streets long and spacious.
Went to the college where my brother Charles and Brunet are.
Le Frere Auventin attended us to`' the noble structure of St. Bertin`'s Abbey.
There are a number of very fine paintings,
which I examined while M. Brunet and the Frere repeated their prayers;
this they are obliged to do when they enter the church,
as they consider it a spot sacred to the Lord; but in my opinion,
all places are alike to our God, who dwells not in temples made with hands,
but takes up his abode in the hearts of the meek and humble.
Round the chapel are hung the arms of the Monks,
as they are all descended from grand and ancient families; they have large fortunes,
which they give up, and have all things in common,
forsaking the allurements of the world.
They at least pretend to lead a life of mortification; fasting and praying continually;
but how far they may be inwardly detached from the
follies of life is best known to themselves.

Christ and his disciples never excluded themselves from the eye of the world;
and I should imagine it is not the design of our Creator that each individual
should live to himself After having expressed our thanks to the polite Monks,
we departed.

26th. St. Mark.
A grand feast!
I think these people do little else than feast; we went with M. to Mass;
a long and tedious ceremony.
I believe they consider the bishop as a being of a superior order;
he walks to the church, surrounded by almost all the village, who join in singing psalms, etc.
A canopy of crimson, fringed with gold, is supported by four old men; and under this,
the great man sits or walks, in state.
They say he is a man exemplary for his piety, charity, etc.
I hope that all proceeds from the right spring.
Education may so far have influenced his mind,
that the forms and ceremonies may to him appear necessary;
but I must acknowledge that I beheld them with an emotion which I cannot describe.
The bishop wears a large ring upon his little finger, which the priest kneels to kiss;
the servants kneel when they present water to wash his hands.
I was so much affected by these strange, and as I thought, presumptuous ceremonies,
that I could not restrain my tears and how earnestly did I wish
that all the world were acquainted with that gentle tranquillity
which results from a humble waiting upon the Lord!

29th. I could not but make the secret comparison between these thoughtless people,
who meet for no better purpose than to idle away their time,
and those friends whom I have left in England.
I daily wish to be again among them;
it would then be my own fault if an hour passed unimproved.

May 4th. Passed the morning alone.
I pity those who are unacquainted with the sweet
consolations resulting from serious meditation;
and with that peace which the world cannot give nor take away.

28th. Boulogne.
Arrived in the afternoon.
Dressed and sallied forth to spend the evening at an English lady`'s;
when we arrived all the party were at cards, to which we also sat down.
While we played,
a circumstance occurred which made me feel in a way that I cannot describe.
The sacrament which is carried to the sick,
and is always announced by the ringing of a hand-bell, passed by the windows.
The company, being mostly French, threw down their cards,
knelt and prayed for a few minutes, and then set to cards again.
I mean not to censure them; they may act up to their judgment and feelings,
but I must confess it would appear to me very presumptuous
to address the great Almighty in a form of words,
at a time when the mind was interested in affairs so trifling,
so inconsistent with that awful sense with which we ought to present ourselves,
when disposed to offer prayer.

On our return I found a very affectionate epistle from my honoured mother;
all friends well, and kindly anxious for my health.

7th. After dinner, the conversation turned on religion; they were very severe upon me,
and rallied me unmercifully, giving me the appellation of Quaker or Trembler.
Nothing could be more unjust than their censures of this people,
whom they conclude to be unworthy of the name of Christian.
I heard all with silent patience.
After having listened for some time,
I declared myself quite in favour of the real principles of Quakerism; and retired,
leaving them to make what comments they pleased.

July 8th. Dined at Marquise; never spent a more disagreeable day;
the gentlemen drank a great deal, and in consequence were very noisy and troublesome.
I was truly glad when the coach was ordered, but we were no sooner seated in it,
than we perceived that our coachman had made as free with the bottle as his master,
and we were obliged to get out and march back, about half a mile to Marquise,
where we again arrived at the Cure`'s. To our great
satisfaction we found the company dispersed;
beds were ordered, and we soon retired;
but my spirits were so agitated by the scenes had witnessed,
that I fainted several times.
I wished myself in some secluded spot, where I might never more be in company with those,
who so shamefully abuse the reason they are blessed with.
I am certain that, if others enjoyed these extravagancies no more than I do,
they would soon be excluded, as destroyers of our peace.
Those recreations which will not bear reflection, are ill suited to rational,
intelligent creatures.
A train of such ideas kept me awake most of the night.
Arrived at Herdinghen the 9th.

August 3rd. Spent a few quiet hours in my own room.
Walked into the country, where we partook of a frugal repast, at a farm-house;
sitting upon hay, with a plank for our table.
The clouds were remarkably beautiful,
and I was disposed to enjoy the calm contemplation
which the surrounding objects seemed to invite.

4th. In the evening Felicite and I took our book to the garden,
and seated ourselves under a clump of trees; we stayed nearly two hours,
and enjoyed a pleasing calm; all nature glowing around us.
I could not but regret the folly which leads men to search for happiness in crowds,
and in pompous parade, when real satisfaction may be purchased at so cheap a rate.
As a flower unfolds in the genial warmth of the sun,
the mind expands in serious meditation and reflection.

9th. Dined at M. Routier`'s with three Anglois.
I was not satisfied with our amusements;
they were of a nature too gay and noisy to contribute to the real delight
of the mind which desires something more than momentary enjoyment.

22nd. Felicite and I took a ride to the Bois de Boulogne, about four miles off;
it is a delightful spot.
We sat under the tress, and enjoyed the tranquillity of the scene.
The disposition of my friend seems formed to enter into my tastes.

28th. Received letters from my kind parents;
they are anxious and unhappy at my indisposition.

29th. The palpitation at my heart returned with great violence.
The physician assures me that it is only the effect
of the weak state to which I am reduced,
I pass the nights almost without sleep, and have very little appetite,
therefore I cannot, at present, expect to regain my strength.
I hope I am not impatient under these bodily afflictions;
they are light in comparison with a wounded spirit.
I have that trust and confidence in my God which makes his will my delight.
Though he afflict me, yet will I trust in Him; and while his grace supports me, I can,
as it were, forget the present pain,
and look joyfully forward to that glory which shall be revealed to those who persevere.

September 1st. A comfortable day, without pain or sickness.
Walked out and enjoyed the air, though winter begins to creep upon us,
and as Thompson finely expresses it, '`lets loose his northern blasts.`'

2nd. Much indisposed, but as it proved a delightful afternoon,
my friend and I went in the cabriolet, to the Bois de Boulogne,
and reposed under the spreading branches of a fine old tree.
As we generally take our books on these excursions,
reading and conversation have their turn, and we enjoy many pleasing moments,
untasted by those who are engaged in a continual round of more expensive luxuries.
How greatly are we mistaken when we consider riches as the only happiness!
The truly pious mind exults in well-grounded hope,
and steadfastly fixes the eye of faith beyond the present scene.

4th. Again visited the wood, and returned about sunset,
which afforded us many delightful views.
They brought to my mind those beautiful lines beginning, '`These are your glorious works,
Parent of good!`' It is impossible to contemplate the wonders of nature
without feeling the heart glow with gratitude to the great Author,
whose goodness is but dimly seen in these his works.

16th. Spent the morning chiefly in my own room; the extreme gaiety does not suit me.
I feel like a stranger indeed!
I have no inclination to familiarize myself with this mode of life; it may do for others,
but give me sobriety, with a mind disposed for reflection.
A letter just received from my dear Jasper,
informs me that he has some thoughts of coming here.
I shall greatly rejoice to see him.
I cannot but observe how ill-informed we English females find ourselves,
in comparison with the French ladies;
they appear perfectly acquainted with the rise and
progress of all material events in the history,
both of their own and other nations.
This is certainly a part of education not merely ornamental,
which might well be substituted for more trivial acquisitions.

17th. I walked to the grotto, and found it improved in beauty,
as the moss has taken root, and flourishes in all its various colours.
Boulogne; evening.
I can scarcely believe that I am now writing in the chamber of my friend Felicite!
At dinner time an arrival was announced; I ran out of the room,
and had the satisfaction of embracing the most affectionate of brothers;
I readily agreed to return here with him, as fresh company had arrived.

+++[+++It will here be needful to break off from the journal for a time,
in order to take a glance at the state of things in the family at home.
It appears that the decided attachment of her brother Jasper
to the principles and practice of the Society of Friends,
had awakened many fears in the minds of his parents,
who were much alarmed for the consequences of his influence among their numerous children;
especially as they could not but see that Mary was
strongly attracted to unite with the views of Friends.
A letter, written about this time by Rebecca Capper, to her son William,
will depict her feelings, in this trying exigency,
so as to excite the sympathy of every susceptible mind.
It may be premised that William never made much, if any,
change in his religious observances,
and always remained a member of the Episcopal Church.

Birmingham, September 18th, 1777.

My Dear William,

A complaint in my eyes still remains;
but I am induced to run the hazard of hurting my sight,
to say a few words respecting a letter which your
brother Samuel put into my hand last night.
Your dear father (for he is indeed dear to me) has not seen your letter,
nor if I can help it, ever shall; for the blow which your brother Jasper has given him,
has almost struck him to the ground,
and I am apprehensive that he could not support another such.
As to my own feelings, I forbear to mention them; for I know,
and am fully persuaded that, grievous as they are,
they ought not to be held in any estimation against that which teaches,
'`He that loves father or mother more than me is
not worthy of me;`' and if it has been your lot,
my child! (for so I will yet call you) to be born
of parents that were ignorant and ungodly;
that neither by precept nor example taught you to serve God in spirit and in truth;
but on the contrary, that it was enough to honour Him with the lips,
though the heart was far from Him--but stop, and examine, O! my soul, do you not,
in this, stand self-accused?
I have indeed been guilty of great neglect of my duty,
in that state in life in which it pleased God to place me!
in caring too much for the things of this world,
and in neglecting myself, and also in not instructing my children,
to seek after the kingdom of God and his righteousness;
not remembering that all these things would be added unto us.
But sinful and wretched as I am, well knowing, that as his justice,
so his mercy is great; and that, upon sincere repentance and amendment, which,
through his grace or Holy Spirit, that He has promised to those who ask for it aright,
and without which we cannot do the least good thing--I say, by this I hope,
and will endeavour, to live better, for the short, perhaps very short,
time I have to remain here.

Now in the midst of this grievous and very heavy affliction,
that we your parents are at this time under,
on account of the separation which is already made in the family,
and more that are likely to be made; I say, in this I can see a ray of comfort,
and can draw this from it; that the Almighty Disposer of all things has permitted,
for wise and good ends, this his afflicting hand to be laid upon us;
that He chastens and corrects those whom He loves and would draw unto Him;
that it has already inclined my heart more unto Him,
and has caused me to look more strictly into my way and manner of life,
and has raised in me a hope that, by his divine and inspiring grace,
I shall be enabled to bring forth good fruits;
to avoid those things which are contrary to no profession,
and to follow all such things as are agreeable to it.
Now this I knew before to be my bounden duty; but we are such poor frail creatures,
(at least I find myself such) as to stand in need of frequent stirring up;
and it may be one among the various and mysterious ways of Providence,
that He permits so many different sects and opinions; as I make no doubt all believe,
at least, that they are guided by the same divine grace of Holy Spirit,
faith and Holy Scriptures.

You say you are inclined to attend the meetings of
Quakers by stronger motives than compliance to Jasper;
that you find yourself enriched by the plain truths they deliver;
that you are charmed with the love, sweetness,
and tenderness of affection which appear among them.
Oh! my child, you see not beyond the mask, nor why it is occasionally put on;
but to gain three proselytes all at once is a great
acquisition!--But stay! where am I running?
or where is my Christian charity, if they think they are in the right way?
A crowd of ideas press upon my mind, but I will only beg one favour of you;
it will perhaps be the last I shall ever ask of you; it is this; that you will,
for a few Sundays, go to the Church of which you have been a member,
(though perhaps an unworthy one) and set your mind in a right frame of devotion,
remembering that you are, at that time, as well as at all others,
immediately in the presence of that God who knows the secrets of all hearts;
and though He regards not time nor place,
yet reflect and consider for what purpose you are come there; and as much as lies in you,
suppress all vain and wandering thoughts;
keep your eyes from looking on the faces of others; and do not,
from their look and manner, judge of what passes in their hearts,
but be careful of your own; and with fervent zeal and humility, attend to those prayers,
praises, and adorations, there offered to the throne of Grace;
and though they may be uttered by a man of like infirmities with yourself,
yet let not that hinder you from sincerely seeking for the assistance of God`'s Spirit,
to enable you to do that which is right in his sight;
and as I am sure you will find what will suit your own feelings; in them join,
with sincerity of heart; for though God knows our necessities before we ask,
yet has it pleased Him to command that we, his poor creatures,
should lay our needs before Him; and if at all times and in all places,
why not when we are gathered together?

I have reason to believe my dear Mary`'s health is but very indifferent at this time,
and that her old complaints return with greater force than ever.
I firmly believe that the agitation of mind she has laboured under of late,
has greatly increased her bodily infirmity.

I think it likely that she and I may never be permitted to meet again in this world;
but though by different roads, my sincere hope is,
that we shall all meet again in the next.
I had promised to myself some pleasure in coming up to London to meet your sister there,
and with joy to bring her home, but I fear that is over; her home cannot be with us,
her parents; for well I know that would be the cause of strife and debate,
which I think it is best to avoid; and if we must be separated,
may that Being who first gave you all to me,
enable me with patient resignation to part with you in whatever
way He shall think fit! but I find myself a poor frail creature,
and do indeed, at this moment fear and tremble before Him.

I had much more on my mind to say to you, but I have lost it; so conclude,
with sincere prayer for your present and eternal welfare, your truly affectionate mother,

Rebecca Capper.

From this letter and from some subsequent remarks in Mary Capper`'s journal,
it appears that she entered pretty fully into her brother`'s change of religious view,
and that this had been so far made known to her parents
as to make them hesitate about allowing her to return home.
She deeply felt her trying position, and she also sympathised tenderly with her brother,
who was, at that time, much distressed in mind.
He seems to have been sent, to convey her back to England, without loss of time.
While they were detained before sailing,
they were in the practice of frequently retiring together,
for the purpose of silently waiting upon the Lord, that they might know his will,
and experience a renewal of their spiritual strength;
and they were often comforted together, on these occasions.

Resuming the journal, Mary Capper proceeds:]

September 18th. My kind friend expresses much satisfaction at my quick return.
I really feel greatly at the thought of leaving her, it may be forever!
Her tenderness and amiable disposition have gained my admiration and my warm affection,
and have greatly interested me in her future well-doing.

19th. Much in my friend`'s room, either reading or preparing for my departure.

20th, My brother and Felicite accompanied me to the Bois de Boulogne,
and we passed an hour very pleasantly under the shade of the fine trees,
not in the least regretting the parties at Herdinghen.
Mere sensual delights are very unsatisfactory to a mind,
capable of tasting the pleasures which result from contemplating the wonders
and the goodness of Him who created and preserves this universal frame.
All nature speaks forth his praise;
and shall not his intelligent creatures admire and extol his infinite wisdom and excellence!

21st. My brother and I declined going to Mass; we passed the time very agreeably;
and I experienced true satisfaction in silence.

25th. My brother and I rode out in the cabriolet;
he made me acquainted with some circumstances, relative to himself,
that are very far from giving me pleasure;
however I must not allow myself to be cast down, but be firm in hope,
trust and confidence.

October 12th. My brother and I sat together.

13th. We have not determined when to go, but I hope soon,
as the family are in a confusion of gaiety,
which seems not to allow a moment for serious reflection.
My brother and I are considered stupid mortals, for we cannot join in the vacant laugh,
noisy song, etc.

18th. It is with difficulty that I keep up an appearance of cheerfulness,
for my spirits are uncommonly affected.
The thought of leaving my friends here, and of seeing those in England,
causes an agitation which I can scarcely endure.

22nd. On board the same vessel which brought us to this place!
I have left the arms of a tender, affectionate friend,
and the tears still steal down my cheeks.

25th. Arrived safely in London last night, after a tedious voyage.
We were both very ill.

This morning we landed from a small boat,
and drove to my uncle Smallwood`'s. I had scarcely sufficient
strength left to embrace the tenderest of mothers!
