== Chapter III.

[.chapter-synopsis]
* Return home in 1777, and memoranda during her slay there
* Removal to Wilmington, and journal while there in 1781 and 1782

+++[+++The return of Mary Capper to the paternal dwelling,
was the occasion of much trial and difficulty both
to herself and to her affectionate parents.
She thus writes, respecting this interesting period of her life:]

[.small-break]
'''

It was after my return from France that an obvious change took place in my manners, etc.,
so as to attract observation.
The ceremonies of the church, when I attended with my parents and the family,
affected me in a very unusual manner; I do not know that I can say painfully,
but with a desire to act more conformably with what was preached.
Sometimes I wept, and sometimes had to be taken out, nearly fainting;
but could not describe my sensations.
I had then no intention of making any change in my religious profession;
but my dear mother`'s disappointment was keen, when, in process of time,
I felt that I could not conform to what I had been taught was necessary to salvation;
and kept much retired, without attending any place of worship.

[.small-break]
'''

+++[+++About the end of the year 1777, her brother Jasper joined the Society of Friends,
and in 1778, he married Anne Fry, the daughter of John Fry, of Whitechapel.
In regard to these important changes,
his mother remarked that if the thing were of the Lord, it would stand; if of man,
it would come to naught.

Mary Capper appears to have made very few memoranda during her stay at home;
but the few which have been preserved, and which are here presented,
give proof of the continued seriousness of her mind, and of her desire,
under a complication of difficulties and disadvantages,
to follow on to know the Lord for herself.]

[.small-break]
'''

September 8th, 1779.
If men are born merely to live, or rather breathe, a few short years,
and then fall to nothing; if virtue is only a name,
or a habit acquired by certain modes of education, why have we a secret,
unconquerable knowledge of right and wrong?
If it be possible to believe that annihilation takes place,
after this span of pain and sorrow, we are of all creatures the most deplorable.
Brutes have capacities to desire and enjoy, but man has a reasonable soul,
which is not to be satisfied with sensual gratifications.
How vain! how weak is the human heart!
Can a reflecting mind be ignorant of its own instability?
Can the maxims of the most learned sophistry fortify us against
the alluring poison of those temptations which surround us?
Can speculation, or gratified passions, produce those calm, happy effects,
which result from a firm dependence on a superior Power,
who will reward our humble faith, or assuredly punish our arrogant pride?
How amiable is the humble mind, which trusts not in its own strength,
which is not above acknowledging its own weakness,
and glories only in its hope and confidence in the living God!

March 12th, 1780.
The Lord is my rock and my fortress, and my deliverer; my God, my strength,
in whom I will trust; my buckler and the horn of my salvation, and my high tower!`"
O! who is like unto our God!

What am I, O! Lord, what am I, that you should so wonderfully extend your love towards me!
Of myself I am worse than nothing; all weakness and contradiction!
One moment, fervent in desire; the next,
cold and languid in the performance of the least of your commands.
O! woe is me; who shall deliver me from this body of treachery!
The Lord himself!
The mighty Lord who is my strength, and my help in the time of need.
He will graciously dart a ray of divine light into my soul;
then shall I plainly perceive that He is the ancient of days, that was and is,
and is to come; the sure Rock of defence to all that trust in Him.

How comfortable are the dawnings of divine grace!
How encouraging are your promises, my God!
Let me rest in your truth!
Give me sure confidence in your mercy!
Permit me not to dwell in darkness!
O! turn not your wrath upon her who is insufficient to bear your displeasure!
Let me not put any confidence in my own strength; for, Lord! you know my impotence;
the secret thoughts of my heart are not hidden from you!
How shall I stand if you leave me to my own guidance! but you are wonderful in goodness,
and I will trust in your mercy.
I have tasted of your lovingkindness, and my soul aspires to the fruition of joy,
at your right hand forever.
Amen.

[.small-break]
'''

+++[+++Soon after making these memorandums, and while in a state of much conflict of mind,
Mary Capper was consigned by her parents to the care of her brother James.
Concerning this event she thus writes:]

[.small-break]
'''

I went to Wilmington, in Sussex,
my dear brother James being married and fixed as Rector there.
His wife, who was a Biddulph, was an interesting, intelligent, pious Christian,
who had her own peculiar scruples of conscience on various subjects;
and very tender was my dear brother of her feelings on these points;
so that the removal into his family was some relief to me.
He affectionately enquired into my religious views, and sympathized in my distress.

I had sometimes secretly attended Friends`' meetings, at Birmingham,
in which I remember experiencing much brokenness of spirit;
but while with my kind brother, I attended his little church.
The private, as well as the more public devotion to which I was witness,
wrought much consideration and deep inward thoughtfulness;
especially as respected participating in what is termed the sacrament,
or the Lord`'s supper, as it came in usual course to be administered by my brother.
It had been, on former occasions,
a solemn ceremony of peculiar comfort to my longing soul;
and I had much conflict and prayer that I might be satisfied
whether the outward and visible sign was important to salvation.
With reverence, deep humility and fear, I received the bread and wine.
I do not recollect that any observation was made on my being evidently agitated.
I sought no human counsel, but the satisfactory, abiding instruction on my own mind was,
that the inward and spiritual grace, of which this was only the visible sign,
must be something of a higher nature, not dependent upon uncertain means.
The best of teachers was pleased to calm and quiet my mind on this important subject,
and I no more repeated the ceremony;
but these convictions and changes were no light matters to me.

[.offset]
+++[+++Upon leaving home for Wilmington, Mary Capper resumed her journal,
from which the following extracts are given:]

November 9th, 1781.
Having passed a sleepless night I rose early, to go by the London coach;
the morning was glorious, and the rising sun presented a beautiful autumnal prospect.

10th. When we reached the Castle and Falcon, London,
I was rejoiced to meet my brother John, who conducted me to Gracechurch street,
where my brother Jasper lives.
He and Nancy expressed their satisfaction on seeing me, in terms the most affectionate,
and my heart beat responses.
I was surprised and pleased to meet with M. Nicholls, whom I had known at Boulogne.
I enjoyed a comfortable evening,
and was relieved from all sense of fatigue by the kindness of my partial,
indulgent friends.

11th. A seat being engaged for me in the Lewes coach, to set out early in the morning,
it was judged best for me to sleep at the Adelphi Hotel,
my brother William accompanying me as protector.

12th. I was lucky in my company in the coach; a resident in Lewes,
from whom I received every possible civility during the journey,
and upon our arrival obligingly introduced me to his sister, a polite, genteel woman,
to whose friendly attention I am greatly indebted.
Being much in need of rest, I was prevailed on to accept a bed there.

13th. Rose comfortably refreshed, and after a good breakfast,
and making the best acknowledgments I could, for my entertainment,
I set out for Wilmington.
I greatly admire the country;
the views of the fine hills diffuse a calm which induces sweet contemplation,
and leads the mind to the Grand Source from which flows every pleasant stream.
The beautiful valleys are a delightful contrast, and attract particular admiration.

14th. In the night the wind was very high; I like the awful sound,
and find it pleasing music, A fine, calm morning.
This place is delightful; the hills are beautiful, even now;
covered with the finest verdure, and appear towering almost to the clouds.
The north aspect commands a most extensive view; part of Kent, the wilds of Sussex, etc.
My father looks remarkably well and cheerful.
We enjoyed a comfortable fireside in the evening; my brother reading to us.

15th. The weather astonishingly fine and warm.
Assisted to finish some necessary work; am always pleased when I am considered of any use.
Tasted the sweets of an hour`'s retirement; then joined the fireside,
and enjoyed the pleasures of friendly interaction with a mind at liberty, glad,
and confident in the living God.

21st. My father talks of leaving us tomorrow; we shall be sorry to part with him,
and his employments turn greatly to advantage;
the shady walk will be much improved by his labours.

22nd. The day fine, though cold.
Rose early; my father set off between nine and ten o`'clock;
my brother accompanied him as far as Lewes.
The original manuscript has the following note affixed to this sentence:
"`This was the last time I ever saw my dear father!`"

25th. A fine mild morning; travelled in idea with my father;
admired with gratitude the beautiful scenes of nature.

27th. Mild and clear as summer; the sun shone on the tops of the hills,
casting a dark shade on the valleys below; the scene was picturesque,
and I enjoyed it with the calm satisfaction of a grateful heart.
Rode with my brother to East Bourne.
I was charmed with the country;
riding on the Downs is pleasing beyond all that I could imagine; the air is, even now,
quite fragrant with wild thyme, etc.
We had an extensive prospect of rich pasturage,
with small villages romantically situated; and a fine view of the sea.

December 4th. Read French; in my closet, read Boyle.
With a thankful spirit, I have confidence in the living God;
my soul rests in his promises, and shall be satisfied.
With hope and confidence I will wait the appointed time.
Be steadfast, O! my soul, for the Lord regards the sincerity of your desires;
weak in yourself, be strong in faith, and fear not!

February 1st, 1782.
Mounted Windore Hill with my brother,
I had no idea of the beautiful view which the hill affords;
nor could I have imagined that deep snow and cold winds had such charms.
Never let us complain that winter robs the plains of their beauty;
each season is fraught with instruction and delight.

28th. Had a charming walk before breakfast; the sun shone gloriously,
and almost every spray was vocal with the song of joyous birds.
Is it possible that the midnight dance, or tiresome frolic,
should exhilarate the spirits,
or afford the sweet calm satisfaction which arises from the contemplation of nature!
Surely no!
My soul now expands and breathes in silence for the
only state fitted to enjoy perfect beauty!

March 2nd. Walked near two hours before breakfast.

10th. Rose at seven; walked till nine.
Went to church.
Whom have I in heaven, but You, O! God;
and there is none upon earth I would desire in comparison of You!

19th. Bear patiently the infirmities of others; you have much to be borne with of others!

27th. Retired with my mind disquieted.
How many and various are the conflicts with busy
passions! folly and vanity rise up daily,
and gain strength from our too feeble resistance.
My King, and my God! to you I cry for strength.
Humbled by a sense of my weakness, to whom can I apply but to the Fountain of Grace!
Still I have faith in his bounty.
My soul waits for the living God; and when He shall have purified me by his Spirit,
all shall be peace and joy!
Let none trust in their own strength, but let all praise and extol the Lord.

April 1st. In pain most of the day, but was thankful for a calm fortitude of mind,
that disposed me to submit with patience.
In the day of trouble I will trust in the Lord my God.
Had I the eloquence of angels, I would exhort all nations to trust in the living God.
Though he correct, he will never forsake the faithful.

8th. Rose before seven; it was quite an effort,
but I should be sorry to fall into my former custom,
of losing in sleep many hours which I find, by experience,
may be used with pleasure and advantage.

21st. Employed in preparing for my brother`'s going to Cambridge;
he thinks of being absent a month; we shall think it a long time.
In the evening I retired to my closet,
where I indulged the sweet satisfaction of contemplation;
the beauties of nature presented themselves in an extensive view,
and nature`'s God was the object of my grateful praise.

23rd. Walked to Falkington with my brother.
Had a letter from my friend Felicite Dupont.
Tomorrow we purpose going to Lewes.

27th. My stay at Lewes was longer than I expected,
and I feel pleased to return to my favourite scenes.
Lewes, though a pretty town, is not in my estimation, comparable with Wilmington.
The fashionable modes and ceremonies of the polite circles, give not the pure,
simple delights arising from the study of nature; in the former pursuits,
the mind seems carried from itself, and wanders in confused trifles; on the other hand,
the glowing beauties of nature irresistibly lead to the great Almighty Power,
whose wisdom and goodness are inexhaustible.

May 11th. Enjoyed my closet in the evening.
It is wonderful that so few seem to be acquainted with the value of quiet.

18th. My brother returned;
our mutual satisfaction at meeting is easier imagined than described.

21st. Spent some time in my closet.
It will not be long before the final end of all created things shall come.
Watch therefore! be steadfast in prayer, always abounding in the work of the Lord.

29th. Unwell, and my spirits depressed.
I earnestly wish to be patient, but I fail daily; yet will I call upon my God,
my strength and my only hope.

9th. My mother received a letter from my brother William,
with an account of his being fixed in a new situation.
In the evening we walked up the hill; the weather was fine, and the sky beautiful,
yet was my mind in a disposition not to be pleased.
In vain do I search for the cause which frequently indisposes my whole frame,
and gladly would I lay aside every unamiable propensity.
Our happiness would be too great, should no internal difficulties arise.
Perfect serenity and peace of mind are foretastes of future bliss,
only permitted at seasons, to encourage our hope and strengthen our faith.
Trials are necessary, that by faith and patience,
we may obtain the prize of our high calling.

[.small-break]
'''

+++[+++Although Mary Capper does not seem to have been
fully aware of the cause of her frequent depression,
during her mother`'s stay at Wilmington,
it appears probable that no small part of it might be occasioned by the
knowledge that her parents disapproved of the change of religious profession
and practice which her brother Jasper had made,
and to which her own convictions powerfully attracted her.
Her father however made affectionate mention of Jasper in writing to William,
as appears by the following extract of a letter to him:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, September 9th, 1782.

[.salutation]
My Dear William,

I cannot say but John`'s letter gave me some pangs for your disappointment,
though I think you judged right in rejecting the offer at Norwich.
Though a suspicious temper is a disgrace to human nature, yet as the world goes,
it is prudent to be circumspect.
It gives me pleasure that your undertaking is with the approbation of all your friends;
it was sure to have mine, if likely to be for your good.
You may depend on your mother rendering you every service in her power,
with the utmost pleasure.
Jasper may be of service to you,
and it gives me pleasure to find you speak so kindly of his brotherly love, etc.
True affection, love, and blessings to you all, from, dear William,

[.signed-section-closing]
Your most affectionate father,

[.signed-section-signature]
William Capper.

--

[.offset]
+++[+++In her journal Mary Capper continues:]

13th. "`Forsake all, and you shall find all; leave your inordinate desires,
and you shall find rest.`"
This is no easy task; self will loudly plead her own cause; but as we keep low,
and attend to the voice of Truth, there will be a forsaking of self,
and a witnessing God to be all in all.
There is a charm in the very dawnings of virtue that irresistibly attracts our admiration,
and leads sweetly on in the pursuit of true wisdom.

14th. Walked to Milton Farm, and found them preparing for their harvest supper.
The quantity provided on these occasions is really astonishing.
We went to see our neighbour King`'s tables set out; they had two boiled rounds of beef,
and several roasted pieces, two quarters of mutton and six legs of mutton;
with six plum puddings.
Their company consisted of men, women and children.

26th. My mother and I went to Lewes.

27th. My mother left me there; she was in much better spirits than myself.

30th. We called at friend Rickman`'s at the Bridge; we also went to Lambert`'s,
the portrait and landscape painter.
Mrs. Lambert showed us the plates designed for the
first number of Curtis`'s botanical work;
they appear exceedingly well executed.

October 1st. I had a letter from my mother, who got safe to town,
and found our friends well.
My brother William is very desirous to have me with him.
I am distressed at the thought of leaving Mrs.
Capper,
nor can I persuade myself that my poor abilities can be any advantage to my brother;
however I am ready to try my best skill in his service.

6th. Went to Church.
Reflected with gratitude that I had neither opportunity
nor strong temptation to join the giddy crowds,
who seem to live wholly strangers to the still, small voice,
which is not to be heard in tumult and confusion.

8th. Letters from London.
My brother expects me in a fortnight.

9th. We drank tea at a friendly Quaker`'s, and were treated with freedom and simplicity.

15th. I have fixed to be in London this day fortnight;
with reluctance I leave these scenes, where I have felt calm, peaceful delight,
and with satisfaction have contemplated the beauties of simple nature;
but the pleasures of the mind are confined to no place; in every situation,
I am persuaded the bountiful Hand that enriches the field and the grove,
ever affords subject for admiration, gratitude and praise.

17th. My brother went among the sick; though he cannot administer health,
I hope the balm of comfort will be permitted to flow from his lips.
The glad tidings of peace are sometimes allowed to reach the afflicted,
through the faithful servants of the Lord.

27th. The last day of my residence at Wilmington!
Words would fail to describe my feelings!
