== Chapter IV.

[.chapter-synopsis]
* Residence in London till 1788
* Removal to Birmingham
* Death of her mother in 1793

[.offset]
+++[+++In the sketch which Mary Capper subsequently gave of her early life, she remarks:]

From the time that I went to live with my brother William, in London,
I regularly attended Friends`' meetings;
not that I was acquainted with their peculiar religious views;
indeed there seemed to be a prohibition of aught but simple evidence and obedience.
The experience of others did not seem to reach my case; all was to be given up,
that all things might be new; and such were the sacrifices required, from time to time,
as none can know or understand, save those who have been led in a similar way.

About this time,
in consequence of my decided resolution to attend the meetings of Friends,
my dear father (no doubt in faithfulness to his own religious views,
and from the desire to rescue a poor child from apprehended
error) requested me not to return to the parental roof,
unless I could be satisfied to conform to the religious
education which he had conscientiously given me.
This, with a tender, heart-piercing remonstrance from my dear, dear mother,
was far more deeply felt than I can describe; and marvellous in my view,
even to this day, was the settled, firm belief that I must follow on,
to know the soul`'s salvation for myself; truly in a way that I knew not!

[.offset]
+++[+++In this time of deep affliction, she wrote, as follows, to her only sister:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
February 11th, 1783.

[.salutation]
My very Dear Rebecca,

Must I forever give up the dear,
pleasing hope of being received into the house and affections of my once kind,
indulgent parents!
Oh! my sister, will you, can you despise me?
I have no firm consolation but in the belief that I am guided by a superior Power.
I have exerted every faculty of my mind; I have resolutely mortified my body,
endeavouring to bring it into subjection,
free from the influence of passion and deceiving sense;
and I have a secret intimation that the kingdom of Heaven is within us;
that in the silence of the creature, is the power of God made known.

O! my Rebecca; if you would examine the uniform desire of my life,
the earnestness of my supplications, and my present wish of being humble, pure,
wholly dependent upon God my Maker, without any confidence in man;
if you would thus consider me, without prejudice, I think you would not, could not,
reject me!
Of my own willings, or self abilities, I deserve little;
but in my heart and understanding, I submit to a perfect Teacher; and in his Light,
is my life and my hope.
Think not, my Rebecca, that I have contracted ideas,
which circumscribe salvation to any particular sect.
God forbid! my heart is contrariwise enlarged in universal charity.
Let each be satisfied in his own mind,
and the censures or applauses of multitudes can only be a secondary consideration,
of no weight.

Would my dear parents deliberately compare my conduct with their own principles,
I think they would not find that essential difference which a superficial view represents.
I wish, and really mean to act as a reasonable creature; redeemed,
and born to newness of life, through the death,
sufferings and resurrection of our Lord and Saviour Jesus Christ;
by whose intercession and promised spiritual assistance,
I am encouraged and strengthened to call, and wait upon the living God.
If there is presumption and self-exaltation in this faith,
I am utterly at a loss how to act; for I dare not trust in man,
whose breath is in his nostrils.
My hope and my confidence are alone in the Redeemer of his people.

No earthly satisfaction could equal that of being approved by my dear parents;
but indeed Rebecca,
I cannot--cannot act contrary to what I believe tends to
my advancement in faithful obedience to the law of God;
the law which I find written in my own heart; for I believe,
from that law shall a man be judged, When faithfully followed, it cannot, will not,
lead him from the Supreme Good.
Every line in Holy Writ tends to strengthen or encourage our hopes,
in humble confidence in the One only Good;
opening our eyes to the folly of trifling amusements,
and to the vain fashions of the world.
Farewell, my dear Rebecca! believe me, I never was more affectionately your sister,

[.signed-section-signature]
Mary.

--

[.offset]
+++[+++The foregoing letter appears to have been answered by the following from her mother.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, February 15th, 1783.

You have kept me in painful suspense for some time, by not answering a plain,
simple question; that is, whether you wished ever to return,
to give comfort to a poor afflicted parent or not.
You have now answered fully to your sister;
but why trouble her with a repetition of the same, or to the same purport,
that you had written from France?
You did very well in not sending the letter you mention to have written to me,
if it run in the same strain, and I am inclined to believe it does;
for my present intention is,
that I shall neither read nor hear any letter or
writing that shall come from you to myself or others,
if I can without difficulty avoid it;
in consequence of which this probably may be the last time I shall trouble you;
and this I intend to be very short; for what can be said to one under such strong,
enthusiastic delusion, as to declare against all prescribed rules in worship, etc.,
and at the same time, has entered into a Society who do not act, speak or move,
or even conduct the most trifling affairs but by prescript?
I mean, in anything that carries the form of religion;
but you presume to have an immediate call, or direction, from that Supreme Being,
whose positive commandment you dare to break, for the sake of a few speculative opinions,
made known to you by those whom you esteem; not by persuasion;
no! for that way they disclaim, but by a far more sly and insinuating way.

O! my child, I could tell you by what means they have worked on your judgment,
but I forbear, as I have not a glimpse of hope that it would be to any good purpose.
O! how does my heart, as it were, die within me,
when I think of the effect it will have on your poor father?
What would I give that it could be kept from him! and that it may be,
as long as possible, shall be my care; for my firm belief is,
that if he was to know the contents of your last letter,
while he is under his present bodily infirmity, he would hardly long survive it;
but of what consequence is that to one who, I fear,
fancies herself under convincement! but do reflect a little, my dear child;
what is it that you are called upon to do, or what to forego?
Our most fervent desire and prayer is that you, and the rest of our dear children,
should, through the Grace or Light that is afforded us by our all-gracious God,
worship Him in spirit and in truth; without which, most certainly,
our prayers become unprofitable, and only vain lip-labour.
But there are some forms, you will say, that you cannot assent to;
I will admit it may be so,
and perhaps there is no system at this time existing that is entirely perfect;
but I firmly believe ours to come nearer to perfection than any other.
You think otherwise; so did Naaman when he prayed,
that when he was performing his duty in that state of life to which he was called,
and bowed in the house of Rimmon, that in that thing, the Lord would pardon him;
and the prophet said.
Go in peace!

Three o`'clock.
I wrote the above last night, after your poor father was gone to bed;
I thought him better yesterday than for some time past;
he wrote a letter to your brother John, and was in good spirits; but in the night,
was seized with a cold shivering, and has ever since been very ill.
He has not been up today, and I am now attending by his bedside;
he is quiet and seems more comfortable than he has been.
The great Disposer of all events only knows what may happen; but whatever it may be,
I earnestly pray that He will permit me such a measure of Divine grace and assurance,
as shall enable me to bear, in a Christian manner, whatever may be laid upon me.

I have run on much more than I, at first, thought to have done, when I sat down to write.
I intended it to be but a very few lines.
My heart still dictates much more, but I will forbear, as they will not let my child off;
one convinced member, as they term it,
is of more esteem in that Society than twenty born and bred in it; but I have done;
farewell! may you be happy,
whatever be allotted for the short remains of your mother`'s days!

[.signed-section-signature]
Rebecca Capper.

[.postscript]
====

One other word will drop from my pen, in spite of me.
Return; return,
my child! and I will receive you with more joy than I did the first moment I beheld you!

====

--

+++[+++Deeply was her mother to be felt for,
and great was the anguish with which this letter was perused;
indeed this period of Mary Capper`'s life was seldom, if ever,
alluded to by her without much emotion.
The conflict was distressing;
yet was she strengthened to persevere in what was
clearly manifested to be the path of duty;
and although her father recovered from that attack of illness,
yet`' as he did not allow her to return home;
and as his last illness was both sudden and short,
she was deprived of the consolation of again seeing him,
and of receiving from his own lips, an assurance of his affection.
It may easily be conceived that this was indescribably trying to her;
but she was enabled to lift up her heart, and to commit her cause unto Him,
for whom she was thus forsaking her earthly home and parents;
and He was pleased to speak peace to her afflicted soul; and in his own good time,
to grant her the hundred-fold, even in this life.
The following memoranda, and letter,
will bear witness to the state of her mind at this period, and for some time after.]

[.small-break]
'''

London, 6th of Ninth month, 1783.
Praise the Lord, O! my soul, and be exceeding glad in the God of your salvation;
for he has done great things for you, and wonderful is his power!
He has plucked your feet out of the mire and clay, and has set them upon a rock;
the only true foundation, throughout all ages to the end of the world!
My spirit is exceedingly glad that the Lord has heard the prayers of his handmaiden,
and in great mercy, granted my earnest request.
He has strengthened me to part with all the nearest and dearest of his gifts;
to sit loose from the tenderest connections,
that I may be free to fulfill the great command of loving the Lord my God,
with all my heart, with all my mind, and with all my strength.

O! let none think the terms hard! our God is a God of infinite mercy;
he is not a hard master, reaping where he has not sown!
My soul can testify of his bounty; and my desire, and my glory, is to adore,
to praise and to magnify his holy name!
Amen!
Amen!

24th of Fourth month, 1784.
There seems a state brought to the view of my mind,
as being attainable even during our sojourn in this world; a state free from sin,
when Christ shall dwell in us, and we in him.
The righteousness which he works in us must be perfect;
every will and working of the creature being laid low, God shall reign over all,
blessed forever!
In this state of freedom from the dominion of sin, temptations and trials may,
and assuredly will come; but as we keep close to the light of Christ,
inwardly manifested, I believe we shall be preserved blameless; without spot or blemish,
to the honour of our great and holy Teacher; to whom be ascribed power,
majesty and praise, now and forever.
Amen!

22nd of Seventh month, 1784.
The ways of the Lord are wonderful and past finding out.
O! let none be weary of waiting upon him,
for he will be gracious to all those who faithfully call upon him!
My earnest cries have gone forth, and I believe the Lord has heard the voice of my prayer.
My groans and my tears have not been hid from him.
Glory, praise and honour be to his name!
Let the creature lie low, that the Creator may be all in all forever and ever.
Amen!

14th of Twelfth month, 1784.
O! how pure, how perfect is the Truth as it is in Jesus!
Keep to it, O! my soul; turn neither to the right hand nor the left, but press forward,
through all difficulties;
for the light of Christ within you will break forth into perfect day,
if on your part you are steady, undaunted, and of a right faith!--O! my God,
help me! leave me not to the delusions, the buffetings of my soul`'s enemy!
Keep me in the patience, that I may watch your coming, and be found of you.
You are worthy to be waited upon, O! Lord, my God! in you is my hope,
and my trust forever!
As rest to the weary traveller, so is true silence to the deeply exercised mind.

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to W. B.

[.signed-section-context-open]
11th of Third month, 1785.

[.salutation]
Dear Friend,

With propriety I believe I may use the term, dear friend,
as all in the Truth seem dear to me.
Since our conversation this afternoon, I have had to remember, in a very lively manner,
the Lord`'s dealings with my soul in early life.
I was at times visited with a sweet sense of purity and truth;
but from my situation and mode of education,
I was at a loss how to come at that which my soul seemed to see at a distance.

For several years the prospect was, as it were, closed, or very rarely opened.
I thought myself a useless being, and I believe sometimes almost repined that I was born;
but about the twenty-third year of my age, the Lord graciously re-visited my soul;
and it was, indeed, as the dry and barren wilderness, refreshed with dew.
I think I cannot forget the sweet incomes of divine favour.
The whole creation seemed new to me;
all things spoke the love and mercies of a gracious God.
Scarcely a day passed over without some sweet openings,
some renewal of my great Master`'s condescension.
I thought myself the happiest of human creatures.
Thus delectably did the God of all my mercies allure me into the wilderness!
Every required sacrifice seemed ready prepared by his own hand,
and I had only to wait his own time.
Happy have I thought it, that he was pleased to stay my mind!
When my dear, loved parents expressed their concern at my change, it was suggested to me,
that for a time, it was my place to be subject in all things lawful,
and way would be made where I saw no way; and far beyond my expectation,
this has indeed been verified.
But what seems more immediately to dwell upon my mind to communicate to you is,
that I have, in my measure,
found that the Lord`'s merciful dealings stir up the envy and malice of our grand enemy,
when our gracious Father is pleased to hide his countenance and try our faith,
after having sweetly led us in the right way.
Then is the enemy as one triumphing over his prey.
O! how is he permitted to buffet, to terrify the poor, timid soul!
My mind has sometimes been as one almost without hope;
and had not the hand of the Lord been underneath, I had surely fainted;
but my spiritual eye was led to retrace the paths I had trod,
and I was favoured to see the Lord`'s dealings,
and that tribulations were appointed to the faithful followers of a crucified Jesus.

With affectionate wishes for your prosperity in the Truth,

[.signed-section-closing]
I am, sincerely,

[.signed-section-signature]
Mary Capper.

--

[.offset]
+++[+++The following brief remark is among her memoranda:]

On the 2nd of the fourth month, 1785, my dear father died without my seeing him!
I heard that he enquired with affection for a pair of garters which I had knit for him,
and that he spoke with tenderness of me.
O! this was like precious balm!

[.small-break]
'''

+++[+++No special mention is made of a change in her mother`'s feelings towards her,
but there is reason to believe that she gradually, from the time of her widowhood,
became reconciled to her daughter`'s proceedings;
being doubtless convinced of the rectitude of her motives;
so that the way was at length made for Mary`'s returning to the parental dwelling.

It appears that Mary Capper was received into membership
with the Society of Friends about the year 1785,
also that she spoke as a minister in their religious meetings soon after that event.
With respect to the latter circumstance, she writes:]

[.small-break]
'''

It sometimes arose in my mind,
that possibly I might have to tell unto others how I had been taught,
and kept from the broad way of destruction; and a few words arising,
with something of unusual power, I think at the Peel meeting, I stood up and spoke them,
and felt very quiet; nor did I anticipate that such a thing might ever be required again;
and thus I was led on, from time to time, not knowing but each time might be the last.
About 1788, I came to reside with my dear mother, at Birmingham,
and she did not object to my regularly attending Friends`' meetings.

[.small-break]
'''

+++[+++The occasion of her leaving London, and going to reside with her mother,
appears to have been the indisposition of the latter,
and is briefly alluded to in the following extract
of a letter to her from her brother William.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 17th of February, 1788.

[.salutation]
My very Dear Sister,

I cannot delay writing to you,
since you say that my silence adds to the painful sensations of your heart.
Indeed, my dear Mary,
if I could write anything that would alleviate one anxiety of your dear breast,
I would not let a post go without a letter.
You will be glad to hear that all things in the family go on as though you were present.
I called this afternoon in Berkley Square; uncle John has had a severe fit of the gout.
I spent Friday evening with Jasper and Nancy; they are well and comfortable.
How could I write so much, and not once mention our dear mother!
I am-much grieved at the account you give of her, and hope to have a better in your next.
Comfort her, my dear girl! give her my sincere duty and affection,
and tell her I am happy that I had such a sister as you, to send to her consolation.
Remember me in affection to brother Samuel, to his wife, and to George.
I am, dear Mary,

[.signed-section-closing]
Your truly affectionate brother,

[.signed-section-signature]
William Capper.

--

+++[+++Though very little allusion to the circumstance is found in any of Mary Capper`'s papers,
it seems scarcely right wholly to omit the mention of a yet more
costly sacrifice than any that she had previously made,
which was called for at her hands, before she quitted London as her home.
She had formed a strong attachment to a young man Friend,
to whom she expected to be married,
when she discovered that he did not set a high value
on his membership in the Society of Friends,
and that he was inclined for more liberty in practice than their principles allowed of.
This was a most painful discovery to her;
and as farther communication with him proved to her,
that he was one who could not fully enter into her religious feelings and views,
she felt it to be her duty to break off the connection,
though it nearly cost her her life;
and she could never afterwards entertain the prospect of matrimony.

The following extract from a letter of her mother`'s,
will show how changed were her feelings towards Mary, and towards Jasper and his wife.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, June 16th, 1788.

[.salutation]
My Dear Mary,

In answer to your last, I feel truly concerned that poor Smallwood^
footnote:[The eldest son of Jasper and Anne Capper.]
has fresh appearances of his disorder;
and sorry I am at the disappointment which his parents must suffer.
If necessary I advise, by all means, that you should attend him;
for whatever my own views may have been, I readily give them all up,
for the good of this poor afflicted child, and the comfort of his father and mother,
to whom give my most tender love.

With respect to the other proposal that your brother and sister have signified to you,
I believe the bent of your own mind must determine you; this I verily believe;
that the goodness of your own heart will incline you to
undertake that which is the most needful for your friends.

I have only to add,
that (wherever you may fix yourself for a time) while you remain single,
I would have you to look upon my habitation, so long as I live,
as your fixed and settled home.
Thank your brother Jasper, in my name, for his attention to your aunt Chase.

Tibbatts^
footnote:[The husband of her sister Rebecca.]
was here on Sunday; he says Rebecca is well.
Believe me, dear Mary,

[.signed-section-closing]
Your affectionate mother,

[.salutation]
Rebecca Capper.

--

+++[+++Mary Capper does not appear to have kept a journal
regularly till after the death of her mother,
but a few remarks were penned occasionally;
and sometimes the petitions of an exercised soul.
The following will, it is believed, be acceptable to the reader.]

[.small-break]
'''

10th of Sixth month, 1789.
My soul! wait upon God;
although heaviness and insensibility may perplex and distress you, yet be not dismayed,
nor weary of well-doing; for assuredly they that wait upon the Lord;
that patiently and quietly wait, shall renew their strength.
They shall mount upwards, they shall rise as upon eagles`' wings,
they shall be raised above this grovelling earth;
but it may be needful that they should feel how necessary it is to wait upon the Lord,
and that, with long patience and deep humility.
O! Lord my God! if it be your holy will,
be pleased at this time to increase my faith and my patience,
that I may more perfectly know and wait upon you!

Eleventh month, 1790.
O gracious Fountain of all our mercies, be pleased to look down upon us,
and save us from our sins!
Jesus, the Redeemer, has died that we might be perfected through his atoning sacrifice;
let us not then make his sufferings of none effect to us ward,
by an evil heart of unbelief!
My soul feels a weight of sorrow for my own insensibility; and many, very many,
are my imperfections, particularly,
O! my God! (may I call You my gracious Father!) I have to lament at this day,
a proneness to impatience and frowardness of spirit.
Gracious Father!
I would confess my sins that I may be healed; but You know all my thoughts,
and the devices of my heart; therefore with all my burden of infirmities,
weakness and folly, I bow at the footstool of your mercy,
and hope to be kept in patient humility,
waiting your time to deliver me from my soul`'s enemies; for the power is yours!

1791+++.+++ At this period of my life, my faith is that there is one God,
who is supremely good, and does good continually;
that at sundry times and in diverse manners throughout all ages of the world,
He has been pleased to manifest Himself to the sons and daughters of men;
that in this our day, He shows Himself in the glorious dispensation of the gospel;
having sent his own Son to be made flesh, and dwell among men for a time,
in an earthly body.

Though mysterious his death and sufferings,
I believe that Christ died to redeem us from sin; and that, in and through Him,
believers have access to the Throne of Grace.

Eighth month, 1791.
My faith being renewed in Christ Jesus, the Son and express image of the living God,
I bow in humility and hope at the footstool of mercy,
looking for redemption and remission of sin.
O! the malady of the soul! how foul it is!

There is not, in nature, an antidote to so great evil;
but the Lord of life and glory came down from heaven, from the bosom of his Father,
to recover lost mankind, and throw consolatory hope into the cup of human woe;
made a bitter cup by man`'s disobedience and pride.

Gracious,
holy Father! open the blind eye! unstop the deaf ear! that we may
see and acknowledge the mystery of your condescending love!

[.small-break]
'''

+++[+++Towards the end of the year 1793,
Mary Capper appears to have been absent from Birmingham, attending upon a sick friend;
during this period she received the following letters from her mother:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, 18th September, 1793.

[.salutation]
My Dear Mary,

I hope they will not remove the young woman till
the doctor thinks it may be done with safety.
Don`'t be uneasy on my account.
I continue tolerably well, when I am quiet;
and what a blessing it is that I have it in my power to be so!
I am not so much alone as you may think, for my neighbours are kind in calling on me.
Your brother George dines with me most days, comes home in good time at night,
and often looks in, during the day.

Farewell, my dear Mary!
I shall be truly glad to receive you, when it is proper for you to come home;
but I am not impatient.

[.signed-section-closing]
Believe me, your sincerely affectionate mother,

[.signed-section-signature]
Rebecca Capper.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Colmore Row, 23rd September, 1793.

[.salutation]
My Dear Mary,

I am well pleased that you may leave Park Gate, with safety to your patient.
W+++.+++ Shorthouse tells me he intends setting out tomorrow to conduct you.
He did intimate, some time ago, a thought of taking you to Liverpool;
now if circumstances coincide, I wish you to embrace the opportunity,
as another may not offer.
Don`'t hasten home at all on my account; I seem at this moment quite well.
I was out only once yesterday, for the weather was rainy, and the wind very cold.
I was very much gratified, and I hope edified, by a discourse on the words of St. James,
"`Let patience have her perfect work.`"

[.signed-section-closing]
I am, dear Mary, your truly affectionate mother,

[.signed-section-signature]
Rebecca Capper.

--

+++[+++Rebecca Capper died in the twelfth month, 1793;
but no particulars are known of the illness that terminated her life,
or of her closing moments.]
