== Chapter VII.

[.chapter-synopsis]
* Departure from Trosnant
* Settlement with Mary Lewis, at Leominster
* Visits to London, etc.
* Death of Mary Lewis

1811+++.+++ First month 30th. Our kind friend S. Waring arrived here,
for the purpose of once more lending her aid in this spot,
which it seems likely that we may soon leave, being about to remove to Leominster.
The prospect feels important.

Fourth month 5th. I took my leave of Trosnant.

6th. On reaching Birmingham, I found Thomas Shorthouse ill.

10th. Our poor friend very ill.
O! it is well he can say that there is nothing but
the pains of the poor body to contend with.
No thought, he says, troubles him; the Lord has been with him all his life long,
and is with him now.

12th. Our dear friend Thomas Shorthouse breathed his last.

17th. A good meeting at the interment.

18th. I went to Coventry,
under an apprehension that time was particularly
uncertain to our long known and truly beloved friend,
John Cash.
I found him confined to his room, and in a very reduced state, but quite sensible,
and with a solemnity of countenance which seemed to bespeak a spirit
in great measure gathered from the encumbering cares of time,
in which he had largely shared.
His conduct was very exemplary, as a man of integrity.
Towards the decline of his life, the fluctuations of trade having reduced his property,
he very prudently and steadily endeavoured to retrench his expenses;
he appeared very cheerful, and truly contented,
having the sweet solace of those who do justly.
It may be said he was, for many years, a preacher of righteousness,
by example and by exhortation; as a minister in our Society, he was truly esteemed,
and he was zealous for the discipline and good order established among us.

24th. First-day.
As I sat by him, I thought under a very precious sense of heavenly favour,
I ventured to remark, that we had partaken of many profitable seasons together,
under his roof.
"`O!`" he said, with some animation, looking expressively round on his family,
"`I hope these dear children have profited.`"
Some little time after, we cordially took our last farewell of each other,
no more to meet on earth; for in a few hours, he quietly passed from time to eternity.

Fifth month 18th. I arrived in Gracechurch-street, London.

[.offset]
+++[+++The following are extracts from an account of the yearly meeting,
etc. sent by Mary Capper to her friend Mary Lewis.]

[.embedded-content-document.letter]
--

Fifth month 20th. My dear friend;
it is my desire to transmit a little to you of that which interests us here,
as I may find time and ability.
Susanna Naish is my quiet companion; she is separated from her choice friend,
Priscilla H. Gurney,
whose health does not allow of her uniting with her friends at this time,
in entering into the affairs of the Church;
and I being under like privation from the same cause,
we often think and speak of our absent yokefellows; and my dear friend,
the condescending goodness of the one Shepherd being unbounded,
surely he is with the solitary in all places, and under every trial; help is laid on One,
mighty to save!
Yesterday I saw several of my relations; my brother John looks pretty well,
but has many troubles; his son Edward remains in the army.
My sister Jasper is much shrunk and looks very languid, but is yet, at times,
in good spirits and active.
My brother William and his wife seem happy in each other.
Henry Hull was at this meeting yesterday, and powerfully counselled us to keep the watch,
and to stand in our allotments in simple obedience.
This morning the yearly meeting of ministers and elders met,
and the business was entered on by George Stacey and Dykes Alexander.
Ann Byrd and Mary Pryor are among the ancients here.
J+++.+++ G. Bevan looks poorly; his wife is unable to be out.

21st. A humble petition for continued help was offered by Rebecca Byrd.
She is very unwell.
Now my dear tried friend, I turn to your letter;
your repeated attacks of illness are surely a great trial,
but I know not how to do better than to commit you to the keeping of heavenly kindness,
and to crave for you and for myself, an increase of faith and patience,
that we may steadfastly abide until our measure be filled up.
I entreat you, my dear friend, dwell not upon the gloomy side of things;
rather let us endeavour to contemplate with gratitude
the Power that has graciously quickened us,
and called us to virtue and to glory; which raises the aspiration,
make me what You would have me to be!
Give my love to H. and S. Waring.
O! my tender friends,
when heavenly condescension renewedly humbles and contrites our spirits,
how we do long for the harmonizing influence of Christian
love to spread over the whole world!

22nd. The women`'s yearly meeting commenced,
and the gathering was so large that it was difficult for all to be accommodated.
Our dedicated, aged friend Mary Pryor,
was wonderfully strengthened to proclaim the continued goodness of the Lord,
and to encourage the humble, exercised ones.
Mary Naftel was refreshing in prayer.

Fifth month 23rd. An instructive testimony was read, concerning John Hall,
of little Broughton, who on his dying bed, declared his steadfast faith in Christ Jesus,
and was made triumphant in death.
A very animating one was also read, respecting Ann Perry, of Coggeshall.
She was a poor orphan who, in her childhood, was placed in a charity-school,
and afterwards removed from one place to another, until the age of nineteen,
when her lot was cast in the family of a Friend.
Here she became truly religious,
and was led to acknowledge the purity and efficacy of the Truth, as we profess it,
and to unite herself to our Society, wherein she became a preacher of righteousness,
in word and in deed.

24th. Edward Simkin and Mary Proud ministered to us at Ratcliff meeting,
which I attended; and a prayer was put up that the sons and daughters of men,
the world over, might in mercy,
be brought under the sanctifying power of the Holy Spirit, and that,
to the name of Jesus, every knee might bow, and every tongue confess.
In the afternoon, a testimony was read, concerning Richard Jacob, of Ireland.
It was particularly remarked therein,
that his steady endeavour was to overcome evil with good.
An admirable attainment!
My heart longs after it, but I come affectingly short; yet I must press on.

28th. The gathering was favoured with a particularly solemn stillness,
which was truly refreshing.
It is a precious thing when this is the case,--when, after our meetings,
either for discipline or for worship,
something remains to do us good,--to stay our minds upon God.

29th. A very sweet and affectionate letter was sent in from the men`'s meeting,
addressed to them by John Kendall; it was expressive of much love,
and a lively concern for the welfare of the Society.
He is in his eighty-second year.
It was cheering, and seemed like the dew of youth in old age.

30th. Henry Hull, accompanied by three Friends, came to pay a visit to our meeting;
his communication was very instructive; particularly cautioning against self-activity,
recommending us to be as ready to receive as to give counsel,
and to wait reverently for the gentle constrainings of the Spirit of Truth.
He remarked also, that diffident minds, to whom this caution least belonged,
would be the most disposed to take it to themselves, and thus, he feared,
might let in discouragement.
He pathetically addressed the youth, calling them into simplicity and early obedience,
that they might obtain the inestimable ornament of a meek and quiet spirit.
He also supplicated sweetly for all, the absent as well as the present.
I felt afresh contrited, and the language was sweetly raised,
what sacrifice so acceptable as reverent bowedness of spirit!
Our business being ended, a solemn pause ensued.
In pure silence there is fulness.
What a people should we be,
if all did but come fully under the harmonizing influence of that humbling Power,
which brings even the thoughts into captivity!
Truly my heart is pained when I ponder upon my shortcomings.
Ah!
I see that it is individual watchfulness and circumspection which is required,
and I pray for holy help.
The importance of constant vigilance presses upon my spirit.
I wish now to advert to your letter; don`'t, my dear,
be too solicitous about your young friend; the Power which has mercifully kept him, is,
I believe, still near to him.
"`All is not lost that is out of sight!`" let us remember this.
Give my love to my friends; I love them, but my spirit is just now contrited within me,
under a desire to be more fully what I should be; more meek and gentle,
and more patient under little trials; there is more in this than we are always aware of,
and I think I never felt it more forcibly than now.

[.signed-section-closing]
With dear love, affectionately,

[.signed-section-signature]
Mary Capper.

--

31st. I was witness to a very awful scene; the sudden seizure, in Bishopsgate street,
of Joseph Gibbins.
He was apparently in health, walking toward the meetinghouse, when he fell,
was carried to a Friend`'s house, and soon expired.
This truly affecting scene probably shook my weak frame; for in the course of a few days,
my voice was gone, and much debility ensued.
In this reduced state, I was very affectionately cared for by my dear sister Capper,
in Ely Place; my mind, for the most part, was graciously kept in a low, tender condition,
susceptible of good.
Towards the end of the sixth month, my bodily strength was a little restored;
and although this is desirable, and to be received with thankfulness,
yet the favour of Divine mercy, sensibly perceived, in dispensing the bread of life,
is above all.

Sixth month 30th. First-day.
I left my dear relations in Ely Place, and was removed to my dear,
and equally kind relations at Stoke Newington,
where I am tenderly and affectionately attended by my nieces;
very sweet it is to be so cared for, in a time of great weakness.
My powers of voice are still suspended, but I am mercifully kept from anxiety.

[.offset]
+++[+++During her stay at Stoke Newington,
Mary Capper addressed the following letter to her brother.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Seventh month, 1811.

[.salutation]
My dear brother Jasper,

It is difficult for me to speak, but as it particularly impresses my mind,
I wish to tell you,
that since my present great weakness and incapacity for joining in conversation,
I have remembered early scenes; and particularly since I came here,
some transactions between you and me, which have been of great importance to myself;
and I think, as I even now record it with tears,
you may be comforted by being reminded thereof; and in low times,
for I believe that even confirmed believers have their stripping times,
you may be encouraged to hold fast your confidence,
and be thankful that you have been an instrumental means of stirring up the pure mind,
or gift, in one poor straying soul, at least; yes, my dear brother,
even though I knew it not; and I believe you were far from knowing,
the work which was at an early period begun, in the secret of our hearts.
And although many an impediment has been permitted,
and we have more and more seen the evils of the human heart,
yet heavenly kindness has been underneath, and helped us hitherto.

To return to our early days; it has been revived, almost like a scene of yesterday,
when we were young, at Rugeley together, that once,
when our parents were out and I was sitting in the little parlour, you called me;
and when I came to you, you had a paper before you, and had been writing.
With a serious countenance,
you asked me if I could recollect anything that you had done amiss,
or could help you to remember what you had said or done that was wrong,
as you wished to keep an account of your actions.
No doubt, I thought it strange, and said something in childish derision;
at which I remember you looked grave, and said the Testament recommended watchfulness;
at which I foolishly laughed, and said that that was an old-fashioned book.
Well I recollect the inward conviction which I felt when you said, "`Oh! sister Mary,
if you begin to despise that book, I am ruined!`"
Away I ran, but felt much distressed; and I know not, that from that time,
I ever dared to speak lightly of the Scriptures, or of religion.

Although when gradually becoming serious,
it was not suddenly that I made any outward change,
and though I had prejudices to encounter, yet, here, my dear brother,
you had as it were opened a door, which step by step I entered.
O! you know not to the full, the strong holds of naughtiness, perverseness,
depraved inclinations, petulance and impatience, which were in my unconverted heart,
more hard and stubborn, surely, than many others.

Have I not then, great, very great cause to be humble,
and to be thankful to the First Cause?
and to be grateful, in tender love, towards the instrument of my first awakening?
Yes, my dear brother, heavenly Goodness has dealt bountifully with me;
and may all your conflicts and all your trials be sanctified to you; and may we,
in our different allotments, be of one heart and one mind;
ascribing the marvellous mercy of salvation unto
the redeeming power of a Saviour`'s love.
Often the secret language of my heart is, "`a Redeemer, or I perish! a Saviour,
or I die!`"

[.signed-section-closing]
With heartfelt affection, I subscribe, your sister,

[.signed-section-signature]
Mary Capper.

--

Ninth month.
After spending a considerable time among my relatives, from all of whom,
as well as from their servants, I partook of particular tenderness and care,
during my long-continued weak and low state, I gradually recovered strength,
and my voice returned, which was very comfortable to me, and relieving to my friends.

17th. I left London, under the care of Mary Harding, and came to her relations at Witney,
Oxfordshire.

24th. We were favoured to arrive safely at Leominster, where we found Mary Lewis,
comfortably settled in her house.

Tenth month 29th. Came to Birmingham, inconsequence of affecting tidings from there.
Our friends Charles and Mary Lloyd have had the affliction
of three deaths in their family,
in about six weeks.
Two of their sons have been taken away in the prime of life,
and have each left a young widow and infant family; and their lovely daughter Caroline,
twenty-one years old, is called away from this life of vicissitudes,
meeting death with calm resignation and peaceful assurance,
through the redeeming love of Christ, the Saviour.
Her life was exemplary, and she was remarkably useful, in the care of the poor,
and the education of their children.
Her affable engaging and gentle manners, also her serious deportment,
and her religious observance of the times set apart for
waiting upon and worshipping the Father of spirits,
in public, are a very sweet memorial of her, engraven in our hearts.

17th. First-day.
Our valuable friend Henry Hull attended our meeting,
and held a large and satisfactory one in the evening.

[.small-break]
'''

+++[+++From this date it appears that Mary Capper was not so regular as before,
in noting down remarks; the next memorandum being an account of the yearly meeting,
after which there is a considerable lapse.
This continues occasionally to be the case,
until the period when she entirely ceases to keep a journal.
The omissions are supplied by extracts from letters, etc.]

[.small-break]
'''

1812+++.+++ Fifth month 18th. The yearly meeting of ministers
and elders was larger than for some years past;
and it was consoling to see the aged standing firm in their Heavenly Master`'s cause.
A very precious feeling of solemnity was graciously spread over us,
and supplication was humbly offered at the throne of mercy.
The business was then opened by George Stacey, J. G. Bevan, etc.
Mary Pryor and John Bateman, as soldiers valiant in their Master`'s cause,
spoke well of his Name,
and testified their thankful sense of the continuance of his merciful kindness.
Certificates for Friends travelling in the work of the ministry were read; among them,
one for Stephen Grellet, of the United States.
He is a native of France.

19th. Stephen Grellet prayed, very impressively, for an increase of true judgment,
and the spirit of right discernment among us;
and that each might be found keeping their ranks in righteousness.
A desire was afterwards tenderly expressed,
that nothing among us might prove a stumbling-block to the simple and honest-hearted;
but that our whole conduct, conversation, and dealing among men,
might manifest a consistent, self-denying life, as followers of a crucified Lord,
and as waymarks to the flock.

20th. The women`'s yearly meeting commenced.
Our honourable, because firm and faithful mother in the church, Mary Pryor,
testified in a very lively manner her sense of heavenly
favour being renewedly extended to us.
Elizabeth J. Fry supplicated for heavenly help,
to keep our allotted places in the church;
she afterwards requested leave to pay a visit to the men`'s meeting,
and Rebecca Bevan diffidently expressed a sisterly sympathy, and desire to accompany her,
if it was deemed suitable.
After solid consideration, the way seemed clear for their liberation,
and three elders accompanied them; namely, Tabitha Bevans, Rachel Smith,
and Sarah Phillips.

21st. Several testimonies were read,
and some animating remarks made on the encouragement to be derived from the peaceful
close of those who had been obedient in the day of the Lord`'s power,
and who held fast their confidence to the end.

29th. A very serious consideration of the state of our Society spread among us,
and one quarterly meeting seemed to claim particular attention.
Just at this time, information was received from the men`'s meeting,
that a deputation was appointed for visiting this quarterly meeting,
with a request that some women Friends would unite in the visit.
This was an encouragement to those who felt bound to go on this service;
the names set down were Sarah Benson, Mary Stacey, and Sarah Hustler.

We were favoured with a visit from Henry Hull,
who was led to speak impressively to mothers;
recommending them to bring up their daughters to usefulness,
and to guard against those indulgences which tend to pride and haughtiness,
lifting up above the cross of Christ.
He also said that it had been very pleasant to him, while in this land,
when his lot was cast in families where there was a manifest care over servants,
and a tender regard to their welfare; not requiring more from them than was reasonable,
and maintaining a watchful endeavour to set them an example of meekness,
forbearance and Christian humility.
With much solemnity, he commended us to God and to the word of his grace.
He then withdrew, with his companions, leaving us in remarkable quietness,
and some of us in contrition of spirit;
somewhat like the early morning of our visitation,
and still prized as a precious token for good.

In the afternoon our business was completed,
and the concluding minute was impressively read;
importing that heavenly Goodness had been mercifully near, to help our feeble endeavours.
The covering of inexpressible calm, which spread over many minds,
after having borne their allotted portion of hidden exercise or
active service for the promotion of righteousness among us,
very far exceeded the eloquence of language to set forth,
or the comprehension of the restless, unstayed mind.
A stayedness of mind upon the object of worship is the solace of the soul.

30th. The adjourned yearly meeting of ministers and
elders met under peculiar impressions of sadness,
and of sympathy with our beloved friend Henry Hull,
who has received information that his wife and son have died of a malignant fever.
He sent a message, expressive of his love to Friends, and that, though in affliction,
he dared not murmur; for when he left his home, he resigned all into the Lord`'s hand,
who had a right to dispose of him, and of them.
A returning certificate which had been ordered for him, was read and signed.
We separated under the sense of precious fellowship.

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to Katharine Capper.

[.signed-section-context-open]
Leominster, Eighth month 18th, 1812.

[.salutation]
My dear loved niece,

Your tender affection, your unity with my poor spirit,
is truly acceptable and sweet to me; the ties of relationship are sweet;
but how much more important, how far more interesting,
when we are permitted a little to understand a fellowship with the Father and the Son,
and one with another in Him! how this softens our hearts! how it
clothes the spirit with compassion for those who are out of the
right way! how it teaches to bear and forbear!

[.signed-section-signature]
Mary Capper.

--

Mary Capper now made her home principally at the house of her friend Mary Lewis,
at Leominster,
and does not appear to have been engaged in much active service for some time.
In the spring of 1814, she went to Birmingham before attending the yearly meeting.
From Birmingham she thus writes to two of her friends.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, Third month 22nd, 1814.

[.salutation]
Dear Friends,

I have thought much of you since I left,
and though my tender affection towards my fellow travellers, in the time of trouble,
can avail little to lighten the actual pressure of grief,
whether openly manifested or more secretly felt,
yet I esteem it a privilege to be made capable of mourning with those that mourn.
In my view.
Christian sympathy enhances the importance of life,
and brings us nearer to the great Pattern of Christian perfection,
who was a man of sorrows and acquainted with grief.
The longer I live, the more I seem to see and be convinced, that human nature,
with all its propensities, must be subjected and refined through suffering.
Marvel not then, my dear friends, when your pleasant pictures may be marred,
or even what you may think your reasonable hopes, disappointed.
As true Christian believers, quickened by Divine Grace, you have a new path to tread;
banded in heart, and united in spirit,
to serve the Lord and promote the spread of his righteousness, my dear friends,
through all your trials, let not your faith fail,
but keep your eye steadfast to the Power that can make you exemplary,
and importantly useful, in your day; that, being proved and tried,
you may be enabled to speak to others of that help
and comfort wherewith you have been comforted.
I believe it is the lack of entire subjection,
which keeps us from the possession of that peace of mind,
which surpasses the natural understanding of man,
and is a precious token of a Saviour`'s love.
Think not that I write as having attained; ah! no;
though at times I am favoured with some foretaste of this Divine gift,
I find painful lets and hinderances; but this one thing I desire to do;
to press forward with an earnest, humble hope, that He who has awakened my spirit,
and a little opened my understanding, will never leave me to my own poor guidance;
and I would encourage you, my dear friends, to hold on a heavenly course,
without fainting by the way; ever bearing in mind,
that it is not by outward observation that we shall stand, but by the Grace of God.

[.signed-section-closing]
Affectionately,

[.signed-section-signature]
Mary Capper.

--

Fourth month 3rd. Ann Burgess held a meeting for
those who have joined the Society of Friends,
or are constant attenders of their meetings;
several were present from my native town of Rugeley,
for whom my heart was truly interested.
Received fresh accounts of the continued weakness of dear Mary Lewis.

13th. At the monthly meeting at Tamworth; here is a large company of young Friends,
who appear naturally lovely and kindly disposed;
but there was a feeling that something more is needed;
that the heart must bow to the yoke of Christ,
and allow the refining fire to consume the dross, and prepare the vessel for usefulness.
There is a great lack of sacrifices and of pure offerings in the Church.

17th. First-day.
Dear Stephen Grellet expressed his unity with the poor in spirit,
and encouraged the humble travellers.

19th. Set out for London.

24th. First-day.
Was at Peel meeting,
and had in lively remembrance the first time of my sitting down among this Society;
unto whom I trust, after many years of probation,
I am now steadfastly joined in Christian fellowship.
My desire is to be brought into, and to be kept in humility and godly fear,
by that which did first enlighten me,
and convince me of the spirituality of true religion.
In the evening came to my brother Jasper`'s, at Stoke Newington.
It feels very pleasant to me to be once more with my dear relatives,
and to be sensible of reciprocal affection after long separation.

25th. At the adjourned quarterly meeting, a precious memorial was read,
relative to dear Mary Bevan.

26th. Spent the morning pleasantly with my dear niece Rebecca Bevan;
she instructs her two elder children,
with the kind and important assistance of J. G. Bevan;
who takes his seat in the school-room,
and appears to feel much interest in the children`'s advancement.
Dear man! he seems gradually declining in bodily vigour,
but his company is very instructive.

27th. At the week-day meeting,
our aged friend Mary Pryor was enabled sweetly to encourage the lowly ones,
to hold on in the path of obedience.

28th. We had a quiet day, in the peaceful enjoyment of social communion.
How precious and highly valuable is that fellowship
which unites families and relatives as in one mind!
Never did I more fully feel or prize it, as a heavenly blessing.

Fifth month 2nd. After the Scripture reading and a pause, wherein the watchful,
attentive mind has opportunity silently to feel its needs,
and reverently to bow at the footstool of mercy, we retired to the school-room,
where I sat at my needle, an observer of the great pains taken by my dear niece,
assisted by J. G. Bevan to instruct the children;
it is very gratifying to me to sit with those who are qualified to teach,
and those who are disposed to learn;
but I perceive it is an arduous task fur the mother of a family,
in addition to her other cares, to dedicate so large a portion of time to education.

3rd. The morning was fine, and we had a little stroll in the garden before breakfast.
At reading time, the dear children were very quiet,
and I thought something precious was to be felt.
I ventured to express my renewed sense of the value and
importance of the practice of thus collecting together,
parents, children and servants, for the purpose of reading the Scriptures,
and in order to experience a preparation of mind
for pursuing our various occupations and duties,
with propriety, and patience.
There will be need of patience unto the end of the race.

After school-hours I accompanied my niece to call on the poor and afflicted;
a delightful employment, when we have the will and ability to give pecuniary relief,
or to instruct them how to find the true Comforter.

6th. I left my endeared nieces, and returned to Paradise Row;
dear Rebecca walked with me and stayed dinner with us, which was very pleasant to us all;
indeed it is precious to feel the uniting bond of love and increasing fellowship;
as with one desire, to be kept by the one Spirit;
knowing our own imperfections and incapacity to keep ourselves from falling.

+++[+++On the 12th of the ninth month J. G. Bevan suddenly expired, during his afternoon sleep.
In allusion to this circumstance Mary Capper wrote from Leominster:]
"`He had finished his course; and though survivors may mourn his loss,
yet the great Head of the Church can raise fresh supplies,
and bring thousands and tens of thousands up and down to cast their gifts into his treasury;
yes to dedicate their all unto their Lord`'s service;
and let him do what He will with them and theirs.`"

[.small-break]
'''

+++[+++The health of Mary Lewis had long been gradually giving way;
she was affectionately nursed by her faithfully attached friend,
who was with her to the last, and who thus wrote, on the occasion of her death,
to some of her dear and intimate friends.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Eleventh month 28th, 1814.

[.salutation]
My dear Friends,

This day about twelve o`'clock, I was enabled to resign with calmness,
the immortal spirit of the kindest friend any individual could have,
into the hands of a faithful Creator; no more to witness her tender,
affectionate care and attention to me.
Dear creature! she slowly declined, though her sufferings have been great,
and borne with unusual cheerfulness.
On seventh-day morning a stupor or drowsiness took place,
with laborious breathings until towards the last, when she calmly expired.
She has uniformly expressed a desire to be laid in her husband`'s grave;
it is therefore intended to convey the remains to Trosnant;
the interment to be on first-day morning.
Dear friends, farewell, I am as well as can be expected, but I need rest.

[.signed-section-closing]
Love to all our dear friends, I subscribe myself,

[.signed-section-signature]
Mary Capper.

--
