== Chapter X.

[.chapter-synopsis]
* Services in and about London, in the years 1823 and 1824.
* Letters, etc.

[.embedded-content-document.letter]
--

[.letter-heading]
To K. C.

[.signed-section-context-open]
Birmingham, Second month 10th, 1823.

[.salutation]
My dear Niece,

No change of circumstances will, I hope,
be permitted to interrupt what I esteem a precious union of spirit:
however imperfect it is, I do hope it arises from a spring unpolluted.
It is a relief to my mind, that your important decision feels satisfactory,
and that calmness seems given as an evidence of right movement.
In all our steppings, this token of higher approbation than our best friends can give,
is truly desirable.
I feel affectionately disposed to receive your friend
as one I could love for his own sake,
because I believe there is a good work making progress in his heart.
O! the condescending Power that begins and carries forward sanctification and redemption;
perfecting the Divine image in the soul.
May you, my precious niece,
be favoured with a faithful helpmate on your heavenward journey!
May you freely dedicate your talents to every service unto
which you may be called! whether separately or unitedly.
Close heart provings strengthen the bond of true union.
I love those who can calmly endure tribulation or conflict,
best known to their own hearts.

[.signed-section-signature]
Mary Capper.

--

Fourth month 9th, 1823.
Mentioned at our monthly meeting at Stourbridge,
a prospect of attending the yearly meeting,
and of some religious service in and about the city of London.
A certificate of unity was granted.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fourth month 17th, 1823.

[.salutation]
Dear M. S.,

I have been concerned to hear of the sickness of your dear children and servants;
this trouble, I trust, is passed over;
leaving the mind farther prepared by experience to encounter the next.
In vain do we look to live at ease, in a world of fluctuations and trials;
neither religion nor the nature of visible things, teaches any such doctrine.
The religion of Jesus, as promulgated in the gospel,
urges the necessity of daily bearing the cross of Christ,
by which we are kept in lowliness of mind, subjection and patience,
looking unto Him who bare our infirmities, and our chastisement was upon Him.
Please to refer to this text; it does not occur correctly to me,
though the precious savour cheers my heart.
I have been under a considerable weight and depression of spirits at the prospect,
under I apprehend religious constraint, of attending the yearly meeting,
with a view to some other engagements.
I believe none can fully enter into the preparatory low dippings,
the humiliating self-abasement, the searchings of heart at such times needful,
but those who, in some sort, have gone through the like siftings,
etc. to fit them for inviting and encouraging their fellow-believers
to lay hold of eternal life and be steadfast unto the end.
Every fresh dedication is a fresh act of faith;
no former experience will avail for present requirings.
For my own part,
I find as much fear and difficulty in decision and in speaking
at this day as in the earlier periods of my life.

May it be well with you, is the affectionate desire of your friend and fellow-probationer.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Cadbury

[.signed-section-context-open]
Warwick, Fourth month 25th, 1823.

[.salutation]
My dear Friends,

I think it will gratify your affectionate solicitude
to have information of my safe arrival thus far,
and that, through condescending mercies, which are new every day,
I am favoured with a calm, lowly frame of mind,
not painfully solicitous as to how I may be disposed of.
In the simplicity of a dependent child,
my heart has craved entire submission and dedication.
Here seems to be my strength, my peace, and my safety;
and here I strive to dwell from day to day.

I have left many very dear, tried friends among you,
unto whom I am bound in Christian fellowship.
All have their secret bitters, their provings, humiliations and distresses.
Their hidden way is known to Him who sees in secret,
and never forsakes his poor suppliant children.
Though our outward path differs,
there is a deep sense that tribulation marks the way to the kingdom;
it is tribulation that works experience, patience and hope;
and thus it differs widely from worldly sorrow, Jesus died for sinners;
to heal their wounds; to seal their redemption I Farewell, my dear friends;
may your peace be sure; Your friend,

[.signed-section-signature]
Mary Capper.

--

Fifth month 7th. The monthly meeting at Warwick was a time of precious union of spirit;
a sweet sense of Divine love was felt among us, in which there is true fellowship.

9th. I left my dear friends under a degree of depression,
in the prospect of a long separation.

[.small-break]
'''

+++[+++This visit to London and its neighbourhood was attended
with many trials to her affectionate feelings,
in the blank occasioned by the death of her brothers, and of many dear friends,
with whom she had been accustomed to take sweet counsel,
and who had been removed from this fluctuating scene, since her former visit;
so that it was evident that she often felt as one stripped and alone;
yet the desire to cherish a thankful spirit, enabled her often to be cheerful;
and the watchful frame of her mind was instructive to those where she sojourned,
as she endeavoured, from place to place, to do her Master`'s will.]

[.small-break]
'''

19th. Reached London on the 14th, and found my dear eldest brother in a weak state.
Passed some days with him, and am now with my nieces, who are in sorrow,
on account of the death of their much loved friend Mary Hanbury,
the only child of William Allen.

29th. After the business of the yearly meeting was satisfactorily concluded,
a very impressive pause ensued, for a considerable time; we seemed reluctant to separate,
so precious was the bond of union and of cordial affection, as one family.
O! that a growing union or fellowship, in the Holy Head,
may be our individual experience; then will there be a harmonious labour,
in our various allotments, to promote the good of the whole.

Seventh month 14th. Attended the morning meeting.
A diary of Robert Searle was partly read: it is the Christian experience of a poor man,
in the station of a servant.
The recital of his conflicts, under the influence of Divine grace in the soul,
much affected, and I hope, both instructed and encouraged me;
seeing the fight of faith is to be maintained, through trials and provings,
however our circumstances may vary.

In the afternoon came to Peckham; here I find an interesting family of children.
The more familiar we are with such,
the more we become sensible how much depends upon a patient, watchful care over them.

17th. My niece and I took tea with Margaret Hagen, a kind friend, in the decline of life.
Her house is beautifully situated in a garden; the calm scene was gratifying,
but a secret sense of spiritual refreshment was more sweet and
encouraging to my soul than all that the visible world can give.
I imperfectly expressed some of my feelings, and we separated pleasantly.

20th. First-day.
The meetings were more refreshing seasons than I have of late experienced.
I dined at Mary Dudley`'s, she, dear woman! is confined by weakness,
and appears to be near the close of her labours and exercises, which have been many.

22nd. Called upon two young women, sisters;
I thought there was a consoling evidence of heavenly and protecting goodness,
while sitting with these dear young women,
and I was thankful that I had had courage to follow the gentle pointing to call.

23rd. After the usual morning Scripture reading,
I had to express my desire for the growth of the
root and fruit of holiness in this family.
I also took an affectionate and serious leave of the servants,
in a manner unexpectedly impressive to myself,
and I believe not quite unprofitable to them; so that I may say,
that after many days of humiliation and some secret distress,
not discovered by outward sackcloth, my weak faith revives a little.
In reverence I note it, as a fresh token of mercy.

24th. We went to meeting; the retrospect is comfortable.
What a privilege it is to retire from the noise and hurry of the busy city,
in order to meet, whether few or many, in religious fellowship;
reverently waiting on the unchangeable Source of mercy, not being soon weary in mind.

Eighth month 2nd. Accompanied Charlotte Dudley to call on a friend;
in a time of religious retirement,
renewed desires were felt after that heavenly power which alone can do us good,
and direct us aright.

4th. Came to T. B.`'s, at Camberwell.
This visit gave me the opportunity of tenderly feeling with a faithful, female servant,
who has lived with T. B. for twelve years, and who is about to leave,
from a sense of gratitude to a brother, now in trouble,
who was like a father to her in early life.
The prospect of poverty and distress does not deter this
affectionate sister from leaving comparative ease and plenty,
to assist her brother in the day of trial.
We had a sweet time together, with a fellow servant, who seemed of a tender spirit.

11th. Attended the morning meeting, with my niece.
In the afternoon, prepared to leave her dwelling,
as the household is about to undergo a change;
these vicissitudes are very impressive and may be instructive.

13th. A very large gathering in Gracechurch-street meetinghouse,
on the occasion of the marriage of my niece.
It was a time of solemnity and quiet.
Comfort and counsel were ministered, and prayer was offered for help,
and wisdom to direct, in all our various stations and duties through life.
I went to Tottenham in the evening.

14th. Went to meeting with my nephew and his children.
My mind was deeply affected with a sense,
that Christian believers must know a breaking down,
before they can experience a building up, in the heavenly power, on Christ,
the chief Corner Stone, elect and precious.
All other foundations must be razed; not one stone left!

15th. I feel much at home here, being left free to pursue my way, as seems best;
my dear niece having considerable domestic occupation, and now, in early life,
filling up, as far as she can, I think, the vacant place of her precious mother.

19th. After rather a restless night, comforted with the thought,
which arose with much sweetness, that the kingdom of heaven,
wherein dwells righteousness, will make amends for all.

A variety of new publications, on many subjects, not uninteresting, and may be,
instructive, are in circulation in most families.
It seems, as far as my observation goes,
that these novelties induce much transient reading, if it may be so described;
but I doubt whether abiding profit, in the useful and substantial culture of the mind,
is thus obtained.

21st. Observed vacant seats at meeting; yet it is pleasant to see that there are some,
especially young men, who do leave their lawful concerns and attend week-day meetings.
This dedication will not surely be time lost, or vainly spent!

24th. First-day.
Both meetings remarkably favoured, as times of waiting for spiritual refreshment,
and witnessing the living Spring measurably to flow.

27th. Took tea with a young couple, and was gratified with the visit.
It is very pleasant to observe young persons entering upon
the important duties of life with seriousness and discretion.

Ninth month 5th. Deborah Stacey kindly called with me,
upon a few friends in their comparatively poor habitations.
It seems right, and in my view, instructive,
that those who abound in ease and outward accommodation, should visit the poor,
and cheerfully give, out of their fulness, a little of the good things that they possess.

11th. The monthly meeting.
A day of some exercise of mind, and considerable weakness of body.
What should we do; where should we find a calm, lowly resignedness of heart and of will,
if the Father of Spirits helps us not?

My certificate was read, and I informed Friends how I had been engaged;
that my movements are not in the usual course of a general visit to families,
but chiefly among the poor, the lonely and the afflicted; and that I have in view,
a meeting for servants, before I leave this place.

13th. This day mostly spent in serene quietness, intermingled with social converse.
These are in my estimation, some of the sweet favours bestowed upon intelligent beings;
freedom of spirit with mutual cordiality, is truly gratifying and often profitable.

14th. First-day.
The morning meeting was a time of sweet solemnity to me, in silence;
and in this I believe spiritual strength is renewed and a pure offering made,
which is accepted.

19th. Dined with Hannah Kilham, who is preparing to sail for Africa.
The meeting for servants in the families of Friends, was held in the evening, and was,
I believe, satisfactory.

20th. Mary Harding accompanied me to Winchmore Hill, through a beautiful country,
luxuriant in gardens, fruits, trees, shrubs and flowers,
which the grateful mind may thankfully admire.
In our way we made a call at Palmer`'s Green,
where we met with refreshment acceptable to the weak body,
and a yet more sweet and precious revival,
in the fresh arising of that which strengthens the life of the soul.
How incomprehensible to the careless, unwatchful, worldly spirit, is this unity,
which is to be felt in the bond of peace!
We were very kindly received under the roof of John Catchpool, with that plain,
simple cordiality which gratifies what I esteem as some of my best feelings.

22nd. A day of unusual fatigue and exercise!
L+++.+++ Catchpool accompanied me, in their convenient little carriage, about ten miles,
and we made seven calls.
In this round, we met with a variety of character and outward circumstances;
some scenes almost of poverty and distress, brought on through lack of care,
industry and prudence.
Thus, when we will mix our own cup in life, we increase the bitters!

23rd. Called on a tender-spirited, pious man, not professing with our Society;
he is afflicted with bodily weakness, though in the meridian of life;
his wife and daughter were with us, and we had a sweet little season of favour together;
in oneness of faith and of spirit, I believe.
O, how precious is this! strangers to one another, dwelling far apart on earth,
brought to acknowledge together the wonderful power of our God!

24th. A very small number give up their time, on these workings days,
to assemble for worship.
The meeting was to me, and I believe to the few present,
a very precious time of fellowship with the faithful and simple-hearted, the world over;
also of very tender compassion for those who rob their own souls of that chaste joy,
of that lovely, gentle spirit of peace, which flows from the celestial Spring.
Returned to Tottenham.

25th. Called on a widow and her son; it was a time of renewed favour;
condescending Mercy, which continues to be ancient and new, tendered our hearts;
and this, as I apprehend, is the daily bread that we are taught to pray for.

27th. A favoured morning at William Forster`'s. After the
Scripture reading we were sensible of an impressive silence.
Dear Hannah Kilham,
who is now on the point of leaving her native country and dearest connections,
for service in a strange land, and among strangers, expressed,
in a very feeling and humble manner,
that nothing short of confidence in her God could sustain her,
in so painful and arduous an undertaking;
and that gratitude clothed her heart toward those who had aided and encouraged her,
whatever may be the result.
We were all tendered and comforted together.

28th. First-day.
In the morning meeting, I found relief,
in the expression of my firm belief in Christ crucified,
as the Reconciler of fallen man to the favour of God; that in Him, our glorified Saviour,
we have redemption, and acceptance with the Father;
and that there is no other foundation than this which is already laid, etc.

29th and 30th. Attended the quarterly meeting.
Some were absent, on the account of the death of Mary Dudley; thus are we stripped,
from time to time!
Came to Clapham.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Clapham, Tenth month 6th, 1823.

[.salutation]
My dear Friend,

Your love manifested in your letter was never more acceptable.
My almost continual prayer is, that our faith may not fail,
even when blind and not discerning the Hand that guides.
To be kept quiet, and still looking to the only sure Helper,
stripped and wholly dependent, is a safe though humiliating state.
There are times when we desire no other, than to be kept in our right allotments,
however trying to our nature.
Ah! we know, in our measure, that a glance of Divine approbation,
a ray of a Saviour`'s love, makes up for all privations; for all that we can suffer,
in this our pilgrimage.
This is not our rest; we seek one to come; full, complete in Jesus, the resurrection,
the life eternal, the light, where darkness cannot enter!
As I awoke this morning, very low and weak,
my mind in some perplexity as to my next steppings,
and how I am to creep through the approaching winter,
the name of Jesus seemed to arise with uncommon sweetness, and to bring with it a calm,
in which I desire to keep still, without attempting to "`awake my Beloved,
until He please.`"
It is consoling that I feel assured you understand this, and a great deal more than this,
without my being more explicit.

[.signed-section-closing]
In tender love subscribes your friend,

[.signed-section-signature]
Mary Capper.

--

Tenth month 6th. Dined with Thomas Brewster;
a friend in whose house I stayed a few weeks many years back, at Woodbridge,
when his sister Hannah, afterwards Alexander, lived with him.
His own family is now grown up.
I felt constrained to refer to days past,
and to commemorate the mercy that I trust has kept us,
through many changes and many trials, on Christ, our hope of salvation;
the Rock that stands sure, in the midst of floods and storms!
May we, with reverent gratitude, take courage and press on; not as having yet attained,
but reaching forward to the mark!

8th. At Gracechurch street monthly meeting, my mind was much tried; we know not,
at all times, the cause of secret trials and siftings.
I do desire an increase of patient endurance.
I expressed a little, but I know not why it is, I rarely obtain relief in meetings;
yet I am not conscious of wilful omission or commission.
I desire instruction day by day, that I may not err, nor hurt the right spirit in any;
nor wound it in myself.
O! it is a great thing to be kept in a humble and discerning mind.

9th. Hannah Messer read to us a remarkable account of a female, in a low station,
at Yarmouth, who devotes some of her time to reading the Scriptures,
and instructing the prisoners, etc.
It is wonderful how much this individual has been enabled to do,
in the reformation of those who have come under her care.
She gains her own living by industrious labour,
devoting one day in the week to her benevolent engagements.

12th. First-day.
Wandsworth.
I cherish the belief that our religious meetings, whether consisting of few or many,
and whether times of silent exercise, of suffering humiliation, or of secret rejoicing,
are to the sincere, times of pure instruction.
In the afternoon meeting, I thought a little life arose among us, toward the close;
we must ever bear in mind that this best good must be patiently waited for.
From time to time, obstructions may arise; nevertheless if we faint not,
there surely will be a rich reward.

15th. At Croydon meeting.
A large proportion of young persons.
An earnest solicitude is felt,
that by this class in every denomination of Christian professors,
Christ crucified for the sin of the world, may be believed in,
and received in every heart, as a Saviour and a Redeemer;
by the shedding of whose blood we are washed; and by whom, as the new and living Way,
we have access to the Father.
Dined with the widow of Frederic Smith; she seems to be waiting, in humility and faith,
to be soon united to those, who, having passed through great tribulation,
and had their garments washed white in the blood of the Lamb, are surrounding the throne,
with palms in their hands.--Returned to Wandsworth.

16th. At meeting, on taking my seat, my spirit was clothed with solemnity,
and if I may so say, entered into deep, secret exercise,
on account of those who walk in a tribulated path, much unnoticed; it may be, unknown.
This spiritual baptism seems to me, too little experienced,
in these days of comparative ease; and dwelling as in ceiled houses,
with gratification in outward display.
But there are an afflicted few, with whom my heart seems to unite;
and so I think it was this day, both in and out of meeting.

18th. Had a little friendly communication with the dear young people at Ann Masters`'s,
also more privately with some of them, before taking leave;
which I did under a sense of their kindness,
and a desire to withhold nothing that I ought to make known to them.
I believe that friendship would be truly valuable,
and our mutual interactions instructive, did we speak to, rather than of, one another.

19th, First-day.
At Southwark meeting.
O! how I did desire that we might not be a superficial people,
nor be satisfied with a nominal religion, but that we might in sincerity,
humility and earnestness, seek and find Jesus of Nazareth,
the crucified Saviour of the world; the Redeemer and the Mediator,
by whom alone we can draw near to the Father.
O! this important truth; how it presses upon my spirit, in meetings and in many companies.
I fear it is not sufficiently pondered in the heart.

22nd. At the Peel monthly meeting.
The meeting for worship was, I thought, favoured with an encouraging evidence,
that mercy is not withdrawn from us, as a Society; that the humble and dependent are,
from time to time, spiritually strengthened.
I mentioned my prospect of visiting families.
My mind was favoured with freedom from anxiety as to the future.

26th, First-day, Dined in a family who profess with us,
but no way opened for a religious visit;
it was therefore perhaps the best I could do to be quiet; though I felt sad,
and mourned over that indifference and dissipation
which stifle the good that might arise.
In the evening, I was in a very different family; there was ability to express,
and openness to receive, what arose as counsel, caution or encouragement;
and we were comforted together.

Eleventh month 2nd. First-day, Christ rejected was the awful subject of contemplation;
and in unison with something similar, spoken by an exercised minister,
the matter was farther enlarged upon,
with the sincere desire that it might impress every mind.

3rd. A favoured time in a poor family;
in the fresh sense of heavenly kindness being manifested without partiality,
both to rich and poor.
It was a time of prayer and contrition of heart.

4th. Though unwell, I thought it best to pursue the plan laid out;
as I would rather suffer inconvenience than give trouble,
or disappoint those who expect a call.
Having to go a considerable distance to a poor family,
and the wind being very boisterous, I was conveyed there.
The mother and children were in waiting, and the father, a labouring man,
soon came from his work.
It is instructive thus to visit those who labour for their bread, and are honest,
frugal and diligent.
There seems a blessing upon these; and among them is granted a nearer access in prayer,
than with those who live at ease, in their sumptuous dwellings.

Twelfth month.
28th. A meeting was held for servants and apprentices employed in Friends`' families.
Allusion was made to the lowly birth, and to the example of the Lord of life and glory,
who was, among men, as a servant; also to the exceeding great love of God,
and to the forgiveness of sins,
through the sacrifice of our Lord and Saviour Jesus Christ, the Sent of the Father;
purifying our hearts from unrighteousness, by the sanctifying power of the Holy Spirit.

Thus close my very slow movements through this monthly meeting,
and a quiet assurance clothes my mind,
so that I thankfully hope that no presumption or wilful negligence,
has been permitted to take place.
I desire to come under the searching Power that knows all things,
and sees me just as I am.
I covet no false covering, nor any subterfuge.

30th. At the quarterly meeting, Sarah Grubb was led to speak, with wonderful power,
against the Babylonish mixtures, in which, as a people, we are mournfully involved,
at this day.
We have faithful testimony bearers.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
London, Twelfth month 30th, 1823.

[.salutation]
My endeared Friend,

How fares it with you?
It is long since I had a line from you, but I feel assured that,
you will unite in my feelings of lowly thankfulness,
when I tell you that I have been mercifully led, in my solitary path of apprehended duty,
to close the protracted engagement in the Peel meeting;
the extent of the widely scattered families far exceeded my expectation.
A meeting was held for servants, etc. which was well attended; and my secret hope is,
that it was crowned with the presence of our dear Lord and Saviour,
and that a measure of his precious power was over all.
Thanksgiving and praise be rendered for his enduring mercy and condescending love,
which is yet stretching forth the Shepherd`'s crook,
to gather the wanderers to the one true fold.
Farewell, my precious friend.

[.signed-section-closing]
Your attached,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, First month 2nd, 1824.

[.salutation]
My beloved Friend,

Your affectionate salutation reached me, after I had dispatched my last to you.
I am now resting for a time with my niece.
I send you my memorandums, which are scarcely worth perusal;
I have considered myself as a little one, in leading-strings,
mercifully kept from "`wills and wont`'s,`" from choosing or refusing;
going forward or stopped by the way, just as my tender,
watchful Leader opened the path before me.
O! what shall I say of his mercy and condescension to one of the least of his flock!
Let Him, the good and gracious Shepherd, be praised!
Do not, my love, think your honest dedication is unacceptable.
O! that there were more, simple, dedicated, faithful servants, in all places.
How would Zion`'s borders be enlarged, spiritual strength increased,
and those streams flow as a river, which make glad the heritage!
Well! we must do whatever we can, and possess our souls in patience.

I dare not name a time for quitting this vicinity; when it arrives,
it will be hailed as a favour.
Yours,

[.signed-section-signature]
Mary Capper.

--

First month 1824.
I am now favoured to partake of a peaceful calm,
at my niece S. C.`'s. Much spiritual enjoyment I look not for;
many things obstruct the feeling of joy; but lowly peace,
with the evidence of being kept by a gracious Lord, in a plain, simple path,
is enough to satisfy the poor, exercised travailing soul.

13th. Visited Esther Whiting; she has long been in a tried state, and is nearly helpless;
the earlier part of her life was passed in faithful service,
in the family of my brother Jasper, and she now enjoys an annuity, from his liberality,
which is some alleviation.
Her mind is calm, and she expressed a desire to be patient,
and to experience the operation of that redeeming,
sanctifying Power which could prepare her to die
in peaceful confidence in her Saviour`'s love.

19th. First-day.
Not without trials of faith and patience.
Too few rightly prize the privilege of the time set apart for public worship.
So lightly, or frivolously, are some minds occupied,
that our meetings for worship are often oppressed;
the light and life which might arise are pressed down, and we are not comforted together;
nevertheless the humble,
resigned and faithful ones may be encouraged still
to wait and to hope for the renewal of their strength.
I thought there was more life to be felt in the afternoon meeting,
which ministered some encouragement.

21st. Accompanied Sarah Foster to Plaistow monthly meeting,
from which Elizabeth Fry took me to Plashet, where a room was allotted to me,
to pursue my own occupations, or join the family as best suited me.
Their family party is large, and their dinner-hour late.
I usually dined and took tea with the children, and joined the family in the evening.
I endeavoured to be present at the morning reading of the Scriptures,
which was mostly an impressive time.
Sometimes I had the privilege of Elizabeth Fry`'s company in my apartment;
but almost every hour of her time is importantly occupied,
in benevolent exertions for the poor and miserable;
much depravity comes under her notice.

What should we do if the foundation on which a believer`'s faith is built were
not sure! but it is confirmed to us by the living Power that cannot fail;
"`the foundation of God stands sure.`"
Rest, O my soul, in this; although storms may arise.
Ah! you poor benighted sinners, may Light mercifully beam on your souls,
and bring conviction for sin!

Second month 1st. First-day.
Plashet cottage.
I have, for about a week, been kindly cared for, in this calm, lovely retirement,
the habitation of Joseph Fry`'s sister.
I was a little relieved by some expression of my feelings, in meeting this morning;
but alas! the anointing Power, the abiding sense of redeeming love, seems low;
patient suffering is the lot of believers; resignation gently smoothes the way,
and faith is an anchor to the soul in the day of trial.

3rd. The weather is now very fine and mild;
the spring flowers open their cheering beauties,
the little lambs are brought forth in the fields; these are interesting objects.

8th. First-day.
The morning meeting was a time of close exercise,
in exhorting and endeavouring to arouse the careless professors.
O! that there was an awakening from a state of ease and deadness,
as to the spiritual life! the afternoon meeting lively;
the evening passed in a calm frame of mind.

11th. Was some hours alone with Sarah Sheppard; this was very sweet to me,
as this dear friend, being very deaf, seems to dwell as in the closet of prayer,
the door being shut.
It was refreshing to sit with her,
as with one who is preparing for a kingdom where all infirmities will be done away.
I hope to remember with profit,
the privilege of being admitted as a familiar friend under this roof.
This dear friend employs herself industriously, in reading,
in working for her numerous grandchildren,
and in attending to abundant applications from the surrounding poor.

12th. Passed the day quietly,
enjoying mutual communication and interesting reading at
Edmund Fry`'s. These allowed intervals are to me gratifying,
even in my present increased years; though not strongly bound to earth or earthly things,
I have a pleasure in contemplating talents improved,
inventive powers and genius rightly applied.

17th. At the monthly meeting I produced my certificate,
and proposed going into the families of Ratcliff meeting.
A feeling, humble-minded, valuable minister, Mary Marsh, expressed her unity,
and her willingness to join me, which was acceptable to the meeting,
and truly cordial to me.

19th. We had three sittings, in which we were favoured with an encouraging hope,
that our engagement was under the direction of that Power which keeps out of error.

22nd. First-day.
I thought more solemnity and settlement of mind prevailed in the meeting,
than in some where there is more expectation of outward ministry.
A precious feeling clothed my spirit.

Third month 1st. We had several very interesting sittings, and may truly say,
how various are the allotments of individuals and of families!
We certainly see through a glass darkly,
and can make but a very imperfect estimate how all
things work together for good to those who love God.

5th. Great indeed is the variety which comes under
the notice of those who thus go from house to house.
Our Guide must be steadily kept in view,
that we may not look on outward things and judge thereby.

10th, We hope to conclude our engagement this week.
A desire daily clothes my spirit, that I may be led safely along;
neither too much cast down,
nor in any degree rising above the rightly directing gift of Grace!

11th. We took tea with Elizabeth Emerson, a valuable Friend in advanced life;
of a tender spirit; encouraging to those who are younger and less experienced.
We also had a time of entering into sympathy with
a Friend and his wife who are in difficult circumstances.
There are several individuals and families, in the environs of this vast city,
who are so situated as to claim tender care, and Christian notice.

12th. We were conveyed in a carriage, as far as it could safely go, and then walked,
to the humble dwelling of a poor Friend; and while sitting with her,
by her little fireside, I think we had afresh to believe,
that the great Giver of all our mercies condescends to comfort those who seek Him,
and who trust in Him.
Among the hidden ones, the poor and the lonely,
we have at times been refreshed together with what
is far better than all that this world can give.
We also visited a family, some of whom were not members of our Society;
we met with a kind reception, particularly from the husband,
whose mind is very susceptible of good impressions.
It is not a name, neither is it forms, nor the relinquishing of outward forms,
which can bring us into possession of the inward and spiritual grace.
A new life, a spiritual creation, a death unto sin and a new birth unto righteousness,
are the genuine effects of believing in Christ,
of cherishing and obeying the teachings of his Spirit.
We paid a very interesting visit to an old man in Trinity Almshouses,
who had been a pilot in early life; he has a very neat, commodious, quiet retreat here.
I think he married out of our Society.
He is much respected, and his appearance is very striking; he is eighty years old,
a fine, manly figure, with an animated countenance; he has long been painfully afflicted;
yet he appears patient and contented, and manifested tenderness and feeling,
with a grateful sense of the blessings continued to him.
He expressed thankfulness that he was remembered and visited by Friends,
whose meetings he attended, as long as his infirmities would allow.--In the evening,
we sat down with Joseph Fry and family.
There is a uniting power in religious fellowship,
which diminishes not with time.--This brings us near the conclusion of our present engagement;
no great things have been attempted; if we have been in the way of our duty,
I believe we desire no more;
a peaceful acquittal will be a sufficient recompense for our small labours.

14th. First-day.
Low, but feeling no condemnation.
I consider it a favour to walk in the valley of humility.
At both meetings and in three religious opportunities,
I thought the best life triumphed over human weakness.

15th. Dear Mary Marsh and I dined in Whitechapel,
with the Friends who showed me so much kindness at Leamington.
I parted with my kind, humble-minded companion, under comforting feelings.

17th. Attended the marriage of one of my dear nieces, and we dined at Clapton.
The day was very fine, and all around was pleasant,
with a calm cheerfulness becoming the occasion.

26th. Clapton.
I have been resting here, in bodily weakness; this,
under the sanctifying influence of heavenly Grace,
maybe one of the means whereby a dependent mind is brought into subjection,
humility and true resignation.
Dear Esther Whiting`'s sufferings have now terminated; I went one day to see her;
there was a sweet sense that heavenly Goodness was near,
though the powers of nature were failing.
May we seek the Lord, in the days of health and vigour, that He may be our support,
when human aid is of no avail!

28th. First-day.
I walked to Tottenham, and was favoured to receive spiritual refreshment.
Dined with Tabitha Bevans and her sister.
I thought we were united in that fellowship which flows from a belief in God,
and in Jesus Christ, by whom we come to God.

29th. Attended the quarterly meeting of ministers and elders,
and spent the rest of the day very pleasantly, with my dear sister Rebecca Tibbatts;
it is satisfactory to see her comfortably settled with her son.

Fourth month 1st. On sitting down in the meetinghouse at Tottenham,
after the interment of Esther Whiting, a precious feeling stayed my mind,
in contemplating the kingdom where the redeemed of the Lord
will forever unite in thanksgiving and in holy rejoicing.

2nd. Came to stay a few days at John Lister`'s, Stoke Newington,
in order to call upon some of the few remaining here,
with whom I was formerly acquainted.

3rd. In our calls, met with scenes of sorrow; saw William Allen`'s little grandson,
bereaved of a young and lovely mother, and visited some young friends,
whose parents are both deceased since I was last under the
roof of my dear brother and sister in this place.

4th. First-day.
Attended the meeting at Gracechurch-street.
A day of some fatigue of body, and trial of mind.
If in all things we are taught to profit,
whether by a fresh sense of our own imperfections,
or a sight of weakness in others where we did not expect it, it is no matter;
instruction may remain for future benefit.

5th. Mary Lister called with me on Margaret Allen.
She is reduced to a very weak state,
yet there seems a lively sense and savour of that which is better than natural life;
and my heart believes this will reign triumphant when the grave shall claim the poor,
perishable body.

6th. My usual hour of rising is now six o`'clock.
The mornings are cold, but not unpleasant; a little turn in the garden,
to observe the progress of Spring, in the vegetables and flowers, seems refreshing.

15th. Some time was very agreeably spent in reading
extracts from the letters of Hannah Kilham and others,
now benevolently engaged in the instruction of the natives of Africa, on the Gambia.
These people appear to be living in a disorderly state,
far from enjoying domestic happiness.
May such as are more favoured thankfully estimate their own privileges,
and contribute to the instruction of others!

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Clapham, Fourth month 17th, 1824.

[.salutation]
My beloved Friend,

I send some extracts from letters of Hannah Kilham, etc.
I wish some liberal-minded Friends in the country, who devise liberal things,
would read the reports,
and find their hearts disposed to add their names to the subscribers,
or transmit a donation.
I think it would be a source of satisfaction, upon serious reflection,
in days yet to come.

Never I think my endeared friend, did I more feel the force of the words,
"`rejoice with trembling.`"
Every returning day and hour brings some proof of weakness,
some disclosure of what is hidden in the heart;
unlooked for circumstances arise to ruffle or disturb us.
O! how pure is that calm, that peace which descends from the Spirit of the Lord!
How different from the spirit of the world, from unsanctified self,
from the unsubdued natural temper!
The state of my own heart leads to these reflections, and to the earnest prayer,
that I may maintain the watch against the cruel enemy.
Farewell, affectionately, my dear friend.
Yours,

[.signed-section-signature]
Mary Capper.

--

17th. It renewedly impresses my mind,
that when a family meet together in health and safety,
to partake of the first morning refreshment, there is a propriety in a serious pause,
and a grateful recurrence to the Source of all our daily mercies.
I am satisfied that we cannot too frequently recollect, that every hour in the day,
we have need of the extension of that Power, by which alone we can be kept from evil.
We separated this day, from the breakfast table, I hope, under profitable impressions.

18th. First-day.
A day of serious engagement.
Oh! for an increase of spirituality, and more entire sanctification.
My anchor of hope is in the Redeemer, to cleanse from all sin.

19th. Came to Clapton.
The weather is mild, and the country beautiful, yet my spirit seems sad, and I am poorly;
but I ever think it right to cherish a lively hope and consolation in the mercy of God,
in graciously providing a Mediator, a Saviour!
Without this hope, this consoling faith, what should I, what could I, do!

21st. In this young and growing family,
there is ample subject of interest and serious occupation.
I had a delightful walk with my young nephew, the eldest child.

22nd. Was gratified in walking, with a little party, to Tottenham meeting.
Our long devoted and experienced friend, Thomas Shillitoe,
spoke with feeling and earnestness, on the subject of entire resignation, or subjection,
to the will of our Heavenly Father; that its effects were peace.
Probably few are better qualified to elucidate this subject;
as his life seems devoted to the fulfilment of apprehended duty.

27th. Came to William Cawthorne`'s, at Somers Town, in Westminster quarter,
this being the only meeting of our Society, near London, that I have not attended.
I cherish the hope, that by and by, I may return, without any painful retrospect,
to the enjoyment of my own home, and more select and endeared friends.

29th. The meeting proved to me a time of comfort,
with a little fresh ability to encourage others to seek after the knowledge of God,
and faith in Jesus Christ, as the Saviour,
by and through whom we are redeemed and accepted.

Fifth month 10th. Left my kind friends at Somers Town; our separation was mutually felt,
apprehending that we might thus meet no more,
as dear William Cawthorne seems in declining health;
patiently and even cheerfully bearing his bodily weakness and harassing cough.

17th. Yearly meeting of ministers and elders.
Though many labourers in years past are now gathered to their final abode,
there yet remains a faithful few.
Among those who have seen many days, and kept close to that holy Power,
which can keep us from fainting by the way; it was cheering to see William Grover,
still active and useful; also James Howarth, etc.; and among the mothers, Mary Proud,
Rebecca Byrd, etc.

19th. Women`'s yearly meeting.
A full gathering,
and something like a fresh evidence that we are still
a people waiting on the Lord for his blessing.

20th, A testimony was read concerning James Birch.
It set forth a character remarkable for simplicity;
faithful to the Grace or Light of Christ manifested in the soul, which, as it is obeyed,
will ever be found powerful to regulate throughout,
and to sustain the soul in every conflict in life, and in the hour of death,
as this dear Friend did experience.
There was also a testimony respecting Elizabeth Foster.

I knew her in former years; she was of a lively turn of mind, which, at that day,
almost revolted at the idea of the sufferings needful to subdue the will,
and bring all into subjection;
but the sanctifying power of the Holy Spirit wrought the great change,
and brought low all that was lifted up, or opposed to the cross of Christ.
She could declare her experience of the marvellous mercy of God, in Christ Jesus,
and she closed her day in peace.

In the afternoon an impressive testimony was read, setting forth the early dedication,
exemplary life and peaceful death of Mary Hanbury, in her twenty-fifth year;
the only child of William Allen.
Many young minds seemed affected, and I thought the desire prevailed,
that the purifying Word of power might do the same
great work of sanctification for all of us.
A precious time of stillness succeeded;
and then a recommendation to be serious and retired in spirit,
and earnest in watchfulness and prayer.

21st. Much was expressed, setting forth our faith in the Scripture doctrines,
concerning the propitiatory Sacrifice, etc.

27th. Our honourable and aged friend, Mary Proud, was enabled,
under much bodily weakness, in the strength afforded, to kneel,
and powerfully to commend the keeping of our souls
to the mighty power of a faithful Creator.
The concluding minute was read, and after a solemn pause, we separated.

Sixth month 2nd. My sister Grace Capper conveyed me to Snaresbrook,
to spend a few days at the beautiful country residence
of my kind and much loved brother George;
for whose uniform affection I feel very grateful.

5th. I think my dear brother seems rationally and
thankfully to enjoy his house and grounds,
on returning from business in the city.
It is one of my gratifications,
to find a thankful mind in the midst of worldly possessions and prosperity.
His carriage brought me this day to Tottenham.

6th. First-day.
Dined with Alice Chorley; a friend whose long-proved integrity, and plain,
honest dealing and speaking, I do admire and respect.

7th. Favoured to feel the thankful hope, that I have not been forsaken,
nor left to my own devices, in my solitary stoppings,
in the course of which I have had many searchings of heart.

9th. At Gracechurch-street monthly meeting,
I felt a concern to go into the men`'s meeting; G. Birkbeck kindly accompanied me.
To myself, it was a very serious time;
I endeavoured to open the view then given me of the
purity of that life which is hid with Christ in God.
I think I felt the awful import of the subject,
and a sincere desire that I might not exceed in words.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
London, Sixth month 10th, 1824.

[.salutation]
My very precious Friend,

I have often thought, since separated from you, and your dear sister Lamley,
(both of you faithful testimony bearers whom I dearly love,) that
vast is the difference between fine speaking and that humble,
lowly, self-denying life, shown forth in the silent, persevering example of a meek,
consistent walk, as in the presence of the Holy One.
For myself and for others, I have been distressed and oppressed;
I have had close provings and deep trials; but in abundant mercy, the thick cloud,
is in degree, dispersed, and a renewed dawn of consolation and of confidence arises.
That Divine Power which delivers my life from destruction, again gently breaks forth.
I note it with reverent gratitude.

[.signed-section-signature]
Mary Capper.

--

Sixth month 11th. Came to the house of my dear brother John,
where I think of remaining a short time;
and if permitted to leave this great city in lowly reverence and peace,
and charity towards all the world, I think I shall be thankful.

14th. We had some sweet portions of reading after breakfast,
and a silent desire arose to be strengthened to live and abide in the purifying,
redeeming spirit of the Saviour.
It seems a growing experience with me,
that there are favoured seasons when a deep inward
sense of the work of sanctification and redemption,
seals the lips in solemn silence.

20th. First-day.
Having made many calls last week, I attended the Peel meeting,
and was enabled to express an affectionate farewell desire,
that the love of God might increasingly abide in our hearts,
in which love we should have fellowship one with another, when personally separated.
My mind was comforted, and a lowly calm clothes my spirit.
Dined at John Eliot`'s, who conveyed me to my brother`'s,
where we passed the remainder of the evening in serious reading, etc.
What a favour, that amid diversity of operations, a precious harmony prevails,
where the Redeemer is believed in, and his Spirit owned,
and permitted to work in us and for us; teaching to bear and forbear,
in meekness and love.

21st. Several of my dear relations called on me, and we separated in much affection,
which sweetened the parting, even if we should meet no more!
Spent most of the day in calmly enjoying the company
of my brother and sister and dear niece Selina.

22nd. After breakfast my heart was renewedly filled with a grateful
sense of the merciful dealings of our Heavenly Father with us,
as a family; that in our different situations in life,
and modes of manifesting our religious faith, we all agree in the great, essential truth,
that to know God and Jesus Christ, so as to obey, is life eternal.
We had a solemn time together, I hope in the unity of the Spirit,
which may yield us comfort and encouragement, at some future day.
Accompanied by a kind friend, I left London in the afternoon,
and travelled about twenty-four miles, to W. L.`'s delightful habitation,
near Berkhamstead.
My mind is in a low, yet calm state; with serious recollection of affectionate relatives, etc.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Sixth month 23rd, 1824,

[.salutation]
My dear Friend,

Yesterday I really turned my back upon the great city of London,
and was soon set down at this neat, little dwelling.
The transition from smoke, dirt and noise, is very striking, but my spirits are low.
I cannot suddenly rise above the deep feeling,
left by a solemn parting from many near relatives;
yet I am thankful in being able to say I am without painful accusations;
and surely this is enough, in a world where offences will come,
and where evil abounds on every hand.

Oh! it is a mercy to be permitted to return towards my own dear friends, even thus far;
in a sound mind and in rather an improved slate of health,
I do not puzzle much about the means of getting forward,
as way has been marvellously made for me.
I am now drawing nigh to the completion of every object I had in view when I left my home.
I am humbled in the retrospect,
and desire no higher joy than the peaceful assurance that the precious Truth,
as it is in Jesus, has in no way suffered through me.
Very affectionately,

[.signed-section-signature]
Mary Capper.

--

28th. Came to Banbury, where I was cordially received by J. and M. Gillett,
who have removed from Shipstone.
Attended the quarterly meeting of ministers and elders.
William Byrd, his wife, and George Withy were there.

30th. The sight of my friends at Shipstone, where I attended meeting today,
and their kind demonstration of affection, undiminished by long absence,
was more affecting than I could well bear.
Dined at dear Sarah Lamley`'s, at Tredington, and proceeded to Warwick,
where I enjoyed the long desired gratification of seeing my very dear
Christian friend and fellow traveller in this probationary state.

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Cadbury

[.signed-section-context-open]
Warwick, Seventh month 3rd, 1824.

[.salutation]
My dear Friends,

I was safely conveyed here on fourth-day,
and dear H. E. received me with cordial affection.
She is looking worn and poorly; her dear sister, R. Lamley, is in a weak state,
though somewhat revived.
Her countenance is wonderfully bright; expressive, I think it may be said,
of a spirit redeemed from evil; her conversation is sweetly innocent,
about the place where angels dwell,
although she thinks that a cloud veils these glorious things from her.
Ah! it is precious to believe that this veil of human infirmity will, before very long,
be rent, and an entrance given into the everlasting city,
where the Lord God and the Lamb are the light thereof My mind is calm;
no distressing retrospect.

I trust I may safely say,
I am satisfied with the secret evidence that my gracious Lord condemns me not.
O! `'tis his favour that keeps in peace, resigned,
and even thankful to be numbered among those who
partake of the tribulations of the gospel,
and who are, at times,
permitted to rejoice in hope that consolations will more and more abound,
letting patience have her perfect work.
I could not manifest to my dear friends what I felt,
at once more being permitted to see their faces.
It was not insensibility; it was not diminished affection,
or diminished interest in that which binds us as links in one chain.
Do tell this to such of my dear friends as I might seem to overlook.

I have no evil tidings to report;
whatever may be mingled in the cup of the true believer
in the mercy of God in Christ Jesus,
all will be well; and in the end, life, light and glory will arise and shine forever!
Farewell, dear friends.

[.signed-section-closing]
Your affectionate friend and fellow-sojourner,

[.signed-section-signature]
Mary Capper.

--

Warwick, seventh month 11th. First-day, Many days have now passed over,
in the sweet enjoyment of one another`'s company, as a little social band.
Rebecca Lamley gradually gaining strength; her mind clothed with simplicity,
gratitude and love: Sarah Lamley is also, at present, one of our favoured circle;
for it is a favour to me to make one with the lowly, the poor in spirit,
who desire to possess their souls in patience, and hold fast their integrity to the end.
No joy is like unto having the evidence that the Lord is on our side!

12th. My dear friend Hannah Evans and I went to the county jail,
having learned from our friend, E. Tatnall,
that there were some female prisoners for whom she felt considerable solicitude;
particularly one in very precarious health, who seems penitent.
We were introduced to three in one ward.
The poor young woman, specially alluded to, was sitting, decently dressed,
in an arm-chair.
It was truly affecting to see, within the walls of a prison, under locks and bars,
a sister by creation, with the appearance of talents,
and of delicacy above the common standard.
They were all committed for a misdemeanour.
Enduring Mercy, which penetrates even prison walls,
yes! the strong hold of the hard heart, was, I do think, manifested,
to the bowing of our spirits together, and the prostration of our souls in prayer.
We went through all the female wards.
In the afternoon I took an affectionate leave of my precious friends,
and came to Birmingham, where I was cordially received at my ever kind friend`'s,
Richard Cadbury`'s. Sweet thankfulness, in mercy clothes my spirit.

14th. I returned the certificate, granted me last year, for service in and about London;
which, having endeavoured to perform to the best of my ability,
I am favoured to return home in a thankful frame of mind; feeling, at times,
something like the simplicity of a harmless child, with the approbation of a tender,
reconciled Father.
O! merciful condescension;
with which no earthly possession or gratification can be compared.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Dale End, Seventh month 29th, 1824.

[.salutation]
My very kind Friend,

Your last communication has been cheering to me;
to learn that weakness and infirmities are borne with meek endurance and resignation,
is precious, as a confirmation that heavenly help is nigh,
even that power whereby Divine Grace triumphs over human nature.
Doubt it not, my Christian friends; I dare not question, or doubt it;
"`That which has helped us hitherto, will help us all our journey through.`"
Naked faith, without claim of merit in ought that we can do is the anchor of my soul.
O! what a mercy, in old age, to rest in redeeming love;
a Saviour crucified! a Saviour glorified!
May we happily be among those who centre here.

When you see E. Tatnall, my Christian love is to her,
with the expression of the animating hope that she
will be helped to hold on in well doing.
I remember the poor female prisoners with very tender feeling.

[.signed-section-closing]
Very affectionately, I subscribe,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To R. and S.

[.signed-section-context-open]
Eleventh month 19th, 1824.

[.salutation]
My kind young Friends,

While I decorated my windows and little apartment with the
yet remaining beauties of a rich and luxuriant summer,
how could I do otherwise than think of the great,
benevolent Power that liberally bestows,
and fits the awakened mind to enjoy the outward blessings that surround us!
Even in the smoky, dense atmosphere of active commerce, and busy streets,
there are times of cheering reflection, and transient views of happier,
purer scenes than we can now see.
I am sometimes favoured to participate in a glimpse of that renovation,
that new creation, wherein old things shall have passed away, and we, being born again,
shall rejoice in the new heaven and the new earth.

Thus I thought of you,
as your kind attention furnished me with the means of present gratification.
The flowers are fresh and beautiful.
Accept my very affectionate acknowledgment, and my heart-felt desire,
that lowliness of of mind, sweet peace, and assurance forever may crown all.
With tenderness and love, I subscribe,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Eleventh month 29th, 1824.

[.salutation]
My long known and valued Friend,

Had you and your dear connections been much less in
my remembrance than has really been the case,
the receipt of yours would not have failed to revive the sincere love,
the desire of my heart, for you in years past;
when I first saw you in the simplicity of a schoolgirl,
and in your growing usefulness to your precious mother,
when she was stripped and bereaved.
The after steppings which have marked your life, so far as they have been known to me,
have obtained my tender regard, and I may perhaps safely say, my Christian solicitude,
that Grace, Mercy and Truth may be magnified in and through you.

Parental duties, etc. make a Christian`'s life serious and important.
What, less than a Christian`'s own experience,
can qualify a parent to "`bring up a child in the way he should go?`"
It is pleasant to call to mind being with you; when, notwithstanding busy,
moving scenes around me, activity in which it was not my personal concern to enter,
I could enjoy interior quiet, cheerful calm,
with a sense of goodwill toward every living creature; and I feel a persuasion,
dear friends, that no lawful station, no honest pursuit, precludes from the love of God;
and that, through this, all the toils, the lawful cares, and the troubles of human life,
may work together for instruction, correction, and perfecting the Divine Will.

When, or if ever, I may again fill the well-remembered corner chair, time must unfold;
as yet I have no glimpse of it; nevertheless my love remains undiminished.
In tender affection,

[.signed-section-signature]
Mary Capper.

[.postscript]
====

P+++.+++ S. I wish to have my Christian love expressed
to+++_______+++. It is a great mercy to be kept,
by the power of God, steadfast and without wavering, as to the object of our faith,
through all the trials of our probationary state, to be abased, to suffer want,
and sometimes to witness Grace to abound, and in all things to be instructed,
to be humble, contrited, thoroughly sensible of our dependent state, at all times,
and on all occasions.
This is mercy! all mercy!

====

--
