== Chapter XIII.

[.chapter-synopsis]
* Death of her brothers John and James
* Reflections
* Extracts from letters, etc., from 1835 to 1838
* Deep spiritual conflict
* Relief therefrom

__Reflections On the Fluctuation of Thoughts.__ First month, 1835.
It has a little opened to my understanding,
that as involuntary thoughts are not at our command,
we are only responsible as we willingly cherish, and bring them into action.
Secret evil suggestions, which we cannot prevent,
arising probably from the yet-permitted power of an unsanctified spirit,
are not our thoughts, so long as they are a grief and burden to our hearts;
and truly they are humiliating, permitted doubtless in order to humble us,
and to show us what yet remains of the unrenewed, evil nature, or it is possible,
that after having measurably experienced, yes! testified,
to the power and efficacy of redeeming Love,
we might be tempted to conclude that the great work of sanctification was complete,
and thus be lulled into a false rest, and forget, or neglect, the important injunction,
"`Watch and pray!`"

[.small-break]
'''

__Memorandum.__ Third month 4th, 1835.
This morning`'s post brought the affecting tidings,
that my dear brother James Capper died in London; he was a dearly loved kind brother.

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Third month 12th, 1835.

[.salutation]
My kind Friend,

Your unfeigned sympathy is truly cordial to me;
also your kindness in sending the lovely harbingers of spring,
which now adorn my apartment and cheer me.
I thought, as I separated them,
(and now think with a sigh of tender sadness) could
my beloved brother James have entered my room,
he would have admired their beauties, and said, with his usual courtesy,
"`And how nicely sister Mary has arranged them!`"
Ah! how memory brings to mind his gentleness in early life,
his patience with my untowardness; and in maturer days,
his liberality in pleading my cause,
as being of an age to judge for myself respecting
the most acceptable way of worshipping God.
I do not remember ever to have heard an unkind word from his lips, or a harsh censure,
on any occasion.
My precious brother was, for a season, deeply humbled under a sense of his unworthiness;
although he had preached Christ, as the Saviour of sinners,
he feared that he had not done all that he might have done for those under his care.
I have not yet received full particulars,
as the survivors have been occupied in the removal of the body to Wilmington,
where he had long been known as a father and a Christian counsellor.
But I have not a doubt regarding the spirit,
redeemed and sanctified by a Saviour`'s love and power;
being stripped of every rag of self-righteousness, it will be clothed in the fine linen,
clean and white.
This is my hope and consolation for myself and my dear friends,
I do feel these privations, in my lengthened life;
yet I should be an ungrateful receiver of continued mercies and privileges,
if a murmuring or discontented thought were cherished in my heart.
Your kind correspondent brings my mouth to the dust, so to speak,
O! if a spark of genuine good desire has ever been kindled,
through so weak an instrument, the praise belongs to a higher Power.
Farewell, my dear friend! with all whom the Father of mercies has given you.

[.signed-section-closing]
Thus subscribes your affectionate friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fourth month 17th, 1835.

The changeable weather is unfavourable to my frail tabernacle;
fourscore years is no short period, but marvellous are the gentle dealings;
the wearing down is gradual, without any violent dilapidation; but with mild warnings,
the great and merciful Lord of all is pleased to instruct me.
My prayer is, "`Teach me Yourself.`"
Yes, Lord! permit me to be numbered with the children who are taught of You,
as an aged disciple, sitting at your feet, with my mouth in the dust;
only in favoured times, if it may so be, in my feeble way,
setting forth your condescending goodness toward your rational creation,
formed for immortality and glory.
Thus my long-valued friend, I have desired to be led in a plain path,
from my early years; far from disputation, or speculation on things too high for me,
but in simple obedience; and through the vicissitudes of my long life,
I have been favoured with a measure of inward tranquillity,
a little foretaste of that peace which this world cannot give, but which is all of mercy.

[.signed-section-signature]
Mary Capper.

--

__Memorandum.__
Received intelligence of the final close of my dear brother, John Capper,
the eldest of our large family; the remaining links of the chain are now only two;
my youngest brother and myself.
My dear brother John died on the 26th of the fourth month, 1835.

[.embedded-content-document.letter]
--

[.letter-heading]
To E. S.

[.signed-section-context-open]
Fifth month 9th, 1835.

My often-remembered young friend, and fellow-probationer, in a land of pits and snares!
I wish to give you a prompt assurance that I have read your
last communication with very tender feeling and interest.
If my experience can avail anything for your help and encouragement, I would say,
fret not yourself at the present strife of words!
It is nothing new.
Controversies and strange voices have existed ever since the fall of man,
disobedience having marred the divine image.
Enduring mercy, in tender compassion, made a new covenant, in order to redeem mankind,
according to the Scriptures,
which testify that the Son of God was manifested
in the flesh,--a body prepared of the Father;
this he laid down, as a sacrifice for the sins of the world; suffering,
the Just for the unjust, that He might bring us to God.
And in his spiritual appearance.
He is made known to the simple, obedient believer,
who will not follow the voice of the stranger;
for the voice of the stranger he knows not.

As sheep then of the Good Shepherd`'s fold, may we, my beloved young friend,
press into this safe enclosure,
and quietly leave all controversy to those whose food it is.
Cultivate inward stillness,
that you may be favoured to know the secret teaching of the Holy Spirit.
Meddle not with argument.
What comes to your ear, unsought, bear patiently; guard against excitement;
wrestle in prayer, both for yourself and others, for strength, if in the right,
still in the right to stay; if not, that heavenly Wisdom may teach the better way.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Fifth month 15th, 1835.

[.salutation]
Dear Labourers,

Be faithful unto death!
There is a rest, unpolluted by the strife of words.
Controversy has no place in the heavenly city.
As one drawing nigh to the end of time, who has indeed been tenderly dealt with,
I turn from the strange voices of the present day, and intermeddle not.
Yet I think I do a little enter into feeling, and Christian sympathy with the faithful,
exercised servants, who have to preach the cross of Christ.
O! may a Redeemer`'s love and power keep you, dear friends, and every deeply proved,
tried mind, from the tender youth to the aged sojourner on this side the promised land,
that you faint not, nor grow weary in the Lord`'s work.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. and Katharine Backhouse

[.signed-section-context-open]
Birmingham, Fifth month, 1835.

[.salutation]
My beloved Relatives,

I contemplate you in London, with several others, as disciples,
or learners from day to day at the feet of Jesus, in the good old school,
with your mouths in the dust, while some maybe busy around you, with a zeal to do well,
and to serve the Lord.
Gentle, yet impressive was the Saviour`'s rebuke, "`Martha!
Martha! one thing is needful I`" O! blessed privilege, to sit at the Redeemer`'s feet,
to know his voice, to learn of him, in the depth of humiliation,
to come unto Him of whom the inspired Scriptures do amply testify.
My faith increases in the promises as they stand recorded there;
and in the gracious influence of the Holy Spirit,
to lead out of all error and into all truth.
O! if we had not a merciful High Priest, touched with a feeling of our infirmities,
and acquainted with our temptations, what indeed should we do!
My spirit is revived by a consoling hope that these clouds and storms, by shaking,
to the very foundation, all that can be shaken, will work together for a good end,
yet but dimly seen.
And I do hope that no unprofitable dismay will obstruct, in any heart,
the benefit of the yearly meeting.
Of course it is not for me, a solitary one, to presume upon my feelings;
nevertheless I may state,
that in some favoured moments of stillness,--in a quiet not to be formed by human skill,
and under a secret sense of that Power that brought me among you as a religious body,
and that is still the mercy of the present hour, I have had a belief granted me,
that this annual gathering will, at times,
be favoured with the overshadowing of divine love and mercy.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Seventh month, 1835.

Marvellous is the condescending mercy that has brought me hitherto,
through a wilderness of pits and snares; and in my old age,
provided all things for my comfort; and above all, settled my heart in a peaceful state;
no more tossed with floating opinions, but watching,
waiting and praying to be perfected and fitted for the kingdom of heaven.
The Lord`'s own works can alone praise him!

Had I the pen of a ready writer, or the gift of an evangelist,
what could I write more impressive than what has
been already written and stands upon sacred record:
"`Do justly, love mercy, and walk humbly with your God.
Watch and pray, lest you enter into temptation.`"
All the wit and learning of the most learned men,
can never equal the precepts of Scripture.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Lamley, Jr.

[.signed-section-context-open]
Birmingham, Ninth month 21st, 1835.

[.salutation]
Dear Sarah,

It seems long since we had any communication.
Months have passed away, not without solemn events and changes,
within the circle of our own kindred; so at least it has been permitted to me,
to experience link after link to be broken.

My eldest brother died a few weeks after the decease of my dear brother James,
who was educated for a preacher in the established mode of worship, and lived,
as a pastor, fifty years at Wilmington in Sussex, where he was beloved and lamented.
In life and in death, all his hope of salvation rested on the Rock of Ages,
which Rock is Christ: his language in his illness, was,
"`None but Christ! none but Christ!
I wish to embrace Him in all his fulness, to be swallowed up in his love!`"
The enemy of souls endeavoured to persuade him (says his watchful,
affectionate daughter) that he would never attain to what he so earnestly desired,
namely, a fitness to meet Christ; but he said, "`The waves of the sea are mighty,
but the Lord on high is mightier!`" and at times, after a sore conflict,
he would break forth into praises.
He was much in prayer for himself and for others;
petitioning his heavenly Father to look upon him, and to have pity; often repeating,
"`Mercy is all my plea.`"
In his dying moments,
being asked if he was comfortable in the assurance that Jesus would receive him,
he replied "`Yes;`" and with his usual tenderness, added, "`and you too!`"
These were his last words.

I hope this little extract, so interesting to me, will not be intrusive.
I wish to convey, as far as expression can do it, my very dear love to your mother, who,
with my own soul, longs to be found at the mercy seat,
waiting for the fulness of redeeming love and power.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. C.

[.signed-section-context-open]
Dale End, Ninth month 29th, 1835.

[.salutation]
Dear absent Friends,

Often-times present in mental view--it is pleasant to hear of your rational enjoyments,
surrounded by a part of your family--permitted to leave
lawful and domestic cares in their lawful places for awhile.
Surely this is a privilege, best and rightly appreciated by the grateful thankful heart,
that traces all our blessings, all our genuine gratifications, temporal and spiritual,
to their marvellous, inexhaustible Source,
the one true spring of mercy to the soul of man, which includes the rational creation,
the world over.

I think we had a sweet, short little meeting in our reduced number this morning.
We had the company of the dear aged Christian minister, William Rickman,
His meek and humble testimony,
to that portion of peace which is the fruit or reward of faithful dedication,
was precious indeed--and to my thoughts seemed to flow like sweet odour,
or Gilead`'s balm--a short impressive address to the school boys, was also instructive.
The report of the dear man`'s kind reception by several Friends,
with his public services, as mentioned by his companion,
and his own grateful acknowledgement, are particularly consoling.

I shall send you a poor scrawl,
as the shades of the evening now seem to come over us almost unawares.
I wish you at any rate to be assured,
that your kind tokens of affectionate remembrance in the repeated messages of love,
are very cordial, and the response is centered in that one emphatic word--Love.

Including you all, parents and kind children, in the precious bond of union,
I subscribe affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.epistle]
--

[.letter-heading]
Fragment on Prayer; addressed to a Friend.

[.signed-section-context-open]
Eleventh month, 1835.

With diffidence, as ever becomes me,
I am willing to attempt expressing my ideas on the subject alluded to in our late conversation.
I am aware that my understanding is very limited,
but I think my simple views are not irreconcilable
with precept and example in the inspired records.
Can there be anything more imperative than the command,
"`Watch and pray!`" or any language more sweet and
encouraging than "`Pray unto your Father,
who sees in secret?`"

Doubtless Christians should live in the spirit of prayer.
"`It is the Christian`'s vital breath;`" and marvellous is the privilege,
unto this day and hour, of communion with the Almighty Power, God over all,
who breathed that breath of life whereby we became living souls!
By the same Almighty Power, we are kept from the path of destruction.
Sweet is the inviting language of our Redeemer,
who has cast up a new and consecrated way, by which we have access to the mercy seat.
"`When you pray,`" said He, "`say, Our Father!`"
Glorious privilege! that while clothed with human nature, feeling and mourning;
our omissions and our commissions,
we may "`kneel before the Lord our Maker,`" in prostration of body, soul and spirit!
Although utterance may fail, there is an availing sigh, a tear of contrition,
and a Spirit, better than our own, helping our infirmities!
I allude not to any forms, but to the real, humble breathings of the soul,
athirst for the living God.

[.signed-section-signature]
Mary Capper.

--

+++[+++On the 26th of the first month, 1836, died Sarah Lamley, of Tredington,
after a short and suffering illness; this event was much felt by Mary Capper.
In allusion to it, and also to a recent illness with which she had herself been tried,
she thus writes:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Lamley, Jr.

[.signed-section-context-open]
Birmingham, Third month 1st, 1836.

[.salutation]
Dear Sarah,

I have abundant cause for thankfulness, having been tenderly cared for in my weak state,
and supplied with all the comforts that I needed.
Above all, I hope I write it with reverence, my mind was mercifully kept in peace;
no doubts troubled me; but,
marvellous condescension! the spiritual Guide of my youth (so far as I
have been an obedient learner in the best of schools) has brought me hitherto;
and with my whole heart, I trust He will be my Guide all my journey through;
the staff and stay of my lengthened day!

Very often do I think of your dear valued mother;
memory retraces the many calm and peaceful hours in your little circle,
the pleasant steps in your garden,
when your precious mother examined and admired the opening buds and flowers.
These liberal gifts we contemplated as coming from Him who adorns this lower world,
and who cheers the grateful mind upon the way to that glorious city,
where anticipation shall be lost in fruition.
May your Christian mother`'s blessing rest upon her children`'s children!
Express my love to your sister, etc.
Farewell, my dear friend.

[.signed-section-closing]
Affectionately I subscribe,

[.signed-section-signature]
Mary Capper

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Third month 3rd, 1836.

I lament the separation of some promising ones;
their being driven by strange voices and tumults from attention to the still,
small voice of the Good Shepherd.
O! my heart pities,
and when enabled, breathes the secret prayer for the sheep
scattered from the true fold--the quiet habitation.
Never, my dear relatives,
did I more appreciate the privilege of being joined to a Christian people,--to the Society
to which I am favoured to be united by increasing conviction at this day,
of its pure, unsophisticated, gospel principles.
The Shepherd of the sheep is indeed good.
O! how gently He leads the simple, as the flock and the children can bear it.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Relation.

[.signed-section-context-open]
Third month 4th, 1836.

The secret language and aspiration of my spirit is, O! that our youth,
entering the field of faith and of responsibility,
O! that they may be kept from the strange disputations of this day.
But why think it strange?
Look at the history of mankind from the fall of Adam;
disobedience has marked every succeeding generation;
subtle device or open rebellion has drawn aside thousands, and continues,
in various ways, to allure and deceive the children of men.
The natural, uncontrolled,
active mind delights in doing something that shall appear goodly; yes,
can make sacrifices in its own will and way, and is gratified in self-complacency,
and it may be applause; yes, in external acts of religious worship.
My long life and observation, tossed and sifted as I have been,
have given me a measure of experience in the delusions of self.
O! how different, how widely different, from the lowly,
humble waiting at the feet of Jesus, the highest Teacher, as with our mouths in the dust;
feeling our own impotency, our own blindness!
Here is subjugation indeed, bearing the true cross.
Ah! my dear, say not in your heart,`" Who shall show us any good?`"
who shall ascend, or who shall descend, to bring our best Teacher?
Believe me.
He is nigh you; the living Word! writing the new covenant on the tablet of your heart.
Believe and obey this, and you will be led gently along, as you can bear it.
When we are faithful in the little,
the way is made for farther manifestations of the Divine will concerning us.
Avoid speculations, and vainly exercising yourself in things too high for you.
If I know anything of true peace, it is in simple, child-like obedience to the still,
small voice of the Good Shepherd, who instructs the lambs and sheep of his fold;
a stranger`'s voice they will not know nor follow.

This gracious, enduring mercy was the Guide of my youth,
turning my steps into the narrow way; and it is the stay and the staff of my old age;
and never did I more fully appreciate what I believe to be the genuine
principles of the Society to which I am conscientiously united,
than at this day.

Sacrifices not a few have been called for,
but not one which is not doubly repaid by sweet peace.
Not one painful accusation is permitted to trouble me;
thankfulness and cheerfulness clothing my spirit,
in the midst of great reduction of bodily strength.

Though I know not the heart of a parent, I feel much for the rising generation;
if there was not faith in an over-ruling Power, our poor thoughts might trouble,
if not overwhelm us; for what a sifting day is this,
among professors of religion! our own little favoured band not exempt.
There seems a prevailing mania, a strife of words and of strange voices!
But the Good Shepherd knows his own sheep, and they follow Him.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Third month 12th, 1836.

[.salutation]
My kind Friend,

Little less than miraculous is the restoration of
this poor body! it is marvellous in my view,
and I believe in the view of those who witnessed the almost suspension of animal life.
For what end thus re-animated, I know not;
it is enough for me to know that the Giver of life is good, though I am blind.
I am still weak, though I can walk alone from my easy chair to my desk,
use my pen as you may perceive, and value the privilege,
as I can relieve my affectionate friends from anxiety on my account.
I have been very tenderly cared for;
indeed the friends of my youth have been more than replaced.
Wonderful favours and mercies have been added to my lengthened days.
Time would fail, and language be insufficient,
to set forth the mercy that keeps my mind calm, lowly, dependent as a child,
disposed to learn at the feet of a crucified Lord.
My heart compassionates those who have left the Guide of their youth,
or who have not yet known the witness for God in themselves,
the Spirit that leads out of error into the plain path of duty.
O! my precious friend, if we were faithful to the dictates of this Spirit,
how many snares and entanglements we should escape; and how would the bitters,
mingled by a Sovereign hand, be sweetened!

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. and Katharine Backhouse

[.signed-section-context-open]
Birmingham, Fourth month 5th, 1836.

The recent intelligence of your devoted kinsman James Backhouse, and his companion,
with satisfactory accounts from Daniel Wheeler,
are consoling evidences that the universal Father
still regards his rational creation as one family,
however circumstances may differ; our limited capacities see dimly,
and we too often lightly esteem our own mercies.
With reverence, at this day, I am ready to testify,
that although the surrender of dear very dear parents (for
I was prohibited the paternal roof,) and of a strong,
heart-engaged attachment, led me indeed in a way that I knew not,
yet I was favoured with an internal calm that could not argue the matter;
to all enquiries, I could only answer,
that my peace of mind seemed to depend upon simple obedience.
And still, in this dependent, child-like state,
humbled by a sense of my evil propensities, which brings me to the foot of the cross,
I can now say that every sacrifice made in obedience, is rewarded a hundred fold;
infinite adorable mercy crowning the poor worthless offerings of his children,
with the assurance that He accepts them, and that Divine Grace shall be with them,
in life and in death.

It seems to me of great importance that there should be no self-complacency,
nor creaturely glorying, but true self-reduction, bearing the cross.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Fourth month 12th, 1836.

A bountiful creator continues to allure us to love, obey and praise him.
Had I the pen of a ready writer, had I the gift of an evangelist, my theme should be,
Praise the Lord!
Let everything that has breath praise Him!
The way to praise that Almighty Power,
who has formed his rational creation for immortality and glory, is obedience.
He has not left us without an internal witness, to manifest our errors and our sins,
and to point and to lead into safe paths.
I assuredly believe that there was a consciousness of good and evil,
even before the Gospel dispensation,`' which is the
fulfilment of prophecy in a Saviour incarnate.
Glad tidings indeed!
Glory to God in the highest!
Peace on earth; good will to men! ratified by a new covenant, written in the heart,
and confirmed by Scripture testimony,
that Jesus Christ came into the world to save us
from our sins,--to redeem us from all iniquity.
What can be more convincing?
Our restless wanderings arise from the neglect of watching unto prayer,
and daily bearing the subduing cross.

[.signed-section-signature]
Mary Capper,

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Fourth month 30th, 1836.

[.salutation]
My very dear Niece,

This doubtless is a time of mourning,
and of tenderly sympathizing in the bereavement of your dear relations;
there are other causes for mourning also, of which I doubt not you are sensible.
I would that I could comfort you, but you have a better Comforter.
The spirit and power of true consolation is nigh,
though it may not always be discerned by those who are cast down.
O! how sweet is the belief that they who are kept through tribulation,
at the foot of the cross, are in safe keeping!
It is my desire that we may not cherish anxiety with
regard to the things which are brought upon us,
in this our day.
Old things revived, as respects our Society.
Misapprehension or misrepresentation, and lack of faithfulness among ourselves,
have assuredly brought about a Babel confusion;
but there is no diminution of that Power which can bring good out of evil,
and cause the vain efforts of his creatures to promote his own gracious purposes.

I am endeavouring to look beyond the cloud,
when (if my natural day be not so prolonged) others may
be favoured to see the Sun of Righteousness shine gloriously.

[.signed-section-closing]
I remain affectionately, your aunt,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Fifth month 13th, 1836.

[.salutation]
My beloved Friends,

Shall I once more greet you with the language of affectionate encouragement?
Though the sun, in the visible firmament be in eclipse, it is not lost.
The creative Power that gave it for an external light remains the same;
even the universal Father of mankind, good,
very good to all who seek aright to know and to obey Him,
as his truly dependent children.
He who set the visible sun in the sky, has not left his rational creation,
formed for immortality, without a witness in the heart, as the Scriptures amply testify.
What indeed should we do, if left to doubtful disputation!
If the true light in the soul become darkness, how great is that darkness!
Watch and pray that the day-spring from on high may
again arise upon us as a religious Society,
somewhat scattered and shaken.
Possessing our souls in patience, may we have compassion one for another!
The foundation stands sure, though there may be builders thereon of wood, hay and stubble.

Well, my dear friends, after this unpremeditated introduction,
I recur to what first arose in my thoughts, in viewing you as contending,
again and again, for the faith, or unchanged Truth,
with fidelity and unwearied diligence.
The Spirit of Truth will guide into all truth.
O! it is a blessed thing to be docile, humble learners at the foot of the cross.

14th. This is the third or fourth time that I have taken the pen,
for I have been cheered by some kind calls from dear labourers,
on their way to the yearly meeting.
Sadness clothes the spirit as we commune together on the things which are brought upon us.
Nothing new! old revilings!
After a time of lukewarmness, or living too much at ease, may it not be said,
a woe is brought upon us, that availing, spiritual sorrow may spread,
and may arouse the dormant faculties to a right and true exercise;
and that babes may be fed with the pure milk, prepared for their nourishment,
that they may grow thereby, and be able to bear stronger meat,
so that they may endure to the end that crowns all,
and experience the salvation of the soul,
through Him who was crucified for the sin of the world,--the Son of God?
"`Flesh and blood has not revealed this unto you,`" etc.
May I not reverently say, the spirit within me prays,
with increasing fervency that revealed truth may work the work of righteousness,
to the praise and glory of the Holy One.

I think I must conclude with what was in my mind as a beginning; thinking of you,
dear friends, there was a sweet, abiding impression that there is a rest,
an undefiled everlasting rest, prepared for the patient, faithful labourer,
in the Lord`'s vineyard.
Your work, my precious friends, may not be finished; this glorious rest awaits you,
and every true labourer, so believes,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Sarah Grubb to Mary Capper.

[.salutation]
My Dearly Beloved Friend,

This day your precious, sweet letter, was handed me.
Oh! how truly cheering it is to witness and contemplate the state
in which Divine Goodness has kept you to this day!
I can look back to my childhood,
when I first saw with wonder the tears flowing from your eyes in meetings;
when you were an example to many, of nobly denying self, taking up the cross,
and following Him "`that endured such contradiction of sinners against Himself,`"
and who has been pleased to lead about and instruct you ever since;
yes, He has kept you as the apple of His eye;
and so I humbly believe He will keep you to the end; guiding your feet,
the few steps which remain,
and ultimately granting an entrance into those blessed regions where none can say,
"`I am sick;`" where there is no more pain, neither any more sorrow;
but the Lamb that is in the midst of the throne does lead to living fountains of water,
and all tears are wiped from the eyes forever and ever!

Some, in this our day, are almost ready to adopt the language,
"`Oh! that my head were waters, and my eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of my people;`"
for truly there is among us that which lays low the pure,
innocent life, that ought to be in the ascendancy;
yet my faith is that better times will come, even to this religious Society.
There is, I do believe, a living remnant left, who,
in being preserved through the shaking which has come terribly upon us,
will shine forth by and by, even as the light, and many will come to its brightness,
so that there will be Quakers still;
those who hold the precious testimonies of the everlasting
Gospel in their primitive simplicity and unmixed purity.
And surely it is unto the truth as it is in Jesus, that the nations must come,
in the fulfilment of the prophecy,
"`The kingdoms of this world shall be the kingdoms of God, and of His Christ.`"

We have had some favoured meetings,
amidst the opposition to the first principles of Friends, at this our annual gathering.
Yes, at seasons, the Lord`'s own blessed presence and power has been over all,
to His own praise; to whom all honour and glory belongs, now and ever.
Amen!

My husband sends you much unfeigned christian love, in which I tenderly unite, and remain

[.signed-section-closing]
Your ever attached friend,

[.signed-section-signature]
Sarah Grubb.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Watkin.

[.signed-section-context-open]
Birmingham, Seventh month 1st, 1836.

[.salutation]
My very dear Friend,

It sometimes seems marvellous in my view that our natural life is lengthened for weeks,
months, and it may be years, after being brought as it were to the brink of the grave,
looking for the salvation of the soul,
through the redeeming love and power of the Saviour, who was crucified for sinners.
No other name do we own, or profess to believe, can save us.
This I consider as the unchangeable foundation of genuine Quakerism;
and it is to be accompanied by a consistency of conduct, not to be controverted,
agreeably to the Scriptural doctrine and precepts left upon record by the Highest Teacher,
and to the example and testimony of holy men of old.
As far as my spiritual understanding has been enlightened,
this is what I apprehend to be Truth.
Secret things belong to the Lord.
My belief is, that sufficient is revealed for our instruction, and that,
while persevering, in faithful obedience, we shall find that lowly, peaceful,
spiritual poverty is a soul-satisfying reward.
I believe it is safe, and best in the present times,
to leave judgment unto the righteous Judge, as to this or that;
and to take the impressive counsel, "`What is that to you?
You follow Me!`"
I hope not to weary you, dear friend.
I think only to add, that Christian union, love and fellowship, were never more precious,
nor more binding to my fellow-professors in the Society to which
I have been conscientiously united for upwards of fifty years;
and I am so far from being dissatisfied, that in my most favoured seasons,
I daily contemplate it as a mercy.
Farewell affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From S. K. a child five years old, to Mary Capper.

[.salutation]
My dear Friend,

I should like to hear you talk to me about heaven,
where dear little children go when they are good; and if you will be pleased to see me,
I shall be glad to see you; please, when will it be a suitable time?

[.signed-section-closing]
I love you, and am your friend,

[.signed-section-signature]
S+++.+++ K.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Answer from Mary Capper

[.signed-section-context-open]
Dale End, Eighth month 14th, 1836.

[.salutation]
Dear little Friend,

I am quite pleased with your little letter,
and I am glad that you love me, for I have much love for children;
and I am glad when they wish to be good, and to know something about that Saviour, Jesus,
of whom we read in the Bible.

When I was a little girl, I had naughty tempers.
I wished to be good, and I often cried when I was alone,
because I wanted to be good all at once.
I was like you, dear child, too young to understand that I must be patient and humble,
and learn that Jesus Christ came into the world to save us from our sins,
and our naughty tempers, and to make us gentle, patient and obedient.
We cannot see the blessed Jesus as He appeared in this world in time past; yet his mercy,
love and power are over us all; to take away our perverse dispositions,
and to prepare us for heaven, that happy place, where all are good, happy,
and blessed forever.
That you, dear S. may be one of those who are eternally blessed,
is the affectionate desire of

[.signed-section-closing]
Your friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To C. B. C.

[.signed-section-context-open]
Birmingham, Ninth month 21st, 1836.

[.salutation]
My kind and dear Friend,

Your affectionate communication was, as ever, very cordially accepted.
That your precious mother will witness the best of Comforters to be near,
through all bereavements and trials, I doubt not.
My best love is to her.
The foundation stands sure that unites the humble followers of the Redeemer.
This is my hope and my anchor.
My soul longs and breathes, in the spirit of prayer, for preservation,
in this day of sifting.
Sometimes I think in my solitude, that perhaps I enter, in proportion to what I can bear,
into what some dear fellow-probationers have to sustain,
in the present state of our religious Society.
My heart mourns;
but I know not what to do better than to leave all unto that Wisdom that rules over all.
In our deep humiliation, we may be dumb with silence;
but O! if we can trace the hand of the Lord in it, we may take courage,
and hold on our lowly way, as disciples of a crucified Saviour,
bearing his cross from day to day, until we put off these corruptible bodies,
and rise triumphant over all opposition, through that Power that conquers death,
hell and the grave.
That I may really be a humble waiter, in patience, at my Saviour`'s feet,
is daily the petition of my soul, and that I may tenderly feel for,
and with my conflicting friends.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Tenth month 21st, 1836.

If it be from the Lord,
doubtless his tender compassion will bring me through
the searching trial which has brought me very low,
in mind and body, and yet keeps me so.
As I write, I feel a fear of taking myself out of the Lord`'s hand;
for he alone can perfect his own work,--the great work of entire sanctification.
On the receipt of your letter,
O! how I wished that I were worthy to mourn with
those who mourn for the state of things among us.
To bear a part in the sufferings and afflictions
of the true disciples of a crucified Saviour,
seems indeed a privilege.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Eleventh month 15th, 1836.

My dear brother James used to say of his wife, that she remained as a bruised reed;
so I think I may say it is with me; but with the cheering hope,
if not the abiding belief, that enduring mercy will not break that which is bruised,
nor quench the smoking flax.
My soul longs for an increase of faith, patience and resignation.
If the tender sympathy, and I believe I may add, the prayers,
of dear affectionate friends are availing, surely I may be encouraged.
I am greatly surprised at the interest manifested on my behalf;
it excites the strong cry at the mercy-seat,
that I may not be permitted to bring sorrow or dismay upon the Christian believers,
nor dishonour upon the glorious cause of the Redeemer.

[.signed-section-signature]
Mary Capper.

--

+++[+++About this period Mary Capper had to pass through much distress of mind,
in consequence of the departure of some whom she dearly loved,
from that path of simplicity and self-denial into which her own feet had been turned,
in early life, and which she still considered "`the more excellent way.`"
Her sorrow on observing that some of these were counting light of those views and practices,
which it had cost her much to adopt,
was so deep that it materially affected her health and spirits for a time;
but He who saw the integrity of her heart,
and who watched over her with a Father`'s love, was pleased, after a season of proving,
to remove the burden, and to grant her a renewal of faith and of confidence,
enabling her again to go on her way rejoicing.
She thus describes her state in a letter.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Third month 15th, 1837.

I have abundant cause to take fresh courage and be thankful; for a consoling hope,
and lowly Confidence in redeeming, sanctifying Power, cheers the path-way before me.
My general health gradually improves, and my cough is abated;
and how shall I describe the favour of being permitted to lie down in peace,
and to take rest in safety, under a protecting Power!
Thus, my dear niece, I am tenderly dealt with.
I go to our religious meetings once in the day; and though faith and patience be tried,
the hope of finally reaping the rich harvest of promise, urges my spirit to press onward,
through all that may at times cloud the beatific vision.
I walk out most mornings, rising about seven o`'clock; my faithful,
valued handmaiden reads portions of Scripture to me; the day is spent mostly in solitude,
and closes with reading a chapter or two in the Bible,
when I am early ready and thankful to retire.

--

[.offset]
+++[+++About the same date, she thus writes:]

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend.

You would no doubt hear, from time to time, of the state of my health as precarious;
indeed I was much confined to my apartments, and yet remain very feeble.
But my spirit is relieved, in mercy, from a distressing exercise,
which almost seemed to separate from the consolations of adoption through the Saviour.
Now, in a humble, lowly calm, with watchfulness unto prayer, and that continually,
a plain path in the strait and narrow way seems set before me;
turning neither to the right nor to the left, to hear what others may say,
but keeping in view what first brought my wandering feet from the broad way.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Fifth month, 1837.

[.salutation]
Dear Labourers,

As ambassadors it may be, often-times in bonds,
it is in my heart once more to attempt to greet you, in a measure of that love which,
I cherish the hope, is a badge of discipleship.

I cannot say that none of the things, brought upon us at the present day, move me;
in measure I think I participate in the clothing of sackcloth and mourning;
perhaps it is a sign of life,
to mourn with those who rightly mourn for the desolation spread among us.
For my own part, I dare not step out of the strait and narrow way,
which I believe is cast up as a safe path for me to walk in,
by faith in the redeeming Power of a crucified, glorified Saviour,
manifested in the humbled soul, as the true light and life, which opens the blind eye,
and leads in the way of salvation.
I am sensible that consoling evidences may be veiled; that bright vision may fail,
in a long, dark and gloomy day; the cloud resting upon the tabernacle.
Is not this the trial and proving of our faith even at the present time?
But with you and your dear husband and family,
I look forward with cheering hope that brighter days are in store for those,
who in faithfulness,
hold fast their confidence in the mercy and love of our Heavenly Father,
as a reconciled God.
Divine compassion can alone begin, carry on, and perfect his own glorious work;
my impotence and ignorance keep me, as I think, at the Saviour`'s feet.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Fifth month 29th, 1837.

[.salutation]
My beloved Niece,

Morning by morning my thoughts seem to bring to my view
the dear exercised labourers of the present day.
Solitary and useless as I apprehend myself to be, my best desires, in favoured seasons,
are earnest, in the spirit of supplication,
that heavenly mercy may be manifested to heal the wounded spirit,
to strengthen the feeble-minded, and to confirm our faith in the one sacrifice for sin;
that we may know the effect of sanctifying Power,
while passing through this time of probation.
My heart seems to press after the experience of a prepared state for a prepared place.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Twelfth month 14th, 1837.

Cough and debility keep me much confined, though I
am favoured to attend most of our religious meetings; and with the ability given,
I think my heart has united with those who are exercised
in desire that we may experience a revival of spirituality,
with that faith which produces a right preparation to worship in spirit and truth.
O! for a more powerful sense of this in all our religious assemblies.
Lowly, persevering waiting at the Redeemer`'s feet,
seems to me the watchword for the present time.
My dear niece, may Israel`'s Shepherd keep you, and all who are dear to you,
with my own soul, nigh to the mercy-seat,
and finally complete his own glorious work of salvation!

[.signed-section-closing]
Your aunt,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To B. and C. C.

[.signed-section-context-open]
Second month 22nd, 1838.

[.salutation]
Much loved Friends,

There never was a day in which I so fully entered into sympathy
with my fellow believers in the sure mercies of God in Christ Jesus.
Though these may have received, in favoured seasons past,
sweet evidences of walking acceptably in the Divine presence,
yet at the present time (it may be for the accomplishment of the
Lord`'s purposes,--for the completion of his own work) the poor,
disconsolate traveller may seem to be forsaken.
I do know something of this continued warfare; but in adorable mercy,
the wrestling soul can hear the cheering language,
"`All is not lost that is out of sight.`"

With you, my precious friends, my desire and prayer is, to look,
beyond all doubts and fears, to a gracious Redeemer, whose power is above all;
for we may feelingly adopt the language, "`This is mine infirmity!`"

[.signed-section-closing]
Very affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_______+++,

[.signed-section-context-open]
Birmingham, Second month 29th, 1838.

[.salutation]
My fellow-probationer,

For whom I continue to feel an affectionate Christian interest.
I think your letter would not have lain so long unacknowledged,
had I anything to offer that could minister availing instruction.
My limited experience however,
leads me to cherish tender sympathy with every one
who is convinced of the sinfulness of sin,
and of our depravity by nature.

It is recorded in Scripture, from the Highest authority, "`A man must be born again,
or he cannot see, or enter, the kingdom of heaven.`"
This new birth, or new creation, is a blessed change of heart; all things become new;
new thoughts, new desires, and new views of ourselves.
I may venture to say, that it appears to me,
that your present humiliating sense of gross commissions,
with your mournful retrospect thereof, and your turning from your unrighteous ways,
are tokens of mercy, that you are not forsaken, or given up to hardness of heart,
so long as a secret spirit of prayer, or good desire, is raised, and kept alive in you.

Although, as yet, you are tossed and not comforted, remember,
there must be a time of trial, before the soul can come to rest on the Rock of salvation.
We are assured, that "`To know the only true God, and Jesus Christ whom he has sent,
is life eternal.`"
This is a knowledge too high for the natural comprehension; but we are also assured,
that the grace of God, or the Holy Spirit, is given unto us to profit withal,
as testified by holy men of old, and by faithful Christians,
from generation to generation.
The Holy Spirit, the Saviour`'s gift, is to this day my Comforter, carrying on,
as I humbly hope, the great work of sanctification throughout, in body, soul and spirit.
From my early years, I had a secret belief that religion was pure and holy,
and that it led to purity and holiness of life;
and I was induced to consider that the Society of Friends
manifested more consistency of manners and conduct,
than was discoverable among others.

The fundamental faith of the Society in a crucified Saviour, as a Redeemer,
and a reconciler to God the Father, I have never doubted;
and had there been more faithful obedience to that Spirit which leads out of error,
I am inclined to believe we had not been so scattered a people as we are at this day.
My enfeebled state of body and mind disqualifies me from entering into argument.
My peace seems to be in quietness, and in holding fast my confidence;
taking a retrospective view of the way in which I have been kept and led hitherto.
With an earnest desire for the welfare of souls, for you and your dear family,
I remain affectionately your friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Fifth month 19th, 1838.

[.salutation]
My precious Friends,

Although my powers of communication are at a low ebb, I would most willingly,
with unfeigned, uniting love, again greet you.
Your dear children also seem to have place in my best desires,
that they may be safely kept in the lowly valley,
and patiently abide the sittings and provings of this day.
I think I do enter into tender sympathy with a rising generation,
and with my fellow pilgrims, who may be, at seasons, tossed and not comforted.
Nothing less than enduring mercy and goodness can keep alive
an availing faith in the Rock of ages,--the Light,
the Life, the Power that leads to a life of holiness.
My soul presses after this in my present weak state.
You dear labourers and faithful servants,
may the hope set before you be clear and steadfast.
To be willing to bear one another`'s burdens, to suffer with those who are tempted,
buffeted and grievously tried, is the work of the good Spirit,
that clothes the Christian believer with the mind that was in Christ,
so far as seems fitting to perfect wisdom: so that my endeared Sarah, I notice,
with a measure of grateful admiration,
your willing submission to a restoration of health,
and renewed power to be helpful in your own dear family and to others,
by encouragement and example, that they faint not by the way,
though it seems rough and thorny.
Your affectionate communications are very welcome and cheering to me.

I was favoured to pass through the protracted winter with
as little ailment as the generality of my aged fellow pilgrims,
and have been privileged to get to our meetings for worship, almost constantly,
having the free use of my limbs at the lengthened period of eighty-three revolving years!
But a recent attack of erysipelas has much reduced my mental and bodily powers.

With all my infirmities, the good Spirit is not wholly withdrawn,
and I wrestle in prayer for resignation, faith and patience.
Accept my imperfect offering, in the love I bear to you and those most dear to you.

[.signed-section-closing]
Affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Grubb to Mary Capper.

[.signed-section-context-open]
Clapham, Fifth month, 1838.

[.salutation]
Dearly beloved Friend,

Your sweet and precious letter has done me good.
O! how delightful it is to see that some hold on their way, in this day of backsliding.
This yearly meeting convinces us that we are still, too generally, a revolting people,
and my portion of labour has been much in the line of laying open our condition,
and calling back the wanderers; for it seems to me to be a day of renewed visitation.
The heavenly Wing is extended to gather into safety;
while yet many are not prepared to come under it,
for lack of being sensible of their danger and of their own helplessness.

There is nevertheless a little band of humble, simple ones,
who feel their entire dependence upon the Almighty Helper,
and these are very near and dear one unto another, wherever they are,
and however circumstanced; among such is yourself; kept, through Divine mercy,
in the holy oneness, maintaining the unity of the Spirit, in the bond of peace;
and although some of your steps, now late in the race, may be painful,
I do believe you will find the end to be crowned with peace and satisfaction forever.
My dear husband let me come alone this time,
he not being vigorous enough to make his coming prudent.

My children feel the tender regard expressed for them in your letters to me.
We seek not great things for them, any more than for ourselves,
either as to temporals or spirituals, but true Wisdom, whose ways are pleasantness,
and her paths peace.
Many are the baptisms, even in youth, known by such as yield to the preparing power,
which brings to a holy settlement, on the sure foundation.

It is very sweet, and confirming to some of us,
to see Daniel Wheeler return safe and sound, in every sense; and to hear him tell,
in a few sentences, of what he has seen of the works of the Lord,
and his wonders in the deeps, and testify to the sufficiency of Divine Grace,
as he has witnessed it in himself and others.
He says that if he had entertained any doubts before (which was not the case)
concerning a measure and manifestation of the Spirit being granted to all men,
they would have been removed by what he has seen among those whose
situation in the world left them in ignorance as to the outward,
yet who acknowledged to being sensible of the reproofs
of the great and good Spirit in their own hearts.
Daniel is as tender and as humble as a child, after all that the Lord has wrought by him,
as well as for him.
I may now take leave of you, my very dear friend, and remain, I humbly trust,
in the fellowship of the gospel, and also a partaker with you in tribulation.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Sarah Grubb.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to Katharine Backhouse

[.signed-section-context-open]
Birmingham, Fifth month 22nd, 1838.

My spirit does hunger and thirst for an increase of holiness,--for complete sanctification.
We seem very much stripped in our religious gatherings;
may we cherish the hope that spiritual strength and confidence may be renewed!
This is not a day with us as a Society,
to proclaim that our cup runs over with heavenly consolation;
nevertheless my earnest prayer is, that I may be kept from turning aside,
and that mercy may crown all with the everlasting anthem of thanksgiving.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Sixth month 10th, 1838.

I have had satisfactory reports of the yearly meeting,
and Elizabeth Robson called upon me, and confirmed the encouraging intelligence,
that we are not a forsaken people.
I believe that if there was more individual faithfulness,
we should be more conspicuously favoured with light, life and power,
as a spiritually minded people, who having left the shadow,
are pressing after the substance.

Second-day.
I have now had the gratification of seeing my dear nephew and niece Mounsey,
and I hope we were mutually refreshed with something better
than the wine of the best grapes of Canaan.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Lamley

[.signed-section-context-open]
Birmingham, Sixth month 22nd, 1838.

[.salutation]
Dear S. L.,

Although a considerable lapse of time may occur between our communications,
I am satisfied it enters not our thoughts, that we are forgotten by each other.
Many a sweet and uniting recollection arises in the retrospect of days past,
when we were favoured to participate in that refreshment,
which renews our faith and our confidence in redeeming love and power,
which is unalterable, though we may witness so many changes,
that we may seem comparable to the solitary in a family.
I am not a stranger to a feeling something like this;
but the spirit of prayer earnestly breathes in secret for
patient submission to the preparing hand of our Lord;
and while thus enduring the separation of the precious from the vile, we may truly,
and very tenderly, feel with and for one another; and when so favoured,
rejoice together in a grateful sense of continued mercies.
I understand that at the yearly meeting,
condescending goodness and mercy were measurably experienced;
so I was informed by a dear aged friend,
Alexander Cruikshank, of Scotland,
humble and tender in spirit.
O! that there were more, of such consistency of life, and circumspect conduct,
under the guidance of the Holy Spirit;
then I do believe the genuine foundation of our faith
and hope of salvation would be more manifest.
The savour of this dear friend`'s spirit seems to remain as precious odour spread around.
I understand that dear, aged William Rickman was a faithful testimony bearer,
in London this year, being upwards of ninety-two.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

Most likely you have been informed that your dear brother is in London,
in obedience to his religious duty.
O! what a favour that there are those yet to be found among us,
to preach the gospel to the poor, the wretched; yes! the most degraded of the human race.
I can scarcely credit the result of your patience,
in arranging the almost voluminous scribbling consigned to your care.
If aught of interest or usefulness can be found,
I am most willing that you should have the selection,
and consider it very kind that you are willing to take the encumbrance.
In concluding these words, my dear niece,
I am reverently conscious that it would be ungrateful not
to acknowledge the tender mercy of our Heavenly Father,
which has kept me, from my youth to this day,
from following on in the broad way that leads to destruction.
For this, his revealed power, and redeeming love, be rendered glory and praise!

[.signed-section-signature]
Mary Capper.

--

+++[+++In explanation of the foregoing remark, it may be proper to observe,
that Mary Capper entrusted her journals, etc. to the editor,
some years before her decease;
and then supplied some of the earlier pages of this memoir;
but it is to be regretted that her memory could not then furnish
some connecting links which would have been desirable and useful.
It is hoped, however, that the pious walk of this lowly-minded hand-maiden of the Lord,
is sufficiently manifest in these pages,
to add one more to the many inducements which are held forth,
to follow in the footsteps of the flock of Christ,--even
of those who obey the voice of the good Shepherd,
and walk in his paths.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Tenth month 25th, 1838.

In my eighty-fourth year, I seem but as a child;
the sustaining arm of mercy is still underneath, or faith and hope would fail,
as I am in some measure alive to the exercises brought upon us, as a religious body,
at this day.
Surely there must be a backsliding from our genuine
principles,--a departure from the faith,
that Jesus Christ, the Son and Sent of the Father, died for sinners;
that his atoning sacrifice, with all its wonder-working effects,
too high for human comprehension, brought light and life,
or grace into the dark heart of our fallen race,
and most mercifully put us into a capacity to experience salvation.
O! how superior is this dispensation to the Mosaic,
with its types and figurative ceremonies.

How is it, my dear niece, that I have ventured thus to pen my views?
My heart, in unison, with every humble believer,
longs and presses after the knowledge of God our Saviour;
whom truly to know is life eternal; and as a weaned child I am, at times, quieted.
May I be thankful for countless favours daily bestowed!

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Twelfth month 4th, 1838.

As the end of my lengthened life draws nigh, my hope of salvation is still in the Saviour.
Your retrospect of the close of time to your precious parents is very impressive;
it is consoling to contemplate the mercy which we have good ground to believe, prepared,
and has gathered their sanctified souls into the kingdom where sin,
the root and germ of sorrow, can no more disturb,
neither interrupt the undefiled rest of the ransomed of the Lord!
I cherish it as a token for good,
that we are brought to each other`'s particular remembrance in our most favoured times.
May we not accept it as a sweet,
encouraging evidence of the power that baptizes into one Spirit,
by the "`one baptism,`" which is beyond elementary washing or dipping,
or anything perishable?

10th. Our quarterly meeting has appointed a committee,
in concurrence with the advice of the yearly meeting, to visit friends in their families,
and to offer affectionate counsel, in that wisdom and discernment which may be granted,
that all may be induced to press after holiness and godly simplicity.
It is well to be stirred up to enter into self-examination.
I think my confidence was somewhat renewed by the visit of four friends to myself.

[.signed-section-signature]
Mary Capper.

--
