== Chapter V.

[.chapter-synopsis]
* Travels during the years 1794 to 1801
* Visits at Stoke Neicington, etc.

+++[+++Mary Capper appears, from the time of her mother`'s decease,
to have devoted herself to the service of her Divine Master;
being a diligent attender of religious meetings,
and travelling much to promote the spread of Truth
and righteousness in various parts of this country.
She was acknowledged as a minister in the early part of the year 1794.
Her ministry was sound and of a spiritual character;
having herself largely partaken of the conflict between flesh and spirit,
she was often concerned to encourage the sincere-hearted,
patiently to submit to proving seasons,
looking for effectual help to the light and power of our Lord Jesus Christ.]

[.small-break]
'''

1794+++.+++ Third month,
8th. I set out with a minute expressive of the concurrence of my own monthly meeting,
to meet Mary Beesley at Bromsgrove,
in order to unite with a committee of men Friends appointed by the quarterly meeting,
to visit our monthly and preparative meetings.

10th. After attending various meetings, returned to Birmingham,
where the meeting for ministers and elders was held in the evening.
Ruth Fallows and Sarah Stephenson were present.

22nd. The friends of the committee met,
and had a solemn opportunity of conference with us, children in the work;
to our edification and encouragement.
It was judged best to proceed in the engagement, previous to the yearly meeting.

24th. Monthly meeting at Shipstone; the gathering was large,
and measurably favoured with solemnity;
to the comfort and encouragement of rightly exercised minds.
We called upon some families, after which we sat awhile together,
under humbling feelings; then separated to return to our several allotments,
having finished the engagement;
through which we had been favoured with tender unity of spirit,
and we now part desiring each others welfare and growth in the Truth.

Yearly Meeting, 1794.
Fifth month, 19th. Martha Routh spread before the meeting of ministers and elders,
a concern to pay a religious visit to Friends and others in America; also John Wigham,
a similar concern; these came under weighty consideration.
In the afternoon there was a meeting for discipline, at the new meetinghouse,
for women Friends; the gathering, very large.
Patience Chester is clerk, and Sarah Hustler assistant.

20th. An affecting epistle from women Friends in Philadelphia was read;
it set forth their deep suffering and humiliation,
when that city was awfully visited by the yellow fever.

21st. Attended the meeting for worship in White Hart Court, to my refreshment and comfort.
Mary Ridgway was particularly favoured, on the words, "`Be still,
and know that I am God!`"
I was inwardly made sensible of the great need there is to keep on the watch,
in these large meetings.
O! saith my soul, that we little ones may be preserved in the quiet, humble, silent,
resigned state!
Aware of the great importance of speaking in these assemblies,
we should wait for that which burns as a fire that will hardly be restrained.

22nd. Certificates were read, in the select meeting,
expressive of concurrence with the concern of the Friends for visiting America.
Some weighty counsel was given,
recommending that they who speak in these meetings
should be careful only to speak from necessity.
The meeting broke up under a covering of solemnity;
and my heart`'s desire is that we may study to dwell in the stillness,
wherein self is abased, and the Power of Truth exalted.

I believe that some of us are tempted to think,
that unless we appear to take some active part in Truth`'s service,
we may be looked upon by others, and perhaps by ourselves, as useless, lifeless members;
but far otherwise is my judgment at this time.
The humble patient traveller, who bears the burden of the word,
until the right time comes for deliverance,
(when the message will be accompanied by a measure of power and
authority,) assuredly works essentially for the general good.

23rd. At Horsleydown, gospel ministry was dispensed through Mary Ridgway,
a devoted servant.
In the afternoon, several testimonies concerning deceased ministers were read,
to the tendering and humbling of some minds; raising desires to run with patience,
the race set before them.
One was from Wales, respecting Dorothy Owen; and one from Ireland, relative to Job Scott.

24th. Our esteemed friend Samuel Emlen, accompanied by another Friend,
made us a very acceptable visit.
The men`'s meeting sent us for perusal,
a very interesting communication from Friends in America; some of whom,
in considering the late awful visitation of some parts of that Continent,
were so deeply concerned for the general good,
that they had believed it required from them,
to represent to the Rulers and persons in power,
the necessity for their exerting their authority,
to endeavour to suppress all public amusements, gaming, stage entertainments,
and dram shops, as being sources of much immorality and profaneness,
widely estranging the mind from God and godliness.

27th. A caution was given to be especially careful that
our conversation savour not of the spirit of this world;
that at a time like the present, when nation seems rising against nation,
and the rumour of war sounds in our ears, we may get every one to our tent,
and there wait to be rightly prepared to meet the overturnings which may come;
not presuming to offer our own conjectures upon events, but rather studying to be quiet,
and to mind our own business;
the important business of knowing a preparation to meet our God.

28th. Answers to some of the epistles were read.
A sentiment ran through my mind,
that a day may come when we shall feel some restrictions in our correspondence;
at least in the length of our communications; refraining even from good words.
We had a very acceptable visit from Thomas Shillitoe and others,
who exhorted us to keep to the power in which our meetings were first established;
that no mouth should utter words without life; but that in humble waiting upon God,
we might know a being baptized into the one Spirit,
wherein all are brought into true harmony.

Ann Tuke and other women friends mentioned a concern to visit the men`'s meeting;
they had the sympathy and concurrence of feeling minds.
Susanna Row accompanied them, and on their return,
she expressed her satisfaction in having been with them.
The meeting concluded in awful, reverent silence,
and we separated under humbling impressions.

[.blurb]
=== Journey In Wales.

1794+++.+++ Eighth month, 3rd. Mary Beesley having long felt a deep concern of mind,
to pay a visit to Friends in Wales, and in the county of Hereford, my mind was,
after serious consideration, engaged to accompany her;
for this purpose we obtained certificates.
On first-day, after attending a favoured meeting at Worcester, we dined at Wick,
with the parents of my friend, and parted from them in much tenderness of spirit,
and in a humbling sense of our own inability for what we had in prospect.
Through the care and kindness of Friends we were suitably provided.
Thomas Goode, of Birmingham, was sent to accompany us through the journey,
and Robert Newman went with us to Ross.
Our first stage was to Ledbury, where we lodged.
One lonely woman Friend, a widow, lives in the town,
and received a visit from us very kindly.

Second-day.
From Ledbury to Ross; at Thomas Pritchard`'s. Went on to Troy;
we had to travel through a beautiful country, but the best life was low with us.

Third-day.
Before we left William Dew`'s, had a little glimpse of the Heavenly Father`'s love,
on which a few words were spoken, and we separated in tenderness.

Fourth-day.
Monthly meeting at Pontymoyle; to which place we walked about a mile.
Though but few in number, there was something of divine power to be felt,
wherein we seemed to be owned as members of the living Catholic Church,
which is of one spirit, and is united to the Head, Christ Jesus.
My beloved friend Mary Beesley was strengthened to open, in a weighty manner,
a concern to sit in the families.

Fifth-day.
We came to James Lewis`'s, a remote situation in a valley at Lanelly, in Brecknockshire.
Rough and fatiguing roads; we walked part of the way, though heavy rain made it difficult.

Sixth-day.
Set out in the morning to visit Richard Harford and his wife, five miles off`";
the road is here esteemed good, and indeed so the main road is;
but to us the rocks and precipices were alarming, though to be admired as awfully grand.
It is a railroad for the use of a coal company:
meeting with their wagons and loaded horses was to me frightful;
however we were favoured to get safely along.
Friends receive us with much cordiality,
making plentiful provision for refreshing the body;
but ah! a few crumbs from our Master`'s table are still more desirable to us,
for we are poor and stripped of inward consolation;
yet favoured quietly to hope for a brighter season.
After dinner we sat -with the family.
If we are preserved from hurting others, or wounding ourselves, it is no small favour.
O! Father, preserve us, and leave us not! for we cannot direct ourselves.
In the evening, sat with James Lewis`'s family.

Second-day.
Were favoured to leave Pontipool in peace, and came to Penhow Castle,
a good old farm house, where we were very hospitably received.
The mistress is a plain, agreeable person, not born in our Society,
but convinced by the secret power of Truth in her own breast: we did not see her husband,
who was engaged in harvest work.
In this family lives a poor old man; blind, and with locks as white as wool;
we spoke to him, and his remarks seemed to do us good,
evincing that his mind was brought into childlike simplicity, as he, in a few words,
described his own weakness, and entire dependence on Divine Goodness.
The mistress of the house said he had lived with them for many years,
and that she had seen him, at times, in the fields,
apparently in a retired state of mind, with tears trickling down his cheeks.
She accompanied us to Shire Newton, where was a small meeting.
We sat with one Friend`'s family, and some neighbours,
who seemed disposed to receive the Truth in the love of it,
as ministered by very feeble instruments, who sought not their own exaltation.
Returned to Penhow by a beautiful road, with a fine view of the Bristol channel.

Third-day.
The master of the house made way for his men and boys, with the maid servants,
quite a large number, to come and sit down with us;
and I think we may in humility confess that our Heavenly Father favoured us,
in ministering, according to the ability given, and we trust to their edification.
Stayed all night at Newport.

I note down, as a watchword for myself,
that I am this day made sensible that there is need to watch;
and most especially in times of favour,
for here is danger of sliding into a state of ease.
I have this day felt the reproofs of instruction in my own mind,
for not being sufficiently guarded in my conduct toward strangers.
There is a propensity in some natures to be open and unreserved;
but I wish to be thankful for the gentle, internal monition,
and to remember that it is needful to be prudent,
especially when thus engaged in the service of the great cause of Truth;
even innocent cheerfulness, if not strictly guarded, may lead into inconvenience.

Fifth-day.
Came to the house of Evan Rees, Neath.

First-day, 17th. Attended the meetings at Swansea.
A day of humiliation and suffering.
Returned to Neath.

Second-day.
Remained at our kind friend Evan Rees`'s; not being fully satisfied in our minds,
which might be the right and safe way for us to move;
we were thankful in believing that our friends felt for us.

Third-day.
Prepared to re-visit Swansea; Evan Rees accompanies us; Friends are very kind.
We visited the few in their families.
There are young people growing up, whose situation seems to demand tender care.

Fifth-day.
Came to the house of Jane Lewis, Haverfordwest.

Sixth-day.
Received the unexpected intelligence of my brother Harry
being called from this uncertain state of existence;
his illness was short, and he has left a young wife, for whom I feel much.
My dear brother was young, hardly past what is termed the bloom of life.

First-day, 24th. A low time in the meetings.
In the family, felt more life and liberty; tender counsel,
caution and encouragement flowed toward the children.
Mary Beesley very poorly.

Second-day.
It appears probable that we shall not feel clear of this
place without sitting in the families of Friends.
Jane Lewis accompanied us into one family.

Fourth-day.
Came with Daniel Starbuck, to Pill, where Samuel Starbuck and wife,
his son and daughter and their little ones reside.
They were formerly from Nantucket; and in the time of the American troubles,
were sufferers, with many others.

Fifth-day.
At meeting; poverty of spirit my allotted portion.
After dinner, walked about a mile to Milford, where Samuel Starbuck, jun.
lives; his wife was sick, and we sat together in her chamber.
We crossed the water, in a small boat,
to visit a serious woman who frequents our meetings; her husband is a sailor;
the vessel lying near shore she sent for him, and I thought we were favoured together,
with a little sweet refreshment, though in a very humble hut,
where outward accommodations were but mean;
but I thought there was something to be felt far
preferable to all that the world could bestow.
Returned to Pill.

Seventh-day.
Daniel Starbuck and his wife accompanied us to a family who profess with us;
but the female branches having married out of our Society,
the spiritual life seems to have received a check.
Surely these marriages have proved a great hinderance to our brightness as a people!
In these parts, in particular, it seems to have been the means of scattering.
We dined with these friends,
and had an opportunity to express the desire which was raised,
that the power of godliness might be preferred to the form.
Returned to Haverford.

First-day, 31st. At both meetings.
A day not without some light and peace, though intermixed with bitters.

Ninth month 1st. Second-day.
We are yet bound here.
Called upon a Moravian teacher who had been to visit us;
truly a uniting power spread over us,
and I believe we parted in that Christian spirit which sincerely
desires each others growth in the real principle of Truth.
Surely there still are different dispensations, as to the outward,
but one and the same spirit.
In a few words, delivered in great simplicity, H. S. exhorted us,
"`as we had received Christ, so to walk in Him.`"
In the afternoon, visited a serious family of Moravians,
who seemed to receive us with open house and heart.
We had a solid time together.
In the evening we had an opportunity of solemn retirement
with Jane Lewis and five of her children;
something of the Heavenly Father`'s love was felt.

Third-day.
Very considerable was our exercise in not feeling at liberty to go forward;
after a season of some trial, and I trust unfeigned supplication,
we believed it right to have an evening meeting; which,
being mentioned in diffidence and fear to Jane Lewis and other friends,
we were encouraged to appoint one.
We particularly desired the attendance of servants and apprentice lads.

The gathering was large, and remarkably still.
I believe there is a tender, honest-minded people in this place;
and assuredly the Heavenly Father`'s love is over them,
and will gather them unto Himself!

Fourth-day.
We attended the women`'s monthly meeting; no meeting for business held by the men;
indeed the discipline is so low, that the very form is almost lost;
we wish that a revival, through the power of Truth, may take place among them;
seeing that many young people are growing up, who are much uninformed.
We rather hope the American Friends S. and A. Starbuck, etc. will be united,
and add a little strength, to these feeble ones.

Fifth-day.
Parted from our kind friends Jane Lewis and others,
in an almost silent feeling of solemnity; our spirits seeming still, as it were,
to hover round them, earnestly desiring their growth in the spiritual life.
We left them in a feeling of sadness, and pursued our journey in pensive quietness.
Our kind and ancient friend Samuel Starbuck, with his valuable wife,
accompanied us on horseback.
Came as far as Westmore, where we were comfortably lodged in a Friend`'s family,
after arriving late, as the road was rough and difficult.

Seventh-day.
Reached Caermarthen.
The company of Samuel Starbuck and his wife, was a comfort and encouragement to us.

First-day, Ninth month 6th. We went to meeting in weakness and fear;
several sober people came in, and it proved a season of favour.

In the afternoon there was a large gathering, and the power of Truth so far prevailed,
that all seemed brought into a degree of solemn stillness.
Some exhortations, and some plain truths, were expressed.

Second-day.
Travelled through a beautiful country to Llandilo; we met Job Thomas,
who conducted my friend and me to his own habitation, a very humble, thatched dwelling.
We were kindly received by his wife, a native of the mountains, who speaks no English,
but whose countenance bids us welcome to the best they can afford, and we feel easy.
It is however somewhat painful that,
as there is not room for our kind friends Samuel Starbuck and wife,
they are obliged to ride a mile farther.

Third-day.
Our kind, attentive friends came to breakfast with us,
and we went nine miles on horseback, mostly over the mountains, to visit a man Friend;
his habitation is mean, but his hearty reception of us, with his solid,
innocent deportment, was ample amends for the fatigue.

Our valued friends Samuel Starbuck and wife left us this evening.
Their company has been very acceptable, and we feel pain at parting from them,
they having been more like parents to us than any we have met on our journey.

Fourth-day.
We took tea with Job Thomas`'s brother and sister.
Some neighbours had been invited to meet at Job`'s house, and a considerable number came.
Job Thomas had something to express, but we sat silent; the people were quiet and solid;
yet I thought they were too much looking without, for that which is to be found within.

Fifth-day.
Went on horseback six miles to Newhouse, where we attended a monthly meeting;
there seemed to be honest enquiring minds, but too much outward.
The members of our Society are very few,
and some of them appear not enough separated from
the language and corruptions of general custom.
The meeting for business very small;
the order of the discipline measurably preserved by Job Thomas; but things are low.
In the evening came six miles, fording the river Towey, to Llandovery.

Sixth-day.
Job Thomas accompanied us thirteen long miles, over rough mountain road,
very difficult for a carriage;
we walked a mile or two and stopped at a very poor looking thatched house;
we had a comfortable dinner, well cooked, for which they charged only eight pence each.
We afterwards forded the river Irvon, and came ten Welsh miles to Builth.

Seventh-day.
Job Thomas left us,
and the innkeeper came guide with us to Rees Bowen`'s quiet habitation.
The road was rugged, and we were glad to reach the house of our kind friend,
being weary in body and mind.

First-day, 13th. Walked to the Pales meeting.

Fourth-day.
Set forward, but it rained smartly,
and we were very wet before we reached the Friend`'s house;
appearances were rather discouraging, the master and mistress being from home,
and a poor servant girl, with three or four children, seemed almost frightened at us;
the house very mean, but like many others we have seen;
and of this we hope never to utter a word of complaint;
indeed we felt it to be cause for thankfulness to be received, and after a time,
things became more comfortable.
When the woman friend returned, she made up a good fire, and gave us some tea,
with a hearty welcome, which quite satisfied us.
Being fatigued, we soon retired to rest,
and were accommodated far beyond our expectation, with a good bed, dry linen, etc.

Fifth-day.
We had a religious opportunity with the family,
under a measure of our Heavenly Father`'s love.
We then set out for Pencraigg; a terrifying storm of wind and rain came on,
such as we had never experienced; but at length,
being sometimes on horseback and at others walking, we safely reached our journey`'s end,
to our no small comfort.
Poor, wet, dirty figures we were! so we went to bed while our clothes were dried.
We here met with James Lewis, from Llanelly, who had kindly been from place to place,
in order to join us; it is some encouragement to our feeble minds,
when we find valuable friends so disposed to help us on our way.

Sixth-day.
A season of religious retirement in the family.
Walked to visit a poor man, with whom we had an affecting time, under a sense of a tried,
tempted state.
Left him in a very tender frame of mind.

Seventh-day.
Weather bound; which is no little disappointment;
however we are preserved tolerably quiet in our minds.

First-day, 20th. Sat their morning meeting; the afternoon being favourable,
we returned to Rees Bowen`'s,
and were thankful to be once more quietly and comfortably accommodated.

Second-day.
My dear friend much indisposed and very low, which is discouraging to me;
I strive after resignation, and hope for a brighter day.

Third-day.
Mary Beesley is better; we went, on horseback, to visit two families,
each consisting of a man and wife, and five children.
In the evening, Timothy Bevington, Thomas Colley, Joseph Gurney Bevan,
and Richard Phillips, arrived very unexpectedly at Rees Bowen`'s,
appointed by the yearly meeting to visit the meetings in Wales;
a service which I hope will prove edifying, for they are in want of help.

Fourth-day.
Went to Builth, after having a meeting.

Sixth-day.
The week-day meeting; a comfortable season in silent waiting.

First-day, 27th. Sat the meeting in poverty, though not without some sense of good.
Father of mercies! if we are right,
strengthen us still in the right to stay! if we are wrong, thy light impart,
to lead and teach the better way!
Surely Thou hast raised in our hearts a sincere desire to
be thy obedient children! the desire after good is thine,
and the work of righteousness is altogether thine;
and thy power alone can carry on and perfect thy own work!

Very unexpectedly, a little light broke in upon us, as we were sitting together,
retired in spirit, after some Scripture reading, and a few words,
spoken in tenderness by Rees Bowen.
It was a refreshment, to our drooping minds, and we retired to rest, somewhat revived.

Second-day.
Rees Bowen accompanied us to the school, near Llanidloes,
where we were kindly received by Robert Whitaker and his wife.

Third-day.
Sat with one family.
After dinner our certificates were read, before the children withdrew,
and we had an opportunity of explaining to them the nature of our engagement.
Had a very pleasant walk to visit the family of Richard Brown; and another family,
in a very poor cottage.
Our minds were comforted in these lowly cots.
We had also a time of solid retirement in spirit with Robert Whitaker and wife.

[.offset]
+++[+++Extract of a letter from Abigail Starbuck to Mary
Capper and Mary Beesley received at Richard Brown`'s.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Milford, 17th of Ninth month, 1794.

[.salutation]
My dear Friends,

We were much pleased to hear from you,
as you have been much the companions of our conversation,
since we left you in this your arduous undertaking,
sincerely wishing you comfort and encouragement in your passing along;
which we have no reason to doubt,
as I believe your minds are engaged to discharge the trust that is committed to you.
Dear Friends, I may assure you it was with reluctance we left you;
for the little time that we were with you had made you feel very near to us,
and we felt a near sympathy with you at parting.

We were obliged for your information of the committee`'s intention of visiting us,
and hope they may be the means of strengthening the weak among us,
for we have need of help; though I am sensible they cannot do the work for us,
(although far more experienced) but that we must each look to our own standing.
It is my wish that we may; and that we were worthy to be remembered by you,
and to unite in desire after strength to press forward.
I believe you will be often remembered by us,
in our sequestered situation and lonely sittings.
We are obliged to you for your care about our getting home,
and can say the satisfaction we received in your company,
more than compensated for the little fatigue of the journey.
We found our children well.
With our united love to you, in which they heartily join, your affectionate friend,

[.signed-section-signature]
Abigail Starbuck.

--

Fourth-day.
A very exercising time in a family; yet we had to believe that Divine love is extended,
to gather the returning prodigal.
Sat also with a young woman who frequents our religious meetings;
her parents being present.
It was a time of renewal of strength.
Had a satisfactory opportunity with the children after dinner; all seemed attentive,
and some tendered; as were our own spirits.
Our minds have been a little refreshed in this place.

10th of First month.
Fifth-day.
Left Llanidloes, and came eight miles to Eskergoch, where we sat their small meeting.
The accommodations very lowly; we had a little refreshment with us,
after partaking of which, and distributing our morsel, came twelve miles to Machynlleth.
Richard Brown accompanied us; his pleasant countenance and his solid conduct,
seemed to do us good.

Sixth-day.
The morning wet, but we set forward with our acceptable guide; afternoon fine;
got to Llwydee, and were kindly received at the house of Henry Owen,
which is surrounded by huge rocks; with a grand view of Cardigan Bay.

First-day, 4th of Tenth month.
The meetings were held at Henry Owen`'s; some sober people attended.

Second-day.
We set out, accompanied by Henry Owen and wife, and our pleasant guide, Richard Brown.
I rode single; the road rugged and stony, surrounded by prodigious mountains,
with precipices, and the sea rolling below; the appearance awful,
but my mind was preserved from apprehension of danger, which was no small favour.
After emerging from between lofty rocks, just at twilight,
Dolgelley appeared rather a pleasant spot, though it is a poor mean town.

Third-day.
Went to a meeting appointed at Tyddyn-y-garreg; but few Friends.
After some conflict, we gave up to what we apprehended might tend to peace;
and accompanied by Richard Brown, proceeded to sit in the families separately,
and were favoured to get through to satisfaction.

Fifth-day.
Breakfasted at Welchpool, where we parted, in mutual tenderness,
from our kind guide Richard Brown.
The country now open and beautiful,
but my thoughts were much with the inhabitants of the mountains.
Reached Shrewsbury.
Buildings and signs of opulence, very different from what we have left.
Our minds in a low spot; though through condescending mercy,
no railing accusation disturbed our measure of peace.

Sixth-day.
The few Friends met us here.
Received letters.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Milford, 10th of Tenth month, 1794.

[.salutation]
Dear and esteemed Friend, Mary Beesley,

We have been anxious to hear how you get along,
and we had the pleasure to hear from you by the Friends that visited this quarter;
their concern was to strengthen what remained,
and to endeavour to build up the waste places,
and to encourage in us a diligent perseverance in the Truth.
It appeared to me that their counsel and admonition
was dropped in much caution and tenderness,
and I hope it may be attended to by us all.
Their visit was truly acceptable.

My dear friend,
I feel myself much obliged to thee for thy tender counsel and advice to our son Samuel,
and hope it may make lasting impression on his mind.
It is my desire, for mine, that they may be enabled to make straight steps,
having their eye single,
to that which is able to preserve from the snares and temptations which may present;
and as for us that are advanced in years, though we are far short of being as way-marks,
it is my desire that we may so conduct ourselves as not to be stumbling-blocks;
but that we may endeavour to press forward,
though many times under a sense of our own weakness and unworthiness,
feeling desires to unite with the living,
and to be favoured to partake of the crumbs which fall from their tables.

Samuel desires gratefully to acknowledge thy kindness to him;
and Daniel presents his dear love to both his beloved friends,
he was pleased to hear of their being at Llanidloes,
and would be obliged by their opinion respecting the school.

--

Seventh-day.
Set out for Coalbrookdale; good road and fine country; the Severn winds beautifully.
Not a little gratified in meeting with our very kind friend, Richard Reynolds, his wife,
and dear Priscilla H. Gurney.

First-day, 11th. Sat the preparative and other meetings.

Second-day.
Called at two schools, supported by the Dale Friends,
for the instruction of poor children.
It was pleasant to sit with the children, and to observe the care exercised toward them.
We then walked to the cottage, a quiet retreat:
we were accompanied by dear Priscilla H. Gurney, who has an apartment at the cottage,
for her own accommodation, furnished in simplicity.

Fourth-day.
Several Friends accompanied us to their monthly meeting, at Shrewsbury.
A small gathering.

Sixth-day.
Came to the house of T. Waring, at Leominster.
Our mare failing in strength, we judged it best to send her to Worcester,
under the care of our attentive and constant guide, Thomas Goode,
whom we also think it right to set at liberty to return home.
We have to acknowledge his uniformly obliging care towards us,
throughout our long journey.

Seventh-day.
Again set our faces toward the mountains, to attend an adjourned monthly meeting,
at the Pales, in Radnorshire.
William Young was so kind as to accompany us.
Got to Rees Bowen`'s about dusk.

First-day, 18th. Agreeably surprised to see Richard Brown, who had come to meet us.
Several sober people attended the meeting, to our satisfaction,
and we hope in no way to their own hurt.
At the meeting for discipline, most of the few members and their children were present,
and we have some ground to think it was a favoured opportunity, to our encouragement.
The hands of the very few rightly concerned Friends
in these parts stand in need of strengthening,
and the dear children of instruction.

20th. A beautiful day for our return to Leominster.

21st. At meeting.
A weighty part of our concern remains to be accomplished;
that of sitting in the families of Friends of this county.

23rd. Entered on the service;
the company of our friend William Young is very acceptable to us,
24th. Simple obedience to apprehended requirings is no small exercise;
but worthy is the Lord to be waited upon, and in humility obeyed!

29th. Came to meeting at Bromyard.

30th. A day of humiliation and poverty of spirit.
Sat with the families; in the evening favoured with a peaceful calm.

Eleventh month 1st. Came to Thomas Pritchard`'s at Ross.

4th. A little favoured with that which tenders and contrites the hard heart;
which is not at our command, but is very precious, and worth waiting for.

6th. Went ten miles to visit a family;
very affecting was the situation of the man Friend; lamenting, in much contrition,
time passed, with faculties abused; an awful lesson!

10th. Rode on horseback to Cowkerry, and sat with the family;
this concludes the engagement here.
My mind is in a low spot; but upon a retrospect, do not feel condemnation,
but encouragement to continued prayer to the Father of mercies, that I may be a humble,
patient believer, waiting at the footstool of Divine grace.

11th. We have not felt at liberty to leave this place, tomorrow being the monthly meeting.
If favoured with a little renewal of strength to our edification, we shall not murmur,
though we feel it desirable to reach our journey`'s end.

12th. Sat the meetings under close exercise; we trust that our desires were honest,
and the rest we must leave;
but O! may the Father of mercies more and more manifest of his own wisdom and pure righteousness,
in the secret of our hearts; and may we who profess the Truth, be humble,
patient and faithful!

14th. Favoured at Worcester meeting, with inward comfort and peace.

[.offset]
+++[+++Soon after the conclusion of this journey,
Mary Capper went to pay a visit to her brother Jasper, at Stoke Newington,
during which she wrote as follows:]

1795, First month, 4th day.
As I rode this evening from London to Stoke Newington,
it came under my consideration whether it might not be profitable to myself,
or in some measure to the dear children with whom my lot is now cast,
to take some written account of my daily thoughts and actions,
with the most prevailing dispositions of my mind.
It is under humiliating apprehensions that I enter upon this work,
as I mean to be honest in the main,
though I often think it a favour that we are not obliged to tell all we think;
for strange is the motley throng of human thoughts!

This morning after walking to town with my brother, Molly,^
footnote:[Mary Whiting, afterwards Harding;
for thirteen years the faithful and beloved nurse in J. C.`'s family;
and one to whom Mary Capper was much attached.]
and the children, went to meeting, where our friend Thomas Scattergood was favoured,
in gospel love and power, largely to minister instruction,
consolation and encouragement to the devoted in heart;
particularly to the young and the rising generation;
and I think that according to my measure,
my desires were sincere and earnest that the dear children (some
of whose minds I am persuaded are favoured with pious impressions,)
may be rightly encouraged to hold on their wav,
in holy integrity.

In the afternoon, after some conflict of doubts and fears,
I ventured to express a few words;
whether under right influence I must leave to Him who judgeth in mercy:
but for this sweet, consolatory word mercy,
as a distinguishing attribute of our Creator and Redeemer,
surely my heart would faint within me!
At the close of the day, while my sister was reading the Scriptures,
my mind was favoured with a little overflowing tenderness.

Second-day.
I attended the morning meeting.
I trust it was not an unprofitable season; it is not pleasant,
but I believe it is well for us to be sifted as wheat.

Third-day.
Favoured with a renewed desire to walk in humility, simplicity and faithfulness,
under which I felt affectionately united to the dear children, their beloved mother,
etc.

The children went to their grandfather`'s, and Elizabeth Fry,
with her daughter Elizabeth, took tea here, I thought their company pleasant.
In the evening my brother read some chapters of the Bible to us,
and my mind was comforted.
In humble gratitude I may note that, during the greater part of this day, I have been,
through adorable mercy favoured, with a secret hope of preservation, and desire after it;
of myself nothing; but in mercy, not consumed!

Fourth-day.
Without much hesitation, left my bed soon after six.
Had a gentle reproof from my niece Rebecca, for being too long in dressing;
she seemed to think I had lost some time,
which I might have employed in improving myself with her, in the French language;
we read together before breakfast.
Went to town; it was monthly meeting.
Desirous that I may be favoured to distinguish the voice
of the true Shepherd from the voice of the stranger,
and that I may be made humble, willing and obedient.

Fifth-day.
In the Scripture reading and solemn pause, my mind was comforted.
My brother was so kind as to read us a little account of the method,
pursued by himself and my sister, in the instruction and education of their children.
With some parts my mind was much affected, even to tears;
and a language arose in my heart,
O! that all parents were thus solidly concerned for the good of their offspring!
As I look toward my other near and dear relatives who stand in this important station,
and towards those who are unmarried, my desire is that genuine religion,
in its true spirit and power,
may so work upon their minds as to open their understandings in the way that is right,
and that will lead to peace, when the world, and all its gaudy, busy scenes,
shall vanish as a dream.

Sixth-day.
Dear Rebecca showed some disposition to self-will
and ill-humour at her studies this morning;
in the evening, in some tenderness of spirit, I mingled my tears with hers,
I trust to our mutual comfort,
and renewed encouragement to strive against the evil propensities of our nature,
and to wrestle for the everlasting blessing.
Experienced sweet reviving hope and faith,
while my brother read a portion of the prophecies of Habukkuk.
Retired to rest in peace.

First-day, 11th. At meeting, my mind rather insensible to good,
but kept alive in the secret hope and belief, that none ever sought the Lord in vain,
though He is pleased at times to hide the light of his countenance from his waiting,
dependent children.
In simplicity, humility and faith is our safety.

Third-day.
Still favoured with desires after preservation, and with some sense of my own weakness,
and utter inability to help or save myself.
Felt also a strong and affectionate desire for the
best welfare of my near and very dear relatives.

Fifth-day.
After the usual reading, M. Whiting walked with me to Tottenham meeting.
A little act of obedience to apprehended duty, in visiting a family under affliction,
seems to have relieved my mind from some oppression;
and the kindness of some friends was comforting to me.
May the Fountain and Father of living mercies be pleased, in his own free grace,
to preserve me, with all his little ones, in simplicity and in true lowliness,
and in obedience to his own requirings; in condescending mercy,
giving us to distinguish what is his holy will concerning us!

Sixth-day.
The first breathing of my spirit was after preservation from all evil,
and that I might more fully know the Power that leads from every hurtful thing.
In the afternoon the little girls and I visited some poor families,
and had a degree of sweet satisfaction in being empowered to give
some relief Great are the necessities of the poor at this day;
added to the extreme severity of the weather; every article of food is at a high price;
a quartern loaf is 1s. 5d+++.+++; much is done by subscription, to alleviate their sufferings,
much is wanted.

Seventh-day.
In my private cogitations, found self still alive,
and that its branches shoot in all directions, and still want the pruning knife.
One of the dear children a little untoward; but upon retiring to rest,
after lying awhile upon the pillow, tenderness and contrition were granted.
Precious are the evidences of a broken heart and contrite spirit;
it is my joy to be permitted feelingly to participate.

19th. Second-day.
Another little girl added to my sister`'s olive branches.
My niece Rebecca, with her little sister Katharine, went to Plashett, with their aunt Fry.
The dear remaining children were as quiet as might be expected,
but I felt myself a very poor substitute among them, and was rather uncomfortable.
I endeavoured to fill my sister`'s station, by attending to the little one`'s lessons.
In the afternoon more at leisure, and enjoyed the respite;
in the evening the subject of our reading was very affecting;
relative to some of the grievous iniquities of the Slave Trade.
O! how cruel is the human heart, when not changed by the power of God!
I feel sad under the consideration.

Sixth-day.
The night was so intensely cold that I could scarcely sleep;
what then must be the sufferings of the half-clothed and hungry poor!

A French lesson before breakfast; read afterwards in the Epistle to the Hebrews.
The children, at their usual occupations, did not give much trouble,
but my mind was anxious and not comfortable.
I seemed to wish for more ability to instruct the young mind,
and felt myself very ignorant in divers useful things.
I thought it would be pleasant to be learned, without the trouble of learning;
as in a higher concern, it is desirable to be humble,
but who is there that likes to be humbled?

25th. First-day.
Walked to town; on our way there and back,
my nephew Samuel and I called upon some poor families, and gave a little,
through the bounty of a Friend in London.
The long continued severity of the weather calls for consideration of the poor.
The river is so frozen that the bargemen cannot follow their usual occupation.
Coals are three shillings per bushel,
and I am told that some of the poor buy them by the quart.
Thermometer twenty-one degrees below the freezing point.

A warm desire has been raised in my heart, on my own account,
that I may both be preserved from offering the sacrifice of fools,
and from keeping back what may be compared to the small tithes,
when they are really required at my hands.
O! for a right spirit, and a discerning judgment!

28th. The meeting proved a time of conflict.
Surely our spiritual enemies are lively!
Still I have hope in the promises.
The Redeemer of men is my Captain and my Saviour.
O! may my spirit cleave unto him, then will my soul be kept from the jaws of the devourer.
Elizabeth Fry took me back to Newington.
In the evening my mind was not in a desirable state.
I spoke to my niece Rebecca in a wrong manner; which upon cool reflection,
I was made willing to acknowledge and condemn.
O! the humiliations which fallen nature stands in need of.

29th. Surely our Heavenly Father deals graciously with us,
when He discovers to us our insufficiency, our weakness and our dependent state!
During the morning`'s reading and retirement,
my spirit was raised in desire to follow our spiritual Joshua,
that I may witness all the polluted inhabitants to be destroyed;
and I wished the dear children might be fed with the sincere milk of the word,
and grow thereby, so as to become valiant in resisting evil.

31st. A dawn of fresh comfort this morning,
and the day passed in more tranquillity than some preceding ones.
It seems probable that my sister may soon be restored
to her important station in the family.
May she grow in spiritual strength!

Second month, 1st. First-day.
Mild but gloomy morning.
We walked to town; the meetings were dull.
If the great Lord and Master shine not in upon our souls,
how is our brightness obscured! yet though he tarry, let us wait for Him.
I dined with Elizabeth Bevington, and lodged with A. Christy.
In the evening we had a time of retirement,
in which I felt a glow of desire that the dear young
people might press through every discouragement,
and follow their spiritual Leader.
And O, gracious Saviour! preserve and lead me also;
that while I apprehend it right to speak unto others, I myself become not a castaway.

Third-day.
Our usual engagements gone through with calmness.
M+++.+++ Whiting and I visited several poor, and relieved their wants,
through the bounty of others; to our gratification and their comfort.
Coals and provisions still advancing in price,
and many are thrown out of work by the frost.

Fifth-day.
My nephew Samuel accompanied me to distribute to the sick and distressed.
In the evening, as I was sitting by the bedside of one of the dear children,
and reflecting on the prevailing disposition of my mind during the day,
I was favoured with brokenness in the recollection that
hasty and impatient expressions had escaped my lips,
to my own hurt and that of this dear child, who gently, and with becoming diffidence,
became my instructor.
Sweet and very precious is such a monitor, and my desire is that I may really profit.

Sixth-day.
"`The word of the Lord is quick and powerful;`" a reprover of evil,
discerning and manifesting the thoughts;
and I have believed it no small favour to be made sensible of such a secret Power.
This morning the dear children not quite so well
disposed for application as at some times;
but who is uniformly disposed toward good?
There is need of patience, both with ourselves and others.

12th. Very severely cold.
At the morning reading and retirement, a little secret hope arose,
that the power and mercy of our Heavenly Father was extended toward us.
My sister went through some of the children`'s lessons;
they also studied with their master.
A liberal and guarded education,
under the eye of judicious and well informed parents or teachers,
appears to me no small privilege,
where the young mind is preserved from imbibing false ideas,
and is instructed as to the different natures of things,
with a foundation of useful knowledge,
instead of that superficial learning which puffs up, and does not profit.
Rebecca and I visited some poor families,
and had the comfort of finding them in improved circumstances.

23rd. Second-day.
The morning meeting was a time of solemnity and instruction.
Dined at Joseph Smith`'s, with Thomas Scattergood and William Crotch.
Called on a sick Friend and was comforted.
The frost seems again broken up;
dreadful have been the accounts of floods in various parts,
and complicated are the distresses of many.

Third-day.
My brother far from well.

Fifth-day.
In the night he was much worse, and our distress was great,
yet something of resignation was felt;
my dear brother expressed that if the time of separation was come,
he had nothing to depend on but mercy; and indeed I believed that,
had he then breathed his last,
he would have been received into the arms of condescending Mercy.
He has been very weak today, though in a favoured, tender frame of spirit.
If we dare desire, it is for his restoration; nevertheless resignation is our lesson,
and may the great Master give us ability to learn, Himself being our Teacher.

Sixth-day.
My beloved brother is much better,
and it appears likely that he may be spared a little longer,
to fill the important stations, of husband and father; which is no small favour.
I think my spirit craves for him, as for my own soul,
that we may find a Redeemer`'s love and mercy, to strengthen and sustain,
in every succeeding combat with flesh and blood,
which can never enter the kingdom of rest and peace.
My purpose of leaving this family, so as to be at my own quarterly meeting at Birmingham,
brings me into a strait; nor have I yet fully determined.

Seventh-day.
My brother continues to improve.
In the evening we were favoured with a little quiet waiting in his chamber;
wherein my mind was affected with a sense of our Heavenly Father`'s love,
and gracious design, in handing the cup of affliction.
My dear Rebecca was particularly brought near to my best feelings, and some remarks,
made in our little private retirement together, affected me;
surely the dear child is under the preparing, purifying Hand!
May all the dear children be preserved from everything that can harm them!

Third month 1st. London, first-day.
I have this day thought it matters little what we suffer,
if it have but a tendency to stay our minds upon God.
The two little girls and I rode to town; there was much snow.
In the evening we had a time of retirement.
It is our design to stop a day or two with my brother and sister in Martin`'s Lane,
as I still think of returning to Birmingham soon.

Third-day.
The weather still cold and gloomy.
I attended Devonshire House meeting; a solid opportunity.
My dear little girls rather too much dissipated, to the hurt, as I thought,
of their own peace, and to my dissatisfaction.

4th. Fourth-day.
We attended Gracechurch street monthly meeting.
Went to see my dear brother Jasper, and were comforted to find him better.
I think I feel desires for our growth in the Truth, and establishment therein.
In the prospect of leaving, I may add, that my visit has been some help,
strength and encouragement, to my feeble mind.

[.embedded-content-document.letter]
--

[.letter-heading]
Extract of a letter from Jasper Capper to Mary Capper.

[.signed-section-context-open]
Stoke Newington, 10th of Third month, 1795.

[.salutation]
My dear Sister,

I feel inclined to write to thee, though at present, I see but one sentence before me;
which is, that since our separation,
the little sittings we were favoured to have during thy visit,
have returned with savour to my recollection;
and some words then dropped have seemed to yield secret nourishment;
particularly those recommending us not to look for great manifestations,
but to keep little and low.
I have been, many times of late, made prisoner under the cruel hands of Giant Despair,
that is, so far as Doubting Castle; yet through mercy, not given over into his power.
Now and then a dawn of hope revives my soul; and having no other refuge but mercy,
through Jesus Christ,
who "`came into the world to save sinners,`" I endeavoured to hold fast this confidence.

--

No further memoranda occur till the summer of next year.

Birmingham, 1796, Sixth month 21st. Returned to my lodgings,
after having been absent two months or more, in which time I have visited,
agreeably and I hope not unprofitably to myself, some of my friends,
attended the yearly meeting, and stayed some time with my brother Jasper`'s family;
setting my brother and sister at liberty to make a little
excursion among their friends and relations in Wiltshire,
etc, 27th. Called at Bingley, and saw our suffering friend P. Farmer,
who appears near her end; long and trying has been her bodily affliction,
and exemplary her patience,
through the aid of that Divine power that helpeth our infirmities.

Seventh month 3rd. I have spent a few days agreeably with T. and E. Biddle,
My mind is under an increasing weight of concern,
in the prospect of joining some Friends,
in a religious visit to the families of our monthly meeting, 7th,
An evening meeting was held, at the request of William Savery, from America.

8th. Our conflicting friend, P. Farmer, was released.
Dined at Samuel Baker`'s, with William Savery, with whom I felt a sweet fellowship.
Secretly and earnestly engaged in desire for preservation; and if it be meet,
enlargement in thy law, O! my Heavenly Father.

13th. Laid before the monthly meeting my prospect of joining
in a religious visit to the families of Friends.

14th. We proceeded in the visit,
and are encouraged to go forward in the strength granted; not looking to ourselves.
John Southall and Mary Beesley are my companions.

Ninth month 6th. Concluded the family visit.
I have little to say, but have a humble hope that mercy will yet be extended to myself,
a poor unworthy servant.

Third month 5th, 1797.
Our valued friend John Southall was removed by death.
I look back with comfort to his simple, humble dedication;
and I have also felt a little consolation in having accompanied
him last summer in the visit to the families of this monthly meeting.

22nd. Our friends Ruth Fallows and John Cash, sat our meeting;
examples of silent retirement in spirit.

25th. Ruth Fallows left us.
I wish instructively to remember her quiet example under suffering.

Fifth month 12th. Having heard of the death of our much valued friend Hannah Burgess,
I think to set out for Leicester tomorrow, in order to be at the interment at Oakham,
and to proceed to the yearly meeting.

13th. Reached Leicester, and was kindly helped forward by John Priestman,
to Ridlingfon Park, a house of solemn mourning.
John Cash and William and Henry Tuke, attended the burial.

London.
The yearly meeting was well attended, and in some of its sittings,
much solemnity was to be felt; to some of us it was a very humbling time,
but perhaps not unprofitable.
George Dillwyn, David Sands and William Savery,
gave a satisfactory account of a religious visit which they
had paid in some parts of Germany and France.
Mary Beesley left London soon after the close of the yearly meeting, but my mind seemed,
from the little I could feel, still bound to London.
I have attended various meetings,
and hope I have from time to time been instructed and strengthened to hold on;
in the renewed belief that it is good to wait, and quietly to hope, and to be patient,
when we are tried and sifted as wheat.

After some consideration,
I thought I might be doing my brother and sister a kindness by staying with their family,
and setting them at liberty to attend the general meeting at Ackworth, etc.
They were absent six weeks.

Ninth month 2nd. I left Stoke Newington and came to Hertford.
Went to Special West`'s, in his little cart; found them in pretty good health,
and in more comfortable outward circumstances than formerly.
I believe their concern for the welfare and prosperity of Zion and her travellers,
is still alive and daily cherished.

6th. A certificate was brought in to the monthly meeting for signature,
expressive of unity with Mary Pryor, in her concern to visit some parts of America.

8th. Concluded it best to proceed homeward,
having for some time had a view of accompanying Mary Beesley in a visit
to some of the meetings of Friends in Worcestershire and Herefordshire;
with which I had acquainted my friends.
John Fry was so kind as to bring me to Luton, in Bedfordshire.
I was very kindly received, entertained, and I may add comforted,
at the house of Daniel Brown; their son took me to Dunstable.

11th. Came home by coach; `'tis pleasant to return in safety:
for this favour I am thankful.

13th. At the monthly meeting, spread my prospect before my friends,
with a sincere desire to have their judgment and feeling, and to submit thereunto.

25th. Quarterly meeting at Leicester.
Some monies were entrusted to women Friends for distribution.
It is a right and a good thing to inspect, and cheerfully to relieve,
the necessities of our poor.

Tenth month 2nd. Arrived at Wick, and found my dear friend Mary Beesley tolerably well.

8th. First-day.
We were at a meeting appointed at Almerly, a spot where none of our Society now reside.
We hope that neither the cause that we were engaged feebly to support,
nor the mind of any honest enquirer, was wounded.
The company of our valued friend William Young,
with some others from Leominster was particularly acceptable.
We sat a meeting at Leominster in the evening, with Friends and others.

10th. Set out for Ross and arrived late.

11th. We attended the monthly meeting, and called on Thomas Pritchard,
who is very unwell, but in a lively, tender frame of mind;
expressing his humble desire for daily supplies of patience,
that he may bear his afflictions with propriety.
We thought it a lesson of instruction.

16th. At Stourbridge monthly meeting.
Apprehending it right for us to propose sitting with Friends in their families,
it was concurred with; Elizabeth Lowe joined us, which was helpful to us.

24th. Proceeding with the work.
There are seasons when these times of retirement in families
are made refreshing to both visitors and visited.
The main end in view is, that all within us may be humbled, and our spirits contrited,
and sweetly united in a harmonious labour for the
prosperity of Truth in ourselves and others.

25th. Dudley.
We have been closely engaged; not loitering, but humbly desiring, as enabled,
to help and to be helped.

28th. Stourbridge.
Visited two very poor creatures, from misconduct and mismanagement.
They have been disunited from our Society, not marrying members of it,
nor showing any regard for its excellent order or wholesome discipline;
yet to such as these, tenderness and love should be extended; and I thought we felt,
in one of these opportunities, that precious,
sacred influence which breaks the hard heart;
and this condescending favour is worth seeking for.
O, how it unites! how it humbles the families of the whole earth, when submitted to;
without distinction of high or low, rich or poor!

30th. Left Stourbridge; not without painful feelings,
as it did not seem a time for our minds to obtain full relief.

Eleventh month 2nd. Came to Worcester, and dined at T. Bevington`'s,
where we met with Sarah Stephenson, Mary Jefferies, Ann Hunt and Elizabeth Bevington;
the two former were engaged in a visit to the families of Friends in this place.
In the afternoon we came to Wick, and passed the evening quietly together.

8th. Mary Beesley returned her minute to the monthly meeting.
I concluded to remain awhile with her, as her mother is from home.

Twelfth month 2nd. Returned to my own comfortable home.

3rd. First-day.
Sarah Lynes, a very young ministering Friend, was at our meeting.

13th. Sarah Lynes attended our monthly meeting, and was largely engaged in the ministry.
Ann Baker requested the concurrence of Friends in her desire to accompany Sarah Lynes.

18th. Our quarterly meeting at Coventry.
Sarah Lynes engaged in stirring up the members of our Society
to a closer attention to the pure principle of Truth,
as we profess it.

20th. As Sarah Lynes had a meeting in the evening,
we thought it might be right for M. B. and me to stay here,
and endeavour to strengthen her hands.
The meeting was large.

22nd. Sarah Lynes was concerned to go into the market
and call the people to amendment of life, etc.
During our stay at Coventry, we attended several meetings appointed by her,
and accompanied her to visit the prisoners in the county jail; an affecting scene!

29th. We returned to Birmingham.

1798+++.+++ First month 1st. My beloved friend Mary Beesley left me.

Third month 23rd. Attended the interment of Sarah Atkins, Jun.
at Chipping Norton.
William Savery was unexpectedly there.
Went to the quarterly meeting at Worcester,
and afterwards spent a few solitary days at Wick,
my dear friend Mary Beesley being at Worcester,
fitting up some rooms which she has taken for a residence.

I stayed several weeks with M. B. in her new home,
and found the accommodations comfortable.
With peace of mind,
all places and all circumstances are made more supportable than we may anticipate.

[.offset]
+++[+++While at Worcester,
Mary Capper thus addressed her endeared friends Ann Baker and Sarah Lynes,
who were still labouring together in the work of the ministry.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Worcester, 29th of Fourth month, 1798.

[.salutation]
Dear loved Ann and Sarah,

How very often have you been the subject of our thoughts!
We have spoken of you, I believe, daily,
and yet more often secretly breathed in spirit that
the Father of mercies might be with you;
the account of your exercises affects us with an
awful sense of Divine condescension and care,
renewedly manifested on your behalf.
We have afresh to believe that it is your meat and
drink to do your Heavenly Father`'s will,
and that you have, at times, to partake of food which the world knows not of;
but we are ready to fear that natural strength must sink under such exertions;
nevertheless we desire to trust in that Power that constrains, and also abilitates,
far beyond our comprehension; so may you be directed, helped and strengthened!

[.signed-section-closing]
In unfeigned affection,

[.signed-section-signature]
Mary Capper

--

Seventh month 11th. Requested permission, from my monthly meeting,
to accompany Mary Beesley in a visit to Friends of Bristol, etc.

22nd. First-day.
After our morning meeting, I walked to Wednesbury,
Deborah Darby and Rebecca Young having an evening meeting there;
it was very fully attended, and proved a solemn time.
O! that all might profit by opportunities like these, and gather to God.

Eighth month 22nd. At the monthly meeting at Atherstone; received my certificate.
It is my desire to have the unity of my friends, in all these important concerns.

23rd. I thought our meeting was favoured with a renewed
sense of our Heavenly Father`'s regard;
such seasons incite us to hope and persevere under discouragement.
Mary Lloyd was enabled to supplicate at the footstool of mercy.

Ninth month 17th. Mary Beesley and I had a meeting at Gloucester,
and then proceeded to Bristol, where we were accommodated at Thomas Pritchard`'s,
and attended the quarterly meeting.

24th. Were at the quarterly meeting at Melksham, from whence we went to Exeter,
and sat the meetings on first-day.
Our valuable friend Ann Byrd was with us at these meetings,
and at the quarterly meeting at Kingsbridge, where she was a help and strength to us.
The young men were, in a particular manner, warned and tenderly exhorted,
on the subject of unbelief.
A dark and subtle spirit of scepticism seems, as it were, let loose in many places.
O! may the God of Truth preserve us.

Tenth month 9th. We were at Thomas Fox`'s, Wellington; sat with the families there,
and had a meeting with Thomas Fox`'s work people.
Went to Milverton; sat in the families,
and had times of religious retirement in the two schools;
the children were remarkably solid, and some of them tendered in spirit.

17th. Came to Taunton, where I saw my nephew Edward Capper,
(the son of my brother John,) who was stationed there,
having enlisted under the banner of man.

29th, Came to Bridgewater, indisposed from a cold, and under trial of mind,
having felt a secret impulse to visit the prisoners in the jail at Ilchester;
but a fear took hold of my mind,
lest we should undertake such a thing without right qualification;
or that having heard of others being so led,
we might mistake tender sympathy for a call of duty.
Under this secret fear,
I did not strengthen my beloved friend in her apprehension of duty,
but rather desired that we might again try the fleece; so we went to Bridgewater,
where we passed a tried week, finding our way closed up.
We then judged it best to open our minds to a few Friends, who, to my admiration,
felt for and with us, and pointed out a way for our relief.
Richard Ball wrote to John Hipsley, who came to us and accompanied us to Ilchester.
He spoke to the jailer and under sheriff, explaining the nature of our request;
but no such thing was admissible.
A chaplain being employed, it was alleged that the prisoners`' minds were comfortable;
so we left Ilchester not much comforted.
We went to Street, where we met with Hannah Barnard and Elizabeth Coggeshall from America.

Eleventh month 22nd. Came home to the house of our kind and fatherly companion,
and friend Josiah Naish, who has been with us a considerable time.

25th. At the monthly meeting at Claverham, and sat in some families;
but receiving information from Worcester, of the death of H. Beesley,
and of the alarming illness of Joseph Beesley, after deliberate consideration,
with the concurrence of our friends, we concluded to go to Worcester.

30th. At Worcester, had the satisfaction to find our valued friend better.

Twelfth month 10th. Came home to Birmingham.

31st. Went to Worcester.
Visited the poor unhappy prisoners in the castle.
Mary Beesley`'s state of health, a heavy fall of snow, and other impediments,
detained us long from our journey.

1799+++.+++ Third month 9th. We set forward.

31st. At Glastonbury, Joseph Naish joined us.

Fourth month 2nd. We went to Compton, passing through Ilchester.
We remembered our feelings there, and were depressed.

3rd. At the monthly meeting at Yeovil.
Returning to Ilchester, we gained admittance into the jail,
to visit the three poor unhappy men, who were to be hanged in a few days.
O! wretched, wretched man, when separated from the love of God in Christ Jesus!

9th. Came to Bristol quarterly meeting.

12th. We went to Newgate, accompanied by several Friends.
It proved a solemn time of warning, exhortation and encouragement, to the poor prisoners;
O! that men would fear the Lord, and walk as in his presence.

13th. With Samuel Dyer, Mary Dudley and others, we visited the asylums for the blind,
and for orphans; in both places there were religious communications.

Dear Mary Beesley alarmingly unwell, which occasioned a painful delay of two weeks;
but every dispensation, if rightly submitted to, is profitable.
When she had a little recovered, we ventured out together,
and were at the small meeting of Lawrence Weston; dined at John Harford`'s,
Blaise Castle, and had an opportunity of serious communication in the family.

30th. At the monthly meeting, at Bristol,
where we proposed going into the families of Friends in the city.
After so doing we felt our minds, through condescending favour,
humbly and quietly stayed,
in the secret hope that we should be helped forward in the line of duty,
through all discouragements.

Fifth month 4th. We came to the house of our very valuable friend Joseph Naish,
who accompanied us to the families at Claverham, Yatton and Sidcot.

16th. We came again to Bristol, where we met our dear friends Sarah Harrison and Ann Byrd.
They, like tender, nursing mothers, entreated us kindly, and cheered our drooping minds,
with the language of encouragement.

19th. First-day.
We entered upon the serious business of visiting the families, also the schools,
and the house of reception for the destitute and vagabond poor.

We remained in and about Bristol for three months, and on the 27th of eighth month,
left our kind friend Thomas Pritchard`'s with quiet and thankful minds.

Ninth month 4th. We reached Worcester; and although we feel poor and unworthy,
yet we can humbly acknowledge that the gracious Creator
and Preserver of men is ever worthy to be served.

10th. Returned to my own home.

1800+++.+++ First month 2nd. This year is ushered in with dearness of all provisions.
The poor are helped by the establishment of soup shops,
and have a quart of good soup for a penny some of the respectable inhabitants attend,
to serve it out and keep good order.
This mode of relief gives much satisfaction.

12th. First-day.
At Gracechurch street meeting.
Thomas Scattergood was engaged in the ministry,
in language somewhat prophetic of a trying day to come,
and earnest exhortation to be prepared for it.
I saw and spoke to Sarah Lynes.
She continues to exercise her extraordinary gift,
and has lately visited the families of Friends of this meeting with Susanna Home.

Second month 1st. Mary Pryor and her daughter Savory dined with us, at Stoke Newington.
Mary Pryor gave us a very affecting description of her voyage,
and preservation on her passage to America;
also permitted us to hear some recent letters from thence,
one of them containing a pathetic account of the death,
or perhaps we may allowably say the happy translation of Samuel Emlen,
whose labours in this country are remembered, by some of us, with heart-felt tenderness.

10th. Attended the morning meeting;
these meetings are often very instructive times to young ministers,
and I esteem it a privilege to sit them.

24th. Attended the select quarterly meeting, and went home with Mary Stacey,
to Lamb`'s Conduit street, where I lodged, and passed my time not unprofitably.

25th. Accompanied Mary Stacey to the quarterly meeting, which was very solemn and quiet.
Awful and affecting were the exhortations and warnings given by our friend Thomas Scattergood.

Fourth month 13th. First-day.
I attended the Peel meeting; which is much altered since I resided within its compass,
many being deceased, etc.
I dined with Robert Webb, who is now mostly confined to his house.
I well remember his kind notice of me, when I first attended that meeting.
I also called on a poor woman Friend, who in days that are past,
showed me great kindness, which I have not forgotten.

27th. First-day.
At both meetings.
Low seasons are sometimes most lastingly profitable.
Walked to an interment at Whitechapel; was glad to meet with Thomas Shillitoe,
who kindly helped me along.
Returned to Stoke Newington in time to partake of
the benefit of the family-reading of the Scriptures,
which often proves a refreshment, after a trying, fatiguing day.

Fifth month 7th. At the monthly meeting.
Sarah Lynes returned a minute.
I dined with her at Joseph Savory`'s;
she very modestly gave some little account of her arduous labours at Leeds, etc.

19th. The yearly meeting of ministers and elders began.
It was pleasant to see the faces of so large a number of valuable Friends,
who since this time last year, have, many of them,
been diligently and laboriously engaged for the spreading of the Gospel;
not only in this part of the vineyard, but extending their visits more widely,
as strength and ability were given, to go forth,
and gather the people to the true Shepherd.
It was also very precious to sit under some sense of the goodness of that Power
which unites in harmonious desire for the well-being of immortal souls,
and that the whole rational creation of God may be brought to know,
and truly to serve Him.

21st. The women`'s yearly meeting opened.
Solemnity was afresh felt to spread over us, and a desire was felt by some,
to be so watchful as to keep our proper stations,
whether in silent exercise or more active service.

26th. A memorial respecting Martha Haworth was read.
Sweet tenderness of spirit was felt, and a desire raised, that through renewed mercy,
our minds may be stimulated to dedication.

27th. Felt secret breathings that solid edification might
be the blessed fruit of these our large assemblies.
Some discouraging circumstances did occur.
By high authority we are taught that offences will come;
but blessed are they who are not offended in Christ!
A letter, addressed to the yearly meeting, by a Friend in Wales,
(probably Job Thomas,) now confined to his habitation from indisposition,
was sent in from the men`'s meeting and read.

28th. At Southwark meeting, formerly called the Park; it was a time of refreshing,
during the offering of supplication by dear James Graham.

29th. Our friend Phebe Speakman, now about to return to America,
addressed us very affectionately.
We received an instructive visit from Samuel Dyer, David Sands, and Thomas Shillitoe.

30th. Much counsel was administered,
encouraging individuals to circumspection in their daily walk;
and to a careful discharge of manifested duty, in speaking the truth one to another,
rather than one of another; and after a silent pause, we separated.

Sixth month 1st. At Peel meeting in the morning.
Felt a secret sense of reproof for uttering words somewhat hastily,
though I did apprehend that I felt a gentle impulse to stand up;
but I believe from my own feelings,
(afterwards confirmed by my friends) that I did not sufficiently weigh the necessity;
and I did not reap the reward of sweet peace;
this I wish to note as a warning for the future.

Birmingham, Sixth month 29th. First-day.
At meeting this morning felt solitary, having no companion in the ministry;
Ann Baker being married, and gone to reside at Worcester,
and M. Lloyd being absent at this time.
In the evening Mary Stacey and Sarah Lynes had a meeting with the inhabitants.

Eighth month 6th. At our monthly meeting at Hartshill,
where I asked leave to visit the preparative meetings; and if the way should open,
the families of Friends, in the South Division of our quarterly meeting,
also some meetings in Oxfordshire,
in which I expect to be joined by my dear friend Mary Beesley.
In the evening I went to John Dearman`'s, as he and his wife had gone from home.

17th. First-day.
More than a week has been passed in my new occupations,
which take up much of my attention; the dear children are very interesting.

24th. My dear friend Mary Beesley came to accompany me in my journey;
both of us having the concurrence of our friends.

25th. We went to the house of our kind friend T. Harris, Long Compton.

27th. Our kind friend took us, in a little cart, to Stow,
where we attended a very small meeting.
We were kindly entertained by a widow, who does not profess with us,
but who seems sensible of the uniting influence of the one cementing Power.
After dinner, something better than ourselves seemed to clothe our spirits;
and encouragement to the widow, and counsel to her son, were expressed.
Came afterwards to Camden.

28th. Rode on horseback to meeting.
Here they have some true mothers among them, and agreeable young people,
so that the preparative meeting is held to some satisfaction.
We lodged at our friend Jeffrey Bevington`'s, and were very kindly cared for by his wife,
who is not only an affectionate, attentive nurse to her infirm, afflicted husband,
but also ready and willing to entertain strangers.

After partaking of the refreshment of the table, and through favour,
of spiritual refreshment together, we considered it safest for us,
in order to find peace, to sit with the other families of Friends.

Ninth month 3rd. Were at the week-day meeting at Shipston; sat with several families,
and with some in the station of servants, not professing with us;
for we sometimes feel bound, in Christian love, to speak a word of counsel,
warning or encouragement, as it may arise in our hearts, to those of other denominations;
well knowing that mere outward distinctions are nothing.

5th. We went to the meeting at Eatington.
Retired to rest under some feelings of discouragement, with many a fear lest, through us,
the cause of Truth should suffer, or any honest mind be hurt.

6th. Visited a family and expressed what seemed to be given us,
amid considerable interruptions.
Sometimes the hope is raised, that although some visits of this nature may be painful,
with little sense of good being present, yet, if of the Great Master`'s ordering,
they may return into remembrance, at a future day.
Before we left the house of our valuable friend J. Bevington,
we felt a concern to ask his judgment on the propriety
of our sitting with his servants and workpeople;
after a little deliberation, it was encouraged, and the way made easy; no harm,
we humbly hope, ensued, and our minds were at liberty to return to Tredington.

7th. First-day.
Sarah Lamley accompanied us to Brails, where the neighbours were invited to meet us,
and a considerable number came;
we may thankfully acknowledge that something better than
ourselves was felt to gather our minds into a sweet stillness;
and the people were, in the ability afforded,
recommended to seek the substance of religion.
Went to an evening meeting, at Long Compton; on the way, took tea with a family,
where to our humbling admiration, we received renewed capacity to offer counsel,
in a feeling sense of secret help.
The meeting was large, quiet and orderly; and may be remembered as a time of favour.

8th. A very stormy morning; when the rain abated we set out,
with our steady friend Thomas Harris, and usual equipage;
viz. a little cart and a blue blanket to keep off the wet;
and we reached Chipping Norton in time for the monthly meeting.
Dined at William Atkins`', and called on some friends.
A feeling of sadness covered our minds, under which it seemed best to keep quiet,
and not to strain our eyes, as in the dark, to discover the cause.

9th. Sarah Lamley met us at Stow, where we attended a marriage; several came in,
particularly some young people, and it was a serious time.
The young couple had been recently received into our Society;
we dined with them at the young man`'s father`'s; a humble habitation,
but we were afresh convinced that there is no respect of persons
with the Almighty Dispenser of good unto the souls of men.

10th. Came to Burford, and sat the meeting on the 11th,
which did not fully relieve our minds,
so we ventured to consult our friends on the propriety of inviting some of the neighbours,
particularly the labouring people and servants, to meet us.
We were encouraged to do what we might find to be required,
and tomorrow evening was fixed for the meeting.

12th. Had a meeting with Friends at Whitney, and returned to Burford.
William Crotch and a Friend from Cirencester, on their way to Oxford,
having heard of the meeting, and seeing us just as we reached the town,
turned about and sat the meeting, which was helpful and encouraging to us.
The gathering was very large, and many stood without;
their behaviour was very quiet and orderly, and a sweet,
solemn coveting crowned the whole, under which we separated.

13th. William Crotch went with us to Chipping Norton; we dined together at W. A.`'s,
and parted with renewed desire for the good one of another.

14th. First-day.
William Gillett kindly came from Brails, to help us forward, on horseback to Sibford.
We sat both the meetings there, and were enabled to exhort to watchfulness,
and to a real engagement of heart to follow those things which make for peace.
In many places, there seems loo much resting in the mere profession of religion.

15th. Came to a meeting at Adderbury.
Very kindly we were received at Thomas Wycherley`'s;
both he and his wife are frequently afflicted with illness,
and their minds seemed to be kept low and tender.
We had a very comfortable night`'s rest, very sweet was the quiet we felt.

17th. We kept within doors at Banbury,
on account of a tumult having arisen about the high price of provisions.

23rd. Select quarterly meeting at Leicester;
we had the acceptable company of Elizabeth Coggeshall,
who exhorted us to renewed searching of heart.
The quarterly meeting next day, a low season.

26th. This morning, had unexpectedly to utter the language of tender exhortation,
to a young man just recovering from a dangerous illness;
his behaviour was serious and respectful.
We afterwards learned that he is a Roman Catholic.

29th. Sarah Burgess and some men Friends accompanied us to Oakham,
where we had a meeting with Friends.

30th. Came to our quiet quarters at Leicester,
where we were again received with encouraging cheerfulness.
Sometimes it seems as if the mind would sink too low,
if it were not for the continued kindness of our friends.

Tenth month 1st. At the meeting here.
Spent some hours with an old acquaintance in an enfeebled state of health;
I hope the time was not unprofitably passed,
though nothing more than social conversation and secret well-wishing transpired.

6th. Visited the prisoners in the county jail, in company with some of our friends.
After dining with our kind friend Sarah Heaford,
we went to Daniel Woodland`'s at Narboro,
he having kindly undertaken to help us on our way to Sutton,
where we propose to have a meeting.

7th. A large and serious gathering at Sutton; the people behaved well,
and we humbly hope it was not a profitless time.
We trust that some instruction has been gained by us,
under the various exercises in this our journey;
wherein some unexpected occurrences and detentions have called afresh for dedication,
and the resignation of our will.
We went to Sutton and back, on horseback,
being each provided with a good horse and steady rider,
a sight somewhat unusual in this day; five horses, each double-mounted!

9th. Returned to Leicester, and attended the monthly meeting.
Afterwards had a religious opportunity with some friends,
in which love and tenderness were felt,
as well as much sympathy with many now under affliction, from sickness, etc.

13th. Reached Birmingham; it felt very pleasant to return,
with peace and thankfulness in our hearts.

18th. This day`'s post conveyed the mournful tidings
of the death of our valued friend Joseph Beesley,
at Bath.
I purpose accompanying my dear Mary Beesley to Worcester,
as she is now stripped of all her near connections.

Eleventh month 11th. Once more returned to my pleasant home.
Public distress is great; flour and bread at a very high price.

24th. Flour is now six shillings per peck.

Twelfth month 9th. At our meeting of ministers and elders,
we were a little encouraged by the company and communication
of our dear friends Mary Ridgway and Susanna Appleby,
though the spiritual life seems low.

10th. At our monthly meeting our dear friend Mary Ridgway, was led to lament our poor,
low state, as to spiritual vigour.

17th. Felt thankful for a quiet retreat, unembarrassed with perplexing, cares.

1801+++.+++ Third month 8th. Ann Alexander and Martha Brewster were at our meetings,
which were both silent.

9th. Spent part of the day with Ann Alexander and Martha Brewster
at Samuel Lloyd`'s. They seem under considerable trial,
in the prospect of visiting families here.
Having heard that Thomas Shillitoe has a similar view, they wait his arrival.

12th. This morning our friends commenced the visit, and sat with us.
We had a solemn pause of silence, which was truly refreshing.
We then were exhorted to become as children; and in nothingness of self,
daily to look unto the Lord, that our own wills might become fully subjected.
And surely my heart is, at this time, truly desirous that it may be so,
a hard strife is at seasons witnessed there.

28th. Sarah Lamley spent part of the day here, to my help and instruction.
O! the good Shepherd continues to be merciful.

30th. Thomas Shillitoe and the other friends called here, and I spent some time with them.
They have now finished their arduous engagement here.
Parting with those who, with meekness and patience, have laboured among us, is not joyous.

Fourth month 12th. First-day.
Thomas Shillitoe laboured, with earnestness, in both meetings,
to direct the minds of the young people especially, to fear God,
and to take heed to the thing which is right.

Fifth month.
Mary Beesley and I went to the yearly meeting.
At that for ministers and elders, Sarah Stephenson, in a weighty manner,
opened her concern to visit America; and Mary Jefferies in much humility,
expressed her belief that it was her duty to accompany her.
The women`'s yearly meeting concluded several days before the men`'s;
they had much important business before them.
We went to Hertford, and from thence, with Special West and his wife,
in their little cart.
Very pleasant it was to enjoy the sweet, fresh air of the country,
in peaceful simplicity, with dear, valued friends, long known and loved;
and whom I do still love, their integrity not having failed,
through a long course of years, and many close and bitter trials.
Their latter days seemed blessed with a more plentiful supply of things
needful for the body than when I first became acquainted with them;
and I thought I could partake of the blessings,
with grateful acknowledgment to the gracious Giver of all our comforts.
We stayed with these friends some days, attended Hertford meeting,
and came to lodge at John Fry`'s, where we were treated with great kindness.
During a time of religious retirement in this family, a poor wanderer,
from the fold of true peace, came in, and sat down with us.
My dear friend Mary Beesley was led particularly to address this unhappy young man,
in a very affecting manner.
The call was renewedly extended to him, to return unto his Heavenly Father`'s house,
and the stony heart was made capable of feeling, so that great tenderness was evinced.

Sixth month 25th. Arrived together, once again, at my quiet, desirable home,
and found the friend of the house, Mary Hands, in a feeble state.

28th. First-day.
The first meeting held in silence.
I renewedly believe that there is a Power altogether
sufficient to instruct the waiting mind,
without a word being spoken.

29th. My dear friend left me.
We were favoured to separate under a renewal of tender affection one for the other,
which is very precious.

Eighth month 17th. Our dear friend Mary Hands was released;
her patience was remarkable to the last.

21st. Under solemn feeling, the last office was performed;
nothing like sorrowing without hope, though the silent tear was shed,
to the memory of one who was most loved by those who best knew her hidden worth.

Tenth month 2rd. Mary Beesley, who came to me lately, accompanied me to Samuel Lloyd`'s,
to see Ann Byrd and Hannah Stephenson.
The long-wished for news, of a treaty of peace with France, was this day announced.

4th. A cold, wet morning, and our meeting very small;
little difficulties should not keep us from assembling together.
We stand in need of having our spiritual strength often renewed.

Twelfth month 6th. First-day.
Our morning gathering larger than sometimes; to some of us it was an exercising silence,
though perhaps not unprofitable.
It is close work, at times, to be resigned to learn in silence.

25th. Expect to go to Worcester tomorrow; the prospect rather gloomy,
it being uncertain where I may settle,
as Cornelius Hands intends to give up housekeeping.
