== Chapter VI.

[.chapter-synopsis]
* Marriage of her friend Mary Beesley in 1803
* Removal into Monmouthshire, etc.
* Death of James Lewis, 1810

1802+++.+++ Third month 10th. At our monthly meeting obtained leave to unite with Mary Beesley,
and Ann Pumphrey in visiting the families of Friends at Worcester, etc.

28th. We entered on the visit.

Fourth month 4th. First-day.
Our valued friend Timothy Bevington, with difficulty got to the morning meeting,
and was strengthened, when there, to deliver an instructive exhortation,
in a very tender and affecting manner.
His health is now so precarious that it seems doubtful
whether he may again be able to meet his friends,
in their religious gatherings;
but his earnest desire that all may strive to enter in at the strait gate,
may be profitably remembered, when his voice shall be no more heard.
In the evening, refreshed and encouraged by the renewed belief,
that our Heavenly Father binds the poor of the flock, the children of the family,
together in sweet union of spirit.

9th. Dined at John Burlingham`'s; were earnestly engaged in mind,
and had to express our desire, for the welfare of parents and children;
four sons and five daughters being present.
Returned home in the evening, after our various engagements, wearied in body,
but mercifully permitted to experience a measure of that peaceful poverty,
which is more precious than the increase of corn, wine or oil.

18th. First-day.
Our morning gathering, after a season of close inward wrestling,
was favoured with a measure of that life which is the crown of all our religious assemblies.

19th. The engagement nearly accomplished, and we may say, with lowly thankfulness,
that our minds have been renewed in love towards
our fellow travellers in the Christian race.
We endeavoured to labour faithfully, in the ability afforded;
some seasons of favour were granted,
in which we not only felt "`good will to men,`" but
could also ascribe "`Glory to God in the highest!`"

24th. This afternoon died our valued friend and nursing father in the Church,
Timothy Bevington.

Fifth month 10th. I returned to Birmingham,
still finding accommodation at my agreeable lodgings.
After attending the yearly meeting,
and spending some time with my dear connections near London, I came to Worcester,
with the view of proceeding in our religious visit.

Sixth month 30th. We came to Alcester, and sat in the families.

Seventh month 1st. Before we left, we sat in one family,
in which the visit was not so comfortably accomplished as we could have desired;
in consequence of a little circumstance having arisen, from which our minds suffered,
and were brought into bondage.
O! the great need of circumspection and watchfulness!

5th. Returned to Worcester, after sitting in the families of Evesham meeting;
we met with some painful things.
Unless the great Master be heard and obeyed,
the servants seem unable to lend a hand of help.

6th. Our kind guide and companion, Richard Burlingham, Jun.
conducted us to Ross, where we attended the quarterly meeting for ministers and elders.

7th. The quarterly meeting was a time of renewed mercy.
Afterwards visited the families.

Eighth month 5th. Came to Bromyard.
Our minds are often brought into sorrow,
apprehending the pure life of religion to have gained but little ground;
the cares of this life, with other deceitful things, seem to choke the good seed.
O! for ourselves and others, that we may increase in faith and obedience,
with a willingness to suffer, when the cause of Truth suffers; or when called upon,
to step forward in the performance of any duty.

8th. First-day.
A considerable number of the inhabitants came, by invitation, to the afternoon meeting;
it proved an open time for communication, and we were thankful, afterwards,
to feel at liberty to return home.
We reached Mary Beesley`'s in the evening; and through condescending favour,
experienced a sweet, peaceful, stillness;
so that we could say it amply compensated for all our trials.
O! the kindness and long-suffering mercy of our gracious Creator.
How He allures us to serve Him! and to obey all his requirings.

For a time we did sweetly enjoy our quiet,
but our minds were soon brought into thoughtfulness; a Friend from South Wales,
James Lewis, having made a proposal of marriage to Mary Beesley.
The subject remains under her consideration, and brings much weight with it,
being a matter of great importance.

Ninth month 2nd. Took leave of my endeared friend; endeared by often suffering together,
and being helped, by that which far surpasses all the efforts of self; and which,
in seasons of true humiliation,
unites fellow-believers in closer bonds than those of natural affection.
The fellowship of suffering is a mystery to the natural understanding of the creature,
but I believe opens lessons of true wisdom to the resigned,
dedicated followers of a crucified Redeemer;
though we feel ourselves very children in this living way,
cast up for the ransomed to walk in.

I again came to John Dearman`'s, to have the oversight of the little flock,
in the absence of their parents.
J+++.+++ D. is at Buxton, in a languid state of health.
This afternoon had the affecting account of the death of Charlotte Phelps,
at the house of her father, Sampson Lloyd.
She was a beautiful young creature, married last eleventh month;
her husband never had the satisfaction of taking her home.

7th. The remains were interred; many were present,
and a solid meeting was afterwards held.
Deborah Darby, Christiana Hustler and her daughter, were with us.

9th. I had the privilege of accompanying Deborah Darby in her consoling,
encouraging visits to several sick and tried friends.
This service, when rightly engaged in,
has often appeared to me to be the sweetest portion of the Christian`'s commission;
to comfort the mourners,
and to direct the feeble-minded where to look for a renewal of strength.

15th. In meeting,
my faith was renewed that they who wait upon the Lord shall renew their strength;
and although experience confirms the truth, that in this world we shall have trouble,
still peace is yet to be found in the Lord.

17th. I account it a favour to be again permitted to return to my old, quiet apartments,
at C. Hands`', after an absence of several months,
in the course of which time I have seen many changes, and distressing occurrences,
with perplexities and dismay.
Ah!
I have thought, without a humble hope, through faith and obedience,
of inheriting the promises, what a vast,
howling wilderness is this world! how tossed and troubled on every side! but the simple,
obedient children of the one Lord, are not left long in a state of sorrowful disquietude;
some sweet calming influence is graciously permitted, to revive the drooping faith,
and to fix the hopes on a better and more enduring portion.

Ninth month 19th. First-day.
Our meeting unusually large.
We had the company of Thomas Speakman, Edward Simkins,
Mary Beesley and Joseph G. and Mary Bevan;
some of whom ministered to our instruction and encouragement.

Tenth month 14th. Went with James Lewis, to his house at Trosnant, near Pontypool;
the house is under repair, and the roads being very dirty, with gloomy weather,
conspire to render the situation, in its present state, rather unpleasant.
The company and assistance of Mary Pumphrey were particularly acceptable to me.
Some substantial privileges are to be found, yet many things are wanting,
for neatness and convenience, according to our ideas.
There is a good new meeting-house, very near; the number of Friends is but small;
yet sometimes, both in and out of meetings,
I have thought there was that to be felt which strengthens
to put our trust in the mercies of a gracious Creator,
whose care is over all his creatures, however remotely situated;
and this consideration sweetly cheers the solitary scene,
and supports through the trials of each succeeding day.

Eleventh month 22nd. Mary Pumphrey and I took an affectionate leave of the family,
both master and servants having manifested great kindness to us.

Twelfth month 8th. At our monthly meeting I obtained leave to unite
with my friend Mary Beesley in some religious service at Warwick, etc.

13th, We went together to Tredington,
where we had the satisfaction of finding our valuable friend Sarah Lamley restored,
in good health, to her family, after an absence of several months,
on a religious visit to Friends in and about London, accompanied by Ann Ashby.
It was very pleasant to find Sarah Lamley serene and peaceful.

In the course of this engagement, we held meetings at Shipston and Eatington,
where we visited the widow Martha Bevington,
and were refreshed by observing her calm resignation.
We attended Warwick meeting, and had the inhabitants invited to one,
which proved a large and solemn gathering.
We also sat with about sixty workpeople and children in the cotton mill,
and we visited the prisoners in the jail.
After attending the quarterly meeting we came to Birmingham.

1803+++.+++ First month 9th. First-day.
A sweet, inward silence prevailed, both in and out of meeting,
for the greater part of this day.

12th. Our monthly meeting.
A measure of true retirement of spirit is yet graciously granted,
in which I feel refreshed, and encouraged to persevere, through trying times.

14th. In a feeling of very tender affection, wrote to my brother Jasper,
from whom I have received a kind letter.

16th. First-day.
Deborah Darby is here on religious service; she appears much worn down in body,
but animated for the cause of religion.
Mary Lloyd is her companion.

19th. Received an account, while at Worcester,
of the death of the wife of my dear brother John Capper.

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Lynes.

[.signed-section-context-open]
Worcester, Second month 16th, 1803.

[.salutation]
Dear Sarah,

Day after day thou hast been brought to my remembrance, with very tender love;
and a favour I esteem it to be capable of this one mark of discipleship.
I am thankful that sometimes I can believe that I have fellowship with the living;
and as I apprehend, in some measure of this I now salute thee.
Since my coming here, I have had the satisfaction to peruse thy letter to Ann Pumphrey;
it was very sweet.
I oft remember thee, and it is exceedingly pleasant to my mind; I may say to our minds,
including Mary Beesley and our dear Ann Pumphrey, for we often speak of thee together.
Thy being excused from some painful exposures,^
footnote:[Alluding to Sarah Lynes having before had
to publicly address the market people in many places.]
though possibly it maybe but for a season, that thou mayest recover strength,
seems to us a present privilege; although thou hast found, and doubtless,
in faithful dedication ever wilt find, help sufficient for the day;
yet nature shrinks at such a bitter cup, and we cannot but fear the things we may suffer;
at least until nature is overcome by Grace.

Thou hast perhaps heard from Ann Pumphrey or her husband;
they both look rather care-worn;
yet dear Ann`'s precious gift sometimes breaks through all, in renewed brightness.
But, my dear friend! is not this a day wherein the true ministers
have rather to mourn in silence than to proclaim glad-tidings!
It seems much the case here.
Great changes are likely to take place; that of our dear Mary Beesley, thou wilt believe,
comes close to me.
Very sincere has been her desire to move rightly.
It is proposed to solemnize the marriage in the Fifth month.

[.signed-section-closing]
In assured affection,

[.signed-section-signature]
Mary Capper.

--

Third month 6th. First-day.
We had the company at meeting, of our aged, honourable friend, Mary Ridgway,
and her companion Susanna Appleby.
Mary Ridgway was enabled to bear testimony to the excellence of gospel Truth.

24th. Mary Beesley and I went to Warwick, and visited a young man in the jail,
then returned to Birmingham,
and the poor young man`'s mother supped with us at Richard Cadbury`'s.
Mary Beesley had to address her in a very solemn manner.

25th. We came to Worcester.

28th. Mary Beesley had a letter from Hannah Evans, of Warwick,
informing us that the young man had been sentenced to five months imprisonment,
instead of losing his life, as he expected.

29th. Mary Beesley received a very interesting letter from the prisoner,
expressive of his thankfulness for the unexpected mercy.
The business of this day was gone through under a very precious calm;
my dear friends declared their intention of marriage;
also Edmund Darby and Lucy Burlingham.

Fourth month 10th. In a large assembly, much favoured with solemn quiet,
my much loved friend entered into the engagement of marriage with James Lewis,
under a sense of Divine approbation.
She was afterwards enabled, in a very calm manner, to address the assembly.
Edmund Darby, of Coalbrookdale, and his friend, entered into a similar engagement,
in the same place.
All things were conducted with much order and seriousness.
We had the company of David Sands, John Abbott, and Deborah Darby.

13th. At meeting we had the company of Sarah Lynes, and it was a time of favour,
wherein our minds experienced some preparation for
setting out to attend the yearly meeting.

15th. First-day.
Attended the meeting at Wycombe, the number of Friends but small.
We did not sit among them without feeling,
and we ventured to express our solicitude that we might all become what we ought to be,
and not deceive ourselves or others.
The afternoon meeting was rather remarkable,
and I think may be remembered at a future day.
Came on to Uxbridge, to our kind friends Ann Crowley and sisters.

16th, Reached London in time for the yearly meeting of ministers and elders.
There was mercifully, a renewed sense of awful solemnity;
and some communications dropped like dew upon the tender grass,
to the reviving of the drooping mind.
Our friend Ann Alexander informed us that a concern had long been weightily on her mind,
to pay a religious visit in some parts of America, etc. which concern was united with.

17th. Thomas Shillitoe, in a very humble manner,
opened a concern to make a religious visit to Holland, Germany, etc.
It was agreed to take up the consideration at a future sitting,
and the dear friend appeared to leave the result with much calmness.

26th. The business which has come before the women`'s meeting,
has been solidly attended to, and some very instructive counsel given.
We separated, after having experienced, in silence, that which satisfies the waiting,
dependent soul.

27th. The concern of Thomas Shillitoe was again brought forward,
and he was liberated for his journey on the continent.
Robert Fowler brought in the certificates of our late friend Sarah Stephenson,
and of her companion Mary Jefferies; the latter,
in allusion to the death of our much valued friend during their travels in America,
acknowledged the gracious support which had been granted her, under the trial.
John Hall returned his certificate for visiting America, which he had been enabled to do,
to his own relief.
After a silent pause, we separated in tenderness of spirit.

Sixth month 1st. Came to Isleworth, where we visited Sarah Lynes.

2nd. Reached Worcester.

21st. It was not without some inward struggle that we left Worcester;
having proved our friends, and found them kind,
it seemed trying to go and dwell among strangers, in almost a strange place.

23rd. Reached Trosnant.
The house in tolerable order, though the workmen have not finished.

Seventh month 1st. Mary Lewis has some serious thoughts of attending the
quarterly meeting for Herelbrdshire and Worcestershire at Stourbridge.
The consideration seems important, not only on account of the distance,
but of leaving the family, after being so short a time at home.

3rd. First-day.
Some of the neighbours came in and sat our meeting very seriously;
there was a very quiet covering over us, which seemed to stay the mind.
In the evening the family met together, and a little refreshment of spirit was felt.
After farther deliberation it was concluded that Mary Lewis
and I should go to the quarterly meeting.

9th. We were favoured to return in safety and in peace.

13th. The monthly meeting held here, was attended by nearly all its members; five men,
five women and a lad!

22nd. Our endeared friends Deborah Darby and Rebecca Byrd arrived on a religious visit.

24th. First-day.
The inhabitants were invited to our meeting in the evening.
The Baptist teacher, a kind neighbour, had proposed giving notice to his congregation,
and it was a large gathering.
At first it was favoured with solemnity;
but as the people were unaccustomed to silent waiting,
several withdrew after something had been expressed,
so that the concluding part of the meeting was not so precious as often is the case,
when we meet and separate under the sweet,
uniting influence of a silent sense of the love of God, raising in our breasts,
love to Him and one unto another.
It renewedly appeared to me, as I sat in this gathering,
a very serious thing to be rightly and truly interested for the salvation of souls.

Eighth month 2nd. Sarah Beesley came.
This evening the few ministers and elders met;
no meeting of this kind has been held here of late;
the revival of this practice felt to me very satisfactory.

3rd. The monthly meeting was held here; nine women and six men.
Mary Lewis spread before them a prospect of making a religious visit in Hampshire,
Devonshire and Somersetshire.
My mind was not a little affected with the consideration of accompanying her,
but I felt very fearful, and reluctant to say anything on the subject.

6th. This morning, after much solicitude to do right,
I ventured to address a few lines to my own monthly meeting.

10th. James Lewis is in much pain from an accident, which has wounded his leg;
no skillful surgeon being within reach, we feel perplexed.

14th. We sent for a doctor from Newport; his opinion is relieving,
though the case is likely to be tedious.

20th. I was informed that the few lines which I sent were presented to the monthly meeting,
but not recorded, as the meeting was very small.
This is satisfactory, under our present circumstances, which are trying to us all.
The prospect of leaving home is rendered very uncertain, by James Lewis`'s illness.
Mary Sterry and her companion arrived.

27th. As James Lewis seems gradually to mend,
I think of returning to Birmingham for a time.

Ninth month 2nd. Arrived at Birmingham,
and was very kindly received at Richard Cadbury`'s.

5th. It is pleasant to be kindly received by my friends,
but I feel the privation of accommodation, that I could call my own;
yet I know not that I could adopt any plan of settlement at present;
and my earnest desire is to be so engaged, whether in one place or another,
as to find peace, at the conclusion of time.

14th. Our monthly meeting granted me a certificate for the proposed journey;
also addressed to Friends in Monmouthshire, where I wish to pass some time.
My mind is now more settled in a quiet hope that we may not have done wrong,
however the present prospect may terminate.

16th. Had the gratification of spending a few hours with Sarah Grubb, late Lynes,
now married to John Grubb, of Ireland, where she is going to reside.

Tenth month 3rd. Went to Worcester.

4th. Proceeded to Leominster, where I met James and Mary Lewis, to my satisfaction.

6th. We had a large public meeting at Ludlow.

10th. Visited the families of Friends in Leominster, etc. and came this day to Ross.

1804+++.+++ Third month 5th. I had a protracted confinement, by a dangerous illness,
at the house of our kind friend Thomas Pritchard, of Ross.
I seemed nigh unto death; but was affectionately cared for by Dr. Lewis, Sarah Waring,
Mary Lewis, and my sister Tibbatts.
I was, at length, once more raised up,
and came with my dear friend Mary Lewis to Trosnant,
where I have received every kindness and attention,
and am restored to a good degree of strength,
so that I purpose going to the quarterly meeting at Birmingham.

12th. Arrived at Samuel Lloyd`'s.

14th. At the monthly meeting, a sweet covering spread over my mind,
under which I was led to consider my late suffering and weak state as a merciful dispensation,
wherein I had been tenderly dealt with;
and whereby I was in measure fitted more fully to feel with my fellow creatures.

18th. First-day.
My mind was strengthened; and my lips were opened,
to encourage the youth among us to seek after the knowledge of God,
and his power revealed in the inward parts.

21st. A letter from London brings the long-expected information
of the death of my poor brother-in-law John Tibbatts.

26th. Mary Lewis came here, from Coalbrookdale,
where she had been to visit our valued friend Deborah Darby, who is in affliction,
and in a precarious state of health.

Fourth month 2nd. We came to Worcester.

3rd. To our agreeable surprise, our dear friend Deborah Darby, came here,
with Susanna Appleby; their company was very refreshing.
I have again been unwell, and my voice has much failed me; but, with thankfulness,
I may remark that my mind is kept quiet and contented.
Susanna Appleby gave us an account of the sweet and
peaceful close of our beloved friend Mary Ridgway.

9th. We arrived at Trosnant, and had the satisfaction to find James Lewis well;
I yet remain nearly mute.

10th. My mind is tendered, under a lively sense of my heavenly Father`'s mercies,
of which I largely partake.
Such tender friends! such care and abundant accommodations,
in a time of long-continued weakness, far exceed what I have any right to expect,
or could have contrived for myself.

17th. My dear friend Mary Lewis has been prevailed on to leave me, and to set out,
with her husband, for the half year`'s meeting at Brecon;
they travel in company with Joseph Clark and his wife, and Ann Metford.
These friends have been a few days with us, I believe to mutual satisfaction;
their little visits to me, in my chamber, were much so to me.
My voice has not yet returned.

20th. Mary Lewis came back; and Joseph Cloud and R. Gilkes arrived.

29th. Our friends were at the meeting in the morning; in the afternoon,
in condescension to my weak state.
Friends met in our parlour.
Joseph Cloud was led to speak very clearly upon the one essential baptism which now saves.
Although my powers of utterance are yet sealed up,
my heart was tendered and my spirit contrited;
and I could secretly assent to what was declared
of the power whereby the soul was redeemed from sin.

30th. Our friend Joseph Cloud, having made one of our little family-circle for some time,
it felt like parting from a beloved relation,
on his taking leave this morning for London.

Fifth month 13th. First-day.
I went to meeting, for the first time, since I left Birmingham; my health being improved,
though I can only speak in a whisper.
Dr. Lewis recommends a change of air and electricity.
I consider it a great favour that I can be calm and cheerful; my situation, with my kind,
affectionate friends here, being all that I can wish.

Sixth month 10th. I have almost recovered my voice in the last two days.

Ninth month 25th. Mary Lewis and I went to Warwick.

28th. Came to William Fowler`'s, Alder Mills; took tea with the aged mother,
a very valuable friend, who lives surrounded by her children and grandchildren;
a lovely train of the latter, twenty-six in number.

29th. We breakfasted at Joseph Fowler`'s,
and afterwards all the families were collected together,
and we endeavoured to feel after that holy Power which can direct aright.
Reached Birmingham, and had the satisfaction to meet James Lewis,
whose company was truly acceptable.

Tenth month 2nd. James and Mary Lewis went home;
I believe we mutually felt the separation, after so long a season of uniting intercourse;
but it is no small favour to part under the sweet influence of heart-tendering affection;
in unity of spirit and peace of mind;
no friendship of the world is like this! which I trust will yet bind us together,
though outwardly apart.
My allotment is still uncertain;
the kindness of my friends supplies me with present accommodation.

7th. First-day.
The morning meeting was large,
and I thought favoured with the overshadowing of that invisible
Power which would gather the mind from the lo! heres,
and lo! theres, and stay the thoughts and wandering imaginations,
bringing all into captivity.
I was thankful to feel this, but a fear possessed my mind, in respect of some,
that there was too great an anxiety after worldly possessions.
It is possible to pursue lawful things too eagerly;
so as to be unfitted for higher and more noble attainments.
It is a good thing, and becoming our Christian profession,
to be content with such outward gain as may enable
us to procure things convenient for us,
without the appearance of grandeur or superfluity.

8th. Heard of the death of our valued friend Richard Dearman, of Coalbrookdale;
his son and wife went there last seventh day,
and did not find him more than usually indisposed,
but the next morning he was found a corpse in his bed!

18th. Set out for London.

21st. First-day.
My brother and sister, etc. met me in town; my dear niece Rebecca looks well,
but thoughtful, on the near approach of her marriage.

24th. The marriage company met.
A very solemn feeling was experienced in the meeting,
and our friend Mary Pryor spoke in a sweet, feeling, and encouraging manner.
The day was passed pleasantly at Stoke Newington.

31st. Went to meeting with my mind in a low state,
yet favoured with a degree of resignation,
and inwardly desiring to be more fully what my gracious Creator would have me to be.
My brother John, and Joseph Gurney Bevan dined with us.
Spent some hours with a sick friend, who encouraged and instructed me,
when I was younger in years, and distressed in mind.
I believe it was mutually pleasant to meet,
and recall to mind the mercies of our Heavenly Father toward us.

Eleventh month 8th. Mary Harding, who once lived in this family,
and was ever affectionately kind to me, spent the day with us,
which brought past days into pleasant remembrance.

19th. Had a letter from my dear friend Mary Lewis,
with an affecting account of her husband`'s declining health,
so that I am in a strait what to do.

Twelfth month 16th. First-day,
As I continue to receive distressing intelligence from Trosnant,
I intend to go to my dear friends in their troubles; at least to partake,
if I cannot alleviate.

19th. Accompanied my brother William to visit some of our old acquaintance,
whom it was pleasant to find comfortably settled,
and serious in their lives and conversation.

20th. Snow and cold deter me from undertaking my journey.

1805+++.+++ First month 9th. William Jackson was at the monthly meeting,
and was engaged to set forth, in a heart-tendering manner, the glory,
honour and peace awaiting every faithful soul.

17th. Called at John Eliot`'s, took leave of several of my friends,
and feel rather mournful.
My sister Anne Capper, my brother William, etc. spent the evening with us.

18th. We parted under more than usually tender feelings.

19th. Came to Thomas Pritchard`'s, Ross, and found, to my surprise,
that James and Mary Lewis had arrived at William Dew`'s.

27th. First-day.
At both meetings.
In the evening, the family came together to hear the Scriptures.
These are often times of refreshment and instruction
to those who hunger and thirst after righteousness.

29th. We left our kind friend Thomas Pritchard and family under
feelings of tender and serious solicitude for their welfare.
We rode pleasantly to Usk.
Found all well at Trosnant.

Second month 3rd. First-day.
The meetings were held in silence,
but some of our minds were secretly engaged in desire
that our ways might be ordered of the Lord.
In the evening, when gathered to read the Scriptures, during our silent waiting on God,
a feeling of awful seriousness spread over us, and tendered our spirits,
so that we all wept; and in brokenness,
it was acknowledged that there surely is encouragement to believe,
and under all trials humbly to trust, in the Lord.
It was a time of renewed favour,
and ability was granted to return vocal thanks to the Giver of all our mercies.

16th. We came to Mellingrifiith, Glamorganshire,
on a visit to John Harford and his sister.
The ride is through a pleasant, romantic country, and the house is delightfully situated,
on rising ground, with the river Taff running, with a tine serpentine sweep,
for nearly twenty miles, along the valley below.

17th. First-day.
The gathering was owned by a sense that the Divine presence is not confined to the many.

20th. Mary Lewis went, with J. and E. Harford, about twenty miles,
to seek out one or two poor wanderers, and to endeavour to draw them within the fold,
that they may find rest unto their souls.

22nd. We returned to Trosnant.

Third month 6th. A solemn stillness overspread us, at our small meeting.
In seasons of inward instruction,
the mind often earnestly desires that all the professors of Christianity would embrace
every opportunity of waiting for that wisdom which is pure and comes from above.
They who will be taught of the Lord must wait upon Him.

22nd. Came to Worcester.

24th. First-day.
I was at both meetings.
Sarah Beesley kindly accommodates me with lodging, etc.
I have gratefully to acknowledge the repeated kindness of Friends toward me,
wherever my lot has been cast;
and this I mention as one of the many favours granted by a merciful Lord,
whom it is my heart`'s desire to obey; also to serve his cause upon earth,
with the best ability which I have, though it be but small; yet a little faith,
and faithfulness with it, is a precious thing.

25th. Came to Birmingham, where I found comfortable accommodations,
with my own goods in nice order, prepared for me, at Thomas Shorthouse`'s,
Great Charles street; also kind friends to receive me,
and to provide for me all things needful, upon reasonable terms.
Can I be too grateful, under a sense of the blessings of which I am permitted to partake!
How long I may be stationary I know not; but I only desire to be here, or anywhere,
just so long as is best for me;
and I did not leave Pontypool without mature deliberation.

28th. I walked to see a Friend who has been very ill.
He expressed his intention, if restored to health,
never more to pursue business with his former ardour,
so as to leave no time for more important concerns.
A poor youth dined with us, who seems nearly gone in a decline.
I hope he was sensible of his true condition.^
footnote:[This young man died soon alter; I understood that his last words were,
"`All is lost, but Jesus!`"]

Fourth month 10th. At our monthly meeting at Tamworth, it was the exercise of my mind,
that the lawful cares and concerns of the present life may not be unlawfully pursued.
I dined at John Fowler`'s, Alder Mills, who is just recovering from a paralytic seizure;
a man in the prime of life, with a young family, thus warned to be prepared for eternity!

14th. First-day.
The afternoon meeting more lively than the morning.
"`The life is the light of men,`" and the crown of our religious assemblies.

21st. First-day.
Our morning meeting was very fully attended,
and there was a sense of mercy being continued to us,
with some renewed ability to minister;
and to point out the difference between the dispensations of the Law and the Gospel;
with a heart-felt desire that we might be so wise as to avail ourselves
of the glorious privileges of Grace and Truth,
brought to light by Jesus Christ.

22nd. Deborah Darby and Rebecca Byrd came to Samuel Lloyd`'s. I called on them,
and found them under a weighty concern to visit the families of Friends in this place.

Fifth month 4th. Received the visit of our dear friends,
which was particularly reviving and consolatory to me, having been in a low state.

8th. Felt encouraged, at our monthly meeting,
to request leave to unite with Mary Lewis in some religious service,
on our return from the approaching yearly meeting.
Our dear friends, who have been labouring among us, imparted sweet counsel,
and Deborah Darby was enabled mightily to petition for the different descriptions present.

12th. First-day.
This morning we had the company and labours of Rachel Fowler.
Christ crucified, a suffering, dying Saviour, was preached,
as being incomprehensible to the natural man,
and still a stumbling-block to the uncircumcised in heart,
and foolishness to the seemingly wise reasoner; but unto them that believe,
the power of God unto salvation.
The afternoon meeting was held in a profitable silence.

London, 19th. At Gracechurch street meeting,
I experienced that soul satisfying silence which no language can describe.

20th. Yearly meeting of ministers and elders.
Much impressive counsel was handed to us, 22nd. The women`'s yearly meeting.
A large and settled gathering.

25th. We received an instructive visit from William Jackson, and some other men Friends.
Much was said to recommend retrenchment, which was summed up, in a few words,
by J. G. Bevan, before they left the meeting, as follows:--`"Friends! the way is narrow;
contraction, not expansion, is the watchword!`"
Much concurring advice was afterwards expressed by women Friends;
perhaps there has rarely been a time when more solicitude has been
manifested for the help and preservation of our youth;
that they may believe in Jesus, and bow to his cross,
in the subjection of their own wills, and in a life of self-denial;
contrary to the false liberty which seeks to lay waste all Christian discipline.

26th. First-day.
At Gracechurch street meeting, an impressive exhortation went forth to the rich,
that they trust not in uncertain possessions, neither be high-minded,
but trust in the living God.
At Ratcliffe in the evening, Christ crucified was set forth as the Redeemer of man.

30th. After vocal supplication and a solemn pause,
the concluding minute of the women`'s meeting was read, and we separated.

31st. The meeting of ministers and elders met,
granted a returning certificate to William Jackson; and having concluded its affairs,
separated under a covering of that silence which precludes expression.

Arrived at Birmingham on the 24th of Sixth month.

30th. First-day.
Our meetings both silent; I thought that something was to be felt, excelling words;
my own mind was bowed in sweet, inward stillness; with a precious,
renewed sense that the spirit of the Lord teaches, in the secret of the soul,
more powerfully than any vocal sound, communicated to the outward ear.

Seventh month 1st. A large meeting at the interment of John Hawker.
This day week he told me that he was in no pain; only waiting the Lord`'s time.

3rd. Some of the yearly meeting`'s committee at our monthly meeting.
A very interesting conference took place, which probably will not soon be forgotten.

Eleventh month 12th. Reached Trosnant.

24th. First-day.
The meeting silent;
yet not without a sense that the Father of spirits instructs his children Himself.

26th. James Lewis having long had a desire to take a journey into Brecknock and Radnorshire,
and his wife not being well enough to go, I set out with him.
The roads were in fine order; the sun shone gloriously, and the country looked beautiful,
though disrobed of its summer mantle.

28th. We accomplished our purpose of visiting our long-afflicted friend, Job Thomas; who,
many years ago, had a fall from his horse,
whereby he was so greatly injured that he has since
been in an affectingly crippled state.
The distance from our inn at Llandovery is about six miles; we forded the Toway,
and reached our friend`'s house about ten o`'clock in the morning;
his wife received us with hearty demonstrations of pleasure,
though she can speak but little English.
We were soon introduced to her husband, who is an affecting object;
having no use of any of his limbs, and his body being much wasted by long-continued,
and as he said, often inexpressible pains, endured for nine years.
Truly it is marvellous how the poor frame has been sustained,
and the mind favoured with a daily renewal of faith,
to believe that an Almighty hand is still underneath.

30th. Came to Joan Bowen`'s.

Twelfth month 1st. First-day.
At meeting, that substantial good, which refreshes the waiting mind,
was measurably spread over us, under which my faith was strengthened in the persuasion,
that our gracious heavenly Father is nigh unto all those who diligently seek him,
however they may be placed, even if in lonely, dreary spots,
separated from the cheering society of their fellow-believers.
A little snow fell.

2nd. A bright frosty morning.
The snow had nearly vanished, and the surrounding hills,
mostly covered with smooth green turf, with the sheep grazing on them in large flocks,
formed a sweet scene of simplicity.
We walked out to make a call, when a company of sportsmen and dogs appeared,
eagerly scouting about, to hunt a poor hare from its retreat.
This seemed like a breach of that sweet harmony and
peace into which the creation might be brought,
were the hearts of men thoroughly redeemed.
We had some difficult walking before we reached John Owen`'s house;
he and his wife received us kindly; they have lately joined our Society.

4th. We set out for home, after taking a tender leave of our friends,
who have been affectionately kind to us; and the secret exercise of my mind has been,
that nothing in my conduct should stumble or discourage the simple and honest-hearted,
from earnestly seeking, and following on to know, the perfect way of God`'s salvation.
Our dear friend Joan Bowen seems as a tender mother, in this dreary part of the heritage;
and she has been wonderfully supported in her lonely situation.

6th. We were favoured to reach home well; and a pleasant meeting it was.

8th. First-day.
Our little gathering was, I thought, particularly favoured with solemnity.
The spirit of supplication, as vocally testified through Mary Lewis,
was very sweetly vouchsafed; and it proved a time of renewal of faith and of hope.
The afternoon meeting was held in silence and seriousness.

19th. Received intelligence of the alarming illness of dear Ann Pumphrey.

21st. An affecting letter informs us that she was not likely to live long,
but sweetly enabled to resign all.
Dear Ann, we loved her much, and believe that, through many tribulations,
she has been fitted for an entrance into rest, holding fast her integrity to the end.

23rd. This morning brought the mournful intelligence of dear Ann Pumphrey`'s death,
on the twenty-first.
Mary Lewis set out with me.

24th. We reached Worcester, and were kindly received by our friend Elizabeth Whitehead.
I called at the house of mourning, and found a group of weeping friends,
though there seems abundant cause to rejoice for the deceased,
her triumph over death being glorious, for the sting was taken away.

25th. A solid meeting at the interment.

31st. At the select quarterly meeting; now but a little band.
Last first-day morning, soon after he sat down in meeting, R. Hudson of Stourbridge,
was very awfully summoned away by death.
The concluding events of this year are very affecting.
We had, at this small meeting, the acceptable company of our valued friend Deborah Darby.

1806+++.+++ First month 1st. The quarterly meeting was a solemn time,
and we were afresh counselled to serve the Lord with full purpose of heart.

2nd. We accompanied Deborah Darby to visit the prisoners in the county jail;
it was an affecting season.

6th. We were favoured to reach Trosnant safely.

22nd. I thought I suffered loss in our religious gathering this morning,
from having been engaged in writing until the very time of going to the meeting.

26th. First-day.
Much snow and small meetings.
Our evening reading and silent waiting attended with brokenness of spirit.

Third month 14th. Preparing to leave my friends for a time;
separation always seems a serious thing.
Mary Lewis thinks of accompanying me to Birmingham.

19th. We came to Thomas Pritchard`'s, Ross.

20th. As we were about to leave, we were much affected by hearing, from Imm Trusted,
that his eldest son, a blooming youth of seventeen,
had died after an illness of only two days.
This solemn event caused us to ponder how far it might be best for us to proceed;
which however we concluded to do, after a time of waiting, in solidity and tenderness.

22nd. I was received with much kindness at my agreeable home in Birmingham,
and have abundant cause for gratitude.

25th. Quarterly meeting of ministers and elders; the committee and many strangers present.
A very heart-searching time.

30th First-day.
Thomas Bigg, from Swansea, was at our meetings; his deportment,
and his weighty communications in few words, were encouraging and strengthening to us.

Fourth month 1st. My beloved friend Mary Lewis having left me, I feel low and stripped;
we often suffer when together, and when separated,
an affectionate union seems to bind us in a tender fellowship.

8th. Some weight of inward distress has, at various times, pressed upon my mind,
relating to some individuals,
engaged in a trade which seems to me connected with a source
manifestly inconsistent with the principle of purity.
I have been in some measure,
relieved by one individual opening the subject on his own account.
I have also, after serious deliberation,
sought and found a suitable opportunity of speaking,
in simplicity and in great tenderness,
to a young man just entering upon a branch of business which seems to me very objectionable,
and contrary to our Christian principle.
I was treated with much civility, and heard with attention;
but alas! interest and false reasoning are strong barriers.

London, Fifth month 19th. Yearly meeting of ministers and elders.
Solemnity was mercifully spread over us as a canopy, and vocal prayer was offered.
Our aged friend John Kendall earnestly recommended
the reading of the Scriptures daily in families;
not to satisfy ourselves with perusing them privately, as individuals,
but to collect the servants, etc. that all may partake.
In the evening the precious gift of prayer was again vocally exercised,
and we parted in solemn quiet.

21st. The women`'s yearly meeting opened.
After a solemn pause, prayer was offered, before the business commenced.
Much stillness prevailed.

26th. Some memorials of deceased friends were read,
and some lively testimonies were borne to the efficacy of that Grace which
carries the humble dependent Christian believer safely through life,
and which is his support in death.

27th. Several epistles addressed to distant yearly meetings were read;
many seasonable remarks were made, and after much deliberation and some alterations,
the epistles were ordered to receive date and signature.
It was profitable patiently and attentively to observe the mutual condescension,
in so large a gathering, to the expressed judgment one of another.

30th. Our meeting separated after a very solemn pause.
On seventh-day evening the meeting of ministers and elders held the concluding sitting;
a favoured time, which ended in a stillness that excluded and exceeded all words.

I was afterwards confined, for many weeks,
with great weakness of body and the loss of my voice.

[.offset]
+++[+++During this time of prostration, she wrote as follows,
to her affectionate friend Elizabeth Cadbury.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Stoke Newington, Seventh month, 1806.

[.salutation]
Dear Friend,

Very grateful has been thy kind sympathy.
My long detention in town, with my weak, low state, has been trying;
and the continued loss of my voice sometimes brings my mind into a deep and awful consideration,
how far I have at any time abused or misused the privilege of speech.
My low times, I trust, are not altogether unprofitable,
and at seasons I am favoured with much quietness and resignation;
with a thankful disposition of mind,
tenderly grateful for the unmerited favours received, and particularly,
the kindness manifested toward me, in these times of reduction.
At my brother John`'s I have been nursed with much affection,
and wanted for nothing that liberality could devise.
Dr. Sims attended me daily, and I am now greatly restored and gaining strength.
Yesterday I came here for change of air; the family is, at present, large;
but as there is a spacious house, I can always retire to a quiet room.
Today they are gone to Plashett.
I am a poor cipher among them; but in contemplating my weakness,
I esteem it no small favour that I am excused from much active duty,
in the busy scenes of life;
though I think I have learned to feel tenderly for those who are called into the arduous,
important station of mothers and heads of families.
O! how these must sometimes be sensible of their cares and burdens, their responsibility,
and their insufficiency, without divine aid.
How often must the heart of these be moved within them;
and how frequent their secret supplication at the throne of mercy!
The soul-sustaining Grace of our Heavenly Father cheers and helps such, to take courage,
and humbly to seek for daily supplies of pure wisdom,
that they may order their ways aright.

Accept my affectionate good-will, flowing to you and your tender children.

[.signed-section-signature]
Mary Capper.

--

When I was sufficiently restored to travel, Mary Harding accompanied me to Trosnant,
where I was, as usual, well cared for, and am stronger,
though yet subject to fluctuations.
These I also observe in my dear friends.
James Lewis is in a very debilitated state;
but we have some seasons of sweet consolation, and spiritual refreshment;
and are encouraged not to faint in time of trouble.

[.offset]
+++[+++The two succeeding letters contain some account of the illness and death of Mary Knowles.]

[.embedded-content-document.letter]
--

[.letter-heading]
Jasper Capper to his sister Mary Capper.

[.signed-section-context-open]
Stoke Newington, First month 22nd, 1807.

[.salutation]
My dear sister Mary,

I have been, during a portion of this day,
employed in lending perhaps the last little help, it may ever be in my power to render,
to our dear friend Mary Knowles.
Today she was too ill to be seen by me; but not many weeks since,
I passed a short time with her,
which seemed to revive all that tender affection
that we felt for each other in years past,
and which, it was pleasant to feel all the intervening billows,
of a troubled and troublesome world, had not been able to overwhelm or quench.
Yesterday, my dear wife was with her;
she is sensible of there being but a step between her and death.
The prospect is awful; but she appears tender and resigned,
and has been greatly comforted by a visit from John Eliot and Robert Howard.
Our kind sister Capper is indeed her good neighbour; I might almost say, nurse;
for she has been at hand and ready to afford her personal aid,
as well as her valuable company.

The attention of Mary Knowles`'s son has been very commendable.

[.signed-section-closing]
Thy affectionate brother,

[.signed-section-signature]
Jasper Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Anne Capper to Mary Capper.

[.signed-section-context-open]
Paradise Row, Second month 9th, 1807.

[.salutation]
My dear Sister,

Doubtless thou hast heard of the death of our poor dear Mary Knowles.
She was closely tried, until near her end, by not being able to feel the presence of Him,
whom she sought ability to pray to and to worship;
and upon whom she very frequently called for forgiveness.
O! how lightly she esteemed all her accomplishments; "`what,`" as she said,
"`the world calls accomplishments.`"
She said to my sister and me, "`I repent in dust and ashes!`"
I saw her the day before her departure,
when she appeared very desirous to feel an assurance of acceptance.
Turning toward me, and taking my hand, she said, "`I commend you all to God.
Possess Him, possess Him, if you can, whatever becomes of me!
I hope I shall not be a cast-away forever!
I believe I shall not.`"
She was quiet when I left her.
Early in the morning the nurse heard her say, "`Lord help me to pray;
I cannot of myself;`" these were her last words.
I trust she found forgiveness and everlasting mercy, for Jesus sake.

--

1807+++.+++ Fourth month.
We attended the general meeting at Brecon, which was a time of instruction,
I afterwards accompanied John Harford and his sisters, on a visit to Job Thomas;
we found him in a state of more bodily ease than sometimes,
and remarkably animated and instructive in conversation;
we were some hours very pleasantly with him.
Since this time it has pleased the gracious Disposer of
life and death to release him from an afflicted body.
The remembrance of our visit is sweet.
From his house we went to Swansea,
where I passed a little time very satisfactorily with Thomas and Mary Bigg;
also at Neath.
After a sojourn at Trosnant, I came to Birmingham, in the ninth month.

Tenth month 14th. I informed the monthly meeting that I expect to winter in Monmouthshire.
This I mentioned for my own satisfaction, as I have ever been desirous,
not to act contrary to the judgment of my friends.

[.embedded-content-document.letter]
--

[.letter-heading]
Joseph Gurney Bevan to Mary Capper.

[.signed-section-context-open]
Catherine Hill, near Worcester, Tenth month 21st, 1807.

[.salutation]
Dear Mary,

We finished our visit to this quarterly meeting yesterday evening.
As to myself,
I am leaving this little piece of service nearly as poor as I entered on it,
so that thy letter, which I received this morning, at the breakfast-table,
was truly acceptable and refreshing; and I read it with emotions of tenderness.

We found it advisable to recommend some things which seem to be well received,
and which we hope may tend to mutual strength,
if the active members of the quarterly meeting are
desirous of doing the little they are capable of,
as in the sight of the Lord.
I think not one of the monthly meetings is without some feeling Friends;
and one may indulge a hope that there are here, at Worcester, some who,
if they are preserved humble, may be the means of some revival.

We were twice with William Young, who now keeps up stairs.
He seemed very much pleased to see us, but was low,
and lamenting the absence of what he said he loved above everything else.
He put me in mind of the apostle`'s words, "`Though now, if need be, ye are in heaviness,
through manifold temptations,`" etc.
May be it is a cloud permitted to make the glory to be revealed more glorious.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
J+++.+++ G. Bevan.

--

Tenth month 30th. My sister Tibbatts and I came to Worcester,
and were kindly received at Sarah Beesley`'s. Mary Naftel being here,
she and I made a few calls together, on those who were sick and in trouble.
This was pleasant to me.

Eleventh month 2rd. My sister and I returned to Trosnant,
where we were received with a cordial welcome; our dear friends are in precarious health.

Twelfth month 23rd. R. S. Harford and his son attended our little meeting.
I thought it an unspeakable privilege, which I would not barter for all the world,
to have the opportunity of thus meeting in companies, though small, to retire from all,
even lawful concerns, and with the best ability that we have, to wait upon God,
the eternal, inexhaustible Source of all good.
O! how refreshing, to the drooping mind, to experience from time to time,
that the Rock of our salvation remains unshaken, though the floods,
the winds and the rain may beat upon the poor tabernacle.
I do afresh believe, that if through faithful dedication we grow in spiritual experience,
we shall acknowledge that there is no joy like unto the joy of God`'s salvation.

1808+++.+++ First month 22nd. I set out for Birmingham,
in consequence of the afflicting information of the sudden death of J. P. Dearman;
a friend whom I loved much, for the integrity of his character;
and much affection I bear to those whom he has left.

24th. Arrived just in time to pay the last solemn tribute of regard;
afterwards I went to his late residence, and found his tender,
afflicted wife more calm than I could have expected,
and a sweet serenity seems to overspread the family.

Third month 29th. Arrived at Trosnant; dear James Lewis seems declining.
It is a great favour to meet in peace and affection,
though a storm may occasionally arise to disturb the calm, and try our faith.
All good is from above, and we are sometimes permitted to feel our own weakness,
and manifold imperfections, that no flesh may glory.

Fifth month 16th. I came, in the mail-boat, across the channel to Bristol,
by eleven o`'clock, A. M,
Passed the rest of the day with Joseph Whiting and his sister Esther.

17th. My nephew Samuel Capper conveyed me to West Town, where he has a quiet retreat.

21st. Reached my brother Jasper`'s, in London.

Sixth month 2nd. The women`'s yearly meeting closed.
The attendance has been large and remarkably quiet.
Several testimonies respecting deceased ministers were read; a very striking one,
concerning dear Job Thomas.
His words, expressed a little before he departed, and taken down by his son,
were indeed an animating testimony to the power of Divine Grace;
and extraordinary was the effect which the reading of them
produced upon our large gathering--many were sweetly tendered;
and well I remembered my last visit to him,
when his countenance seemed to bespeak his near approach
to the kingdom of undefiled rest.

5th. First-day.
After the meetings, came to Stoke Newington.
Stayed awhile with my niece Rebecca Bevan, who is now the careful mother of three children.
They are about removing to Tottenham.

8th. Came to Trosnant.
James Lewis is very weak in body, but his mind is clothed with love.
I thought I never felt more satisfaction and comfort in returning here;
all seemed pleasant and peaceful.

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah (Lynes) Grubb.

[.signed-section-context-open]
Trosnant, Eighth month 16th, 1808.

[.salutation]
Dear Friend,

Although it is a very long time since we had any
visible proof that we are remembered of each other,
yet I cannot think former days are forgotten.
We hear thou art the mother of two babes,
who doubtless claim thy maternal care and tenderness;
but nevertheless thy faithful dedication of heart to a gracious Redeemer continues.
Oh! this is precious to those who love the God of their salvation.
It is a great thing that thou art happily united to one
of the Heavenly Father`'s children and servants,
who can feel, unite and labour with thee.
While I write, my heart seems warmed with a salutation of love and encouragement to you,
dear labourers in the harvest of the Lord.
May nothing ever dismay or discomfit you!
I am a very poor, unworthy individual;
but the God of my life has been marvellous in mercy to my soul.
When the enemy has pursued as a lion, the power of the Lord has appeared gloriously,
so that I can speak well of his name; and all that is spiritually alive within me craves,
that the children of men may seek the Lord, and know Him for themselves.
Thou probably knowest that, since Mary Beesley`'s marriage, I have been mostly with her.
Such a quiet retreat, I have considered a favourable asylum,
as my health has lately been precarious.
Indeed I have abundant cause to be humble, and as dear Ann Pumphrey used to say,
to be good, and to be thankful.
Dear Ann! how sweet is the remembrance of her!
With unfeigned affection, I subscribe,

[.signed-section-signature]
M+++.+++ Capper.

--

Eighth month 17th. Martha Routh came to stay a few days, which was very pleasant to us.

22nd. We accompanied our dear friend to Shire Newton,
where she had a meeting with a few serious persons, and then proceeded to Bristol,
with John Grace, As Mary Lewis and I returned home,
we felt the loss of our valuable friend`'s instructive company.

29th. Joseph Clark, Joseph Naish, and his sister, and Priscilla H. Gurney came here,
to sit with Friends and attenders of our meetings, in their families.
Thomas Evans is gone to Myrthir, on account of the illness of Arthur Enoch.
He returned with the afflicting intelligence that Arthur died before he got there,
leaving a young widow and three helpless babes.

Ninth month 1st. This morning,
our dear visiting friends had a very contriting opportunity
of religious retirement with us;
our spirits were humblingly united in renewed faith and hope in the Fountain of mercy.
We were refreshed together,
and encouraged to believe that our heavenly Father is still nigh unto us,
and unto all who sincerely seek Him.
In the evening the corpse of Arthur Enoch was interred.
A number of the neighbours came to the meeting, which was a solemn time.
Those who kindly assisted on this occasion, and some others, supped with us.
Mary Lewis was engaged in solemn supplication for all.

2nd. After experiencing a renewed sense of Divine mercy, extended to us collectively,
we parted from our endeared friends, who pursued their journey,
in order to visit the scattered few in North Wales.
After serious thought on the subject,
I applied to my own monthly meeting to send me a certificate
of removal into the monthly meeting of Monmouth.

Eleventh month 19th. We received the very affecting
account of the death of Arthur Enoch`'s young widow.

23rd. Several neighbours came to the interment;
it was sorrowful to think of the three young children thus left.

1809, Third month 5th. I came to Birmingham, 23rd,
Feeling my mind secretly bound and gently constrained, in love to my friends,
and under an apprehension of religious duty, I joined Sarah Hustler and William Forster,
in visiting the families of the North monthly meeting,
which engagement we were enabled to perform, and separated one from the other,
after experiencing a measure of that sweet fellowship which surpasses all worldly friendship,
or mere natural affection.

Fourth month 29th. Came along to Monmouth; the country was beautiful,
and my mind was mercifully clothed with precious peace, so that the ride was not tedious.
Had the satisfaction once more to join my dear friends at Trosnant.
James Lewis, though considerably enfeebled, testified his gladness on my arrival,
and I am thankful to be peacefully at liberty to unite in the cares of this family.

1810+++.+++ Second month 1st. Our long-afflicted, patiently suffering,
and endeared friend James Lewis, calmly breathed his last, having,
a short time previously, exclaimed, "`Be Thou with me, O! Lord.`"
On being asked if he were comfortable, he answered, "`Yes; leave me to the Lord!`"
These were the last words he uttered.
His truly attentive, watchful, tender wife was enabled to assist to the last;
finally closing the eyes of this nearest and dearest connection in life.

8th. The remains were interred, after a solemn meeting.
James Lewis was a man of unusual simplicity, and without guile;
humble and of a retired spirit; yet hospitable and affectionate toward his friends;
a lover of those who followed after righteousness.
Many a time, during his long decline, he said, that he loved every body;
especially those who loved the Lord Jesus, out of a pure heart.

18th. This day received the affecting intelligence of the death
of our very dear and justly valued friend Deborah Darby.
A dedicated servant, and a messenger of glad tidings to many,
she has been in her comparatively short day.
She was an example of diligence in her apprehended duties;
and was peculiarly fitted by nature and by Grace, for the work whereunto,
there is abundant cause to believe, she was called.
Surely it is allowable to mourn the privation that we sustain; though, no doubt,
the change to our precious friend is glorious.

Third month 28th. Mary Lewis and I attended the quarterly meeting, at Birmingham,
had the satisfaction of meeting several of our dear friends, and were refreshed together.
During our stay at Birmingham, we were affected by hearing of the death of Edmund Darby,
the only surviving child of our dear friend Deborah Darby.
He was about twenty-nine years old, and has left a lovely family;
only out-living his valuable mother about five weeks.

He was married at the same time and place as Mary Lewis,
and only survived her husband seven weeks, though so young a man.

Fourth month 19th. We returned to our habitation at Trosnant; it is a quiet retreat,
but we miss the dear head of the family; for although weak in body,
he was lively in spirit, so that it was very sweet to be with him.

Fifth month 5th. Mary Lewis, Thomas Evans, and I crossed the channel,
and were kindly received at Bristol, at my nephew James Henry Capper`'s.

Arrived in London on the 18th.

21st, Yearly meeting of ministers and elders.
Though many dear and useful friends are removed by death since last year,
and their loss is much felt, yet there is encouragement in the assurance,
that the Fountain of help is still open,
and that the Head of the Church will not forsake his people.

23rd. Hannah Fisher was appointed clerk to the women`'s yearly meeting.
The attendance was large, particularly of young persons, many of whom appeared serious;
and it was very pleasant to observe their settled attention to the business,
which is conducted in much condescension and harmony,
with a view to promote the good of the body.
Benjamin White, from America, came into our meeting, accompanied by Joseph Gurney Bevan.
He exhorted us to be humble; and with much tenderness,
he particularly entreated mothers to be more careful to
adorn the minds of their young children with meekness,
humility and virtue, than to put upon them any outward adorning.

31st. After many precious seasons together, and much instructive counsel being given,
our yearly meeting concluded.

Sixth month 2nd. The last sitting of the meeting of ministers and elders was held,
and we were favoured to separate under that solemn covering of silence,
which subdues imaginations, and brings the thoughts into captivity;
a marvellous power prevailing over the mind, which no words can fully set forth;
it is more precious and more refreshing to the immortal spirit than words can be.

Seventh month 7th. Returned to Trosnant.

17th, This evening one who had lived in this family from a little lad until this day,
when he is a stout young man of twenty-one, left us.
Tears were shed on all sides.
It is no marvel that such separations should be felt,
the young man having lived long under the same roof
and participated in many times of favour,
when heavenly goodness has tendered our hearts, daring our family retirements,
and in which the late dear master of the family was frequently so broken in spirit,
humbled and contrited, that the same feeling seemed to spread over all, Thomas was,
we have reason to believe, a faithful servant; diligent, neat, quick in his business;
affectionate to his master through his long illness; ingenious and cheerfully obliging;
so that he was very valuable in the family.
This little testimony seems due to him, from one who sincerely desires his welfare,
and that he may be kept by the Good Shepherd, and find mercy and peace.

21st. Again the trial of separation!
James Lewis`'s nephew, who long partook, with kindness and watchful attention,
in the necessary fatigue and care of his dear uncle, has now left the house,
so that we are reduced to a small number.
Serious thoughts have arisen as to the propriety of quitting this lonesome spot;
but we shall not do it hastily.

Ninth month.
I still find, that of myself, I can do no good thing, but am weak and frail;
the Lord`'s lengthened out mercy is my only hope.
