== Chapter VIII.

[.chapter-synopsis]
* Removal from Leominster and re-settlement at Birmingham
* Death of her brothers William and Jasper
* Religious services, etc. to the end of the year 1820

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Capper.

[.signed-section-context-open]
Leominster, First month 23rd, 1815.

When I can look into my own heart,
and have a sense of its natural propensities from my youth up,
how marvellous appears the mercy extended to me; so that, my endeared niece,
the secret acknowledgment of my soul is,
God is love! and willeth not that any should perish.

O! that the whole rational creation, the world over, would receive, own,
and strive to obey, his Divine gift of Grace in the heart; then might we,
as one large family, together praise the Lord for his goodness,
and his mercy which endureth forever.
I have long been a debtor to my much loved niece R. Bevan, for a nice,
affectionate letter.
I have not been unmindful of the privation and grief
that has been recently brought upon you,
by the awful change which has taken place in the circle of your choicest friends,
your justly valued, much loved Christian adviser having filled his measure;
his pilgrimage ended, he has left an example to those who loved him,
to follow him as he followed Christ.

[.signed-section-signature]
Mary Capper.

--

[.offset]
+++[+++She this year again attended the yearly meeting,
concerning which she made the following memoranda:]

London, Fifth month 22nd. The select yearly meeting met.
Many are the vacant seats of those who have been eminently useful in their day;
but with humble hope, and confidence in redeeming, sanctifying Power,
we look towards a rising generation; many of whom appear to have given up their names,
and to be advancing in dedication and usefulness.

William Grover and George Stacey were at the table.
Some tender cautions were given, with respect to those benevolent associations,
in which members of our Society are now so conspicuous.
There was a fear in some minds, even while they rejoiced in the spreading of knowledge,
the distribution of the Scriptures and the instruction of the poor,
lest a danger might secretly lurk in the pleasure received from eloquent speeches,
and flowing language, at the public meetings of these associations;
especially lest our dear friends should thereby lose their relish for simplicity,
and be gradually drawn from the love of silent waiting in our meetings for worship;
that waiting wherein they may know Jesus to be in the midst,
teaching as man never taught; and by whom we have access to the Father.
There was much worthy of observation in these remarks.

24th, The women`'s yearly meeting began.

25th. A testimony concerning our valuable friend John Kendall, deceased, was read.
He was favoured with heavenly wisdom, in his early years,
and dedicated a large portion of a long life, and much of his substance,
to the promotion of righteousness.
In his love to his fellow-men, and desire to draw them off from misspending their time,
he occasionally entered public-houses, and twice the theatre;
in order to persuade those present, who were his neighbours,
to consider the importance of life, and of the soul`'s salvation.
In the afternoon, a testimony respecting dear Mary Lewis was read.

26th. At Devonshire-house meeting,
some powerful testimonies were borne to the Divine mission of the Saviour upon earth,
in his outward appearance, and to the operation of his Spirit,
revealed in the hearts of the children of men.
Many seemed to be seriously affected.

28th. First-day.
Martha Routh was enabled to preach the glad tidings of the gospel;
and Jesus was set forth as a Saviour and Redeemer.

31st. Sarah Hustler gave in a written account of the money entrusted to her last year,
when she accompanied Elizabeth Coggeshall into Germany and the South of France,
She also expressed that she had been thankful to
be the medium through which the liberality of Friends,
in this land, had contributed to comfort many; and that,
while employed in relieving their distresses, she had often thought of her sisters,
in her native land, with desires that they might rightly appreciate their privileges,
and be willing to make sacrifices to supply their suffering fellow creatures.

E+++.+++ Coggeshall tenderly touched upon the superfluity observable in clothing,
etc. and we were called upon to show our gratitude to the Author of all our blessings.

Sixth month 1st. Instructive counsel was given,
relative to the care which should be exercised over servants of every denomination;
that nothing may exist in our families that can in any way harm them;
and that as much as in us lies, we may encourage them in that which is good.
The clerk, in a very feeling manner, read the concluding minute;
and after a silent pause, we separated.

[.small-break]
'''

+++[+++The mind of Mary Capper appears to have been frequently
much exercised on behalf of that class of persons,
who are employed as haymakers, etc. in the neighbourhood of London;
and at this period she expressed her interest for them in the following address,
which she had printed and circulated amongst them.]

[.embedded-content-document.letter]
--

[.letter-heading]
An affectionate Address to those who are employed in harvest work, 1815.

How rich, how beautiful are the fields! how promising are the crops,
to supply the wants of man and of cattle!
Shall we behold them without one grateful acknowledgment
to that bountiful Giver from whom all our mercies flow?
The earth is the Lord`'s, and the fulness thereof; and you, my fellow pilgrims,
who labour and toil in gathering the produce of the fields, and in heaping up stores,
you are partakers of the fruits of the earth,
you eat of the bread that strengthens the heart of man;
and that it may continue to be given to you in abundance, is the desire of thousands,
who are themselves supplied with it.
Words can but faintly set forth, how affectionately, how earnestly,
your Christian friends wish, that the blessing of the Lord may be with you,
in the fields, when your hands are diligently employed in hard labour.
They earnestly desire that when the toil of the day is over, peace,
the inward peace of your minds, may make your rest sweet, and refresh your weary bodies,
fitting you for the task of the succeeding day.
Let affectionate solicitude, for your soul`'s sake,
prevail upon you to avoid all excess in drinking;
it is an ungrateful waste of the Creator`'s bounty.
Drunkenness unfits both the mind and the body for all that is innocent and good,
it is a shameful inlet to bad and idle words, to profane and filthy communications,
and to foolish jestings, which things are dangerous in their consequences,
and often lead into serious harms,
that might not be even thought of in the beginning of familiarities.

Permit a stranger to put you in mind, that without serious thoughtfulness and prayer,
neither the poor nor the rich, the labourer nor the master, is safe.
We cannot in our own strength resist temptation.
Oh! it grieves your friends, who are interested for you,
who observe you when you are not aware, it grieves them,
when the old men amongst you commit folly,
and the young unhappily follow the sad example.

Why will ye not accept a Saviour`'s redeeming love, who suffered, was crucified and died,
to save us from our sins?
Receive this exhortation in seriousness,
and let it make some impression for good on your hearts,
as it is offered to you by a fellow traveller who
has your present and eternal happiness in view.

And you, dear young children of the poor,
who attend your parents and others in the labours of the fields;
remember that your Heavenly Father careth for you; that he pitieth you,
even whilst you are ignorant of Him.
Think upon his goodness and mercy; He would keep you from sin, from all wicked words,
from lies and deceit; take heed, dear children,
that you learn not these things from those who are older than you,
and ought to teach you better things.
Love one another, be gentle, kind and good; then nothing can harm you.

--

[.offset]
+++[+++Mary Capper again attended the yearly meeting in 1816; her diary thus continues.]

Fifth month 20th. The yearly meeting of ministers and elders met;
and after a time of reverent waiting, very low as at the footstool of mercy,
vocal prayer was offered.
Jonathan Hutchinson joined Wm. Grover, etc. at the table.
Mary Naftel, in a weighty manner, informed us of a concern to visit Friends in America.
After much silent deliberation,
a belief was expressed that the meeting might safely sanction the movement,
and the language of encouragement was held forth.

21st. Elizabeth Robson opened to the meeting, in much simplicity,
her apprehension that it was required of her to visit
those under our name in France and Germany.
Much tender feeling was expressed, and the decision was left to a future sitting.

22nd. Soon after the women`'s yearly meeting gathered,
a very precious stillness prevailed, and seemed to spread over us through this sitting;
a gentle hint was given to be watchful when out of meeting,
so that the beneficial impressions received might be retained.

23rd. Four testimonies were read, respecting deceased ministers,
who had been favoured to finish their earthly pilgrimage in peace,
and with a lively hope of acceptance, through Christ the Saviour,
who redeemeth the believers in Him.

24th. It was remarked, that while many are running to and fro in the earth,
in order that knowledge may be increased, the retired humble Christian believer,
who finds no power to go forth, and can only rejoice with trembling, may,
by secret and sincere prayer,
be instrumental in the promotion of truth and righteousness.

28th. Some very interesting accounts were sent in from our men Friends,
relative to the civilization and improvement of the Indians in North America.
Friends in that land still extend much care towards them; schools are established,
and Friends reside among them; many of the women and girls have learned to spin, etc.
The report mentions that an ancient chief expressed the satisfaction which they felt,
in observing the stability of the Friends who had settled among them;
that even when the great guns shook the earth they did not seem disturbed;
from this they concluded that the Good Spirit was with them.

30th. Counsel was expressed, tending to encourage and comfort the lowly-minded,
and to animate all to watch unto prayer,
that spiritual mindedness might increase among us,
and that our worship might really be in spirit and in truth;
even though without verbal ministry.
We received an acceptable visit from Richard Phillips, accompanied by William Grover.
In the evening we concluded our business, which has been transacted in much harmony,
and under a sense of that gracious, condescending mercy,
which the Christian believer prizes above every earthly enjoyment.

Sixth month 1st. The adjourned meeting of ministers and elders opened
with a fresh manifestation of that Power which draws into solemn stillness,
and prepares the mind for secret or vocal prayer;
the latter was offered on the bended knee.
The concern of Elizabeth Robson was again seriously considered,
and it appeared right to liberate her for the service.

26th. At the quarterly meeting for London and Middlesex,
Elizabeth Fry of Plashett cottage, was liberated to accompany Elizabeth Robson.

Ninth month 24th. Attended the monthly meeting at Hereford,
and under a persuasion that it was a right movement,
requested a certificate of removal to the North monthly meeting of Warwickshire.

Tenth month 7th. Requested permission to have a religious
meeting with some of the inhabitants of Leominster,
before leaving that place;
and informed Friends that I felt inclined to pay
a visit to some families not professing with us,
as way might open for it.
The monthly meeting concurred therein, and appointed John Southall to accompany me,
when desirable.

8th. Made one call,
where we were favoured with a precious sense of the tender mercy of the Lord.

10th. Sarah Waring accompanied me to the house of a very respectable widow,
where we took tea; an opportunity was afterwards very willingly given,
to have the company of a faithful servant,
who had been with her mistress during many years of affliction, and who, being sickly,
had received great kindness in return.
After relieving my mind, we parted in mutual good will.
I afterwards called on several more of my neighbours, and was always kindly received.
As I found ability given me, in tenderness and love,
I expressed my solicitude for the welfare of the immortal soul,
which will have an existence when we shall no more meet, in these poor, frail,
mortal bodies.
The neighbours were invited to attend one of our religious meetings,
and the house was pretty well filled.
Stillness prevailed, and some of us were enabled to wait on the God of all grace.
Something was expressed in love to souls.
I had particular satisfaction, and felt great sweetness,
in calling upon two Moravian families.
I thought the spirituality of faith in Christ, the Saviour and Redeemer of men,
was to be found among them.

I left Leominster in a low frame of spirit,
though I did not feel condemnation for anything that I had done, or willfully left undone.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Five Ways, Islington, 9th of Eighth month, 1816.

[.salutation]
Dear J.,

I have lived many years, and have seen many changes, and have known privations,
by a final separation as to sweet intercourse in this world from those most dear unto me;
yet this I can testify without boasting, that heavenly kindness has sweetened every cup.
I have of a truth nothing in which I can boast, for I am weak and imperfect as others.
In the days of my youth I was volatile, prone to folly,
and more tempted by evil than some others seem to be,
but the unsearchable riches of our Heavenly Father`'s
mercies have kept me from destruction unto this day;
and with the ability he gives from time to time, I can speak well of his name;
for though he is pleased to bring our spirits low,
and to humble us that we may know ourselves, and what is in our hearts,
again he shows himself gloriously, that the poor and contrite ones may trust in him.

Dear +++_______+++ thou knows these things in the morning of thy days;
and an unspeakable favour it will be if thou keeps close unto that which will keep thee,
Christ within, the power and safeguard of the Christian traveller.
I need not warn thee to beware of the lo here and the lo there,
and that thou go not after them.
Thou hast kind, affectionate counsellors around thee, who, I doubt not,
will aid thee to follow that which is right,
and strengthen the witness for good in thy heart.

[.signed-section-closing]
I subscribe thy sincere affectionate friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, 1st of First month, 1817.

To see thee again amongst us, kept by the power of heavenly goodness,
from the evil of the world, plain, humble, and without guile; oh +++_______+++,
language is short in describing what kind of cordial satisfaction
this gives to those,`' who have experienced the fallacy--the
uncertainty of this world`'s most fair and flattering promises.
Believe it,
there is no joy comparable unto that which arises
from a well-grounded hope of the soul`'s salvation;
no torrent of surrounding temptation; no gloss of false liberty; no subtlety of argument;
no custom of nations--will, I affectionately hope,
ever draw thee to turn aside from the religious principles of thy youth;
but that growing years may confirm and establish
thy judgment upon the foundation of Christ crucified,
is, I believe, the prayer of thy best friends.

I crave the stability, the encouragement of all who profess and have tasted,
and spiritually seen that the Lord is good; that nothing may dismay or harm those,
is the present fervent desire of thy affectionate friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Capper.

[.signed-section-context-open]
Birmingham, Second month 11th, 1817.

[.salutation]
My dear Niece,

I was affected by the account of thy dear father`'s sufferings,
and being something of an invalid myself,
I thought very affectionately of my much-loved brother, as I lay awake on my bed.
I remember the love of our youth; mutual endearment is even more precious now,
in my old age, than in the morning of my day.
Tell my dear brother that an increased sense of fellowship binds me to him.

I call to mind thy dear father`'s first communication
respecting his sense of the sinfulness of sin;
and to the best of my recollection, it was the beginning of serious thoughtfulness,
upon the nature of sin, in my mind; though my foolish heart made light of it,
just at that time.

But little as a beloved brother may think that he had to do with it, so it is,
that I connect the incident, the love for him,
and an awful reverence for the watchful Shepherd of souls;
as then and now working together for good; even to the end designed,
of mercifully redeeming, fitting and preparing for a mansion of purity and blessedness.

[.signed-section-closing]
With a large portion of love to you all, thy aunt,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Birmingham, Second month 27th, 1817.

[.salutation]
Dear +++_______+++,

I am now favoured with apartments where I retire in sweet quietness,
and at seasons enjoy a peace of mind that no power on earth can give;
and all the gratifications of worldly pleasures are but as dross, in comparison with it;
not for anything that I have done,
but in adorable mercy this precious foretaste of blessedness is graciously given,
to soften the infirmities of increasing years, the decays of youthful vigour,
and above all, to increase faith, to strengthen hope,
to clothe the mind with genuine "`humility, and fix our affections upon things above,
where all is joy and purity.
That, dear +++_______+++, in life and in death what can there be so essentially important,
as the true knowledge of our faithful Creator,
and of Jesus Christ whom he has sent to reveal the way of eternal salvation?
How can rational beings with immortal souls live carelessly, unconcerned, as it were,
upon a subject so important?
Cherish the living spark, the good seed in thy heart,
and thou wilt find growing fruit to the praise of the good Husbandman,
and thy own unspeakable peace;
an inward calm and gentle joy with which no stranger intermeddleth.
The stranger to this secret operative power in the soul,
entereth not into its nature and origin, neither can he; but the soul that has tasted,
though but imperfectly, of this revealed goodness, is at times constrained, as it were,
to say and to crave, Oh that men would seek the Lord, that they might know him,
and praise him, for his mercy and for his goodness.

Though, dear +++_______+++, we are assured that they who seek shall find,
and that treasures of Divine wisdom and knowledge shall be opened unto`' them,
yet there is many a dark and gloomy day on this side the promised land.
It must needs be that we feel the separation which sin has made between us and our God,
that we remain children of nature, liable,
prone to corruption and disobedience to God`'s holy law, until we be quickened,
made alive unto the necessity and goodness of our heavenly Father,
by the revelation of Christ within the hope of glory,
and the name or power given by which we must be redeemed or saved.
Keep close, dear +++_______+++, to the religion of thy parents; let their God be thy God,
and he will open thy understanding, and make plain,
things that may at times seem too hard for thee.
Humility and contrition of spirit seem the only safe dwelling place
whilst we are clothed with these poor corruptible bodies;
and we shall find that there is great need of patience
unto the end of our Christian pilgrimage.

It is very pleasant to hear of dear Mary Naftel--that
she is favoured to get along so comfortably,
and under the care of kind friends who can feel for and with her.
If thou hast opportunity, please to express my tender affection; and tell her,
if thou thinks well, that I begin to feel settled, as it were, amongst my own people;
and as far as my capacity seems to go, I feel thankful for the present,
and desirous to leave the future unfoldings,
to the great Hand that has graciously and in marvellous mercy, led me hitherto.

[.signed-section-closing]
Very affectionately, thy friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, Fourth month 18th, 1817.

[.salutation]
Dear M. S.,

Doubtless thou hast had accounts of my weak state of health;
I am indeed again reduced very low, but I see it is my place to be quiet and patient,
which is the petition of my spirit more often than the day.
Subjection of the will,
and the reduction of all that is contrary to the righteous law of Christ,
however secret it may be, is the work and end of pure religion in the soul;
whatever our name, situation or rank in life.
Sickness and retirement do not exclude trials of faith; nor do I believe that an active,
busy scene, in things lawful, precludes the precious influence of that divine,
heavenly Power, which, if believed and obeyed, leads out of error,
and opens the way of truth.

My voice remains suspended, so that it is a fatigue to make myself understood.
I have the great privilege of a quiet, pleasant, little room, where I am much alone.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, Fourth month 26th, 1817.

[.salutation]
Dear W. F.,

Though I am now in as poor and weak a state as thou hast heretofore seen me in;
yet being favoured to feel some liveliness of spirit,
and interest in those things which I am persuaded make for peace,
I earnestly desire the increase of spirituality among all professing Christians;
that we may manifest of a truth, that we believe in God,
and in Jesus Christ whom He hath sent.
To experience the change from nature unto grace, is more to be desired than kingdoms;
and is worth enduring conflicts and distresses, to know realised in ourselves;
and if so might be, to prepare us, to strengthen,
help and encourage other burdened souls.

I doubt not thy continued dedication is attended with many trials and sacrifices,
but also with many gracious helps, many sweet mercies;
and thou knowest these cannot be bought too dear; in fact,
what has the most favoured servant to give, which has not first been received?
The best enjoyment of every good gift is a grateful sense of the bounty of the Giver.

--

[.offset]
+++[+++Mary Capper did not attend the yearly meeting,
but her sister Anne Capper sent her the following particulars.]

[.embedded-content-document.letter]
--

Fifth month 11th. First-day.
We had a precious company to dine; our dear brother and sister John Capper called,
and silence ensued.
Mary Proud and Mary Alexander spoke sweetly,
and I think our dear brother and sister were comforted.
My brother is seventy.

19th. Today my Jasper is sixty-six; upon looking back,
I find both the brothers increasingly desirous of yielding themselves to best guidance,
and preciously drawn from visible things.
The opening of the yearly meeting of ministers and
elders today was a time of refreshment to many.
Elizabeth Robson gave an account of the labours of herself and companions;
also of their great trials in having to leave William Allen in his affliction,
and in the death of his wife.

20th. William Byrd first broke silence, in testimony; then his wife in prayer.
Then Hannah Field, from America, with much simplicity,
informed us of her prospect of visiting those under our name in France;
and Elizabeth Barker hers, to be the companion of Hannah Field.
Much sympathy and unity were expressed.

23rd. At the meeting for worship we were comforted together; bread was broken, blessed,
and handed to them that were brought low.
The dear, simple-hearted American Friends dined with us;
eight of our children were with us, and many others.
After dinner, in a religious opportunity, Hannah Field and E. Barker,
had to exhort and encourage us.
E+++.+++ Barker also appeared in supplication.

25th. First-day.
Thy dear brother, Ann Crowley, and I,
were privileged with the company of the dear American Friends,
to go with us to attend the interment of my aged friend, Benjamin Angell, of Brentford.
I think he was eighty-three.
The instructive society of our friends was very precious to us.
At the funeral,
Hannah Field encouraged all present to come from shadows to the living substance.
E+++.+++ Barker and Ann Crowley were engaged in reverent supplication,
and several friends in testimony.

31st. The select yearly meeting concluded under a very solemn covering.
My dear husband is very poorly,
but we have had to commemorate the Lord`'s tender dealings with us; he is so favoured,
in this time of sickness, that it is with reverent,
humble gratitude I perceive the increase of his faith and love.
Surely goodness and mercy have followed him all his
days! of this I also have largely partaken.

--

+++[+++Rebecca Bevan also sent an account of the daily transactions of the women`'s meeting,
to which she subjoined the following; her last address to her aunt.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Tottenham, 1817.

I have endeavoured, my dear aunt,
to keep a daily account of the proceedings of our yearly meeting,
but it is so inferior to what I could have wished, that I believe it must go,
without any other recommendation than the affection which induced me to begin it,
and I hope thou wilt accept it as a proof of my love.
I was gratified by thy kind letter,
sent by one who appears to have grown so much in all that is good,
as almost to discourage some of her companions in the Christian race;
but while I have been writing this, the words,
"`In my Father`'s house are many mansions,`" have afforded me a ray of encouragement,
and renewed my hope.

I think, if I could slip away from my engagements,
I could enjoy a few quiet days with thee; but at present, that is out of the question;
my dear boys are just coming home, for a six week`'s vacation,
and our two youngest have the hooping cough.
I believe the rest have all had it, and it is not very violent.
My father is but poorly.

[.signed-section-closing]
Thy very affectionate niece,

[.signed-section-signature]
Rebecca Bevan.

--

+++[+++Rebecca Bevan died the 9th of the eleventh month of this year,
in the faith and hope of a humble Christian,
having endured a very suffering illness with much patience.^
footnote:[See Piety Promoted, Part XI. page 189.]]

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Sixth month 7th, 1817.

[.salutation]
My dear exercised Friends,

I seem as though I could not well forbear to communicate
a little of my feelings toward you,
as they arise in freshness,
though it may be but in a very small measure that I can enter into your tribulated state.
A petition something like this has arisen on your behalf; "`O! Father,
help with holy help, thy humble, dedicated servants;
sustain them continually through heights and depths.
Their conflicts are fully known to thee, though it may be, not unto any fellow mortal.
O! when the poor, weak, human frame is overwhelmed, and seems ready to sink,
and the heart to fail, may it please thee,
thou source of true consolation! to be the strength
of the heart! to pour in Gilead`'s balm,
and prove thyself their Holy Physician.`"
Weak and solitary as I am, yet I cannot count myself dead,
so long as I am capable of feeling an interest in
the labours of those who are actively engaged.
May the Lord of the harvest be in the midst, and bless his servants,
and crown his own works!
I hope, if it be best, that a little respite will be given you,
to recruit your health and spirits.
Depression is not unusual in bodily weakness;
but doubtless there is a suffering with the Church, spiritually, that goes yet deeper;
nevertheless, my precious friends, look forward--the end will crown all;
because you do know in whom ye have believed, and because your Redeemer liveth,
ye shall live also,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. C.

[.signed-section-context-open]
Alder House, Tenth month 10th, 1817.

[.salutation]
My dear Friend,

Thou canst better think than I tell, the feelings of my heart,
respecting the alarming state and inexpressible sufferings of my dear,
much loved niece Rebecca Bevan.
Greatly will she be missed in her family,
and in that station where her services and abilities were called into action.
The intelligence received gives no reasonable hope of recovery.

Dear creature! while I secretly participate in the present affliction,
and mourn the privation that will be felt by near and dear connections, the cheering,
precious consolation of my soul is,
that the all-wise Disposer of events sees fit to gather
her devoted spirit from the trials and pains of the body,
at an early period of life.
The Divine will, done in us and through us, is all in all.
My views extend to that blessed time,
when the kingdoms of this world shall become the
kingdoms of our heavenly Father and of his Christ.
It seems that tribulation, pain and suffering,
is the medium whereby grace triumphs over nature; sustaining faith,
the gift of mercy and goodness, will, I humbly hope, uphold us through all.
I seem strongly inclined to return home;
retirement will better Suit the sympathetic sadness that clothes my spirit,
though the friends here are tenderly kind.
Still it is not my own little apartment, nor so much in the way of seeing you,
as a part of our family connection,
and hearing almost every day or two some account of my dear afflicted relatives.

[.signed-section-closing]
My love to all,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Birmingham, Eleventh month 11th, 1817.

[.salutation]
Dear J.,

Whether I may write to thee, or from concurring circumstances,
which sometimes disqualify or impede communications, I may remain silent,
I think that in sincerity and real affection thou mayest rest satisfied
there is a secret precious bond that strongly unites us in one view,
one permanent object, of important interest; and though for a season we have our trials,
thou dear +++_______+++, in the morning and prime of thy youth,
and in the evening and decline of my natural life, this is my consoling, unshaken belief,
that we shall reap the matured fruits of patient continuance in well-doing,
if we secede not from that gracious Power which worketh (as I assuredly believe,) in us,
to will and do that which brings solid peace to the soul.

Dear +++_______+++, suffer no inward or outward suggestions,
no rising tumult of thoughts to discourage thee from pressing after that which
is manifested in the secret of thy soul to be light and pure life unto thee.
We must not look to others for example, though it may be, at times,
we may be animated and helped to hold on in integrity
by the faithful followers of a crucified Saviour.
Our safety is, the reproofs of instruction by the still small voice within.
Happy,
yea happy for those who humbly bend to the power of the religion
of Jesus whilst they are in the tender years of youth.
Nothing can be more true than that it keeps them
from a thousand snares and makes their virtues strong.
Seeing thyself weak, poor and helpless, subject to much tossing and trouble of mind,
from doubts or from fears of falling through divers temptations,
does in no wise manifest thy being forsaken,
but rather that thou art under the direction of Him who teacheth as no man can teach;
that he is leading thee and proving thee to show thee what is in thy heart,
to humble thee and draw thee out of every confidence,
but in the revealed Word or power of Jesus in thy soul.
I believe it is safe to keep these secret manifestations within the silent recesses,
entering, as it were, the closet, having the door shut,
that the intercourse may be in secret with Him who knoweth and alone can
answer the prayer or inmost breathing of the awakened soul.
If my small experience has taught me anything in this best of schools,
the Divine Teacher instructs in stillness, and leads gently along;
the docile learner scarcely perceives the progressive steps of attainment.
The fear of offending willfully in thought, word, or deed,
predominates as a check to evil, and as a spur to obedience.
Hold fast the knowledge and the power thou hast received;
and when thou art sensible of coming very short of the standard of Truth, in lowliness,
in quietness and patience, wait the return of increased faith and power.
There is forgiveness and mercy with Him who knoweth us altogether.

Whenever opportunity offers, please express to our valued dear friend Mary Naftel,
that her message is very cordial and acceptable to me,
and she has a return of my love and tender desires,
that when her arduous labours are finished in your land, she may,
under divine protection, return in peace into the bosom of her own family.
My health has been benefited by a visit to my native town of Rugeley,
and inhaling the pure air of Staffordshire, sweet and clear.

I have written thee a long letter,
and hope it will convey an outward sign of the sincere and dear love I bear to thee,
as thy friend and fellow traveller to a better world than this.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to her brother Jasper Capper.

[.signed-section-context-open]
Birmingham, Second month 7th, 1818.

[.salutation]
My dear Brother,

Often in my solitude I think of thee; my heart seems increasingly bound to thee,
as we descend the slope of time.
In some of my best moments, thou seemest present with me; and in my low strippings,
I think of thee.
When Satan whispers ugly things, and would fright my soul from prayer,
sometimes on my knees, "`with teary face,`" like the poor Indian, bending low,
I seek relief; and though many a time no form of words presents,
there seems a spiritual intercession, and a calm succeeds; not always immediately.
Faith and patience are kept alive by exercise.
Then, again, I think of thee, and my soul takes courage.

May we not be thankful that we can, in the secret of our hearts, believe,
"`The precious blood was shed, to cleanse this heart of mine!`"
Yes, thine and mine! from all sin! that being justified, we may be glorified;
clothed in the fine linen, white and clean, as no fuller on earth can make it!
No skilful alchemist can so separate the precious from the vile!
My beloved brother, may we be more, and yet more,
favoured with joy and peace in believing, is the prayer of thy sister,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Cadbury

[.signed-section-context-open]
Worcester, Fourth month 27th, 1818.

[.salutation]
My very dear Friends,

I don`'t know how I can sufficiently prize the privilege of having your kind regard,
and the love of your dear children, which is as a cordial in my advancing days.
I think I shall return on sixth-day;
I am aware that I shall then have but a very short
time to rest before my journey to London,
should my health continue equal to the undertaking.

Dear Jesse is, I hope, better; I believe he has learned from the best of teachers,
the Spirit of Christ manifested in his heart,
that it is good for us to suffer cheerfully, when pain or affliction is brought upon us.
Please to express my tender love to him, and tell him that I remember, when I was young,
that I was often sick, and my high spirits were brought low;
and now I am increased in age,
I am very sensible that these dispensations were blessings to me;
as they gradually led me to think upon my Creator,
and that there is a heaven where purified spirits live forever.
Dear Jesse, I believe, often thinks of this,
and herein I trust we have sweet fellowship one with the other,
though we do not often express it in words, and we may be personally separated;
but there is a precious union of spirits, sweeter to my mind than worldly possessions.

[.signed-section-signature]
Mary Capper.

--

Fifth month 18th. Yearly meeting of ministers and elders.
Some of the old standard bearers still remain.
William Tuke, lively and zealous for good order and discipline.
William Grover, William Allen, and Dykes Alexander at the table.
Hannah Field, in a very humble, simple manner,
informed us that she believed the time was drawing
near for her to return to her native land;
she spoke very modestly of her labours, but said, that for the encouragement of others,
she could thankfully acknowledge,
that she had been helped and sustained in all her difficulties and trials;
with tenderness of spirit,
she also mentioned the affectionate regard and kindness which she had everywhere received.

19th. A particular solemnity seemed to spread over us, when William Rickman,
of Rochester, in a humble, affecting manner,
laid before us a concern for visiting some parts of North America,
for which service he was liberated, after weighty deliberation.

20th. The women`'s yearly meeting, gathered in remarkable stillness.
The meeting at large is much helped by the business being conducted with propriety,
and so as to be clearly heard;
a prevailing quietness contributing greatly to the advantage of the whole.
A memorial was read concerning Special West;
it was very interesting to observe how heavenly goodness followed him through life,
and crowned him in death.

22nd. A very large gathering, and again favoured with a settled stillness.
We are greatly privileged with a clerk and assistants,
fully competent to their important office.
A testimony concerning Martha Routh was read.
Much excellent counsel was given.

24th. First-day.
At Gracechurch street meeting,
the Christian doctrine of true self-denial was remarkably held up to view;
viz. "`Art thou slothful?
deny thyself!
Art thou covetous?
deny thyself!
Art thou hasty in thy temper, and prone to speak what may pain others,
and wound thy own soul?
Deny thyself!`" etc.

25th. A very impressive testimony was read, respecting Rebecca Bevan.
After having endeavoured to fill the stations of child, wife and mother,
with scrupulous propriety,
she had no anchor of hope but in the mercy of God in Christ Jesus,
in the love and righteousness of her Redeemer;
and here her faith was ultimately both strong and animating; so that we,
who loved her much, have abundant cause to rejoice in the belief,
that all is well with her.
She was thirty-four years old.
As she attended the last yearly meeting,
the circumstance of her early death seemed striking to many;
Hannah Field particularly alluded to the solicitude which
she then expressed for the guarded education of children.

26th. A testimony concerning dear Sarah Hustler was read.
Some beautiful and impressive truths were declared,
and encouragement was expressed to such as were cast down.

27th. A recommendation was given to avoid providing
more than is needful for the table on first-days,
that servants might not be unnecessarily engaged.
A desire seemed to prevail that we may all be fervent in spirit,
and alive to a sense of the condescending goodness of our Heavenly Father.

29th. Our yearly meeting closed, under the favoured covering of a solemn silence,
which no description can fully convey to those who have never known its power.
No words can so fully calm and satisfy the soul!

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Cadbury

[.signed-section-context-open]
Stoke Newington, Seventh month 6th, 1818.

[.salutation]
My dear Friends,

Your continued kindness towards me, raises a very grateful feeling in my mind.
I have considered myself largely indebted to dear S.;
her watchful attentions are not forgotten.
I have moved about but little,
as I yet remain weak and unequal to those exertions
which I see others so actively get through.
Indolence does not seem to beset me, and I desire to move in the path appointed to me;
sometimes I think it amounts to very little active service.
I have spent some very pleasant time with my dear brother Jasper;
some days we have been much alone.
I hope our religious experience has in degree increased with our years, and that now,
in our declining days,
we are strongly united in a bond that cannot be broken by the power of the grave.
Our hope, our confidence is anchored upon the Lord of life and glory.
O! this is precious, and calls for the deepest sense, and the acknowledgment,
of condescending goodness and mercy toward the children of men.

[.signed-section-closing]
Affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Ninth month 18th, 1818.

[.salutation]
My dear Friends,

I came from Stoke Newington yesterday;
my dear brother Jasper has long been a severe sufferer;
I never saw him anything like so ill,
nor do I recollect ever to have seen any one in such unremitting pain.
You, my dear friends, well know the anxiety of watching over an endeared sufferer,
when all our efforts are ineffectual to give ease;
my beloved brother`'s mind is evidently fixed upon the Redeemer;
these storms shake not the foundation,
though the poor tabernacle totters with the vehemence of the blast;
but the Rock of ages stands sure; what a marvellous mercy is this!
My very tender love is to your dear, precious, suffering child;
though it would gratify me to sit by him,
and to witness the condescending goodness that keeps him in peace,
while his poor mortal body continues from day to day, to be in much pain and affliction,
I am satisfied that the pure Spirit, from the Fountain of all good,
often sweetly unites us when personally separated.
I esteem it a great privilege thus to believe.
My absence from you, dear friends, would be increasingly trying,
if I did not apprehend that I am desirous to be just where I think I ought to be,
although very little, if any obvious benefit arises from my small services;
I do not so much look at that as at the gentle pointings and openings in my own mind.

[.signed-section-closing]
Affectionately I subscribe, your friend,

[.signed-section-signature]
Mary Capper.

--

Ninth month.
I have received an account of the death of dear Jesse Cadbury,
who was only a child in years.
He expressed that he was satisfied he should die in the Lord,
and go to that better country, where he should sing Allelujah forever.
Dear, precious child! his love to me now feels inexpressibly sweet.

Birmingham,
Eleventh month 13th. I accompanied two friends on
a visit to the few remaining at the Alder Mills;
this pleasant spot, a few years ago, wore the appearance of an earthly paradise.
Distress and separation of families, with many strippings and sorrows,
have now marred the pleasant picture;
and the tender sympathy of friends is cordially accepted.

18th. After our meeting,
I accompanied Elizabeth Cadbury to call upon some Friends who are parents;
we took the Epistle on education, issued by the last yearly meeting,
and it was read with seriousness.
Some observations were made,
as an incitement to watch carefully the opening capacity of the infant mind,
to receive religious instruction;
and to cherish the first breath of the spirit of prayer;
the gentle desire to know the Author of their days; to encourage them to think of Him,
to love Him, to fear all that might offend Him.

Good impressions are often discoverable in young children,
before the natural will and the bias of evil example, or strength of wrong dispositions,
gains the ascendancy and precipitates them into evil actions;
so that it is highly important for parents and instructors, to endeavour,
with all possible attention,
to find opportunities for instructing them in the principles of the Christian religion,
leading them to the Saviour, that they may receive his blessing,
and be enabled to resist the tempter.

26th. Dined with the young family of our deceased friends John and Priscilla Dearman,
who were both taken away in the prime of life;
but there is a protecting Power extended to the orphan; such have an Almighty Father,
who heareth and answereth prayer.
I hope the visit was not unprofitable.

Twelfth month 8th. Called on several Friends with the epistle.
Great openness appeared, even with thankfulness that so much care is manifested among us,
and extended towards those whose situations and circumstances in life, much,
if not wholly, exclude them from the privilege of attending the yearly meeting,
and of other interesting intercourse with their friends.
In the afternoon we sat with some young people, a brother and a sister,
who were early left motherless; they manifested much tenderness,
and their flowing tears seemed to do us good;
our minds were sweetly brought under the influence of heavenly goodness.

16th. I united with S. and R. Lloyd in calling on some friends in the station of parents;
the epistle on the subject of education and early religious instruction,
was seriously read to them; they were also recommended to introduce into their families,
a publication by Henry Tuke, setting forth the principles of the Christian religion,
as professed among us; with Lindley Murray`'s Compendium, on the same important subject.
The Book of Extracts of the yearly meetings`' minutes, much elucidates our discipline,
and brings before us beautiful advice,
that has been issued by successive yearly meetings, for the help of the body; this,
with many other excellent publications, were recommended to be read in families.
We found that most parents could acknowledge their need of encouragement,
in their endeavours to watch over themselves and their dear children;
lest they should faint in their minds, or grow weary,
or negligent in watchfulness and prayer.
Our visits seemed to be accepted with feelings of unfeigned good will,
like those which prompted them.
That which unites sojourners here in one desire to
obtain the blessing of the promised land,
was, in degree, felt from house to house.

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Capper.

[.signed-section-context-open]
Worcester, First month 18th, 1819.

It was very kind of thy father, in his almost solitary sitting,
when his health and spirits were so much affected,
to turn his thoughts in this tendered frame towards me;
his free communication is truly gratifying.
I am often alone, and then,
what I consider mental intercourse with my beloved relatives is sweet;
the confirmation that it is at times mutual is encouraging.

Thy beloved brother`'s visit, I doubt not, was gratifying;
I think I should have participated with you in the chaste
joy of seeing dear relations walking in the Truth.
Real gratitude for such favours is not the produce of our native soil;
the happy culture of Divine grace brings first the blade; and so, if not untimely nipped,
comes the ripened crop; but the husbandman, in nature`'s field, has long patience,
and he is not dismayed at every dark and gloomy day.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Her Brother Jasper and His Family

[.signed-section-context-open]
Birmingham, Fifth month 1st, 1819.

[.salutation]
My dear brother Jasper, etc.

To be hasty in feeling disappointments, and not prompt to acknowledge gratifications,
will not, I hope, be laid upon me.
This very morning I received a fourfold kindness,
making ample compensation for my disappointed anticipations.
Wrong, you did me none, so to forgive there is nothing; and in the present instance,
I may consider myself a gainer, by thy pen being called into action,
to tell me that you loved me, etc.
It is more to me than a library of books!
My dear sister, the comparatively transient pain, which is past,
is more than repaid by present feelings;
arising from a spring afresh discovering itself from beneath
an accidental covering of some scattered fragments.
`'Tis enough! the stream remains undiminished,
and I am now in my own comfortable apartments, alone,
without interruption enjoying your kind communication.

How manifold are my consolations!
I would not change my imperfect sense of the mercy
and the favours conferred daily upon me,
for the possession of worldly wealth and power.
With reverence, not with boasting, I write; for I am sure it is of the Lord`'s mercy.

My beloved brother and sister! it may possibly be our experience in days to come, that,
whilst others in stronger health,
are more actively and conspicuously engaged in promoting the right thing,
and in beholding the manifestations of the Lord`'s power in the earth,
we may have to taste of the pure water that flows softly, in the low valley,
where there is freshness and greenness, and where the longing soul is satisfied,
even though separated from Christian friends, gathered together to help one another.
The great Helper of these, also "`setteth the solitary in families.`"

I have to contemplate many distresses around me,
in the present day of commercial troubles.
The gracious Creator of man has surely some wise, benevolent purpose,
in this chastisement;
his humble children and dependent servants will submit with reverence,
and crave for patience of soul, with wisdom to direct their steps.
My dear nephew and niece!
I did not know the power that I seem to have possessed,
to cause such a muster of your forces in your four-fold epistle.
There is strength in love,
which does as much execution as silver trumpets and battering rams.
In most cordial, sweet affection towards every one of you, including the lovely children,
I subscribe your strongly attached sister and aunt.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Tenth month, 1819.

[.salutation]
My endeared Friends,

No human language can, I believe, fully set forth, that quickening, living virtue,
which unites the heart, soul and spirit of those who love the Lord Jesus,
and cherish his redeeming power in the soul.
Surely I was favoured to feel something of its precious influence in being with you;
and since my return home, I have often thought of you,
with the same impression of your deeply hidden,
and more openly manifested trials and engagements.
Your life, spiritual and natural, with all that you are, and all that you have,
is the Lord`'s; let Him do what seemeth Him good!
A little while and time shall be no longer!
Be of good cheer, my much-loved friends! press on, meekly and steadily,
without over much solicitude; trust the whole rational creation, and your own souls,
as quietly as you can, or may obtain faith to do, into the hands of a faithful Creator.
He worketh wonders in his unfathomable mercy.

In recurring to dear J. G.`'s impressive exercise of spirit, as I was at the time,
so have I since been,
led to trace something like the deep and mournful travails of Isaac Penington,
when he expresses himself thus;
"`O! how I have prayed for the lost world! for all the souls of mankind!
How hath my soul bowed in unutterable breathings of spirit before God,
and could not be silenced, until He quieted, or satisfied my spirit,
of the righteousness and excellency of his will, and bid me leave it to Him!`"

It would be precious, if so ordered, that you found your family well,
whether you are permitted to rest and enjoy your
domestic comforts for a shorter or a longer time.
May Israel`'s Shepherd protect your tender lambs, and bless them with docile spirits;
that they may be kept within his safe enclosure, and come to know Him for themselves,
as the good Shepherd, who careth for the lambs, or the little ones,
who desire to love Him, and to obey his voice.
To your dear mother, please to express my tender love;
advancing age has its trying weakness;
but O! the sustaining comfort of looking to a Saviour`'s love; through whom,
even in our weak estate, we have access to God.

Farewell, my dear Christian friends! accept the love of your attached friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans of Warwick.

[.salutation]
My dear Friend,

It is a reviving cordial to the Christian traveller,
when we can feel union of spirit by the way, each having an appointed path to tread,
and pressing toward the same mark; yet the heart, surrounded by its fellows,
often feels alone; and none can fill this void, or satisfy the soul`'s desire,
but that Almighty Power in whom we live, and move, and have our being.
It will perhaps be matter of surprise,
though I hope not irreconcilable to thy best feelings,
that my mind has been seriously impressed, for some time past,
with a view of a visit of a religious nature, to the families of Friends at Coventry;
to some in other places not in profession with us,
and more particularly to the county jail and house of correction, at Warwick;
so impressive has been this prospect, that I concluded it best to consult a few friends,
who encouraged me to lay it before our monthly meeting.
A certificate is ordered; this must detain me till our next monthly meeting, unless,
without infringing upon any rule of good order, I might go forward to Coventry,
while the weather is somewhat mild.
I wait the decision with quiet submission.
I think I have no self choice, in the time or the thing.

Now, my dear friend, I claim thy help and sympathy.
Long as I have been engaged in this way, this is the first movement I have made alone;
and I seem like a very child, in want of help and direction.
Let me hear from thee soon.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Eleventh month 24th, 1819.

[.salutation]
Dear Friend,

How precious is it to feel the unity of the Spirit
in the bond of peace Although there may be,
and there are, in our present state, seasons, not a few,
when dark and cloudy days obstruct our vision, surely I may, with serious,
contrite feeling, say, that condescending mercy has graciously joined me to a people,
in whose religious principles my soul finds full satisfaction;
and language cannot set forth the precious fellowship, that in some favoured times,
solaces my poor spirit, in the company of those who are spiritually alive,
even in these trying days, when we are indeed a mixed people, and the pure life is often,
to our apprehension, trodden down.
O! the sense of this is surely a sign that we are not spiritually dead,
nor living at ease in the midst of the desolation that surrounds us.
Our humble trust is still in the Lord, though unbelief abounds in the nation.

I am satisfied and confirmed by thy judgment, and strengthened by thy sympathy,
to wait the full time of the meeting`'s approbation.
I believe it is, in most, if not in all cases, safest and best,
to avoid giving occasion of offence or remark.
I have not a decided sight, whether I had best move with or without a companion;
this I trust will rightly open in due time.
I feel satisfied the delay is no hurt to me; and in all things, there is instruction.

[.signed-section-closing]
In dear affection,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Hannah Evans to Mary Capper.

[.signed-section-context-open]
Eleventh month 27th, 1819.

[.salutation]
My dear Friend,

I received thine, and am pleased my last met thy approbation.
In respect to thy having a companion, I think that is a very weighty consideration,
except any friend should feel a similar engagement of mind, and you could,
in true gospel fellowship unite; then it might be helpful,
for I believe there is strength in unity; if not, in my simple opinion,
it will be best to go without any constant, nominal companion; for I do believe,
that in the important work of visiting families, especially,
except it is one who is rightly brought under the weight of the service,
it is better to go alone.
And be not discouraged, my dear friend, at the prospect of having no outward companion,
for I have no doubt but He who putteth thee forth will go before thee,
and encamp round about thee, and that is enough.

Well! thou hast my free sentiments,
which thou must place to the account of true friendship;
I trust I am deeply interested in that noble cause which thou art labouring to promote;
and that it may please thy Divine Master to "`send thee help from his sanctuary,
and strengthen thee out of Zion,`" was the petition of my spirit this morning,
before I left my pillow.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Mary Capper to Katharine Capper.

[.signed-section-context-open]
Dale End, Eleventh month 29th, 1819.

[.salutation]
My dear Niece, etc.,

The communications handed to me, one day last week, have not failed to help and cheer me.
There is strength in unity;
and very precious is that secret Power that joins the spiritually living,
in one hope of salvation.

Thy dear father`'s tender interest and kind concern for me,
is truly welcome to what I esteem some of my best feelings; the approbation of a mind,
humbled on a bed of languor, is likely to be genuine,
and is strengthening to that in my heart which I hope is pure and lowly,
only desiring to do the will of my heavenly Father.
I feel little and childlike, and a sweet tenderness of spirit keeps me calm;
like what I can imagine to be subjection to a father`'s will.
My dear love is to my sister; her exertions and patience are admirable;
you all have much anxiety and fatigue; so it seems that, through diverse dispensations,
we are led, by the same Hand, in the path of subjection.
I hope we shall often think of one another, when duties, differing in kind,
call for resignation and endurance.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to Hannah Evans.

[.signed-section-context-open]
Twelfth month 7th, 1819.

[.salutation]
Dear Friend,

Very cordial is thy letter!
I think I feel grateful for such free, sisterly kindness,
and thankful for the confirmation that the secret movements of my heart have a spring,
better and higher than self-will or self-contrivance;
indeed I think my views are simply to do what is required at my hands,
ere my natural day is ended; my strength is small, but I dare not dwell on that,
though it is discouraging.
My heart`'s desire is that patience, humility and dedication may be perfected,
in the way that my Lord sees meet.
The time for my liberation approaches quickly.
I have been a little engaged about home, so as to leave free from debt.

I think of coming first to Warwick; though the concern there is of less extent,
yet it is important, and in its near approach, very weighty.
I like to anticipate being under thy roof, in simplicity, quietness,
and above all in Christian sympathy; and how very few feelingly know what this is,
O! how precious to the poor exercised mind!
I have not heard of any one to accompany me; but that I leave, and subscribe,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to the Family at Stoke Newington

[.signed-section-context-open]
Warwick, Twelfth month 18th, 1819.

[.salutation]
My dear, loved Relatives,

I am desirous to relieve your affectionate solicitude by informing you,
that I am cared for with all possible tenderness;
and my weak body has borne exposure to cold and fatigue without much suffering.
How shall I fully set forth that condescending,
merciful regard which has clothed my mind with stability,
and kept me close to that Power,
by which I believe I was moved to leave my own comfortable dwelling,
in order to do whatever might be developed for me, as a dutiful child.

I came, in simple obedience to apprehended Christian duty, to Warwick, on the 9th,
and was affectionately received by Hannah Evans,
whose mind seemed prepared to feel with me.
William Whitehead, a kind, valuable elder, of this meeting, entered into my views;
and being well acquainted with the jailer and his wife,
he easily obtained access for me to the prison, where, accompanied by these two friends,
I arrived about the time fixed for the visit.
The poor men prisoners were all placed in the chapel;
a great calm mercifully spread over us, and supplication was offered,
that heavenly mercy might, in truth, be felt to be over all.
The stillness was admirable;
and we were favoured to feel a measure of our heavenly
Father`'s love to be extended to us,
wherein help and comfort were offered to the longing soul.

On fifth-day morning, we were introduced to the women; it was an affecting time,
and many tears were shed.
I do believe Divine mercy was near to us;
and I know that Christian good-will flowed towards this unhappy,
misguided part of our fellow creatures.
How marvellous is the love of God! how it would gather all!
With earnest solicitude that we may be kept lowly and patient in the day of trial,
I very affectionately subscribe, your closely attached relative,

[.signed-section-signature]
Mary Capper.

--

+++[+++The following account of the visit to the female prisoners was afterwards sent,
anonymously, to Mary Capper; it was written by a person who was present on that occasion,
in a letter to a friend of hers.]

[.embedded-content-document.letter]
--

[.letter-heading]
Visit paid by a female Friend to Warwick County Jail.

December, 1819.
This person had a private interview about two months since,
with the servant who murdered her mistress.
She is one of the Society of Friends.
Last week she paid a visit to the female prisoners, and you must set her before you,
in a dark brown gown, a handkerchief pinned close up to the chin, and a plain muslin cap,
covered with a black silk hood.

There were thirty persons assembled, who rose up to receive her,
and remained standing till she began to pray, kneeling.
She sat down with her eyes fixed on the ground, as if in deep thought, and then rose,
saying nearly the following words, "`This silence, no doubt,
will be incomprehensible to your minds, but it is nevertheless useful.
I wish you to check your busy, active imaginations, to be silent and to think;
to consider your past ways and your present situation, with all that belongs to you,
temporally and spiritually; to remember the great God,
who although a God of power and justice, is also a God of mercy;
who will hearken to your prayers, if offered with unfeigned repentance,
through faith in his Son, Christ Jesus.

Think of your sins, with that humiliation which becomes us all; but particularly, those,
in your unhappy situation, who are placed here under locks and bolts and bars,
for having offended against the laws both of God and man.
In the world, you have practised deceit, and sought a refuge in lies; and are you happy?
You have coveted and taken what was not your own; and are you happy?
No!
Yet you thought you should be, or you would not have done these things;
you see then that you were mistaken.
I pity your mistake; and as a fellow-pilgrim in the journey of life, earnestly tell you,
that there is no happiness on earth,
but in that obedience which is the evidence of our gratitude to God the Father,
and faith in Him, and in the merits and sufferings of Jesus Christ his Son.

Many of you have been tempted to do wrong through poverty, distress and bad company;
and when you return into the world at large, as I trust many of you will,
may you remember what, before, brought upon you sorrow and degradation;
and never fail to pray for the grace of God, to enable you to forsake your evil ways;
that, by honesty and staying at home, not going from house to house,
hearing and telling lies, you may obtain kind friends,
and be happy by leading a new life.
I warn you against hardening and encouraging one another in vice, while you remain here,
by laughing at sin and making light of your crimes; but may the care bestowed on you,
by the excellent mistress of this establishment,^
footnote:[Esther Tatnal.]
who is equally earnest with myself for your souls`' welfare,
be hereafter rewarded by the knowledge,
that sinners have been turned from the evil of their ways, and that you can say,
with humble thankfulness of heart, "`Our Father which art in heaven,
hallowed be Thy name!`"
She then shook hands with all the prisoners, and addressed them individually.
To the murderer she said,
"`May God Almighty bring conviction to thy soul!`" and I
could not help addressing my mite of exhortation to her,
by begging of her to improve her mind.

The individual spoke for an hour and a half, so you will readily believe,
that this is only a very small part of what she uttered,
but I have endeavoured to recollect the heads of the exhortation.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Capper to Hannah Evans.

[.signed-section-context-open]
Coventry, Twelfth month 23rd, 1819.

[.salutation]
My dear Friend,

We parted peacefully; may I not say sweetly?
though feeling our mutual privation.
I fancy thee at home missing thy nursling; and I feel as weaned from a tender,
nursing mother.
Well! do not let us dwell too much upon these pleasant things by the way;
possibly it is best for us to walk alone!
My strength is small, but I believe it will revive as occasion requires;
do not let us doubt, but humbly believe from day to day.
My mind, through marvellous condescension, is favoured with stability and calmness;
with a childlike tenderness towards all the creation of our universal Father.
This is from a Power, higher and better than anything of my own.
I hope I am thankfully sensible of the mercy, and not impatient,
nor dismayed at the strippings and secret plunges of my spirit,
again and again showing me what is in the human heart,
and teaching me that the sanctifying power of Christ, revealed by the Holy Spirit,
believed in and obeyed, is the only safe armour of the Christian.

[.signed-section-closing]
I subscribe, affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Foshil Lodge, Twelfth month 28th, 1819.

[.salutation]
My kind Friend,

Thy sympathy is cordial; I have had my plunges and strippings,
since I last wrote to thee; yet let me, with reverence and humility, say,
that my mind has been kept from sinking below the confidence of a Christian believer,
whose only sure reliance is on the Rock that followed Israel, and that Rock is Christ.
I have been into some families; and I am thankful that thy judgment strengthens my own,
that it is safe, and best for me, to be alone;
I trust it is no presumption or self confidence,
but in that measure of love and good-will which daily clothes my spirit.
I have had no offer of a companion,
so that I have been spared the trial of having to decline.

Thy tender feeling for me will, I believe, be afresh excited when I tell thee,
that my precious brother Jasper suddenly breathed
his last on the 24th. He was truly a precious brother!
We were, I trust, joined in spirit, so that death cannot separate us.
On the 9th of last month, he very solemnly said, "`When my time is come,
if I should say little or much, anything or nothing, I request it may be said,
that I died, relying on the mercy of God, through Christ Jesus;`" and on the 11th,
"`None but Jesus can do helpless sinners good, and I am one!`"
He was at that time very ill, but afterwards revived for a time.
About a week before his death, the pain, etc. having returned, he said,
"`I never saw myself so lost and undone without a Saviour,
as I have done in this illness.
I have suffered anguish of mind; and but for faith in the Saviour,
what should I have done!
He has paid our great debt!`"
On the day upon which he died, he expressed to his wife, his belief,
that when he should be taken from her, God would be her consolation.
The last conflict came on, just after lying down in bed,
and he peacefully expired in the midst of his family.
We have often had sweet converse together; that is over,
as it respects this state of existence, and it becomes us to leave all that is to come,
in the ordering of a faithful Creator.

I came here yesterday, with a view to have some rest, which I need.
The links which bind me to earth and to endearing connections,
are gently loosening one by one; and my spirit, in some favoured moments,
aspires to a more perfect union.
Farewell, my much-loved friend, I subscribe affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Family at Stoke Newington.

[.signed-section-context-open]
Twelfth month 29th. 1819.

[.salutation]
My dear Mourning Relatives,

I am much affected by the intelligence of dear Katharine`'s letter.
Although the event has for some time been anticipated, nevertheless,
now the spirit has fled, what a void does the affectionate heart feel!
In my measure, as a sister, increasingly united to a brother,
evidently increasing in all that is lovely, and fitting for heaven and blessedness,
I participate with you in mourning our loss.
Every day, for some time to come, will, I seem aware, add to your sense of it.
Necessary arrangements, arouse every tender emotion of the heart; scenes past,
and sweet communion almost forgotten, revive with fresh interest.
Link after link seems to be rapidly breaking; but there remains a soul-cheering belief,
that although yet but faintly seen and imperfectly understood,
there is a union which cannot be broken!
When you are shedding tears over the grave of our very dearly beloved one,
calm resignation,
and the assurance that his redeemed spirit is clothed with the righteousness of Christ,
in whom he trusted as his Saviour, may be your stay and your strong consolation.
Long have we known him as disclaiming every rag of self-righteousness.
How often was his spirit broken and humbled!
It is precious to remember these seasons.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. C.

[.signed-section-context-open]
Warwick, First month 7th, 1820.

I have had no very late intelligence from any of my dear sorrowing relatives.
Much I think of them, but our mourning is sweetened by hope;
how widely different to a gloomy spirit of sorrow!

With heart solacing satisfaction I recur to the last time I spent with my beloved brothers,
now both of them taken from pain, sickness and sorrow; their immortal spirits,
I assuredly believe, sanctified, redeemed, and admitted into the kingdom of heaven;
where the ransomed of our Lord join in the glorious anthem of thanksgiving and praise.^
footnote:[Her brother William died in the third month, 1819.]

I am not, however, insensible of my own privation.
The affectionate communications of my dear brother Jasper have now ceased,
yet a precious sense remains of a union never to be broken,
and here every discontent is swallowed up, in the perfect fruition of light,
life and love.
It is very sweet to reflect,
that my present engagements were known and approved by my beloved brother,
at a time when his spirit was so nigh to the haven of rest and of purity.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Rebecca Lamley.

[.signed-section-context-open]
Birmingham, Second month 14th, 1820.

[.salutation]
My dear Friend,

With tender love I remember thee, and think of thy lowly diffident mind.
There is surely a possibility of dwelling so much upon our own weakness and unworthiness,
as to overlook, or sink below, the heavenly gift of Divine grace,
which is given to every one to profit withal.
"`The Lord preserveth the simple;`" and I do believe, dear friend,
that through merciful kindness, thou art one of the simple in heart,
desiring to follow a crucified Saviour.
Take courage, then, and think upon a Redeemer`'s love more than upon thy unworthiness.
It is not because of our righteousness, but of mercy,
that we come to know the mind of Christ,
and deliverance from those things that grieve the Holy Spirit.
Take courage, I again say, my tender friend, and give no place to distrust.
I subscribe, with endeared love, thy fellow traveller and friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Birmingham, Second month 15th, 1820.

[.salutation]
My dear Friend,

I hope it may not be too much to say that the union
that I have been favoured to feel with thy spirit,
brought me into a measure of suffering which has not passed lightly over.
These secret dippings may possibly be among the "`all
things`" that work together for some good,
we cannot now see; and here I do desire to leave what I do not understand.

Thy lines were cordial,
and I am thankful that thou couldst feel sweet satisfaction
in reviewing my little acts of dedication.
I may humbly say, that in delivering up my certificate on fourth-day,
I believe there was a precious evidence felt by more minds than my own,
that I had been mercifully kept from hurting the cause unto which my heart is bound.
My prevailing petition was and is, "`Abba!
Father; keep me from evil; the evil of my own heart,
and the evil that abounds in the world; thine is the power,
and the glory forever!`"--How very beautiful and
instructive are some of the morning portions;
it seems helpful, consoling, and uniting that we can read them,
as if we were personally together.

Thou possessest the rare and happy art of compressing so much in a little,
that I am almost afraid, my lengthened scribbling should surprise,
I will not say alarm thee.
Do not, my dear Christian friend! if thou canst avoid it,
suffer thyself as it were to catch at discouragements when they present inwardly.
Thou knowest what I think on this subject.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Third month 7th, 1820.

I begin to think the time long since I received thy __"`multum
in parvo,`"__ but I am satisfied that we are united in spirit,
even though mountains should rise up between us.
How sweet and cordial it will be to my feelings, to welcome thee under my roof,
is not for me to express.
I quite approve thy note, and thank thee for the perusal of it; it has been delivered.
I am at no loss to enter into thy feelings as therein expressed.
Ah! "`What is the chaff to the wheat!`" and what is outward
conformity if unaccompanied by true spirituality of mind!
Here it is that Christians taste and know the true unity, and can feel one for,
and one with another, in their pilgrimage, and in this painful mixture of things,
where faith, patience and forbearance are often brought into exercise.

This evening is our meeting of ministers and elders.
The Dudley and Stourbridge Friends add to our little number.
We are preserved in unanimity and affection, which is better than increase of numbers.

8th. I hope I shall not improperly call for thy sympathy,
but it seems as if the small measure of my active services must be filled up,
without much delay; so that, after a time of serious consideration,
and something I believe of that dipping and stripping,
known only to those who have trodden in the same path,
I have this day laid before my friends,
a concern to attend the ensuing meeting for Friends of the principality of Wales,
at Coalbrookdale, next month; also to visit the families of Friends in Shropshire, etc.
Thus I have again thrown myself upon my friends, and I feel little, low and quiet.
The approbation expressed was encouraging,
and my heart craves to be kept by that sustaining Power,
which alone can effectually keep from error, on the right and on the left.
My love to T. S. and to his wife and family; I do not forget them.
A rising generation claim the love and interest of those
who are hastening to the close of their earthly pilgrimage,
and who wish peace, with joy unspeakable,
to those who may fill up the places of the faithful.

[.signed-section-closing]
Farewell, affectionately,

[.signed-section-signature]
Mary Capper.

--

+++[+++In this visit, Mary Capper was accompanied by her friend Hannah Evans,
from whose memoranda the following extracts are taken.]

1820+++.+++ Fourth month 15th. I went to Biringham,
to accompany my dear friend Mary Capper in a religious visit
to the families of Friends in Shropshire monthly meeting.

17th. We went to Coalbrookdale,
and were cordially received at our valued friend Sarah Darby`'s.

30th. Went to Horse-hay,
where we were kindly entertained by our friend William Stanley and his wife.

Fifth month 2nd. In the evening,
a meeting appointed for the workmen employed in the iron works,
was held in one of the mills.
It was estimated that more than a thousand attended;
I think it may be said to have been a memorable meeting,
for the feeling mind must have been sensible of the
condescending goodness of heavenly Love.
It was thought dear Mary Capper was on her feet near an hour and a half,
during which time, as also in time of silence, it was as quiet,
as though all had been of our own Society.
It was truly a satisfactory meeting.

14th. First-day.
At meeting, morning and evening; the last at Coalbrookdale.
It was a precious time to us,
wherein we felt the over-shadowings of heavenly kindness and love,
to the reviving and strengthening of our minds; from this meeting, we came away,
comforted and refreshed.
Also in the evening, when the family, etc. were collected to read,
was a precious opportunity.
Divine goodness and mercy were afresh extended.
The spirit of prayer was felt, and vocal supplication offered.

Having gone through the families in this monthly meeting, I can in sincerity say,
with reverent gratitude, that I have often had cause to be thankful,
that I was permitted to accompany my endeared friend in her arduous engagement;
and have had to admire the condescension of Divine goodness and love,
in furnishing and helping his faithful, dedicated servant, from day to day,
to divide the word aright, to the several states of the visited.
And although I have had little to do in verbal communication,
yet I trust I have not been altogether an idle, unfeeling companion;
but have often felt a deep secret, travail of spirit, and fervent breathing,
for the support of my beloved friend,
and that the Divine blessing may attend her labours;
and I think I may say our spirits were nearly united in the bond of gospel fellowship.

19th. Under a precious feeling of our heavenly Father`'s love,
we took an affectionate farewell of our kind friends at the Dale,
and returned to Birmingham, in the enjoyment of sweet peace.

21st. We parted under a sense of that uniting love which remains to be a badge of discipleship,
and I returned to my own habitation with thankfulness.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Polesworth, Ninth month 5th, 1820.

I am low, in mind and body, yet I dare not let go my confidence,
that heavenly Mercy will not leave me to follow a vain shadow, or to kindle a fire,
and warm myself with the sparks.
There is nothing that my soul longs after with so much earnestness,
as the real substance of the religion of Jesus, the soul-satisfying bread of life,
daily ministered to nourish and keep alive the immortal spirit.

Fifth-day.
I returned home this morning, a little weary.
Thou mayst rest satisfied, my dear and affectionate friend,
that I take as much nourishment as I conveniently can,
and my health and strength seem marvellously equal to the exertion required.
Do not let this subject occasion thee solicitude.
I should prefer, if thou wilt indulge me,
that we rarely advert to anything merely personal.
I subscribe, in a very feeling sense of thy love.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Mary Capper.

--

+++[+++The following is a memoranda of a religious visit in Herefordshire and Worcestershire.]

[.small-break]
'''

Ninth month 13th. Our monthly meeting at Birmingham.
The sympathy and unity expressed, and the solemnity that spread over the meeting,
were precious and encouraging to me.

17th. First-day.
At Bromyard, we were a poor small company at meeting.
There is deep instruction, to a rightly waiting, exercised mind, in these low sittings;
all our dependence, for spiritual refreshment,
being simply upon Him who is the Spiritual Head of his people.
My heart does admire, and greatly desire, that I may reverently,
and thankfully estimate the marvellous condescension, and mercy of our faithful Creator.

18th. I called on a poor family who once belonged to our religious Society;
but from causes well known to themselves, distress and perplexity have been their lot;
nevertheless such poor wanderers should be, at times, sought after,
visited and invited to turn to the good Shepherd for help.
I came to Leominster in the evening,
and was very affectionately received by my kind friends H. and S. Waring.

19th. S. Waring had a minute willingly granted,
to accompany me through the families of Friends in Herefordshire.

20th. The quarterly meeting large, and a time of spiritual refreshment.

22nd. S. W. and I came to Hereford,
on our way to the interment of dear Rebecca Pritchard,
she was about twenty-four years old; a lovely wife and mother.

24th. First-day.
Ross.
The interment was a solemn time; it was attended by the mournful husband, his father,
and Roger Merrick his father-in-law, etc.

26th. We visited Roger Merrick; the house of mourning and the children of affliction,
often afford lessons of deep instruction, and I thought it was so, on this occasion.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Ninth month 28th, 1820.

Thy cordial sympathy and encouragement are acceptable.
In this mixed scene, O! what a favour is the sweet drop of love;
inducing the poor mind to look to the pure, undefiled source;
thence comes the true union of spirit, which subsists through all low times;
enduring all that may be allotted; trusting and believing that we shall not be forsaken.
The designed end of our trying times doubtless is, that we may be a praying people.

[.signed-section-signature]
Mary Capper.

--

Tenth month 6th. J. Newman kindly conveyed us in
his carriage to visit a family at a distance,
some of whom attend our meetings; two of the daughters have joined our Society.
We found their father a serious, kind and liberal-minded man,
and our visit was truly pleasant to us.

10th. Came to Hereford.

13th, Some serious neighbours came to tea; some well-meant enquiries were made,
and I believe were cautiously answered.
Conversation on important subjects requires watchful circumspection.

18th. We took tea today with a Baptist teacher, with whom, and his humble,
sweet spirited wife, I had in years past some acquaintance.
It is precious to find, that unity in the one Spirit, continues unchanged;
we had a little sweet converse, and thought the time came too quickly for our separation.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Hereford, Tenth month 18th, 1820.

[.salutation]
My dear Friend,

I desire to be really thankful, that day by day,
my mind is measurably stayed upon the requirings of the day,
with little of unavailing anxiety.
Many times I do think myself a poor, weak child, learning to step alone;
being set upon my feet, I must creep or go as I can.
This matters little, if I be kept from dangerous falls.

I cannot yet fix a day for quitting this place, as I am in a little suspense,
as to the movements of my sister Anne Capper.
Should she, in her return from the North,
pursue her design of passing some time at Birmingham,
I feel strongly inclined to meet her and her daughters there;
my sister`'s health is so very precarious, that it impresses my mind,
that this opportunity missed, I may see my dear sister no more.

19th. We have several visitors, not of our Society, especially some young women,
who appear to have seeking, tender minds, and their behaviour is quite agreeable.
Two of this description breakfasted with us this morning.

The longer we stay here the more we find of a spirit of enquiry
after the pure spirituality of religion and its effects;
yet we feel a fear that there is much danger of some talking away what they feel,
and which is intended for their own help.
As to my own steps, I am satisfied it is not my proper business to direct them myself,
but simply to follow, as my heavenly guide leads the way,
and mercifully keeps me childlike enough to obey.
Farewell,

[.signed-section-signature]
Mary Capper.

--

19th. Two very serious young women took tea with us; they had been at our meeting,
and they appeared to be pleased with the Scripture reading, etc. in the evening,
also with the expression of a little affectionate counsel.
Something is at work to disturb the false rest and the indifference which has long held
many Christian professors in a state of lukewarmness and of dangerous security.
May the work go forward, to the glory of our gracious Lord.
O! that the unsanctified activity of the creature may not hinder its progress!
To my poor frame, this was a wearisome day;
but I do not see it best to withdraw from such society as may fall in our way,
without our seeking it, or from those who may desire information,
though maintaining their own opinions.
My soul craves the clothing of Christian candour, of meekness,
lowliness and godly simplicity, that so nothing may harm me,
nor the increase of pure righteousness be hindered, through me.

21st. Two young men called, and appeared serious and tender.
One of them, with whom we had before conversed respecting women`'s preaching,
to which he had strenuously objected, as contrary to Scripture injunction, expressed,
with gratifying ingenuousness, that, after comparing the texts,
he thought he might be mistaken, and that he had maintained the argument too warmly;
a modest confession, more beautiful than any victory!

25th. The monthly meeting at Ross was small; every feeling within me seemed bowed,
and bound to the suffering spirit of the tried and oppressed ones;
of which number I believe there are some in this place.

31st. I came home; and my sister and nieces arrived at Richard Cadbury`'s, in Bull street.

Eleventh month 5th. After having cordially met, we have now parted in sweet affection;
my preciously endeared relatives set out for home this morning.
The separation was accompanied with heartfelt regret,
but a soothing calm blunted the keen edge of pain; for we feel a humble confidence,
that our spirits, whether absent or present in person,
are anchored on the immovable Rock, the soul`'s best hope.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Birmingham, Eleventh month 8th, 1820.

[.salutation]
My very dear Friend,

The visit of my precious relatives has been short,
but the interview has left feelings not easily, I trust, to be forgotten.
My dear sister is weak in body, and endures much suffering,
but her strength of mind seems to raise her above human infirmities.
Her testimony to the power of Jesus the Redeemer was very impressive and excellent.

My mind now seems bound to pursue my own uncompleted concerns, as soon as I well can.
I think of going first to Bromyard.

[.signed-section-signature]
Mary Capper.

--

11th. A kind friend accompanied me to Bromyard.

12th. First-day.
Several Friends came, very kindly, from Worcester,
as I had mentioned to them a concern which I felt,
to invite some of the inhabitants to sit down with us in our religious meeting;
the help and countenance of my friends were very encouraging.
About three hundred persons attended, and their behaviour was becoming.
My mind obtained some relief;
but there is often a painful sense how poor our endeavours are to arouse the lukewarm,
and to induce a steady retirement to the gift of grace in the soul.
This must be left to the Great Physician.
Came to Leominster in the evening.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Eleventh month 14th, 1820.

[.salutation]
My kind and dear Friend,

I now address thee from Leominster;
a place which revives many an interesting scene, finally closed as to this life;
yet it remains to be a place of interest.
Where indeed,
can our lot be cast that we do not feel an interest in the salvation
of souls! though the power to manifest it may sometimes be withheld,
the secret breathings of the spirit, with sighs and petitions that cannot be uttered,
are not, I surely believe, unavailing; at least they tend to keep our own hearts tender,
pitiful and humble.
I left Birmingham as intended, and came to Bromyard.
I had mentioned to a few friends my view of inviting
some of the inhabitants to our meeting.
The prospect was discouraging; there is only one family under our name in the place,
and as a religious body we are but little known.
However, I find it my business to keep in as much simplicity as I can,
to the gentle intimation of duty, and to leave all the rest.
Friends were very kind,
though some expressed that such invitations were rarely much attended to, in that place.
Information was also received that the only female Friend in the town was very ill.
Through all, my view remained unchanged.
An active, kind, feeling Friend accompanied me from Worcester,
and I lodged at G. Kilsby`'s; his sister Ann was in a dying state,
and finally closed her earthly pilgrimage on second-day,
I believe in the sweet and peaceful assurance of a heavenly inheritance.
Several Friends from Worcester joined us on first-day morning.
Two o`'clock was appointed for the meeting with the inhabitants,
and a full attendance there was; the people were serious and attentive,
and I trust that many were favoured with a sense of the enduring love,
and of the renewed merciful calls of our heavenly Father.
I have been thus particular in my detail, in order to set forth how good the Lord is,
and that we should rely upon him, in all and through all.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Mary Capper.

--

17th. Mary Watson, from Ireland, travelling through our land on a religious visit,
accompanied by her daughter Jane, wished to hold a meeting here this morning;
it proved a precious season.

20th. S. Waring and I went to Hereford.

21st. Our friend Mary Watson came to the monthly meeting.
Her company was encouraging,
and the meetings were favoured with the renewed extension of that
Power which alone can do the soul abiding and effectual good.

22nd. I returned to Leominster.

26th. First-day.
Attended both meetings; at these times,
when met for the renewal of our spiritual strength, as we have no outward dependence,
the rightly exercised heart retires as into the inner temple,
and patiently wrestles for the Divine blessing,
and for ability to worship in reverence and in truth;
so that each may obtain the heavenly savour of goodness and mercy, cleave thereunto,
and daily live under its influence.

Twelfth month 3rd. First-day.
I believe there is, among the little company here, an exercise of spirit maintained,
that while others of our fellow Christian professors may congregate in larger bodies,
and join in outward performances, in prayers and songs, etc., we may be found humble,
and acceptable worshippers.
In the evening, a young man, a stranger, came to my quarters,
as he said with a desire to receive some religious counsel;
he seemed to be simple-hearted, and I afterwards understood that he is one of a poor,
dissipated family, in this place.
He is like a brand plucked from destruction; and is one who, with other lads here,
was apprenticed by the philanthropic Webb, who some years ago,
distributed a large amount in an extraordinary way.

Tenth month 8th. Made a few calls which were relieving to my mind.
I also made a few purchases for distribution,
with a view to benefit both the seller and the receiver.
In the afternoon visited at the house which dear Mary Lewis inhabited.

9th. Took tea with the Moravian teacher, named Church.
His mother`'s name was Chase, and her brother married my Father`'s sister.
My aunt Chase and her daughter were of the Moravian connection, and died in London,
within a few hours of each other.
Our meeting together at this time was satisfactory;
for notwithstanding some diversity of view and of practice,
true unity is to be experienced in the one Holy Head.

10th. First-day.
The neighbours being invited to sit with us, more came than could be accommodated.
O! the love of God in the heart; how it would gather the minds of all,
and stay them upon that teaching which is truly profitable in all things,
as to our social, relative, and religious duties.
We must patiently bear with our own, and one another`'s ignorance.
If good arises, and is felt to flow among us, it is of the Lord`'s mercy;
may He have the glory, and the grateful praise forever and ever!
In the evening I was favoured with a measure of lowly calm.

17th. First-day.
At both meetings, and had a parting opportunity with a few individuals.
In tenderness of spirit, and I believe with good desires we separated.

18th. Worcester.
On leaving Leominster, heaviness clothed my spirit,
though I know not that I brought it upon myself, by wilful omission or commission;
but I do mourn over the want of real renovation and sanctification in the human heart.

20th. The quarterly meeting.
It is gratefully to be acknowledged,
that notwithstanding many in our Society have adopted the customs of the world,
and drunk of its beguiling spirit, we are yet a favoured people.
In our religious assemblies may be felt a gathering Power,
that would help us in our Christian pilgrimage,
and increase our knowledge in divine truths, settle, stablish our Christian faith,
and sanctify our hearts, with all our affections.

25th. This morning, as I sat alone, a lowly calm covered my mind,
which was very precious and encouraging; and it seemed to increase,
while reading some beautiful chapters in Isaiah,
descriptive of the peaceable kingdom and government of Christ.

29th. My dear friend, and true Christian helpmeet and companion, Hannah Evans, arrived,
to unite with me in a visit to the families of Friends, and other service in this county;
this was cordial and reviving.

31st. First-day.
In our religious gathering this morning, we were favoured to unite in spirit,
and were again enabled to believe, that the Lord continues to be gracious,
and to give his waiting children to taste of his mercies;
and at times feelingly to acknowledge that He is good,
and ready to do good to all who seek Him.
The evening reading was instructive.
Thus favourably closed the year.
