== Chapter IX.

Religious services in Worcestershire, her own quarterly meeting,
etc.--Death of Anne Capper.--Mary Capper returns home near the end of 1822.

1821+++.+++ First month \st. Worcester.
We began the visit to the families,
being gently constrained to unite in this work by a measure of Christian love.

4th. We have sat in many families, we hope to some profit.
It is little, however, that we can do one for another, though at seasons,
a constraint is felt to leave our own home comforts,
and thus to visit the professors of the same religious faith.

7th. First-day.
At meeting we were again favoured to experience that it
is good to wait for a renewal of spiritual strength.

14th. First-day.
One of close religious engagement,
and of inward breathing of heart to be kept in the path of duty.
Heavenly counsel can alone direct, and keep in safety, from day to day.

18th. In our meeting for worship,
we had renewed cause to acknowledge that the Lord`'s mercies are both ancient and new.

23rd. A fine, mild day.
We walked in the garden, and I think gratefully enjoyed the sun,
in its brightness and cheerful influence on all around;
not forgetting the bountiful Giver of all we enjoy.
Bless the Lord! all ye who partake of his mercies, in all places;
whether surrounded by the beauties of the country,
or supported by his daily Providence in the noise of the town.
O! the heart that trusts in Him can acknowledge his power to sustain in all lawful engagements.

28th. First-day.
The afternoon meeting was largely attended, an invitation having been given,
more especially to servants and apprentices employed by Friends.
The intent was partly answered, but there was a mixed company,
which was not quite so relieving to the minds of those,
on whom the weight of the concern rested, as it might otherwise have been; however,
when we have done what we can, we must endeavour to be quiet.

30th. Left Worcester and came to Netherton.
We were pleased with the delightful calm,
and with the beauties of nature surrounding the habitation,
and still more so with our reception from the family.

31st. We were conveyed to the small meeting,
where condescending Goodness was in the midst.
I thought in my heart, how excellent is a lowly, stayed frame of mind,
waiting for that spiritual refreshment, which comes from the presence of the Lord.

Second month 2nd. My dear companion so unwell that we have had a restless night.
In renewed times of proving, and fresh trial of faith, the best we can do seems to be,
to endeavour to be still, both in body and in mind,
that the secret word of instruction may be rightly distinguished; either in reproving,
humbling, or opening new springs of help and of pure knowledge, for our own advantage,
or that of others.
In something of this state of mind, we sat down with this family; it was a serious time,
I hope to mutual profit; a little spiritual refreshment was ministered to my own mind.
I do crave this, from day to day, lest I perish.

4th. First-day.
We had a very crowded meeting at Bewdley, some invitation having been given.
The gathering was attentive, and was affectionately addressed;
may it be blessed of Him who giveth the increase.

5th. After the morning Scripture reading, something by way of an affectionate farewell,
mingled with some gentle caution to this kind family, most of whom are young,
was feelingly expressed, and we separated in much love.
Arrived at Worcester.

6th. Called upon a young woman, not of our Society, whom I had before visited,
when she was under the reducing effects of sickness,
and when her mind was susceptible of good impressions.
Returning health, youthful vivacity, with an attractive share of personal beauty,
and mixing in gay, dissipating, fashionable amusements,
and those frivolities which allure from seriousness,
and fail not to mar the growth of holiness, have, I fear, for a time at least,
laid waste the engaging loveliness of a humble and broken spirit;
though there are still tokens of a tender mind.
Dear young woman! my heart feels an interest in her true happiness,
and I am well satisfied in having made the call, which she seemed to receive kindly,
expressing her sense of the motive, with rising tears.

7th. We came to Evesham.
Our minds were favoured with a peaceful acquittal,
having gone through our late engagements,
with a sincere and watchful desire to be kept simple,
humble and faithful in the line of duty; the only way of peace and safety.
Richard Burlingham and his kind wife gave us a cordial welcome.

8th. The monthly meeting; a time to be acknowledged as a renewal of condescending favour.
What shall we render to the Lord!

11th. First-day.
In the morning meeting, Richard Burlingham spoke impressively; in the afternoon,
a considerable number of servants in Friends`' families, labouring men, etc.,
came by invitation, and their behaviour was becoming.
The nature of silent waiting, for the renewal of our spiritual strength,
was a little explained; it is but little understood, among Christian professors;
and to be fully so, its incalculable benefits must be, in some degree, experienced.
Hearing or doing is too often rested in, as religious worship;
with very little sense of that heart-humbling Power that contrites the spirit,
and prepares an acceptable sacrifice, though no vocal sound be heard.

13th. In the evening I read to the family an account
of my dear brother Jasper`'s illness and close;
a very precious feeling spread over us in contemplating the dissolution of a brother,
so beloved by me in life.
We separated under a tendering sense of heavenly
goodness and mercy toward the children of men.
O! that every rational creature would seek to know the God of our salvation,
that so all might praise Him.

14th. Sat with a young woman to whom tender counsel was given,
with sincere desire that she might be preserved from the strange notions of liberty,
and of alienation from the cross of Christ, which seem to abound.
Our safety is in humility and in stillness; that we may be taught to know ourselves,
and often to resort to the place where secret prayer is wont to be made,
where the simple-hearted wait for an increase of understanding,
to know and to keep in the paths of uprightness, that they may be at peace.
These read the Holy Scriptures with reverence and lowliness of mind,
that they may come unto the Light, the Life and the Way,
whereof the Scriptures do testify, even Christ the Lord.
We had our fears for this dear young woman,
but parted in the tender clothing of Christian love.

16th. A day of much engagement.
In the evening, sat with the heads of this family.
How precious are the Lord`'s visitations! when received and cherished,
how wonderfully does He, here and there, raise up servants and handmaids,
to set forth his praise,--to testify of his power and mercy!

17th. An unlocked for opportunity occurred to express our interest for
two young persons for whom we had felt much when under their father`'s
roof This seemed a time of tenderness not to be lightly esteemed.
Times of instruction, we may feelingly say,
are in the hand of Him from whom all our mercies flow.
Soon after dinner we left this kind, interesting family, and little circle of friends,
with hearts united, I believe, in a bond of love and precious fellowship,
strong and lasting;
to endure so long as we continue upon the immutable foundation of Christian faith.
We came to Alcester.

18th. First-day.
In the afternoon a little company of serious neighbours sat down with us,
and we may gratefully acknowledge that it was a precious season.

19th. Sat with the heads of the family where we dined; the children were not present,
though some of them old enough.
We thought it a privation; in some visits of this nature,
we have had cause to believe that heavenly kindness was extended to the dear young children.
We returned before tea, and sweetly enjoyed the domestic comfort of the family.
How precious is Christian harmony and quietness of mind, when either the toils of life,
or the duties of a day, are drawing to a close,
without a bitter sting or restless anxiety!
O! this is marvellous mercy! soul-satisfying reality!
no idle tale! no cunningly-devised fable!
May my soul, in unison with every humble believer, bless the Lord.

20th. I felt unwell, but set out, with my dear companion and helper,
and I believe true burden bearer.
We had some distance to walk, to sit down with a widower and his sister;
our feelings were those of lively sympathy; but hope shone, as a cheering ray,
upon the way to obtain the crown immortal, at the close of the earthly pilgrimage,
when we shall no more mourn the separation one from another.
The one redeeming Lord and Saviour worketh his own righteous work, in the humble,
contrite heart.

21st. A precious meeting in the morning.
In our little evening company, we had some beautiful Scripture reading;
the concluding chapters of the Gospel of John.
How pathetic, how convincing, to minds which resist not heavenly influence,
is the language setting forth the crucifixion, the resurrection,
and the re-appearance of Christ to his disconsolate disciples;
as they were assembled together,
"`the doors being shut,`" he manifested himself in the midst.
O! how graciously were we enabled, at this time,
to comprehend something of this heavenly visitation, and to close, with sweetness,
the evening of this day.

22nd. After taking a serious and affectionate farewell of our kind friends,
and of a valuable female servant who had waited on us, we went to Warwick,
where we arrived about noon, and entered the neat,
comfortable habitation of my endeared companion and friend Hannah Evans.
We were received with smiles of welcome by her sister and faithful servant,
and are thankful for such an asylum, being weary and in want of rest.

After a few days repose at this place, my mind was unexpectedly tried and brought low.
I trust I am not apt to seek, or to enter into important engagements,
without seriously pondering the subject in secret,
ere I venture to open it even to my dearest friend or companion;
but after some time of trial, and I may say distress,
I thought it best to acquaint Hannah Evans,
that I believed I must visit four poor unhappy men,
recently committed to the county jail, for robbery and murder.
This disclosure did not surprise my friend,
for she had had a secret sense of the conflict of my mind,
and this was helpful and encouraging to me.
Thus I believe the dedicated mind is renewedly prepared for every fresh act of service,
whether it be considered little or great.
It is not having been helped in times past that will suffice or sustain;
but through self-reduction and abasement,
our confidence is afresh fixed upon the unfailing Helper
of those who seek his divine direction and guidance.

26th. Suitable arrangements having been made, my kind friend Hannah Evans,
and a few serious persons, accompanied me to the jail, where we were freely admitted.
The mistress of this vast family, Esther Tatnal, being unwell,
we were attended by her daughter,
and by the gentlewoman who was with us on a former occasion.
My mind was under a weighty concern, as we were conducted by the head turnkey,
into a clean commodious room, where the four poor men were seated on a bench.
The turnkey then left us; it was a heart-affecting moment.
First sat the desperate ringleader;
then the brother of the unhappy woman who was executed for the murder of her mistress,
and whom we visited three times within these walls;
this poor fellow seems to have been drawn in by wicked companions;
he is about twenty-five and ignorant, but not unfeeling;
he was greatly agitated on reference being made to his sister.
We have been told that his afflicted mother died soon after hearing that he was
committed under suspicion of being guilty of the same awful crime as his sister.
Another of this wretched, deluded gang, also appears young; the fourth is middle-aged,
and the father of several children; when his poor wife received the sad intelligence,
she was taken ill and soon died, leaving a new-born babe.
We understand that he was in an agony of distress, when his poor destitute,
helpless infant was brought to him, and that he said, "`Had I followed my wife`'s advice,
I should not have been in my present situation,`" They all sat very quietly,
and seemed to attend seriously to what was expressed.
We then took an affecting leave of them, under a mournful sense of human depravity.
We had an impressive religious opportunity, in the chamber of E. Tatnal,
whom I was concerned to find in a feeble state, her life being of public importance,
as well as private benefit.
She knows, however,
where to seek that which can sustain through every duty and every affliction.

28th. The monthly meeting, when Hannah Evans returned her minute.
There is nothing of which self can boast, but we can, in lowliness of mind,
speak well of the gracious Power that helped and kept us,
as we went along together in the work.
I continue awhile with my dear friend, as my strength is much exhausted.
Very tender is her care and attention, and I desire to be grateful for this,
among many other favours bestowed.

Third month 4th. First-day.
The morning meeting was small; our numbers being few, and some of these few,
not rightly estimating their privileges, possibly not fully knowing them,
often neglecting assembling with their friends for worship.
The afternoon meeting was attended by many serious persons,
who were invited to sit down with us, in our simple way.
The opportunity was a relief to some who often feel a solicitude
for the more universal spread of that righteousness which,
we read in Scripture, is to cover the earth as the waters cover the sea.

8th. Many calling to see us, it proved something like taking a solemn farewell.

9th. This morning I left the house of my dear friend and companion, Hannah Evans,
and her domestic circle,
from every one of whom I had received all the soothing
kindness and attention which my feeble state required.
I have now arrived safely at my own comfortable apartments in Dale End, Birmingham.
My heart craves a lowly, grateful and abiding sense of the Lord`'s manifold mercies.

13th. I was much gratified with the company of my dear niece M. and her husband;
they were returning from visiting their relations in the south;
it was to me an unexpected and interesting interview,
and I think it was mutually endearing; my heart owns,
and my hand records it as very precious to me;
and I felt thankful for an apartment and a table furnished with
things needful to refresh my dear relatives on their journey.
We parted, as we had met, in the sweet feeling of love and harmony,
but my mind seemed to tarry with them; they are young, and may live to see many days,
and vicissitudes.
One immutable truth will, I hope, be engraven on their hearts;
the invincible power of God, revealed by grace in the heart,
as brought to light by Jesus Christ, the Redeemer, the Saviour,
by whom we come to know our own incapacity, and our need of a new heart,
new thoughts and new affections;
a knowledge hidden from those who are wise in their own conceits.

14th. Our monthly meeting,
where I delivered in my certificate granted for the recent religious engagement.
The best report I could give was the acknowledgment of heavenly condescension;
unto which every faculty of my soul desires to be in subjection; yea, evermore, so be it!

Mary Capper to a Young Man.

Third month 27th, 1821.

Dear J. G.,--It is a precious thing to remember,
and to be remembered by one another for good.
Often times, dear youth, have I remembered thee,
and I am gratified by thy sweet token of affectionate regard toward me.
If a union of Christian good-will can afford help,
and surely there is strength in that love which wishes well to souls, thou art favoured.
Thy dear parents, thy Christian friends, all plead for thy establishment on the Rock,
Jesus Christ, the Saviour sent into the world, clothed with humanity,
to be crucified for the sin of the degenerate, human race, who died, in his human nature;
was chastised, smitten and bruised, for our sakes; bearing the iniquities of us all.
O! who shall understand these things, except the Father reveal them.
A Saviour crucified for our sins! a Saviour glorified for our justification!
Flesh and blood cannot reveal this great mystery;
but heavenly condescension opens the understanding of the babes,
the lowly and the simple in heart.
It is not by human art and subtle reasoning, but as we become subjected,
and receive the kingdom as little children,
willing to be turned from the evil of our ways, our self-will,
our selfishness in all its devices,
that we can understand the love of God in Christ Jesus.

Often I think of thee; thou art not left to grope in the dark;
the instruction of pious friends has been as line upon line, precept upon precept,
extended towards thee; and to crown all, that light has arisen in thy heart,
which is graciously given to the children of men to profit withal.
I humbly hope it may yet shine more and more, unto the perfect day;
to show thee the exceeding great love of God in Christ Jesus, who is revealed herein,
to sanctify us throughout, in body, soul and spirit.

I think of thee, I trust, with a Christian interest;
I think of thee as in the dawn of human life, full of warm energies; glowing, at times,
with vivid expectations, even of temporal enjoyments.
Thy human nature points at this,
and urges the natural heart to press after this delusive happiness;
we may look round about us,
and see to what a mournful crisis this has brought thousands
of our fellow sojourners on this side the grave.
Surely we may cherish the consoling belief,
that a gracious God is dealing very mercifully with thee;
in pity for thy immortal spirit; He sends the gentle consumption of the body,
to teach the heart wisdom.

Submit, dear youth, to the power of the indwelling Word of light and life,
that searching, quick and discerning Word,
unto which the Holy Scriptures do amply bear testimony,
and of which we particularly read in the first chapter
of the gospel records of the Apostle John.

I need not say more, and I hope I have not said too much, to testify my real good will;
thou hast indeed a place in my best love.
My heart`'s desire is,
that the end of our faith may be crowned with the salvation of our souls.
Thy dear parents have a share in my best wishes.
Farewell! whether we see each other again in mutability, or not,
I do cordially and very affectionately subscribe,

Thy friend,

Mary Capper.

To Hannah Evans.

Fourth month 23rd, 1821.

Dear and kind Friend,

Cherish not the apprehension that I have any view
of the near approach of the spirit`'s dismissal;
my hope, if it be best, is, that my feeble frame may gently decay, without acute disease;
nor would I willingly be impatient under the bonds.
Let the Lord work his own work, for my full sanctification, is my prayer.
I am recruiting, and my voice has returned, though as yet weak.

Dear E. S. with her afflicted daughter!
I often think of them.
It is in times of lowliness of mind that we have the sweetest fellowship one with another,
in a measure of that blessed union which binds and
bends the natural will to the cross of Christ.
May our abiding be here; let others soar above, or where they will!

With love, I subscribe,

Mary Capper.

To the Same.

Fourth month 29th, 1821.

My precious and endeared Friend,

United in the fellowship of the gospel,
being partakers in measure of each other`'s consolations and trials,
may our souls be possessed in patience, through drought and famine!
I dare not for a moment harbour the thought that heavenly kindness has forsaken us,
however we may be tried, tossed and not comforted;
it is doubtless a necessary discipline, a salutary chastening.
In this I take courage,
that nothing in heaven or earth can compare with a Redeemer`'s love and power,
and "`all the fitness He requireth is to feel our need of Him.`"
Are we not then, in this sense, claimants on his compassion, his mercy and his love?
Never did I more fully feel it so.

Thy friend,

Mary Capper.

To the Same.

Fifth month 28th, 1821.

My dear Friend,

Last week,
I was inclined to accept an invitation to visit a
young woman who is a member of our religious Society,
and who sometimes attends our meetings, but whose appearance, manners,
etc. differ widely from the simplicity of our profession,
and from that into which the pure spirit of Christianity leads.
This dear young woman was deprived of her mother when a babe,
left much to inconsiderate persons, and much indulged.
No wonder then, that submission to the restraining power of religion,
to the cross of Christ, formed no part of her instruction;
but the good Shepherd leaves us not thus to stray, wander and perish.
With what heavenly kindness He seeketh that which is turned
out of the way! and healeth that which is wounded!
Yea! hath long patience with that which is crooked.
In lowly reverence,
my heart ponders and admires the mercy and goodness extended to us all.

We have now an encouraging hope,
that this young person is really under a deep consideration
of things belonging to the soul`'s salvation,
and I was comforted in this little visit.
She has made a decided stand,
and determined no more to frequent the theatre or other places of diversion,
though solicited by her companions,
and even urged by those who ought to be the guardians of her youth.
Instead of the fathers, children become teachers.

I observed, and perhaps a little entered into thy mournful anticipation,
of the execution of the sentence on the three misguided, unhappy men,
who suffered on sixth-day; so abiding was the feeling, that on seventh-day,
I called upon the distressed widow and family of B. I found her sorrowful,
but not violent in the expression of her grief.
She seemed to receive my visit just in the way I could wish; she said, and I believe,
she thought, it was very kind to call upon such a poor afflicted, deserted family.

She hoped, that as her husband had told her, he had made his peace with God.
She asked if I would like to see his corpse.
I secretly started, as it were, at the idea; however, after a little pause,
I accompanied a young man, who was there, into a decent, clean chamber,
where the coffin was.
The young man appeared very serious, and drew aside the face-cloth.
The countenance was in no way disfigured.
I was satisfied in paying this little visit, as following an impulse of humanity,
and my mind seems relieved by it.
I understand the poor family are left in low circumstances; a trifle which I gave,
was thankfully received.
Farewell, my dear friend; may thy soul prosper, and be in peace, prays thy friend,

Mary Capper.

Seventh month 2nd. I came to Warwick, from our quarterly meeting at Leicester.
My strength being unequal to much travelling, I have written to my monthly meeting,
to inform my friends of a concern, which I have long felt,
to hold some meetings among various religious professors in this county, Worcestershire,
etc. as way may open for it.

4th. I attended the monthly meeting here, and Hannah Evans was liberated to accompany me,
should my own meeting concur in my view.
Thus it is comely to move in good order.

8th. First-day.
I accompanied William Whitehead and Hannah Evans to a meeting for worship,
held annually at Berkswel; the house was well filled with country people,
who behaved quietly.
Tender counsel and serious exhortation were expressed among them.

14th. I received the document from my monthly meeting.

15th. First-day.
William Whitehead and Hannah Evans accompanied me to Harboro,
a village where Friends have a meeting-house,
but no meeting had been held there for several years;
it seems to be a populous neighbourhood.
Many serious persons attended both meetings; some, I believe,
were sensible of a secret feeling, which has no fellow,
nor can the skill of man form any thing like unto it.

We had taken some provisions with us,
but a poor man`'s table was kindly spread for us with refreshments,
of which we cheerfully partook; and before we separated,
our spirits were refreshed with something better than outward bread.
The father of this family is a serious man, in the meridian of life,
but so nearly blind as to be incapable of doing anything
for the support of a wife and numerous children.
His mind appears to be favoured with submission; his eldest son, a steady,
agreeable youth, who attends our religious meetings, is an apprentice, at Warwick.

18th. A suspension of vocal utterance, with much weakness, attends me.
In unspeakable mercy, my mind is calm, and I hope to be quiet, in passive duties,
or to be willing to do what may be required, and I may be enabled to do,
from time to time.

19th. The coronation of George the Fourth.
My heart, it may be with many others, breathed an early morning desire,
that our present king may receive the anointing, not symbolically alone,
but that grace and holiness may be poured into his heart.
May his people thus pray for him,
and may the King of kings answer the prayer by a blessing upon
us all! the choice blessings of an increase of true godliness,
and of peace one with another!

20th. Health and vigour a little revived,
with a quiet hope that some prospects may be fulfilled.
My friends are very kind and helpful, for which I desire to be thankful.
The highly respected mistress of the county jail, Esther Tatnal, took tea with us.

21st. My heart was affected by the coming of an interesting old man from Harboro`',
to inform us, with much simplicity, that he had been solicited by many of the people,
to come over and invite us to have another meeting among them,
and that the people of the fields might be asked to attend;
by which I understood the labourers, particularly those now engaged in harvest work.
It is cause for thankfulness, that these,
who literally gain their living by the sweat of their brow, have a desire to know,
and to feel that mercy, that goodness, and that power,
whereby we are brought to an experimental knowledge of sanctification and salvation,
as testified of in the Holy Scriptures,
and unto which the Spirit of Truth bears witness in our hearts.
We dismissed the poor old man with some tracts, and parted in mutual goodwill.
O! it is precious when a savour of good is felt;
be the outward appearance ever so mean and lowly.

22nd. First-day.
Had a meeting at Radford,
where we were kindly and freely accommodated in a noble old mansion,
now occupied by persons who attend our meetings.
About one hundred and fifty people assembled, and great stillness prevailed.
Our hearts were thankful for such renewed favours.
I crave continual preservation, and that every act of dedication may be sanctified,
and all within me kept from presumption,
and from whatever is contrary to that which is alone our sanctification.

These public gatherings are very trying to my nature, and often reduce me to a low state,
and cause me to search, and to re-search, who hath required them;
but in my ponderings on my bed, I have renewedly believed that I must not draw back,
whatever it might cost me; my peace seems at stake, and all else I must leave.

23rd. We took tea at J. Greaves`'s, at Barford;
they very kindly permitted a large room in their house to be fitted
up for the reception of those invited to sit down with us,
in order to wait for, and to feel after,
the fresh manifestation of that heavenly Power which
alone can do our souls effectual good.
We had a large assemblage; the order and the quiet were admirable,
as the heat was oppressive.
If Jesus was in any measure exalted, and had dominion in the heart,
his glorious name be praised! but the reduction which I feel is not to be described.

25th. Much discouraged by the illness of my dear friend and helper, Hannah Evans,
as it does not seem probable that she can accompany me to a meeting appointed at Leamington.

After a time of inward breathing for help,
a strong cry or prayer was raised for entire resignation,
and a lowly calm was graciously granted.
In our little gathering at meeting, this morning,
the petition of my heart seemed answered; a sweet,
indescribable stillness clothing my spirit,
as a token of assurance that I should not be made ashamed of my hope.
It was a close trial to leave my dear friend behind; however,
a kind feeling female companion was found; we took some refreshment with a kind friend,
who is now at Leamington, with her daughters for their health.
Their appearance, their serious countenances, with their expressions of regard,
also their company and that of several others, were a comfort, help and strength to me.
The gathering was large, and a peculiar solemnity spread over us,
during a considerable time of silence.
Supplication was then offered, I hope reverently and feelingly,
after which ability was given to speak of faith in Christ, as a renovating principle,
designed to work a change in the heart, to which the Scriptures testify;
the Spirit by which they were penned, opening them to our understanding,
that we may come unto Him of whom the prophets and the apostles did write, etc.

29th. First-day.
My dear friend is mostly confined to bed, my voice is again suspended,
and my bodily weakness is great; yet in marvellous mercy,
we are kept in quiet contentment, and even, at times,
can be cheerful though we are something like a hospital of infirm, deaf, lame,
and temporarily dumb; for Hannah Evans`'s nephew is here, and is unwell;
and her sister is very deaf.

31st. Last night was nearly sleepless,
from an apprehension that I could not be easy without proposing another meeting at Leamington.
I think I do not feel so much an unwillingness to submit to such a requiring,
as a fear of mistaking any apprehension of my own for a higher impression.

Eighth month 7th. My dear friend continues so unwell
that she has consented to have medical aid.
All religious prospects seem veiled for the present.

8th. I was at the little meeting; I thought we sat in low places;
these searching times are doubtless designed for our good,
that we may become grounded in that faith and confidence which is not easily shaken,
I accompanied an acquaintance from London, to inspect the county jail;
the strangers were highly pleased with the cleanliness and excellent order of the establishment.
But few are now in confinement there; one poor man is in, for stabbing another,
so that he died.
It seems to have been an act of passion, not malice,
and the poor culprit excited our compassion,
by the deep traces of sorrow in his countenance, though he said little.
We sat down with him, and I believe did enter a little into his distress;
it was affecting to witness, but less so than the careless manner of some,
who appeared unconscious of the misery consequent on sin.
Escape from confinement, too often seems the main object with these poor creatures.

12th. First-day.
I was at both meetings,
where we were favoured with some renewed extension of heavenly good;
also in our evening reading and retirement in my dear friend`'s chamber;
she seems to be recruiting.

14th. A thankful and contriting sense of mercies received, continues to cheer,
even under the sackcloth that covers some of our spirits, when, from day to day,
we are led in a way that we know not, and hidden,
inexpressible conflict is our allotment, doubtless for our farther purification,
being encouraged to believe that we are branches engrafted into the living Vine.
We know that the husbandman purgeth the fruit-bearing branch,
that it may bring forth more fruit.

16th. Our dear invalid came down stairs.
The mind seems to have no better anchor than resigning all unto Him who formed us,
and who knows us altogether as we are.
None other can give patience, calmness and submission, to the poor conflicting spirit;
this my soul does witness, in self-abasement.

19th, First-day.
My dear friend able to go to meeting this morning,
and in a feeling manner to bear testimony to that Power, which, as it is received,
cherished and obeyed, keeps the soul alive in times of trouble.
In the afternoon, we went with her brother Daniel Evans, to his habitation,
Goodrest Lodge, which is on a large farm; in the evening,
we had a meeting with a considerable number of servants, labourers,
etc. which ended well.

20th, After the Scripture reading,
something was expressed by way of stimulating the
mind to meditate upon Scripture doctrines and records,
that we may receive a right understanding of them,
and guard against our own constructions or interpretations.
Daniel Evans conveyed us to Leamington, where notice had been given of a second meeting.
Many came to it who were of a serious description; and it may be,
the design was answered, and the sacrifice accepted.
We returned to Warwick in peace;
my dear companion not having materially suffered
from the exertion and the excessive heat.

22nd. At the small meeting, a precious time of refreshment,
of spiritual feeding upon that which is meat indeed, and drink indeed!
In the evening, a meeting was held for the servants of Friends, young persons, etc.

24th. Mournfully affected by the information, that, at the assizes,
several criminals were condemned to suffer death; among them the unhappy murderer.
Much feeling thoughtfulness came over us,
as to the desirableness of visiting him or his companions;
but after a time of deep consideration,
and being satisfied that our own will was given up,
though we were not disposed to proceed lightly in so important a thing,
we were favoured to rest, in a calm and peaceful belief that we were excused.
Yet Christian concern, with a tender breathing of spirit,
that mercy might be extended to these our unhappy fellow creatures,
was cherished in our hearts.

25th. We were kindly received, at our former quarters, at Alcester.

26th. First-day.
In the morning, several strangers were at our meeting; in the evening,
in consequence of a general invitation having been given, a very serious,
well-behaved company attended.
It is gratefully to be acknowledged, that at this day.
Christians of different names, and in various ranks of life, can cordially meet together,
in our meetings for worship in a Christian spirit,
where little or nothing presents to occupy outward observation.
That a large, mixed company, sometimes incommodiously seated, should mostly be so still,
so serious, during a time of silence, is admirable;
and not a little consoling and helpful,
to the rightly engaged and truly spiritually minded among us.

+++[+++Respecting this evening meeting, her companion and friend, Hannah Evans, thus writes,
"`My dear friend, Mary Capper, was greatly favoured; she was largely engaged,
in gospel love, both in testimony and supplication; it was indeed a memorable time,
and brought to my remembrance ancient times,
when the power of the Highest so eminently overshadowed the assemblies,
to the convincement of many; and I was ready to say in my heart,
surely some good will be experienced from this opportunity.`"]

28th. Had a meeting with some of the manufacturers of needles, who are employed here.
The quiet behaviour of all was very satisfactory,
and we hope the time was not unprofitably passed.
Marvellous is the mercy that would gather the wanderers, and the forgetful ones,
into the Shepherd`'s fold, and protect them from the destroyer.

29th. A favoured time at the meeting.
In the afternoon came to Evesham, and were, as usual,
cordially received by Richard Burlingham and family.

Ninth month 2nd. First-day.
In the evening, we had a large gathering of labouring men,
and of lads employed in nail-making.

3rd. We took tea at the next house,
and had a lively remembrance of having been favoured together some time back,
with a precious sense of heavenly Goodness; since this time,
the family have been tried by the long illness and death of a sister,
in her twenty-second year.
She suffered much, from pain and weakness, and from reflecting upon mis-spent time,
and talents unimproved;
but she was favoured with an evidence of the extension of redeeming Love,
and closed her day in brightness.
Some of her remarks were read to us this evening,
and a humbling sense of the mercy which follows us all our lives long,
drew our minds into stillness and much sweetness.
A little expression followed.

5th. Attended the meeting at Bewdley in the morning; and in the evening,
had a very large one at Kidderminster; about fourteen hundred persons present,
many of them employed in the carpet-manufactory.
At the close of the meeting, many were anxious to shake hands with us,
and blessings were pronounced upon us.
In condescending mercy, the evening closed peacefully,
which compensated for bodily fatigue.

6th. Exhaustion kept me late in bed; we were permitted to be quiet,
and sweetly retired in the family till evening,
when we attended a meeting appointed for the neighbouring poor, at Bewdley;
the feeling when among them was very precious.

12th. The quarterly meeting at Ross was well attended; many young persons were there,
whose serious countenances were cordial to their well-wishers.
I believe it was a time of spiritual refreshment.

16th. First-day.
In the morning meeting, renewedly confirmed in that faith, which,
if we were but humble enough to submit to its operation,
would work by love to the purifying of the heart.
In the afternoon many of the neighbours sat down with us, by invitation,
and I think it was a time of profit.
I am satisfied that the Divine will is,
that we should come to a more perfect knowledge of the exceeding riches,
through Christ Jesus, which are in store for those who patiently seek,
and faithfully obey, the revelation of the Spirit of life and truth,
in the secret of their hearts; and who rest not in outward and visible signs,
which fall short of the thing signified.

17th. A day of social enjoyment with our friends.
This is very gratifying, in its right time and place; the mind being at peace,
though in a lowly state, and being resigned again to suffer,
according to the Divine will.

18th. We left Ross, after being enabled to express, in the family,
what relieved our minds,
and contributed towards our looking homeward with peaceful hearts; not in exultation;
ah! no;
but in humble thankfulness for the mercy and condescension
that kept us from wilful disobedience,
and has brought us, thus far, without condemnation.
O! it is an unspeakable favour to know, and freely to acknowledge,
the heavenly power that keepeth the heart from being overcome of evil.

19th. Sat with the few friends at Alcester in their meeting,
which was a precious time of religious retirement, and tenderness of spirit.
O! that the children of men, the world over,
were brought into a willingness to wait in stillness,
that they might know the power of godliness, and go on from stature to stature,
increasing in holiness; that sin and transgression might in very truth be finished.
We considered this meeting (in which we had sweet unity with the truly waiting,
lowly spirits,
who have no outward teaching to depend upon) as a gracious
close to the religious engagements which we had in view,
when we respectively left our habitations.
Unto our heavenly Guide, our holy Teacher, our alone effectual Helper,
and merciful Keeper, be all the praise!

To Hannah Evans.

Birmingham, Tenth month 3rd, 1821.

My very dear Friend,

That we have thought of each other, and moreover, with the best ability that we have,
have prayed for each other, is an assurance consoling to my feelings;
thus our separations are measurably sweetened,
and our hearts encouraged to believe firmly, and to watch constantly;
so that whether together or apart, our confidence in Him who is our Rock,
may be sure and steadfast.
On entering my parlour, it seemed lonely, but peaceful,
and this is what our souls thirst after.
I hope we have both felt thankful for the favour of being led along
in that path of dedication which opened before us,
and for being brought back to our habitations without any sense of condemnation.
My spirit was much tendered,
and my heart inexpressibly affected with the consideration of these mercies,
as I sat among my friends at meeting this morning.
O! the heart contriting sense of heavenly goodness is no cunningly devised fable,
but a blessed reality, sometimes granted to the poor, the humble, the obedient mind.
A taste of the precious favour is sufficient to encourage
the believing soul still to press onward,
and not to tarry in the dark, dreary valley of perplexing doubts and fears.
Farewell, my precious friend! my heart salutes thee.

Mary Capper.

To the Same.

Eleventh month 15th, 1821.

My very dear Friend,

The first thing that arises to communicate is, suffer not my length of silence,
at any time, to cause a crooked thought to perplex or distress thee.
"`Fervent prayer and firm believing,`" are far better occupations,
in times of doubt and uncertainty.
Thou knowest we love each other, or this freedom would not be comely.

I receive very affecting accounts of the increased weakness
and protracted sufferings of my dear sister Anne Capper;
at the same time it is cause of gratitude,
that her faith and her prospects of glory are so lively,
and her rational powers so strong.
I think much of her.

+++[+++Her sympathy for this beloved sister,
was soon to be exchanged for thankful rejoicing for her deliverance.
Anne Capper peacefully breathed her last, on the 19th of this month.^
footnote:[See an account of her in "`Piety Promoted,`" 11th Part.]
Upon this occasion Mary Capper wrote to the family as follows:]

Warwick, Eleventh month 21st, 1821.

My precious Relatives,

The account of the release of my dear sister reached me this morning.
Very calm and lowly was the clothing of my spirit,
with an assurance that those who have passed through many tribulations, and who have,
through faith, endured to the end, cease from their labours,
and enter into their Master`'s rest, pure and undefiled!
Ah! my brother; ah! my sister;
how often have we conversed on subjects connected with this incomprehensible theme!
My heart retraces the longing, thirsting desires of our souls,
even while clouds and fears and distresses intervened.
The veil is now rent, or drawn aside, to those who are gone from works to rewards;
to us who remain, surely it is a stripping season; we must endure a little longer,
I hope in patience.

A bright, instructive example has been set before you, dear children,
of what the Lord does, for those who seek Him and obey Him.

Farewell, affectionately,

Mary Capper.

To Hannah Evans.

Severn House, Twelfth month 3rd, 1821.

My dearest Friend,

I feel a reverential thankfulness, that in thy present tried, low state,
heavenly mercy so evidently sustains thee through all.
May we cherish the blessed hope that heavenly goodness will be with us all our life long!
Nothing short of this can keep the soul in patience, and give resignation,
when all visible things speak, as it were, desolation and breaking up.
What a stay to the poor mind to have an immutable foundation;
even the sure mercies of God in Christ Jesus!
A life of ease, and enjoyment of earthly things,
is in no wise desirable to the soul that has had a taste of the pure,
sanctified joys of redeeming love.
Hold fast thy lowly confidence, my precious friend;
and may the great Restorer of all righteousness be with us,
at all times and in all places!
Do not exert thyself to write; I do not desire it.
I am well satisfied that we have closely-attached hearts,
and I trust we are both travelling on towards the end of all sin and sorrow;
no more to feel sickness, cloud or doubt, or even animating hope; but to enjoy light,
life, and purity forever!

Mary Capper.

To the Same.

Birmingham, First month 31st, 1822.

My very dear friend, and fellow traveller towards a land of promised rest;
where human frailty, sickness, sorrow, and perplexing things,
arising from ourselves or others, will no more offend.
Let us press on; not as having yet attained, but looking forward,
with strong faith in that invincible Power,
whereby all our spiritual enemies may be subdued; yea, Satan trodden under our feet.
Peradventure this may not be shortly, but surely, in due time;
this my heart takes courage in believing;
and the more we press after the pure river of life,
the more we shall drink of its refreshing streams;
nevertheless there is a time to be athirst,
in order that we may know how to estimate that which ministers refreshment and strength.
Sound faith and love, patience and perseverance,
are the cardinal points of a Christian traveller,
after boxing the compass from side to side!

To the Same.

Birmingham, Second month 19th, 1822.

My dear Friend,

I cherish the gladdening hope that thou wilt be here ere long,
and am thinking of having a cleansing from the external defilement of smoke,
etc. that no outward appearance may affright thee.

I think my soul longs for inward washing, purification,
and entire redemption from all that defiles the inner temple of the heart,
that the best of friends may dwell there.
This entire sanctification through the Holy Spirit, how wonderful,
how important! yet how neglected by many! and how slow in
its progress when we think we are earnestly desiring it!
Day by day, it seems in my view a marvellous work; and though at times I am cast down,
I am not in despair,
for I know in whom I have believed although for a
season He seems to hide Himself from our view,
and then our hearts are sad; yet, are we not kept from presumptuous sins, meek and lowly?
O! my precious friend, surely with some measure of experience, we can say,
it is the Lord`'s doing; for our souls have been sore vexed.
Thus I believe, in our different allotments, the Father of mercies, God only-wise,
permits his children to be exercised and disciplined.
To be humbled, and to keep humble, is not the work of human prudence.

My dear love is to you all, as fellow travellers, pressing after the mark.
Doubtless we often tenderly sympathize with each other;
we have all equal need to watch and pray continually;
though there is a difference in circumstances, situations and tempers;
nevertheless all is summed up in this, a Saviour or I die! a Redeemer, or I perish!

Mary Capper.

To the Same.

Key-Hill, Third month 12th, 1822.

My affectionate Friend,

I have only been out once since I entered this hospitable dwelling,
but my cough is much relieved.
I think of returning home tomorrow; our select monthly meeting is to be in the evening;
a poor little few! but what can we do better than
desire to keep our places in humility and faithfulness?
the Power that has raised the few labourers can raise up and send more,
hew and when he sees meet.
I believe it is safer to look to the fountain than to the streams; yet,
as the streams flow pure, and unite, they may form a broad river.
Thy tender love and precious sympathy suggest something like this, of an encouraging,
cheering nature to my exercised spirit.
I know something of depression that seems to weigh me down;
my heart breathes a desire that we may yet be kept from falling,
and finally be made conquerors, through a Saviour`'s redeeming, all-vanquishing power.

In tender love,

Mary Capper.

Sixth month 12th. After secret prayer for right direction,
and that a plain path might be opened before me,
I ventured to inform my friends at the monthly meeting,
that I had a view of some religious services within the limits of our quarterly meeting.
In reverence, my spirit was bowed, and I believe there was a fellowship of feeling,
and a desire to liberate me to pursue the path of apprehended requiring.

I think my heart`'s desire is that all my steps may
be ordered by that Power which alone can keep me,
so that the evil one harm me not, and that no harm be done by me.

I passed some days quietly, in my own comfortable apartments,
where I have all the accommodation I desire, and which I hope I willingly leave,
when called upon so to do.
I visited some poor neighbours, gave away tracts, wrote letters, and arranged all,
so as to leave with calm satisfaction.

24th. Lodged at Sarah Gillett`'s, at Shipstone.

25th. My dear friend, Hannah Evans, from Warwick, joined me,
and we went to the select meeting.
Our number is small, nevertheless we may gratefully acknowledge,
that through divine mercy, we maintain the unity of the Spirit in the bond of peace;
though we often sit as in the valley of humiliation, and as in solitary places.
The reports given by our friends who had been appointed to attend the yearly meeting,
though expressed in few words, were very satisfactory and animating;
somewhat comparable to the odour of precious ointment, descending to the outer skirts.

26th. At the quarterly meeting, we had line upon line, and precept upon precept.
In the evening, we came to Sarah Lamley`'s very pleasant dwelling at Tredington.

27th. William Lamley kindly conveyed us to Warwick, where, once more,
I was favoured with a peaceful feeling, under the roof of my affectionate friend.
It is a peculiar favour to be united in spirit, while we feel our own entire dependence,
at all times, upon an invincible, though to the natural eye, invisible Power;
this is more precious, and more to be desired,
than any other gratification we can have in being together.

+++[+++The following was written, about this time, to her nieces,
who had recently lost their last remaining parent.]

Sixth month, 1822.

I feel tenderly for you, my endeared nieces,
as being yet comparatively in the morning of your Christian pilgrimage, and natural day;
be thankful that you can believe,
there is a secret gracious Power that keeps us from hardness of heart,
and works in us and for us that sanctification which comes by the revealed love of God,
in the manifestation of Jesus the Redeemer, through the Holy Spirit.
Keep lowly and watchful; that your steps may be rightly ordered,
and the end will then be peace.
Temptations gradually lose much of their power.
Merciful kindness places the poor dependent believer, after a time of probation,
in a state of comparative quiet,
wherein the fulfilment of the will of a faithful Creator is his paramount desire.
I wish thus to express myself, with real humility and caution;
nevertheless this is my present view of Christian advancement;
and happy are they who hold on their way, through every successive stage,
and persevere through every trial.

I passed through some exercise, in the prospect of leaving my quiet habitation,
to be engaged for an uncertain length of time; but necessity seems laid upon me;
the rest I must leave.

I hope your visit to Sunderland will be mutually beneficial and comforting.
I have twice read the very interesting testimony respecting your precious mother;
and though it appears long, I do not know what part could well have been omitted.

What a life of extensive usefulness!
What unfeigned love, and what activity, to serve her fellow-probationers,
under every name and circumstance!
Above all,
what an exemplification of that which the Spirit
of Christ Jesus can work in the human heart! subduing,
sanctifying every thought and imagination; giving the victory over all,
with a full sense and acknowledgment, that not unto us,
but unto his Name belongeth the glory!
O! the humility, the wonderful patience, granted to your precious parents!
May I reverently pray that our end may be like theirs! or,
in the language of your redeemed mother, simply petition, "`Thy will be done!`"
Here I desire to stay my mind, and be at peace.

Once more, my endeared relatives, may it be well with you in life,
and in the hour of death, fervently desires your aunt,

Mary Capper.

Seventh month 3rd. Monthly meeting.
The meeting for worship was to me a time of deep secret feeling.
My dear friend Hannah Evans obtained leave to unite with me in my engagements.

4th. We visited two females and their brother, who are in the county prison for debt;
he is in a very suffering state, from a disease which is increased by confinement;
they have been in prison more than two years, and have little hope of liberation.
We pitied them much; especially as one brother has already died within the walls.

5th. We again entered the prison doors, not unfeelingly, nor in a light mind;
we first had a private interview with a poor unhappy man,
committed for killing his own son.
He said it was done in a fit of unguarded passion; he appeared sorrowful,
and spoke of his guilt with mournful self-condemnation; also with particular feeling,
of his aged mother, who lived with him, wishing me to call on her.
It was truly affecting, and tears of sympathy flowed.
William Whitehead and Esther Tatnall were with us;
the poor man was grateful for the visit.
We afterwards sat with the women; it was a time of serious feeling,
and of solemn supplication.

7th. First-day.
We held two meetings for worship, at Harboro`', in a meeting house belonging to Friends;
both gatherings filled the house.
The clergyman of the parish said that he would give notice;
and at the close of the morning meeting,
his two very agreeable looking daughters came up to us,
and invited us to dine at their father`'s, saying he would be pleased with our company.
This is worthy of grateful remark, as manifesting the diminution of prejudice;
and I think we should be thankful for every increase of Christian good will,
and in true lowliness of heart, render the praise where alone it is due.

Unprofitable indeed is the labour of the servant, unless the Lord grant his blessing.
May we watch and pray continually, lest, while we seem zealous for the good of others,
we neglect our own hearts, and evil find an easy dwelling there!
My spirit is often humbled under a sense of the possibility of thus falling,
even after my heart may have been enlarged in love to my fellow creatures,
and my lips opened, in some measure to set forth the love of our heavenly Father,
and to invite sinners to repent, and to accept salvation.
Much lowliness, and oft-times fear, have clothed my spirit.

8th. A calm day, under the roof of my dear friend.
We have in contemplation another visit to the jail.

9th. William Whitehead accompanied us to the prison, where we always gain easy admission.
We sat with the men and boys in the chapel, about one hundred and fifty in number;
it was affecting to see so many lads; some of them scarcely eleven years old,
who had been guilty of theft.
Poor S. D., committed for the murder of his son, still excites our compassion,
by his mournful countenance.
We have reason to think that our visit was satisfactory.
The improvement in the discipline of the prisoners is very great;
there is wonderful order, obedience, and cleanliness.
The women and lads are employed, and many of the men knit, or stitch patten ties, etc.
We left them with the heart-felt desire that their future days may be their best days;
that, in repentance and amendment of life, they may know the way of peace.

10th. Our little meeting was a time of sweet contrition; with a precious,
consoling belief, that the Lord is on the side of those who wait upon Him,
and who can truly say that they have none whom they desire in comparison of Him.
We afterwards called upon a friend in trouble.

To Richard and Elizabeth Cadbury

Warwick, Seventh month 10th, 1822.

My dear Friends,

It seems long since we parted.
My chief aim and desire is, to fill up whatever may be required in the allotment assigned.
I seem low and dependent every way; my health, my powers,
depend upon renewed strength and mercy every day.
We have had some heart-tendering opportunities in the county jail.
The worthy, kind,
and seriously-minded mistress is particularly prompt
to promote whatever may tend to her own information,
or to the good of the great household.
She may be considered a blessing in her important station;
she carries authority in her solid, yet gentle manners and countenance;
and seems to be loved as well as obeyed.

Mary Capper.

11th. We were conveyed a little way into the country,
to see some persons who have separated themselves from the
religious Society of Friends and joined the Unitarians,
and who are bringing up a large family in this way.
Much Christian solicitude has been manifested by divers Friends, toward them;
the parents more especially, as being responsible for the instruction of the children.
Little good seems, at present, to result from the care repeatedly extended,
as respects the ground and foundation of faith.
There seems to be a subtlety in argument,
and in reference to certain Scripture testimonies, which, as yet, fortifies the heart;
and if we are right who have strong consolation in believing on Jesus,
as a Redeemer who shed his blood, a ransom for sinners,
a propitiation for the sin of the world, our Mediator and Advocate with the Father,
then there surely must be a veil over the spiritual understanding of these seceders;
and nothing short of heavenly Power can convince and convert them.
To pray for one another, with the best ability that we have,
is a duty ever to be cultivated.

13th. Called on a poor old woman, who has for some years been in outward darkness;
her placid countenance and lively sense of mercies received,
in the midst of privations and sufferings, seemed to do us good,
and to confirm our belief,
that the Fountain of pure light and of consolation is revealed, without partiality,
in the seeking, humble heart.
This belief is precious and cheering.

14th. First-day.
William Whitehead kindly accompanied us nine miles to Berkswell,
where Friends have a meeting-house.
Very few of our own Society met us;
it would have been pleasant if more had inclined to come,
to countenance and hold up the hands of those who
are concerned to labour for the spread of religion.
The house was crowded, and many stood without; notwithstanding the heat and the pressure,
their behaviour was becoming; every serious mind may be encouraged,
and thankfully acknowledge that there is an evident
improvement in the manners of the people generally,
particularly observable when invited to sit in our meetings,
where there is little to attract outward observation.
Their stillness and sobriety are instructive to those who are engaged, in Christian love,
to visit them.
This opportunity was, I believe,
favoured with that condescending mercy that is both ancient and new.

The meeting at Warwick was postponed till evening,
and was attended by a considerable number of the inhabitants,
I hope it was a profitable time of religious fellowship; in the solemn feeling that,
with our Heavenly Father, high and low, rich and poor,
are equally the objects of his tender regard, and matchless love.
How marvellously does the Almighty Father remove every narrow prejudice,
cause discouragement to vanish,
and from time to time open the understanding in things belonging to the soul`'s salvation;
drawing aside the veil of human ignorance,
and sometimes opening the lips to set forth a little
of what the Lord of life and glory hath done,
and in his faithfulness will do, for those who truly seek to know and to obey Him!
I thought, as far as it concerned myself,
that I was sweetly compensated for exertion and fatigue.

15th. A day of rest; with little interruption,
save what often occurs in the necessary attention to the common concerns of life;
and these concerns may frequently be numbered among the things which may
tend to the furtherance of our growth in Christian experience.

16th. We came to J. B. Lowe`'s, at Eatington; a retired spot.

18th. An instructive time at meeting.
Sat awhile in serious retirement with W. B. in his almost solitary dwelling.
We have some ground to believe that these visits from house to house,
with a feeling desire after that which is of more
value than temporal prosperity and ease,
are mutually profitable; bringing into view, and into deep consideration,
the state of our own hearts, and how we stand,
in the all-seeing eye of a faithful Creator.

19th. Visited a poor widow in affliction; her calm resignation was striking;
also her confidence that her heart will be sustained in peace through all; and that,
if bread and water only be her lot, she shall be content,
and commend her family to the Lord.
Surely this is the blessed effect of the power of religion on the mind!
We called on William White, a Friend far advanced in age; he lives in great simplicity,
with a grandson who works as a shoemaker; without female aid, the house is comfortable,
neat and orderly.
The grandfather is provider and head cook,
and they appear to eat their bread in quietness, and to be cheerful.
It was very pleasant to see a youth, of really pleasing person and mariners,
contented to follow a humble occupation, in a retired village,
and to live in a very lowly way, with his aged grandfather.

20th. After a day of retirement in spirit, and of secret prayer for renewed direction,
and continued help in our Christian movements, I thought we were favoured,
in sitting in the evening with J. L. and his wife, with a sweet and encouraging sense,
that the stream of heavenly life flows soft and sure, to the refreshment of the retired,
waiting soul; though we may again and again thirst and be weary.

21st. First-day.
In the morning, sat the small meeting.
The pure Fountain of life is open for the few, as freely as for the larger number.
In the afternoon, many serious persons came, by invitation, to sit down with us.
We were favoured to meet and to separate in much stillness;
the meeting closed with prayer.

23rd. Sat with the only two families, at Tredington, who profess with us,
and were favoured to feel that contriting Power which is ancient and new.
Some part of this day was agreeably and profitably spent
in reading some very interesting writings of Friends,
and their sufferings for the testimony of a good conscience,
and the promotion of universal righteousness,
in the time when Friends were first gathered to be a people,
conscientiously separating from established forms, and with upright hearts,
seeking to possess the substance typified in the shadows of good things to come.

24th. At meeting at Shipston, and had a family sitting,
wherein we were unexpectedly favoured with a more
than common sense of the extension of heavenly love;
for which condescension to our low estate, humble thanksgiving was rendered.

25th. After breakfast and reading, we had a profitable pause;
some encouragement was given to dedicate a portion of the morning to retirement,
prior to entering into the occupations of the day.
For men of business this is especially necessary,
in order to keep the mind calm through the perplexities which may occur;
without such a stay the mind is in great danger of being estranged from God and godliness.

26th. Called on several; one large family where the mother was deceased.
It was pleasant to see the young people seriously disposed;
encouragement flowed toward them, to keep out of the mixtures,
to be content in a plain way of living, and to seek the Lord`'s blessing,
which is the best riches.

27th. A day of close engagement.
After dinner we went to Stow; and on to Morton,
to call on a poor woman who was born and educated in our Society,
but who married out of it.
Friends had visited her frequently, and kindly cared for her.
When we entered the little cottage,
our surprise was great to find that the poor woman had breathed her last about midnight;
and that on third-day (this being seventh,) her husband, on coming out of his garden,
where he had been digging potatoes, fell from his chair and expired, without speaking.
It was an impressive scene,
to behold a husband and wife thus lying lifeless in one chamber;
they were about seventy-seven years of age,
and had lived harmoniously together about fifty years.
We sat down with a few of the kind neighbours, who had waited upon this feeble pair.
The little religious opportunity was consoling;
for a calm belief seemed to clothe my spirit, that,
as their lowly hearts had been united in life, so, in death,
their spirits were not separated.

28th. First-day.
Went to meeting at Stow.
An invitation was given to the townspeople to sit down with us at four o`'clock.
It proved a crowded company, but very orderly, considering the heat, thunder and rain.
It was an instructive time.
After meeting, my feelings were closely tried, in having to give up my dear companion,
who was obliged to return home; however, we desired properly to submit.
I felt lonely, though my mind was favoured with quietness; and this wonderfully sustains,
through whatever comes upon us.

29th. Took an opportunity of expressing some tender counsel and encouragement,
to the elder daughter of the family where I am staying;
her peculiar circumstances call for sympathy.
Those who dwell at ease, and are surrounded with accommodations,
little know the difficulties that many large families have to encounter.
Attended a very large meeting, at Stow, on the occasion of the burial, in one grave,
of the poor man and his wife, who died at Morton.
Vocal labour seemed called for.
It was a time of no small fatigue; but this is the thing least to be considered,
if the blessed Name be exalted.

Eighth month 4th. Went to Arnscot, where a Friends`' meeting is annually held;
it was large.
My mind was in a tried state, though mercifully kept patient;
and I was thankful for the labours of some dear friends,
who had to speak of the efficacy of the grace of God,
revealed in the heart to cleanse from all sin, when believed in, cherished, and obeyed;
and purifying from evil thoughts, words and works.

Christ died to save us from our sins, and not in them.
O, the importance of every heart coming to know Jesus, in his spiritual appearance,
sitting as a refiner with fire and as a fuller with soap!
It is mournful that many religious professors seem to remain at ease in a nominal profession;
with but little of that sense of sin, in all its deceitfulness,
which is discovered by the shining of the true Light in the heart.
Many seem content to be thought moral and respectable;
but this falls far short of coming unto Him whose gracious
consoling invitation stands on Scripture record,
"`Come unto me, all ye that labour and are heavy laden!`" with the precious promise,
that they shall find rest.
All other rest is polluted.

As I was bereft of my companion, dear Sarah Lamley kindly joined me,
in sitting down to enter into feeling with a man and his wife who came from a distance;
the poor woman married out of our religious Society,
wherein she had her birth and education.
By this step she and others who have come under my notice,
have brought upon themselves many distresses which they might have been spared.
We had another sitting with persons similarly circumstanced,
having a large family to bring up.
We endeavoured to impress upon them the necessity of seeking the Divine blessing,
and that the parents should encourage one another to live a religious life,
and to be conscientiously diligent in attending some place of public worship.

6th. At Radway, I again met my kind and endeared companion, to our mutual comfort.
The monthly meeting was held here,
and afresh we had to acknowledge the mercy manifested toward the children of men,
and toward our little religious band, though scattered up and down,
here a few and there a few, with many deviations from rectitude.
Mercy is still graciously extended towards us, as a separate people,
and still preserves faithful standard-bearers,
both in advanced age and among the rising youth, even in some solitary situations.
We have sweet, clean, comfortable accommodation at the cottage of H. Summerfield,
a wonderfully active, kind friend, in very advanced age, who has, for many years,
gained a comfortable income by her industry.

7th. Attended the meeting, paid several family visits.
There is much outward simplicity in this little group of cottagers,
and in their rustic manners; something to be learned, and yet something wanting;
viz. more earnestness, in many, to experience the work of sanctification.

8th. A pleasing young friend procured a little cart, to convey us about three miles,
to the village of Tyso, where we arrived safely, after jumbling over very rough roads.
We sat in one family, and then called on another, consisting of a man,
his wife and three children, in a poor habitation.
We thought ourselves well repaid for our exertions,
for there seemed to be peace in the dwelling, and heavenly kindness near us.
These are precious feelings, and I think we are made thankful for such favours,
extended to ourselves and others.

10th. Had a very comforting time with dear Hannah Palmer, in her eighty-ninth year;
her natural and spiritual faculties lively.
It was inexpressibly sweet and refreshing to feel an undoubted evidence,
that there was no cloud in her way; nothing to separate the soul from God;
no distrust or unbelief; but confidence that, by the new and living Way, Christ Jesus,
there was, and is, free access to the Father.
Marvellous mercy! the work of redeeming love!
We took tea with a widow who has many trials; the little circle of Friends,
in this retired, quiet spot, are not without their distresses.
It is well to visit such in their own dwellings;
and possibly some good may arise from passing a few days among them.
This evening we had a precious little sitting with a poor man,
at the close of his hard day`'s labour, in the harvest field;
his spirit was so tendered that the floor was wet with his tears.
Ah! these are times of special favour.

11th. At meeting in the morning we found the necessity of deep labour,
and of diligent watchfulness,
in order to experience the arisings of the fresh spring of life.
In the evening we had a crowded meeting of the villagers.

12th. We left our very kind, aged friend, H. Summerfield, with affectionate feelings,
and in a grateful sense, that merciful condescension had been with us,
under the humble roof of this dear friend,
whose earthly pilgrimage seems to be drawing to its close.

13th. We were conducted to Campden,
where we were cordially received at the comfortable habitation of Mary Bevington.
She is a widow, in weak health and advanced life,
yet freely disposed to entertain and to help those who, she believes,
are bound to promote the cause of righteousness.
As our time here was likely to be short, it seemed to impress our minds,
that some steps should be promptly taken for having an evening meeting with the inhabitants;
this our kind friend quickly promoted; the Town Hall was proposed, easily obtained,
and a carpenter set to work; so that a neat and commodious room was soon fitted up.
It was a large meeting, but very still;
and we had cause to be thankful for the help received,
enabling us to do what seemed required.

+++[+++Mary Capper`'s humble-minded companion, Hannah Evans,
having left a few memoranda respecting this religious engagement,
and particularly mentioning this meeting at Campden,
the following remarks are extracted therefrom,
as showing how these labours were appreciated by those who witnessed them.]

Although I kept no journal, while I accompanied my endeared friend Mary Capper,
in her religious visits to Friends in the South monthly meeting of our county,
yet I can now, after the close of the work, say,
that my heart was often clothed with thankfulness,
and I am at this time humbled under a sense of the weakness and
poverty which I often felt when sitting by this dedicated servant;
yet I trust I was not an idle spectator,
but enabled secretly to unite with my dear friend in the important work,
with earnest desire that I might be enabled to be a help-meet,
and bear part of the burden.
I did often thankfully believe that she was greatly favoured,
and instructed to divide the word aright;
particularly so in a public meeting held in the Town Hall at Campden;
where the Most High was graciously pleased to honour us with his presence.
My beloved friend was engaged, for nearly an hour and a half, in a beautiful testimony;
during which time I seemed, in an uncommon manner,
to be in the enjoyment of heavenly Goodness,
so that I thought it something resembled a Pisgah
sight of the holy land of rest and peace,
in a way rarely known by me.
The people behaved with great solidity,
and I thought the opportunity was cause for thankfulness.

+++[+++To return to Mary Capper`'s diary:]

Eighth month 14th. We had a time of lowly reverence of spirit, with the dear,
humble-minded friend, under whose roof we have been kindly entertained and refreshed;
soon after we took our leave, apprehending it may prove a final farewell.

15th. We came to Long Compton, and were but a small company at meeting;
but we had afresh to experience that the spirit of the contrite ones is,
from time to time, revived;
so that it remains to be a blessed thing to be the Lord`'s poor.

16th. We visited an aged, infirm couple, in a very poor dwelling; we may observe,
that when individuals among us lightly esteem their privileges,
and turn their backs upon them, in the early period of life,
their advancing years are often marked with distress,
and the want of those comforts which they might have had; nevertheless, in this case,
we had to admire the enduring mercy, extended even to old age;
the cheering rays of light and of saving love, breaking in upon them,
as in the eleventh hour, in their poor desolate dwelling; this is marvellous love indeed!
We afterwards visited another of these poor forlorn ones, in his old age.
He lives with a daughter-in-law, who has a large family,
and who seemed to have her hands and her mind full of cares and encumbrances.
She looked rather shy upon us at first; but after a little free discourse,
and some little acts of kindness, the clouds began to dissipate,
and I felt a flow of tenderness toward her; viewing her as encumbered with many things,
and possibly unacquainted with "`that good part,`" needful for keeping the spirit calm,
and all things in subjection.
After a time, she was informed, that the object of our visit was,
to sit down quietly with her father-in-law, who was present;
and she was invited to sit with us, which she readily did, with several of her children.
The free and unchanging love of our heavenly Father broke in upon us.
Wonderful is his mercy and goodness!
The dear children were quiet, and the poor woman melted into tears.
We left her under much feeling, and upon our telling her,
that there was likely to be a meeting for the inhabitants on first-day evening,
she said she should be glad to attend.
Thus can the precious love of God soften obdurate hearts!

In the afternoon, we had a time of sweet retirement with James Bissel,
in his humble dwelling, where he has lived in solitary widowhood upwards of twenty years;
he is eighty years old, and his children have settled at a distance.
It is admirable to witness the peaceful content, the comfort, neatness and order,
of some of these solitary ones; and how little suffices for nature`'s real wants,
where the mind has happily found the true anchor.

17th. I feel both weak and low; but through adorable mercy, I still go on,
from day to day, in bowedness of spirit, I trust, so as to bring no condemnation,
nor grieve the pure mind in any.
If this be the case, I may be content, and render thanksgiving.

18th. First-day.
In the evening we had a very full gathering; there was seriousness and stillness,
but there did not seem to be the prevalence of that Power which contrites the heart,
nor the openness to receive its influence, that we have known in some places.
The cause we desire to leave, except as it induces a close heart-searching for ourselves;
this secret work is, I am aware, needful; both when at home, and still more so,
when moving from place to place, as we are at present engaged in doing.

22nd. We came to Brails; both of us poorly, and low in mind;
yet not without a cheering hope, that by and by, it may fare better with us,
and that we may be comforted with a little of that comfort,
wherewith we have sometimes been enabled to comfort others.

23rd. We met, a large family party, at breakfast.
One of the little boys is about to leave home for school; we had a sweet time of feeling,
with him and his brother who remains at home in delicate health;
their hearts seemed tendered at the thoughts of separation, and it was like soothing oil,
to participate in the sense of their brotherly love.

W+++.+++ Gillet and sons have a manufactory in this village which employs many poor people;
some of them came yesterday, at the request of the young bride, to take tea at the house.
They were all neatly dressed.
After their repast, we heard some young girls read in the Testament.
J+++.+++ G. has a school-room fitted up,
where he teaches these poor children to read and write;
we saw some verses of their composition,
which were to be admired for their simplicity and originality;
they chiefly related to the beauty of nature`'s scenes around them; the birds, fields, etc.
There seemed something peculiarly pleasant,
in the thought of these poor children being encouraged to observe objects around,
and to cultivate and improve their minds.
We were told, their essays were put into a certain place, to be examined by their master,
who opens the budget once a month.
This afternoon we visited a poor weaver, who has come to meetings for some time;
we went to his habitation, which we find the most satisfactory way,
when it can with propriety be so; we found his wife in a very declining state of health,
and in a feeling frame of mind; an infant was asleep in the cradle,
and there was a little girl, about seven years old,
who manifested susceptibility of mind, by her tears, as we sat in solemn stillness;
this was very precious to us, as the effect of that power which standeth not in words.
Vocal prayer was reverently offered, and we believe the visit was acceptable.

In the evening, in retirement in this family, we were refreshed together,
in drawing nigh to the true Source of help.
As our minds are stayed here, all our wants are made known;
and our pure desires are answered in due season,
in the measure best suited to our growth and establishment
in the Wisdom that comes from above.
I trust these steppings among our friends are made mutually profitable.

25th. First-day.
Our minds were, I believe, afresh humbled with the prospect of the day opening before us;
quiet resignation is the best preparation for whatever may be brought upon us.
After breakfast and the Scripture reading, I was constrained to express something,
by way of stimulating to good order in sitting down to meals; that we may be favoured,
in our short pauses at such times, to participate also in renewed refreshment of spirit.
Paying but a slight regard to these moments, allowed, in a family for individual,
secret breathing to the Fountain of all our rich supplies, temporal and spiritual,
is attended with great loss.
There is a danger of the lamp of life, in a spiritual sense becoming dim,
and even being extinguished, by the cares of this life.
The deep work of regeneration, redemption and entire sanctification,
is not sufficiently the object of Christian professors.
The meeting in the morning was small; in the evening there was a very large attendance,
and the meeting closed under a reviving hope that mercy and goodness were over us.

26th. Once more came to Shipston,
as it seems that the close of our engagements here away is drawing nigh.
I think we simply desire to depart in peace;
to be willing to invite some of the inhabitants to sit with us tomorrow in our meeting-house,
looks like the way to a peaceful release.
This fresh act of dedication requires fresh-submission.

27th. The company of our kind friends from Brails, and of dear Sarah Lamley,
was truly cheering.
The house was pretty full, but want of punctuality in coming,
interrupted that stillness which we consider a needful preparation for
the spiritual refreshment which comes from the presence of the Lord.

I believe this meeting was thought satisfactory,
yet in several of the last which have been held,
my mind has not been so entirely relieved as on some former occasions.
I desire humility and patience under the trial, as I am not conscious of wilful omission,
or presumptuously engaging in service, without the fresh constraint.

28th. After a night of close searching of heart,
with a desire for right discernment and entire resignation,
I concluded to propose to my dear companion, if she could see it right,
that we should stay over first-day, and have another meeting.
Disappointing as this was to us, I was encouraged to believe,
that I should be helped through this proving time.
The thing was mentioned to a few friends, and no obstacles arising,
my heart was partly eased of a painful oppression,
and we had a comfortable time at the meeting this morning.
Afterwards we came to Sarah Lamley`'s, at Tredington; a nice resting place!

29th. These kind friends being freely disposed thereto,
we had a meeting this evening in their house, which has been licensed for the purpose.
A good sized room and large passage, were nicely fitted up with seats,
and accommodated about one hundred persons.
It proved a satisfactory time.

31st. We have been favoured with two days of rest, both of mind and body,
in this rightly regulated family,
where the circumspect conduct of the mother seems to spread over,
and influence the household.
Our time was pleasantly, and not unprofitably, passed in reading, writing,
and walking in the garden and fruitful orchard; also in a stroll in the village,
which is a poor scattered place, with very few good houses.

Ninth month 1st. First-day.
We were conveyed to Shipston in Sarah Lamley`'s carriage;
the first meeting was a time of some rather remarkable counsel being expressed,
especially to the young men, relative to the subtlety of the human heart.
Nothing short of living under the all-regulating power of the Holy Spirit,
manifested within us, can keep from evil.
In the afternoon a very large meeting of the inhabitants gathered,
and sat becomingly with us.
It was a time of some openness, and I trust ended well.

2nd. Arrived at Warwick, with peaceful and thankful hearts,
and in renewed confidence that all will be well that is ordered of our gracious Lord.

4th. The meeting was comforting.
In a close retrospect of our late religious movements,
I hope I have been afresh instructed, and confirmed in the belief,
that the Lord teacheth his servants to profit; secretly instructing, gently reproving,
and sealing his counsel with an evidence that no other teacher can impart.
W+++.+++ T. a solid and agreeable Friend, a minister, who is at Leamington for his health,
spent the day with us.

11th. Our little gathering was favoured with the
fresh extension of our Heavenly Father`'s regard.
W+++.+++ T. is still here; his solid, waiting frame of spirit was helpful,
and the exercise of his gift in the ministry, truly acceptable.
He dined with us, and we then went to the prison.
It was distressing to see so many fresh faces and wretched objects.
Many have come for a short term of imprisonment; some waiting orders for transportation.
Very trying to the keepers of the jail is this class of prisoners;
they are less subordinate than the others,
and their manners and language more licentious.
Alas! alas! poor unhappy men!
We sat down with them, and prayer was offered for them;
but we know that no efforts can avail, unless the Lord of life touch the hard heart.
The poor man is acquitted of the intentional murder of his son,
and is only to remain a few months in confinement;
but we have reason to fear that he has not a right view of this mercy.

To One of Her Nieces.

Ninth month 12th, 1822.

I have no discouraging language to hold forth;
very marvellous in my view is the mercy that redeemed my life from destruction,
and withholdeth not his goodness in my old age.

Prize your privileges,
my beloved relatives! nurtured in the pure principles of gospel Truth,
the unsophisticated religion of Jesus!
My heart, my understanding,
my every faculty is satisfied with the pure principles professed by the Society,
in their first powerful promulgation, and as I now believe them to be,
held by the honest, simple and pure in heart, and the faithful in word and deed,
among us.
To be united in such a Society;
to know the Foundation and living Corner Stone! ah! my soul,
what is there comparable to this! not the increase of corn, wine or oil,
or of any worldly possessions!
With these views, my precious relatives, I do, at times,
feel a gentle constraint to leave my own home comforts, which I highly value,
and to go from place to place, and from family to family, with a heartfelt desire,
so far as ability is given, to stir up the pure mind, which is liable, you know,
to be oppressed; hardly rising at times above visible objects.
Alas! how few come clean out of selfishness,
and of the spirit and defilements of the world!
Far am I from writing thus, as having overcome,
but my heart`'s strong desire is to press on;
not looking too much at discouraging things, past, present, or to come;
but with a steady faith to put my trust in that Power
which can subdue all that stands in the opposition.
O! how does the Lord instruct us to live above perishing things, even his goodly gifts.
How are we led along, as we can bear it!
Thus, in all things, we may gather instruction;
leaving such as we understand not to a future day.

Mary Capper.

Ninth month 22nd. First-day.
With the unfeigned desire to be kept in my right place,
I signified my wish to have some of the neighbours invited to the afternoon meeting.
In the morning several came,
and I thought a very precious sense of everlasting love was spread over us,
and gathered our spirits into that serious calm,
wherein the voice of the true Shepherd is distinguished from the voice of the stranger;
a blessed preparation for each heart to receive heavenly
instruction immediately opened therein;
or, if so permitted, through the medium of words fitly spoken.
The afternoon meeting was largely attended, and afforded me some relief.

23rd. We once more entered the prison, and sat down with the women,
most of them newly committed.
I felt particularly interested for a poor old woman,
who seems likely to be executed for coining,
and who seems scarcely aware of her awful situation.
When we were last among the women, something impressive was felt and expressed,
to a poor old female, who was confined for life.
She has since died, we hear, in a favoured state of mind.

25th. Our quarterly meeting.
It was to me a time of tenderness of spirit, and shedding of tears, not of sorrow,
but of precious feeling, under the ministry of a Friend from London,
travelling with certificate.

30th. I left Warwick, and my dear,
affectionate and truly sympathizing helper and companion,
in the work whereunto I believe we were both of us bound;
though her labour was frequently in silence, an important help it was,
and my heart was made thankful for it.
It is doubtless allowable to feel the separation, and to be sad for a season;
yet in our several allotments, lowly peace will be found.
I arrived at my own comfortable apartments, after an absence of more than three months.
The mercies and comforts shed around me are very many,
and I desire preservation from evil,
and that I may render praise and thanksgiving to the Father of Mercies.
Now and ever be his glorious Name magnified!

In the tenth month I visited the families at Stourbridge and Dudley,
and had large public gatherings in both places, I believe to satisfaction.

Eleventh month 13th. Delivered up my certificate.
The retrospect of an engagement so important, and in the latter part without a companion,
seems to contrite my spirit, and again to raise the grateful acknowledgment,
that in marvellous condescension,
strength is given to those who have no might of their own.

To One of Her Nieces.

Twelfth month 30th, 1822.

I do not forget thee, my beloved niece,
as one desirous to be and to do just what thy Heavenly Father would have thee.
Conflict, doubt and fear may assail,
even after being favoured with an evidence of the uprightness of our intentions.
This is no new path.
Do not bewilder thyself, but try to be content with a little ray of light.
I commend thee, with my own spirit,
to the gracious care and guidance of the great Shepherd of the sheep!
I am gratified by Mary Hanbury`'s love and remembrance.
She has no small share in the desires of my heart,
that the children in our Heavenly Father`'s family
may be kept from all that can hurt or destroy;
so that the holy plant may rise into excellency and dominion.

In much affection, thy aunt,

Mary Capper.
