== Chapter XI.

[.chapter-synopsis]
* Account of her last journey with certificate, as a minister
* Concluding extracts from her diary.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Bromyard, Second month 11th, 1825.

[.salutation]
My much loved Friend,

Thou knowest that I may be reckoned among those who
see but a very little way before them,
scarcely knowing what an hour may bring forth.
Desirous, I hope I am, to possess my soul in patience,
and to be found watching when our Lord cometh.
However weak, poor, and unworthy to be esteemed a servant,
my heart`'s desire is to be made willing, without unavailing hesitation,
to do the Master`'s will, to the best of my understanding and ability; if I err,
when thus simply surrendered and dedicated, the stripes will be few and gentle.

On receiving the alarming intelligence of Thomas Hughes`'s illness,
it almost immediately sprang in my mind that I should go to Bromyard.
In a prudent point of view, it seemed unlikely, and I said little about it;
but the event, the death of a young man,
who had for years considered me as an adopted mother,
and for whom I had felt the solicitude and affection of a relative, seemed so decisive,
that I did believe it required of me to look beyond bodily infirmities,
fears and discouragements, Richard Cadbury, like a kind friend, and sympathizing brother,
offered to accompany me, which was a truly acceptable relief,
and the journey was performed with less fatigue than could have been expected.
The interment took place the following morning.
The attendance was large.
My long-suspended voice was restored, when on my knees, in the act of prayer.
I remain but weakly.
Farewell, affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Cadbury

[.signed-section-context-open]
Second month 17th. 1825.

[.salutation]
My dear Friends,

I came safely to Leominster, in improved health, though still in a weak state,
but I do not feel condemnation for making the effort.
I have, before this day, found that when the mind is weightily impressed,
and we can calmly look beyond surmise and doubt, for help and direction,
there is a strength equal to the day.
My heart`'s desire is to live close to this Power, in deep humility,
at all times and under every dispensation.
My low seasons are doubtless profitable,
and I desire an increase of every Christian virtue,
to the praise of my Redeemer and Lord.

I am well satisfied with having spent a few days at Bromyard,
under the roof of my much valued young friend.
I felt the settled assurance that all was well with him,
and that there was mercy in the dispensation, unseen by mortal eye.
It was gratifying to learn the general estimation of his character for industry,
integrity and benevolence; also as a consistent member of our religious Society;
prompt and useful in the station where his lot was cast; unassuming and exemplary.
`'Tis consoling to those who loved him to contemplate his meridian sun thus set in brightness.
My love is to you all, affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Third month 23rd, 1825.

[.salutation]
My kind Friend,

I think we parted under reciprocal feelings;
my spirits were rather below their usual key,
so that the beauty of the bright sunshine did not cheer me,
and I thought I left thee in perplexity.
It was not in my power to help thee, though fellow feeling may not be altogether useless.
I believe there is individual profit in it; as far as respects myself,
my mind is humbled, and my spirit tendered,
in feeling with the tried and the afflicted ones.
The ways of Providence are a great deep; we cannot do better than submit, in reverence,
as dependent beings, who see through a glass darkly.

I was very pleasantly received; my apartments clean and delightfully comfortable,
though surrounded by smoke, dirt and noise without;
but there is a favoured retreat wherein outward disturbances cannot enter.
This is the secret place, where my spirit strives to enter and abide.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Birmingham, Fifth month 2nd, 1825.

[.salutation]
My beloved Friend,

My appetite and strength continue very weak; but what shall I say of the mercy,
the goodness and heavenly kindness shed round about me!
The envious power of the evil one seems rebuked, and not a thought has troubled me.
It is the Lord`'s doing; and O! may patience and resignation still be granted.

I am sorry thou art suffering from various causes; but thy mighty Helper,
in whom is thy trust, will never leave nor forsake thee.
All thy troubles will, ere long, be taken from thee, or thou from them.
My dear love to thy sister, and to your faithful Mary.
Hannah Simms is a great blessing to me;
I consider her as the servant granted to my fervent prayers.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Fifth month 12th, 1825.

[.salutation]
My tender Friend,

I have been once out, but the exertion is rather too much at present,
as I walk very feebly; my spirits are lively as ever, and I do not pass my days idly.
It seems desirable to set many of my little concerns in order,
as I wish as little trouble as may be to those who survive me.
I consider my present restoration among the Lord`'s gracious dealings toward me;
and I am content; yea!
I ought to be very grateful, very humble, and resigned either to life or death.

[.signed-section-closing]
Thy affectionate,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Fifth month 17th, 1825.

[.salutation]
My dear Friend,

Among other kind friends,
thou hast manifested a tender solicitude in the time of my weakness.
I believe the great reduction of my strength occasioned some serious apprehension,
but it has pleased that great Almighty Power, in whom is my confidence and hope,
again to revive, and daily to recruit my poor frame,
for the great end of farther sanctification.
The days of my pilgrimage I consider as not a few;
and though I have seen and felt much evil,
nevertheless my quickened spirit can often praise the Lord my Redeemer,
and speak well of his name.
His Light and Love is revealed in the heart, and being obeyed,
there is understanding given, to walk in the way that leads to pure peace,
putting to silence all unavailing speculations, doubts, and perplexities,
which disturb the wavering mind.
Sweet is such a foretaste of rest, prepared for the people of God; of every age,
nation and denomination, who are brought to receive the heavenly gift of the kingdom,
as docile children; in no wise presuming to question.
Why is it thus?
The Almighty Power can work this subjection in the heart;
for marvellous is the power of redeeming Love!
Seek after it, my dear friend.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Eleventh month 7th, 1825.

I have but little to say of my movements; my secular concerns are few.
I have food and raiment convenient for me.
O! I have comforts befitting old age; a cheerful fire, a good bed,
etc. all that my drooping nature wants!
My bodily health continues beyond what might be expected;
my mind--O! here is the marvellous mercy! my mind is kept lowly, calm and content;
though daily in the exercise of faith and patience.
I have been much from home; some little engagement, one way or other,
has claimed my attention, and a willing mind has been granted.
However small, if any, the service, peace and love have been the unmerited, free reward;
and again I retire, as for an uncertain period, to wait, and to be ready,
come whatever may come.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Birmingham, Eleventh month 18th, 1825.

[.salutation]
My beloved Friend,

Ere thou receivest this,
thou wilt probably have heard of the death of S. Burlingham`'s amiable wife;
the interment to take place on first-day afternoon.
If thy bodily ability permit,
I think our tender regard and sympathy would not
admit of hesitation to meet in the scene of sorrow.

I am not very well, yet I dare not get from under the solemn pressure on my spirit.
Ease and quiet seem desirable,
but no outward consideration can come in competition
with the little sacrifices we can make,
in endeavouring to fulfill our apprehended duties, whether active or passive.
I very often think, my dear friend, of thy comparatively solitary, patient,
enduring exercise, and unfeigned solicitude for the increase of righteousness.
Thy secret wrestlings and earnest prayers, in the silence of all flesh, I do not,
cannot doubt, are as acceptable as the obvious, active services,
where something of self may be intermingled, sometimes I have thought more availing.

In heart-humbling feelings on my own account, and endearing love to thee, I subscribe,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Birmingham, Third month 7th, 1826.

My affectionately and truly-interested fellow traveller in a path hidden from human view,
and with which the worldly selfish spirit has no fellowship!
Thy feelingly communicated letter of sympathy, it is almost needless for me to say,
is as a refreshing stream, proceeding from the inexhaustible Fountain,
that sends forth its pure water, far and wide, into the low valleys and thirsty ground.
Much as I have been reduced, in body and in mind,
I am satisfied with the lowly calm that is afforded,
and in which I feel no discouragement, but am ready to say, It is enough.
Yet I feel a solemn seriousness,
in the view of opening my concern to my friends tomorrow at our monthly meeting.
I have had a little conference with my dear friend Rachel Lloyd,
whom I esteem as a worthy elder and mother in the church.
Though, my beloved friend,
I perhaps know but little of the peculiar circumstances
that are now permitted to try thy faith,
yet can I, dare I,
doubt the sufficiency of that Almighty Power that has been with thee all thy life long?
Did not Mercy watch over our childish days, and the yet more dangerous years of youth,
when vivacity and inexperience led towards evil,
which might have embittered our growing years?
This Mercy follows us still; it is our hope and stay to this day; our all in all!

8th. A certificate is ordered to be brought to our next monthly meeting for me,
as friends have expressed unity with my prospect; so far, my spirit seems relieved.
In precious fellowship with thee, my dear friend, farewell!

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Third month 11th, 1826.

Increase of years wears down the powers of nature,
but sometimes I marvel at the activity of my little, weakly frame;
shaken as it has frequently been, through the long space of seventy years! and, even now,
I seem like a child beginning to learn the perfect will concerning me.
Sometimes light arises out of darkness, and simple dedication,
with the little strength that I have, seems the way to obtain peace.
Thus, after a time of much reduction of mind and body, with a little revival of strength,
a prospect, which I have had at times for some years, has revived;
to visit the meetings and families of Friends in Derbyshire, Notts,
and some parts of Leicestershire.
The undertaking seems great; I have indeed felt it so;
almost enough to overwhelm my weak powers; but I am not my own,
and the time draws on when all sacrifices will be over, and redeeming Love be all in all!
The unity of my friends is helpful to me.

I have received a very satisfactory account of the
calm and favoured close of dear Sylvanus Bevan,
the son of my late precious niece.
O! the mercy which, in youthful days, as in old age, is the crown at the end.
Who can desire human life, when redemption is complete?
My accommodations, I know, are not altogether what some of my liberal friends desire;
and some things there are, not very agreeable; but my dear niece, here I am,
with food and raiment, a faithful servant,
etc. etc. quietness within my walls! and what can I expect better, should I attempt,
in my own will, to make a change?
Such things as are not to my mind, I desire my mind may be brought to bear,
and that I may be thankful.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Evans.

[.signed-section-context-open]
Birmingham, Third month 26th, 1826.

[.salutation]
My endeared Friend,

It is a precious privilege to have spiritual unity,
and secret fellowship, in hidden trials and provings of faith.
Christian pilgrims have their sufferings;
how else should they be disciples of a crucified Lord?
and if we look around, on those who turn their back upon spiritual sorrows,
is there any trouble like unto worldly sorrow?
wave upon wave, a troubled sea! and no powerful Word, to speak.
Peace, be still!
Every tender feeling within us may compassionate the various sufferers of this day;
the monied men, the manufacturer, and the labourer,
are all involved in the present far-spreading dismay.

[.signed-section-signature]
Mary Capper.

--

1826+++.+++ Fourth month 15th. Arrived at Sarah Fox`'s, Nottingham.

18th. The quarterly meeting large; a considerable number of serious Friends; though,
as in other places, the deeply experienced fathers and mothers are but few.
A rising generation must learn for themselves to sit at the feet of Jesus,
and be taught in the way of the cross.

20th. My very kind friend, E. Cadbury, left me; I feel the privation, being now alone,
among almost strangers, though friends are very kind.
Sarah Fox, the mistress of this family, is very delicate,
and mostly confined up stairs just now; but there are young persons in the household,
who are very active and affectionate.

26th. Privileged with a shelter within doors, from the rain.
Those who are to be visited are so kind as to come to me.
I feel weak and poorly; but wonderful in my view,
is the daily covering of Christian good-will, which condescending mercy spreads abroad,
in the midst of my poverty of spirit.
I hope I am in my right allotment in this place, and that I may be, in my measure,
instrumental to stir up the pure mind in the followers of Jesus.
Took tea with J. Armitage and his wife;
surely it is for my own instruction that I am brought among these friends.

29th. Sat with two sisters in declining years;
I thought the quickening life or power seemed at the lowest ebb that I had known,
in retirement of this kind, since I came here.
A young man afterwards sat down with me,
and I believe something arose like life answering to life.
This is marvellous! when light is thus permitted to shine out of darkness.
In the evening, sat with a family, in solemn,
quiet waiting for the renewed revelation of the light and life of Christ in the soul.
O! how different this from lifeless form,
or any outward dependence! how pure the desire to acquaint ourselves
with that great and glorious Power that worked out our salvation,
in us and for us!
Yea! how chastened are our sorrows, how subdued our anxieties,
our every trouble and care,
when we can be truly resigned to the will of Him who ruleth over all,
and doeth all things well!
This little season has left a sweet savour.

30th. First-day.
Before I rose, a grateful sense of past favours contrited my spirit,
and raised the secret prayer,
that the unseen but sustaining Arm may continue to direct my steps; that no presumption,
no unwatchfulness, no neglect of prayer, may be permitted to misguide or delude me.
When we met, in our little circle, to breakfast, there seemed a remaining dew,
after a time of refreshing;
and we had again a sweet token that the Lord`'s mercies are new, every morning.
Our more public gathering for worship was, I hope, a spiritual benefit to some;
but the want of united diligence, and inward watchfulness, for the arising of light,
of life, and of prayer, is surely a hindrance from that approach unto God,
which the quickened soul thirsts after.

[.embedded-content-document.letter]
--

[.letter-heading]
To E. L.

[.signed-section-context-open]
Fifth month, 1826.

"`O! Thou that hearest prayer, unto thee shall all flesh come!`"
All have need of prayer.
"`If my people, which are called by my name, shall humble themselves, and pray,
and seek my face, I will hear from heaven and forgive!`"

Jesus, the Saviour, though without sin, prayed oft-times, as we read in the Scriptures;
He enjoined his disciples, and all that believe in, and follow Him, to watch and pray,
that they enter not into temptation.
The Spirit of the Lord teacheth us to pray as we ought, though words may not be spoken.

[.signed-section-signature]
Mary Capper.

--

Fifth month 7th. First-day.
At both meetings.
With reverence I record it! my spirit was clothed with lowly
dependence on that Power whence all our sure mercies come;
and again I thought a ray of light mildly shone out of darkness,
and I saw that it was good to be patient under humiliation,
wherein a willingness is wrought in us to suffer with those, who,
in their several stations in the spiritual family,
are labouring for the fresh arising of life and power in our meetings.
As we are a people who profess to have no dependence on outward ministrations, we,
above all other Christians, have need to cherish the spirit of prayer, and an inward,
reverent waiting for the renewal of our faith, and for ability to worship aright,
and to walk worthy of our profession from day to day; otherwise our meetings are dull,
heavy and vain pretensions.

11th. I thought the meeting was favoured with the overshadowing
of that mercy which is ancient and new;
but here, as in other places,
there are comparatively few who make the necessary sacrifices to
attend these religious meetings in the middle of the week;
of course,
there is a great individual loss of that spiritual
consolation which would renew the best.

13th. Fervently prayed to be kept in the path of duty, humble and simple-hearted,
in no way presuming upon what I may think I know,
or ever have known.--Paid a visit to an aged man, in very precarious health,
yet cleaving to life; his earthly possessions, it is to be feared,
are somewhat like chains, which fetter the spirit.
O! I hope these bonds may be loosed.

15th. As my weak frame needs rest, I was conveyed about three miles, to S. R.`'s,
in a small, quiet village.
The country is beautiful, but it is a cold, backward spring.

17th. Surrounded, in this peaceful spot, with rural sounds, and simple variety,
my health seems to recruit a little.

19th. Having had about sixty sittings,
it presses upon my mind to have a meeting with servants who live in Friends`' families.

20th. Mentioned the subject to some friends, and nothing discouraging arose;
but it ever seems a serious thing to gather an assemblage together.
I desire to keep lowly, and fearful, lest in any wise, I should do evil.
Surely I do wrestle in prayer, as far as I can understand what this means;
I do supplicate, on the bended knees of my body, and in prostration of all within me,
that fatherly compassion and mercy may keep me from error, and presumption, in thought,
word and deed!
I have no might or wisdom of my own.

21st. First-day.
A large gathering.
Love to souls, in the offers of redemption from the bondage of sin,
and of sanctification, with access to the Throne of Mercy, by Christ,
the new and living Way to the Father, was a little opened;
and counsel given to servants to be faithful in their different stations,
not as eye-servants; with some encouragement,
to the sufferers in the troubles of the present times,
to endeavour after patient submission; and that there may be a serious search,
how far any had lightly esteemed the Lord`'s mercies, in a day of comparative prosperity.
It may be, these very things which seem against us, may eventually work for good.
I thought the meeting closed with solemnity.

23rd. Walked a considerable distance, to visit a poor family; I found the mother,
an aged Friend, with two daughters, in a small room, all that they had,
except a shop below it; they were washing.
On entering this little dwelling,
I thought there was a sweet consoling evidence that the Son of Peace was there;
more precious than the odour of rich perfumes,
or than the rare curiosities which adorn the apartments of the affluent.
I was thankful, and well repaid for bodily toil.

24th. Early occupied in serious consideration.
O! who can set forth the secret ponderings of a heart, quickened with desire to know God,
and to obey his will, concerning the rational creation which He has formed,
to fill the right place and allotted station therein!
May the Spirit help my infirmities! that I may ask aright for wisdom
and understanding in the things belonging to salvation.
Surely I do wrestle for the heavenly Gift, that leadeth into all truth,
as it is in Jesus! not trusting to my own poor comprehension,
which sometimes troubles and perplexes me, with what comes to the outward ear;
nevertheless I dare not but rely on the mercy which kept me in my youthful days,
from time to time manifesting a glimpse of the incomparable beauty of holiness;
I dare not doubt the gracious design to complete the work of sanctification and redemption.

29th. First-day.
At the morning meeting, my mind was under an unusual sense of distress,
comparable to a thick dark cloud,
obstructing the strong consolations that are in the faith, and the truth,
as it is in Jesus the Redeemer, the atoning sacrifice, according to the Scriptures,
which record my heart believes in and I can, at times,
joy and rejoice with full confidence in this salvation,
for my own soul and for the souls of all who are reconciled to God the Father,
through the mediatorial offering of Christ Jesus, his Son.
This dark and distressing feeling in measure passed by, as in much brokenness of spirit,
and in the ability given, I spread it before those present; expressing my desire that,
if any tender mind might be thus tried by the assaults of Satan, such might, with me,
be fervent in prayer, until we had an evidence that our Lord rebuked the evil spirit,
and in mercy, strengthened and increased our faith.
In the evening, at the house of a friend, the same subject presented itself;
my mind was brought into deep sympathy with the inexperienced who might be so tried;
and counsel was given to be still, and to wait in humility and reverent silence,
upon God, that He might be pleased more fully to open the spiritual understanding;
that He might reveal his will in us, and give us the knowledge of the Son,
by whom we have access to the throne of Grace, with Christian boldness.
I have a lowly confidence that God the Father does and will teach his humble obedient,
praying children, by his Spirit in their hearts;
that He will deliver out of spiritual distress,
when we are simple enough to trust in Him,
without bewildering ourselves with the notions and opinions that are abroad in the world;
and if we cannot contend, or give strong reasons, for our faith in Christ, I believe,
that if we are willing in our measure to suffer for him,
we shall in due time reign or triumph over his enemies and ours.

I accompanied a religious neighbour this day,
to visit the poor women in the House of Correction; about twenty sat down with us.
I was affected at the youthful appearance of some; their indiscretion,
with its consequences, was set before them,
and supplication offered on their behalf We afterwards went in the town jail;
I only saw the women, and I thought they were not past feeling.
We returned from this little visit of Christian charity, not dissatisfied.
There is a committee of females who visit these houses of confinement,
to read the Scriptures, etc.

30th. At the monthly meeting,
I was engaged to set forth what had appeared to me comparable to bonds and fetters,
keeping the pure Spirit from arising into dominion.
My spirits remain oppressed, and lowliness of mind is my portion;
though I feel no condemnation, which I consider a special favour.
All I ask is a peaceful acquittal, in having endeavoured to do what I could;
the effect I would humbly leave, even when sadness may be my portion.

31st. Took leave of this kind family, from whose servants, as well as themselves,
I have received much attention.
Mary Armitage accompanied me to Mansfield, where I was kindly received.

Sixth month 2nd. One of my young friends accompanied me to the almshouses;
six occupied by Friends, and six by females not of our Society.
"`A place for everything, and everything in its place`" seems here exemplified;
and that but little room is actually needful, where there is good order.
All was neat and clean; and I thought I could live, content and thankful, in such a spot,
with the love of God, and a sense of his mercy in Christ Jesus.

4th. First-day.
In the meetings, painful apprehensions arose that some were not humble enough;
that they had notions and ways of their own choosing;
disputations and cavils about Scripture doctrines,
and the simple testimonies of experienced Christians,
who declare the Truth as it is in Jesus, When thus tried,
it is well to wait till discernment is granted, so as to divide the word aright.
I hope seasonable caution and counsel were feelingly delivered.
I took tea with a dear old Friend, and we had a refreshing time together.
The spirit of prayer seemed to be poured forth; now that I am retired to my chamber,
the close of the evening, in the outward, appears beautiful; the setting sun is bright,
and all around is calm; nature is clothed in tints of glory and loveliness.
O! for such a final close, spiritually, when the soul shall quit these changing scenes.

6th. The monthly meeting was a time of favour;
we should learn to be humble and patient in times of distress,
for such times are occasionally brought upon the Christian.

7th. Had the gratification of seeing my nephew and niece Backhouse,
on their way from the yearly meeting, with their daughters,
the interview was precious though short.

8th. Took tea with one of the Friends at the almshouses; these little, neat,
quiet dwellings and humble inhabitants,
seem peculiarly suited to my present frame of spirit.
Godliness with contentment truly is great gain.
Most of the inmates appear to prize their happy lot, and to live in peace and good will,
assisting one another, as need requires, in sickness, etc.
I called on two infirm, afflicted women, not members of our Society;
one of them had kept her bed for two years.
This dear old disciple spoke, with tenderness of spirit,
of mercies in the midst of long continued helplessness and pain,
and said she would not exchange her situation with the young, the healthy,
and the thoughtless; her firm belief was, that when the right time came,
her Lord would take her unto Himself.
Another poor woman appeared patient under much suffering,
and expressed her desire to be resigned to her good Master`'s will.
He being very merciful, and comforting her.
This confirmed me in the belief that the God of consolation is with the poor,
in their solitary dwellings.
This charitable institution is a noble instance of liberality;
having been built and endowed by a townswoman,
who had accumulated property by keeping an inn,
and having often entertained Quakers at her house,
she generously provided for some of the poor among them;
she likewise appointed members of our Society as Trustees.

13th. Sat with this interesting family.
A caution to avoid disputation on Scripture doctrines was affectionately expressed.
This caution has arisen in my mind from place to place,
and I have no reason to think that my plain admonitions have given offence;
whatever may be the notions which prevail, or may in future prevail,
this must be left to a superior controlling Power.

14th. I think I have endeavoured to fill up my little services here,
and that I may be favoured to depart in peace; a reward sufficient to satisfy.

15th. My kind friends conveyed me to Chesterfield,
and left me under the kind care of A. Storrs.

18th. First-day.
Scarcely twenty at meeting.
It is consoling to have the gracious promise fulfilled that,
where two or three are gathered in the name of Jesus,
they witness Him to be in the midst, as their Teacher.

20th. The quarterly meeting fully attended, and much seriousness prevailed.
After parting with our friends, I felt desirous of proceeding with the family-visit,
and I went to dine with two valuable Friends, William and Rachel Brantingham,
who are in the station of elders.
We took tea at their married daughter`'s. I hope there are good desires in their hearts;
with the young, there must be time for the bud, the blossom and the fruit.
With watchfulness and prayer the work will go forward.

22nd. The few who did not neglect the usual meeting were refreshed;
to me it was comparable to a cordial drop of Gilead`'s balm; a short but precious time!

23rd. Had an opportunity of communicating some caution and encouragement,
from my own experience, to a young man who has joined our Society.
After we have tasted that the Lord is gracious, the injunction remains.
Watch and pray!:--I was favoured with ability, this evening,
vocally to ask for preservation from all that can harm, in declining years,
when weakness and infirmity may increase.
I asked not from a sense of desert or worthiness,
but that fatherly compassion and mercy might crown our last days.

25th. First-day.
William and Martha Smith, who arrived yesterday,
expressed their grateful sense that heavenly Goodness was near, in our little gathering,
this morning.
In the afternoon, we had the company of a considerable number of serious persons,
who had been invited to sit with us.
Strength was given to point out the difference between
mere profession with the lip and tongue,
and that conversion or change of heart, wrought by the Holy Spirit revealed in the soul.
It is not enough to confess that Christ died for sinners; we must receive Him,
and own Him by obedience, as a Saviour, a Redeemer from sin,
and a Leader into all righteousness.

27th. Arrived at the house of Joseph Wooley,
a pleasant situation at the extremity of the extensive village of Blyth.

28th. A long dry season, and a fervid sun,
seem to cause considerable languor in animal and vegetable nature.
I walked into the village, and sat down with a widow and her son, in a cool, retired room.
I felt comforted in the time of waiting on the Lord together;
and again I am confirmed in the belief, that it is good for us thus to visit one another,
under the gently constraining influence of Christian love,
something like iron sharpening iron.

30th. Mary Dudley mentions, in her journal,
a medical man who behaved with great kindness; he sent a post-chaise four miles for us,
and received us very hospitably at Bawtry.
On my intimating a desire to sit down with the family,
every arrangement was willingly made.
Servants and inmates came, and all seemed serious.
The landlady of the Crown, who gratefully remembered Mary Dudley, also joined us;
and I believe the sweet influence of our Heavenly Father`'s love was felt among us.
It is this alone that can do us any abiding good!
it is the fresh sense of this that comforts my heart,
renews my faith, and encourages me to hold on my way.

Seventh month 1st. A day of some rest, grateful to body and mind.
My lot is in a kind, amiable family; the daily care of little children,
and the well-regulated exertions of parents,
may evidently be so ordered as to harmonise a whole family,
and to cultivate that watchful frame of spirit which manifests
our dependence on a superior Power to teach and guide us;
a Power that keeps us from evil, and promotes a sweet union and affectionate accordance,
when met in families or social companies.

2nd. First-day.
In the evening, the neighbours having been invited, a large number came.
I was particularly impressed with the serious countenances of the men,
who mostly seemed of the class of labourers.
Help was given to declare our belief in the doctrines and testimonies of Holy Scripture,
concerning the birth, crucifixion, and resurrection of the promised Messiah, the Saviour,
and the propitiation for the sins of the world, the Sent of the Father,
to redeem those who believe in Him, and who, through his grace, forsake their sins.
The gathering separated seriously, and thus, once more, my spirit was relieved.

4th. At the monthly meeting it was a satisfaction to see the discipline
of the Society conducted with so much good order,
where there were so few.

6th. At meeting, at Chesterfield, I thought a sweet refreshing silence did us good.

7th. William and Rachel Brantingham accompanied me to Ebenezer Bowman`'s, at One Ash,
a remarkably secluded spot, surrounded by the diversified wonders of nature; the hills,
the dales, and the caverns afford ample scope for entertainment and instruction;
this is in what is called the Peak country.
Although other views occupy my mind, I cannot but see and admire the beauties of nature.

8th. Another day brings fresh desire to proceed in my engagement.
Some of the more remote places, and difficult of access, seem to remain,
and my strength is small; but I hope for renewed help.

9th. First-day.
Attended the meeting at Mony-ash.
The villagers having been invited to come in the evening,
the meetinghouse was filled with a quiet company.
I felt thankful in believing that there was a right sense of that which
alone can do our immortal spirits good,--the love of God in Christ.

10th. The Friends here are very tenderly considerate and kind.
In the afternoon, Ebenezer Bowman conveyed me to Bakewell.

11th. Friends rose early, and we set out, some on horseback, and others in carriages,
to attend the monthly meeting, held at the Bridge Inn, Matlock, about eight miles off;
the road is fine and the country beautiful.
I thought the meeting was a time of encouragement,
and of tender feeling with one another, in our different allotments.
If I am but kept in reverence and godly fear, filling up my appointed duties,
doing neither more nor less than is required, and acting under Divine teaching and power,
it is enough; this is the daily concern of my heart, at home and abroad.

We were somewhat disturbed by a noisy, indecorous party of young people;
and as they sat with the door open,
I just stepped in and civilly asked if they would give me leave to offer a few tracts.
They were civil in return, answering,
"`Yes! surely;`" but they appeared young and thoughtless.
I spoke a few words seriously to them, to which they listened with attention,
and they were afterwards more quiet in their behaviour.
On our leaving the inn, I observed some of them reading; possibly a little hint dropped,
even to the giddy, under feelings of tender compassion, may not be altogether lost.

12th. Visited a humble cottage,
where a Friend keeps a little school for the village children, some miles from Bakewell.
This Friend has made a large collection of the spars
and minerals which abound in the neighbourhood,
and he kindly gave me some specimens.
I left this little solitary family with the conviction
that heavenly kindness is spread abroad,
in a way not to be circumscribed by our limited apprehension.
Came to One Ash, in what seemed to me a boisterous blast,
but what is here considered a refreshing breeze.
Very diversified are our local situations and our habits.
There is instruction in all.

13th. Two female Friends, travelling with certificates, arrived late, with their guides;
an addition of four, besides their horses.

15th. After the Scripture reading this morning,
a reviving sense of mercy and goodness being near, shed a precious feeling over us,
to which L. S. bore her testimony.
I ventured to inform E. Bowman that a tender feeling toward
the servants employed both in in-door and outdoor business,
induced me to inquire if it would be easy to collect them,
which I left under his consideration.
A poor woman walked five miles,
in order to have an opportunity of sitting in religious retirement with us.

16th. First-day.
This morning the servants were collected, and we sat down about fourteen in number.
The universal love of our heavenly Father, who created all for glory,
and is calling to virtue, revealing the Spirit of Christ, as a light,
and a leader out of darkness and ignorance, was spoken of.
After attending meeting, on my preparing to leave this kind family,
I was peculiarly comforted, cheered and encouraged,
by E. Bowman and his wife proposing to accompany and convey me, from place to place,
through their borders.--We travelled slowly along together, making divers visits,
till we came to Thomas Howitt`'s, at Heanor.

21st. The chapter in the Scriptures which was read in the morning,
was succeeded by a solemn pause,
during which the truths that we had heard seemed
to open a view of the awful effects of disobedience,
hardness of heart, and unbelief,
from whence proceed all imaginable wickedness and deeds of darkness;
turning from this dismaying scene to where Light, Life, and Mercy shine,
and are followed by acts of obedience, how cheering,
how consoling is the hope set before us!
We came on to Derby, having visited the scattered families of Friends,
upon the way from One Ash, in their solitary dwellings.

22nd. A day of weakness, but I cherish the hope that all which may seem against us,
may work together for the furtherance of our faith, etc.
Just now, I seem entirely ignorant as to my future movements,
though I can see no way of escape without going into the families of Friends here.

24th. I have an affectionate invitation from Susan Greaves, of Stanton;
also one from S. F. Church, teacher in the Moravian Congregation at Ockbrook.
I feel grateful for this Christian attention, and disposed to accede to their wishes;
but other engagements are now in view.
Came to Castle Donington,

25th. Several Friends came from Nottingham to the monthly meeting.
I believe it was mutually gratifying to see each other;
and it was a yet greater favour to experience the renewed evidence of a Redeemer`'s love,
by which the lowly-minded were refreshed and comforted,
on their pilgrimage to the promised land.

29th. I may thankfully say, I have been helped every way, as occasion required;
and I consider as a peculiar favour, the calmness which clothes my mind.
There is much instruction in the various dealings of our heavenly Father,
in order to convince us of our sinfulness,
and of our need of redemption through the atoning sacrifice.
How variously and how wonderfully,
the work of repentance and faith is begun and carried on, if not willfully rejected,
even in the heart of the poor, the solitary, and the unlearned in this world`'s wisdom!
Up and down, where I have been, sickness,
affliction and trouble seem to have been the means of spiritual instruction,
by loosening the strong bond of natural attachment to earthly things.

Eighth month 2nd. In a solid meeting for worship,
I took a Christian farewell of my friends, in much tenderness.
In the evening, came about six miles, to a place where I was cordially received,
into a large family of children and grandchildren.

3rd. Accompanied my friend to the village, to make calls on the sick and poor.
I thought, as we sat to wait upon the Lord with a poor cottager,
that there was a heart-humbling sense of heavenly kindness,
as a token of acceptance of this almost solitary, and in the view of high professors,
this despicable way of seeking the Lord.

4th. The morning chiefly occupied in private retirement, and serious conversation.
This was succeeded by some trial; there being a large mixed company at dinner.
It was rather a thoughtless assemblage; and although not designedly indecorous,
mirth and levity became irksome to some of us.
I ventured, with deference to the master of the house,
to ask leave to make a few observations, and a becoming quietness ensued.
I then expressed my ideas of rational cheerfulness,
and of a grateful participation of the bounties liberally bestowed for our bodily refreshment,
which no human skill could produce,
seeing that no man can cause a grain of wheat to grow and fructify;
shall we then eat and drink, and forget the Power that supplies our need?
Something of this sort was said, and listened to with a degree of attention;
and possibly it may recur at a future day.
I felt much for my kind friend, whose situation appeared to me very trying.
In the evening we went together to the village and sat down in a cottage;
many came in and behaved quietly,
and I felt an openness for expressing something on the faith and practice of our Society.
We parted in cordial good will.

5th. After an opportunity of religious retirement
with my dear friend and some of the servants,
I took my leave and returned to Derby.

6th. First-day.
Some strangers were at the meetings.
Our simple manner of worship having nothing of external attraction,
and reverent waiting on the Lord in silence being little understood,
those who come among us from curiosity, or in order to hear,
are likely to be disappointed.

7th. Commenced visiting the families.

10th. I felt very low, and unfit to minister to others; but in sitting with a poor,
working man this evening,
the liveliness and tenderness of his spirit were a help and comfort to me.
The day closed in a thankful calm.

14th. First-day.
Sat with a pious poor man from the country;
there are several of this class who attend our meetings,
and I think they help to keep alive the sacred flame of devotion among us.

16th. Went six miles to visit the Moravian settlement at Ockbrook.
S+++.+++ F. Church is connected with our family through my aunt Chase;
he and his wife were truly kind, and I felt a secret unity of spirit with them,
which is beyond names and forms.
We separated in love, and a sweetness, best known to Christian believers,
as being one in heart, seeking the Lord Jesus.

17th. The meeting at Derby proved a time of solemn parting;
my heart was contrited in a view of the steps that I had been led to take.
Goodness and mercy have kept me stayed upon my best Helper, eternal in the heavens;
and my spirit bows, in reverence and thankfulness, as with my mouth in the dust;
believing that it is of the Lord that no condemnation disturbs my lowly peace.

20th. First-day.
Loughborough.
The neighbours being invited, a large number came to meeting in the evening.
I was surprised at the extension of condescending mercy, in opening gospel doctrine,
and Scripture testimony, respecting the consolations which are in Jesus,
his redeeming love, and his atoning sacrifice, as well as his light, life and power,
now revealed in the hearts of the children of men, to turn them from darkness unto light,
to create a clean heart and renew a right spirit within them.
This is the religion we profess; if we walk inconsistently,
unmindful of prayer and watchfulness, condemnation must rest upon us.

21st. Took tea with a poor family;
I believe the life of pure religion binds them together;
and we were refreshed in the sense hereof, though they are among the lowly ones,
having little of this world`'s goods.

22nd. Received the affecting account of the death of dear Mary Lloyd, formerly Dearman.
A short time ago, she was young and lovely, gentle and engaging.
Her spirit, I consolingly hope, is now clothed with purity,
and admitted into the kingdom of rest, to join the redeemed.
Occupied in visiting several poor families,
some of whom occasionally attended our meetings;
among them is a tenderness of spirit worth cherishing.
I wish this care may ever be observed among us, as a people professing goodwill to all.

26th. The time being come when I apprehended myself at liberty to leave this place,
I proceeded to Leicester.
It is not easy to set forth the thankfulness of my mind in being thus brought in safety,
and without a painful feeling of wilful omission or commission,
throughout my many weary steppings, and my long absence from home.
Though in a weak state of body,
my mind seems to be resigned to enter into farther exercises,
if such be the will of Him whose servant I desire to be;
His will being my sanctification.

29th. Entered on a visit to the families at Leicester.
I am well aware that there is no advantage in dwelling with or upon my own weakness,
or surely I feel unfit again to enter on such an arduous duty;
but the welfare of my Christian fellow travellers is more important than my own ease,
my health or my natural life, if I may only be enabled to hand a little help.

31st. We read that our Lord and Saviour often withdrew from the multitude and prayed;
and that He condescended to teach his disciples how to pray.
Why is it,--how is it, that we live so little in the spirit of prayer?

Ninth month 3rd. First-day.
A day of much exertion.
In the morning meeting there was an earnest pleading with those of our religious Society,
that the light, the life, and the power of godliness might shine,
with increasing brightness, among us; that our upright,
conscientious dealing in all our concerns, our consistency and genuine plainness,
throughout our life and manners,
might show forth to others that we were taught in the school of Christ.
In the afternoon, many of the neighbours sat with us,
when the universality of the mercy and love of our Almighty Father was feebly set forth.

11th. Preparing to leave my kind friends here, with the intention of holding a meeting,
at Hinckley.
I was favoured with an opportunity for freely communicating, to a young medical man,
some impressions on my mind, which appeared to be well received;
this was an unexpected relief,
and confirmed me in the persuasion that it is well to wait, in the patient belief,
that for every right thing, there is a right time.

12th. Favoured with quietness, in looking towards my departure hence;
and before leaving had an opportunity of religious retirement with the servants,
to my satisfaction.
I feel for servants.

13th. Ann Heaford kindly accompanied me to the Crown, at Hinckley.
She has long been acquainted with the landlady of this large,
well regulated establishment,
who seemed to consider it a privilege to spend part of the evening with us,
14th. We also had her company at our Scripture reading, after breakfast, to our comfort.
Some sober people attended the meeting, and our religious principles,
as founded on the gospel tidings of life and salvation, through Jesus Christ,
were in measure set forth.
After parting from my friends in tenderness of spirit, I came to Coventry,
having accomplished my engagement.

[.asterism]
'''

+++[+++Thus closed the labours of this devoted servant,
as far as regards travelling in the work of the ministry;
and here also ends her own diary; but,
as long as she was able to pen an occasional memorandum,
and to correspond with her friends,
the effusions of her heart and pen gave undoubted proof of her growth in grace,
while the genuine fruits of the Spirit were abundantly brought forth in her consistent,
humble, daily walk.

The reader is now presented with such extracts from her letters, etc.,
as appears best calculated to demonstrate her progress in
that path which shineth more and more unto the perfect day.
The first extract is from a letter to one of her nieces,
written before she reached her home, from the journey,
the particulars of which have just been given.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Warwick, Ninth month 24th, 1826.

Thou mayst surely think that I have lingered on my way, when thou seest this date;
but I believe I may venture to say, I could not make haste.
My attention was turned to the poor, and almost unknown ones,
in solitary dwellings and lonely cottages.
O! how condescending Goodness shines, at times, like the enlivening sun,
upon the penitent, humble, hidden Christian believer!
The retrospect of such times as these, during my journey, is consoling and encouraging;
and now, at the close of this engagement, reverence, tenderness and lowliness of mind,
are the sweet reward of this little dedication.
It is enough!
I ask no more.

[.signed-section-signature]
Mary Capper.

--
