== Chapter XII.

[.chapter-synopsis]
* Memoranda
* Extracts of letters, etc.
* Death of her friend Hannah Evans, and of Mary Capper`'s only sister.

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
14, Dale End, Birmingham, First month 3rd. 1827.

[.salutation]
My long loved Friend,

We live to see various events and changes, but we do not forget our dear,
unseen fellow-sojourners in a state of probation,
and in what is at times a weary pilgrimage.
Although it is ordered by our heavenly Leader,
that our path through the wilderness lies hidden from each other,
surely there are favoured seasons of sweet union in spirit.
While each is pursuing the manifested way of duty, the port, the haven of rest,
ever aimed at, and sometimes in marvellous mercy opened to our view,
seems to bind together the disciples of the one Lord.
My mental feelings have of late been various; I desire to bear, with patient,
humble submission, the purifying fire,
though I may be again and again cast into the furnace.
I am satisfied that my Redeemer, the Son of God, liveth, and that, through Him,
my soul will live also.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Dale End, Second month 5th, 1827.

Many are the ponderings of my mind,
on the important and deeply interesting subject of the hidden evils of the heart.
My late reflections have been, that the subjugating power of Divine Grace,
as it does much for the obedient soul, gives a quick sense of evil;
manifesting the exceeding sinfulness of sin, and separating the precious from the vile.

8th. I have been prevented from following the train of my thoughts,
so as to communicate them to thee,
yet I desire to tell thee a little of the path I now tread.
Self-reduction is a hard lesson to most of us; after years of religious profession,
and even sacrifices not a few, some natural propensities still cleave close;
and we may not be fully aware of their power unless occasion stirs them up.
It is easy to conclude that all is well,
when no temptation presents,--no provocation of temper arises;
but I hope my late meditations have tended to increase my faith, my reverent,
humble confidence, in the mediatorial sacrifice of redeeming love.
The unfathomable mystery I willingly leave; and with thankfulness,
cling to the things revealed to my understanding.

I think I have even recently seen, that when we are exercised in our Christian warfare,
with deep humiliations, in the conflict of nature with Grace, it is at times,
a preparation for some unforeseen trial or privation.
The spirit being hereby contrited, and the heart humbled, there is a submission wrought,
a lowly bending under the hand that afflicts, and to the Power that forgiveth sins,
that healeth all our mental diseases.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Second month 27th, 1827.

A short time back I had not a thought of so soon taking my seat by your fireside.
I anticipate being in my old corner; bear in mind that I am not a stranger,
nor a visiter for a day only.
I hope it is not presumption,
when I think that it is Christian love which gently constrains
me to leave my home and my dear friends here,
in order to manifest, in person, the best desires that I am capable of forming,
for my young friends, that in their early steps, and in the progress of their pilgrimage,
they may ever keep in view, the redeeming, the sanctifying power of God the Father,
revealed through Christ Jesus the Son; as testified of in the Scriptures,
from Genesis to Revelation.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Fifth month 18th, 1827.

[.salutation]
My dear Friend,

I have not forgotten you; I have a pleasing recollection of the afternoon spent,
under your roof, with T. D. etc.
`'Tis sweet; yea! like unto precious oil, which gently flows over all,
and smooths the rough surface,
when we are favoured to feel the influence of Christian love,
that love which thinketh no evil, but hopeth all things, even in dark and gloomy days,
looking with an eye of faith, beyond those troubles and offences that do come,
and will come upon us in this world.
I much wish to know how dear Candia Burlingham is; she is a patient sufferer,
and I have no doubt but that her Lord is purifying her immortal spirit,
for an admittance into his glorious kingdom, where nothing shall any more offend.
My dear love to them all.
To thy husband, thyself, and the dear children, with their kind governess;
I think I need not say much in order to assure you of my love unfeigned.
While I write and think of you, my spirit breathes the petition,
to the Father of Mercies, that He would never forsake you, but lead you in a plain path,
keep you, with my own soul, from evil, sanctify us throughout,
and clothe our spirits with the fine linen, clean and white,
that we may be fit companions for the redeemed.
My soul longs for this complete work.
Farewell,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Birmingham, Twelfth month, 1827.

[.salutation]
Dear J.,

As a friend long interested in what concerns the
best interests of thy parents and their children,
yea, reaching to the children`'s children,
the warm glow of my love spreads as a widely unfolding mantle over them,
encircling parents and relatives, your grand parents,
the dear friends I have abundant cause to remember in this
my native country--they stand not on the back ground,
in my present view of years passed by.
Well and gratefully I recollect their kindness, when I was as one desolate,
and in manner forsaken by father and mother.

These are times to be remembered when friends were raised
up to feel with and for me in my mournful walk.
Indeed, with reverence, and I hope in true deep humility, I may testify,
our redeeming Lord, the Sent of the Father, the Reconciler, the Mediator and Saviour,
has been my guide, my helper, to this day;
and my only consoling hope is that Jesus the Son of God, according to Scripture,
without note or comment, will finally be my soul`'s salvation.
Unspeakable I consider,
and I hope with unfeigned gratitude I oft in my silent
retirements contemplate,--the favour of a calm,
steady conviction,
and firm unwavering adherence to those principles of Friends which
first humbled my heart under a sense of my need of purification,
yea, redeeming from the sins of thought, word and deed.
Oh, who is there can purify his own heart, and make it clean in every part?
Suppose we admit the Spirit worketh in us and for us--who and what is this Spirit,
by and through whom was Grace and Truth brought to light?
I joined you as a religious Society, surely believing that you not only professed,
but truly believed and cleaved close to a crucified Saviour,
and this is my abiding faith.

Desiring that the Lord may direct your steps and hide you from the strife of tongues,
I remain with a sweet overshadowing sense of that love which is ancient and new,
the affectionate well wishing friend of thyself and wife
and children--it matters little what we have known,
or what we have suffered, if so be that through sanctification,
all things work together for good.

[.signed-section-closing]
Thy sincere friend as heretofore,

[.signed-section-signature]
Mary Capper.

--

+++[+++In the Twelfth month Mary Capper attended the quarterly meeting held at Coventry,
and went to Warwick, where she writes:]

[.small-break]
'''

Twelfth month 24th, 1827.
Found my dear friend, Hannah Evans, recovering from some alarming symptoms of apoplexy;
we secretly enjoyed our mutual intercourse, in precious unity of spirit.

[.offset]
+++[+++On the last day of the year, Mary Capper wrote thus:]

[.embedded-content-document.letter]
--

[.letter-heading]
To her Niece Katharine Backhouse

[.signed-section-context-open]
Twelfth month 31st, 1827.

[.salutation]
My beloved Niece,

I am inclined to believe that we both accede to the
truth that it is well for those who can look back,
uncondemned, on the past year, and recount their mercies.
With humility and contrition we may see, and mourn over our omissions and commissions,
our defects and infirmities; to this very day I am as weak, of myself, as the least babe;
by watching unto prayer, is my faith renewed, my hope of entire sanctification,
and of salvation.

I dare not cherish dismay or discouragement, though I secretly mourn,
in times of deep humiliation; but with reverence and thankfulness,
my heart owns the mercies of God in Christ Jesus.
O! how unspeakable is the favour when we stumble not at those things, which, as yet,
we do not comprehend, but with reverent fear, keep low,
and patiently wait for farther illumination.
May presumptuous disputation ever be kept from us,
and from entering the thoughts of a rising generation!

--

+++[+++In the early part of 1828, Mary Capper visited her friend Sarah Lamley, at Tredington;
and about the 14th of first month, went to Warwick,
where she found her long-loved friend Hannah Evans much indisposed,
and concluded to remain with her for a time.
It proved to be to the conclusion of her course.
They were permitted many times of much enjoyment together, during Hannah Evans`' decline,
partaking of the sweets of true Christian friendship and love.
While there Mary Capper heard of the death of a friend to whom she was much attached,
respecting which event she wrote to Richard and Elizabeth Cadbury as follows.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard and Elizabeth Cadbury

[.signed-section-context-open]
Warwick, First month 25th, 1828.

[.salutation]
My kind Friends,

On all occasions I witness your prompt exertions
and affectionate desires to serve and gratify me.
What shall I render for the continuation of mercies which I consider
as flowing from a far purer source than any good in me!
I wrestle in the spirit of prayer,
that a thankful heart may crown every blessing so graciously bestowed.
The details respecting our late endeared friend have been perused with no common feelings,
the thoughts of my heart have been night and day occupied on the solemn subject.
O! that ten thousand times ten thousand may be gathered
to the standard of the Christian faith,
the faith in which this, our highly favoured friend, lived and died;
in the glorious hope of salvation, through Christ Jesus, who shed his blood for sinners!
To see how a Christian can die is a privilege; but to die the death of a Christian,
clothed with the light, and life of our Mediator and Advocate with the Father,
O how glorious!

--

+++[+++In a memorandum made at Warwick, Mary Capper says, respecting Hannah Evans,
"`I was favoured with strength to attend my beloved friend in the last conflict of nature,
which was suffering in the extreme, from sickness,
etc. so that I was thankful when it ceased.
She died on the 13th of second month, 1828;
and although I have to mourn the painful void,
I am thankful too for the retrospect of our precious union and fellowship.`"

Mary Capper attended the yearly meeting this year,
and remained in and about London till the seventh month,
visiting her friends and relations.
Her only sister, Rebecca Tibbatts, was then in poor health;
and on the 5th of the seventh month, she departed this life,
at the house of one of her sons, who had long made her a comfortable home,
and been affectionately attentive to her.
Mary Capper was much gratified in being occasionally with them,
and witnessing their mutual attachment; she also was comforted in the belief,
that it might be said of her dear sister, who had had many sore tribulations,
that her last days were her best days.
She died meekly confiding in her Saviour, and exclaiming, "`Happy, happy, happy!`"

Thus rapidly was Mary Capper stripped of her near relations and friends; but through all,
she was enabled to confide, and to rejoice,
in Him who had attracted her to Himself in early life,
and for whom she had been enabled to give up all.
He proved Himself to be to her a never-failing friend, almighty to console and support.

She was much tried, while in London, by the serious illness of her faithful servant,
Hannah Simms, who had lived with her eight years,
and whom she had taken to town with her as her attendant.
Hannah Simms was, with difficulty conveyed back to Birmingham,
to which place Mary Capper also returned in the eighth month; on the 23rd of that month,
Hannah Simms breathed her last; much regretted by her affectionate mistress,
though she writes on the subject, "`I was favoured with a calm,
lowly resignation of my will to that Divine Power who reigns over all,
and who orders all things well.
My kind and attentive friends,
Richard and Elizabeth Cadbury propose my being their inmate for a few days,
and E. C. with the affection of a relative, came for me.
I have some consoling ground to believe that dear Hannah Simms has, for some time past,
been under the refining hand and power of the Redeemer,
who prepares a place for all those that patiently abide the fire and sword,
sent to separate the precious from the vile.
Her hope of salvation was fixed on the immutable Rock of Ages, and this Rock is Christ.`"

An awful visitation of fever was permitted this year at Ackworth School,
and many who attended the general meeting, were made partakers of the affliction.
Rebecca Dickenson, a lovely young woman, the daughter of Barnard Dickenson,
of Coalbrookdale, took the fever there, and died, after about twelve days`' illness,
at Darlington, where she had gone on a visit to the house of John Backhouse,
whose young people also took the same complaint at Ackworth.
While they continued struggling with the fever,
Mary Capper wrote to her niece Katharine Backhouse as follows:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, Ninth month 5th, 1828.

[.salutation]
My dear Niece,

Yesterday I received the affecting account of your trials; my own sink in the scale,
as of minor weight, save only, as in some sort,
they fit my heart and spirit to enter into sympathy with the afflicted.
O! how sweet and confirming when the young Christian believer,
thus called away by the Lord at the early dawn of the day,
can emphatically testify her only trust, her hope and her joy, to be in a Redeemer,
a Saviour from sin and its condemnation; how this encourages us to press forward,
though we may mourn the privation!
The dear friends who have been bereaved may allowably indulge a tender sorrow,
but I hope they will be comforted by the evidence of their dear child being safely landed.
For you and your children, affecting as the event has been,
and painful as is the uncertainty which still rests on the future,
my faith points to the Rock of our salvation,
trusting that the sustaining arm of Divine help will be underneath,
in the trials of each succeeding day.
Your dear Ann, in her weak, low and suffering state, with sorrow around,
may prove a favoured scholar in the school of Christ, her Redeemer.
This sickness, not being unto death,
may be to the manifestation of the power and glory of God.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Birmingham, Twelfth month, 1828.

[.salutation]
Dear J. and C.,

Accept my little offerings; though trifling, they are tokens of my affection towards you,
and`" your dear rising children.
It cheers some of our hearts, yea, those who are not parents can rejoice in believing,
that in these days of deep trial and sadness, there is an unchangeable power,
sparkling and more powerful than the vivifying outward sunbeams,
in fructifying the seed of the kingdom of heaven,
although the storm and the blast beat terribly.
In deep reverence and Christian humility may we cherish the hope sure and steadfast,
that the dark days will pass away, the winter be over, the voice of the turtle,
the singing of the birds, will be heard in different dwelling places.
Hold fast your integrity my Christian fellow believers
of the mercies of God in Christ Jesus.
Train up the lambs as of the flock of Christ committed to your charge in the wilderness.
Suffer not the dear children to gain dominion over parental authority.

My love, please to express impressively to your mother W.,
she is very affectionately in my remembrance.
It is unnecessary I should enter into domestic details.
I hope we are each desirous to be found in the right path, whether in the commencement,
or drawing to the close of time.
I subscribe sincerely your friend,

[.signed-section-signature]
Mary Capper.

--

+++[+++Ann Backhouse, did apparently recover from the fever,
but symptoms of consumption showed themselves early in the following year;
and Mary Capper thus writes to her afflicted parents:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Third month 11th, 1829.

Very many are the trials, and various the provings of faith and resignation at this day;
but shall we call in question the dealings of Omnipotence,
in whatever is brought upon his servants?
Rather may we unite in prostration at his footstool,
supplicating that neither things present nor yet to come may shake our Christian confidence.
Entire reduction, perfect submission to the Refiner`'s power,
seems in my view a great work, a work of wonder, but a needful work; for here indeed,
no flesh can glory.
My kind nephew! thy communication of affection and unity is truly acceptable;
surely it is well thus to encourage one another.
The declining health of your endeared child is indeed affecting;
a rose in the bud is no small sacrifice;
but to bloom in perfect beauty sheltered from the storm and blast,
O! how cheering to the Christian believer is the prospect.
We may weep, but there is a balm to mollify our wounds.
Your precious child is gently dealt with, to be thus kept,
by the power of redeeming love, patient and calm,
and no way dismayed at the apprehension of an early dismissal from the world,
"`with life`'s bitterness untried.`"
The God of all consolation, who comforteth those that are cast down, be with you,
and manifest his power, in a day of trouble.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Fifth month 11th. 1829.

[.salutation]
My kindly partial Friend,

I would relieve thee from thy solicitude as to my health, which is improving.
O! for sanctification of spirit; I feel far short of this;
and no doubt it is safe to be humbled at the Redeemer`'s feet;
what else can keep us from falling,
through the power of temptation suited to our various temperaments.
Let us pity the fallen, and fear for ourselves.
To thy dear husband`'s sister, under solicitude for the sight of her eyes,
so precious a gift,
I wish to express the love and sympathy of a fellow pilgrim toward the Celestial City,
where there is no darkness at all!

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To B. C. and M. C. In London at the Yearly Meeting.

[.signed-section-context-open]
Warwick, Fifth month 28th, 1829.

[.salutation]
My kindly interested Friends,

Whilst you are met in a large number,
for the help and strengthening of the different members, imploring that healing balm,
which can comfort the mourners and cure the wounded,
the solitary ones may also have their portion of exercise in spirit.
I believe my right place was with those left at home, stripped of many,
whose countenances and help are missed; however, it is perhaps wisely ordered,
as it breaks our dependence upon human aid, that our faith may be increased.
It is likely that you would hear of the death of John Whitehead.
I felt bound to attend the interment, for which purpose I came to Warwick; you,
my dear friends, may judge that it was no light matter to me, to sit as one alone,
to be gazed at by a very large concourse, but my mind was kept calm.
O! how condescending is our heavenly Father.
Can we, his poor children, be too humble, too watchful!
I hope what was spoken was right; no condemnation rests upon my spirit,
which I consider a great favour.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To C. B. C.

[.signed-section-context-open]
Leicester, Seventh month, 1829.

I have abundant cause, with reverence,
to acknowledge that all things needful to my comfort are provided for me;
living as in the bosom of affectionately attached friends, what can I desire more,
but an increase of humility and of thankfulness,
and of watchful obedience to the beneficent author of all our mercies.
Thy love is very precious to me; it is a sweet cordial, in lengthened years,
to love and be beloved.
May we continue to look straight on, toward the mark for the prize of our high calling,
undismayed by those things that are brought upon us, in our pilgrimage journey.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Warwick, Ninth month 28th, 1829.

My well esteemed Friends, and endeared by long continued family attachment,
and repeated acts of kindness and attention to me in particular,
still manifested by parents and children; `'tis my wish to cherish the union.
I hope that with true thankfulness of heart,
I may on my part acknowledge the mercy and heavenly favour,
that like the knot more and more closely tied by receding in opposite directions,
we are strongly bound in spirit and fellowship by the safe immutable guide of salvation;
though sea and land may separate us from personal intercourse,
and the time draws nigh when present scenes will be changed,
and an eternity open to our view; oh, `'tis a mercy not to be set forth,
to contemplate a Saviour--to know that our Redeemer liveth,
and that in him we shall see God.
I enter not into the disputations of the present day; notions, differing opinions,
and futile arguments upon subjects too high for human capacity, are no new thing;
they had early place in the wise and learned of this world, who are recorded,
and may yet be reputed, as wiser in their generation than the children of Light;
the God of pity and of mercy, past our finding out, may open the blind eye,
and unstop the deaf ear of those who as yet do not see aright.
`'Tis a mercy when a plain path is set before us, and experience confirms our confidence,
that in watching unto prayer and simple obedience to manifested duties, is our safety,
and keeps the host of enemies within and without,
so far in subjection to the power of the truth as it is in Jesus,
that we hold no parley with them.
This, dear friend, is the path of my religious experience,
and I find nothing in my advanced years (74,) that induces me to let go my humble,
yet confirmed confidence in the propitiation, the redemption,
the purifying spirit and reconciliation to God the Father,
by the mediation of Jesus the Sent of the Father, as set forth in the Scriptures,
preserved from generations for instruction, or reproof, or consolation, unto this day.
The doubting, disputing mind, claims pity; `'tis a sad unsettlement;
why should we pry into secret things that belong unto the Lord?
Enough is revealed to satisfy a humbled obedient heart.
What is now hard to be understood,
it may be because we are not prepared to receive
it whilst clothed with infirmities of flesh and blood,
is it not safest and best to leave in the hand of that gracious creative Power,
who has formed man for glory and for virtue?
Oh! it is good to feel submissive lowliness and godly fear,
that no presumption get dominion over us.

I would still in much sincerity express my Christian love
and unfeigned good will to every branch of your family,
known and unknown, and subscribe, as in days past,

[.signed-section-closing]
Your real friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To C. B. C.

[.signed-section-context-open]
Dudley, Eleventh month 4th, 1829.

The report from your dear parents is truly acceptable; the retrospect of years 2;one by,
when, in our youthful vigour, we joyed together,
and exchanged lively tokens of affection, seems to touch a tender chord yet in tune,
and raises tears; not tears of murmur or regret, ah no! but of grateful recollection,
that enduring Mercy has kept us from the broad way of destruction,
and in adorable compassion, forsakes not in old age.
In sickness, weakness and suffering, when mental and bodily powers fail,
O! how consoling is the belief that the arm of Omnipotence sustains us,
sanctifies every dispensation, and prepares his children for a glorious immortality;
a purchased possession for the ransomed and redeemed of the Lord.

[.signed-section-signature]
Mary Capper.

--

+++[+++Early in the year 1830, Mary Capper went to Coventry,
where she was detained by a lingering illness, the effect of a cold.
While there she wrote:]

[.embedded-content-document.letter]
--

[.letter-heading]
To J. and Katharine Backhouse

[.signed-section-context-open]
Coventry, Second month 4th, 1830.

I should not now, perhaps, call to mind your days of sorrow, in the bereavement,
and in the deposit of the remains of your beloved child among strangers; but,
with you my dear relatives,
I have a grateful remembrance of the mercy mixed with the dispensation,
by that gracious Being who fitted and emancipated
the soul of the young Christian for heaven.
I seem gently impressed to communicate the language which arose in my heart,
on reading thy testimony, my dear niece,
corroborated by others who knew something of the life and manners of your precious child;
the language still arises with freshness, Happy,
happy spirit! so early released from a mortal tabernacle.
May we not say, favoured to know comparatively little of life`'s bitters,
and spared the many conflicts which, in the allotment of unerring Wisdom,
the wrestling spirit has to endure, in life`'s protracted, lengthened span.
But who shall say to the righteous Judge of the whole earth.
What doest Thou?
O! for a calm and quiet mind, to live by faith,
a simple faith that asks not why or wherefore, nor requires sensible tokens,
but receives the transient gleams of good, from the most excellent Glory,
with deep reverence and gratitude.
This is what my spirit presses after, not as having attained, but I dare not halt,
through unbelief.
Your lonely situation, in a foreign land, may be blessed;
you and your dear children may seek and find, by patient waiting for it,
the refreshment which cometh from the presence of the Lord.^
footnote:[See notice of Ann Backhouse, in Memorials of deceased Friends, by S. Corder.]

I am almost weary with writing, and have not yet noticed your pleasant prospects,
myrtles, orange trees, etc. the snow-girt mountains, and the volcano.
Admirable I doubt not; but my little home in Dale End suits me better.
I hope you may be favoured in due time to return
in peace to your own country and endeared friends.

--

+++[+++On the 29th of the third month, Mary Capper made the following memorandum:
"`I have had so much fever as greatly to reduce my strength,
and am still nearly confined to my bed and chamber.
This is a trying dispensation, though made comparatively easy by many mercies;
let me gratefully acknowledge favours received!`"

[.offset]
About this time she addressed these lines to the friends where she was staying:]

[.embedded-content-document.letter]
--

[.letter-heading]
To J. and S. C. While resident under their roof, in much bodily weakness.

[.signed-section-context-open]
Coventry, Third month, 1830.

As an individual incorporated into the Society of Christian believers,
denominated Quakers, not by education nor much familiar intercourse with any of them,
not in my minority, but in more advanced years of my life; and having seen,
with serious observation,
it may be rather more variety of scenes and manners
than falls to the lot of every private person,
I may say, that although I was ignorant and as easily led into folly as my associates,
brought up in the same habits and dissipations, there were times when I was led,
in deep thoughtfulness, to query with myself, What is a profession of religion?
Having, at an early age, gone through the forms of what is called our National Church,
and with reverence partaken of the outward and visible
sign of faith in the blood of Christ,
as an atoning sacrifice, ofttimes it arose in my mind, What has this done for me?
Does the inward and spiritual grace subdue my evil propensities,
and direct my steps into a path of circumspection and self-denial,
consistent with the promises made for me in my unconscious infancy,
and afterwards made binding, on my own responsibility,
as I came of age to understand the nature and import of the engagement?
I was aware that the ceremony was but a shadow of the substantial good.

I simply relate my own experience, implicating none; "`to our own master,
we must stand or fall.`"
Without a laborious investigation of the opinions of the various denominations of Christians,
but not without sacrifices, hindrances and discouragements, by little and little,
not rashly, but after mature deliberation, in simple obedience to apprehended duty,
I attended the religious meetings of Friends.
To me, solemn and reverential was that stillness, that silence,
which seemed to hush every thought.
I believe, that in this still calm, there is a renewal of spiritual strength to be known;
yea! an enlargement of spiritual understanding, in communion with the Father of Spirits,
which surely is true, spiritual worship.
Thus, as an individual, I was led step by step,
and found no difficulty in comprehending the ground
and consistency of adopting plainness of speech,
behaviour and apparel; all seemed consonant with apostolic counsel, evangelic doctrine,
and the example of the early Christian converts.
A corruption of language and of manners has crept in,
and is adopted by many Christian professors, in the present day.

The Society of Friends having seen this,
and being gathered in early times as a '`people turned to a pure language,`'
I marvel not at their setting a cautious guard against innovations.

[.signed-section-closing]
A friend to consistency though no dictator,

[.signed-section-signature]
Mary Capper.

[.postscript]
====

N+++.+++ B. It has been remarked that the Romans were particularly
careful to preserve the purity of their language.
The state itself, it seems, thought it a subject so worthy of attention,
that no innovation was allowed, in their public acts, without permission.
Seneca gives it as a certain maxim,
that when a false taste in style or expression prevail,
it is a sign of corruption of morals in the people.
(See Pliny`'s Letters, Book the First.) Why not apply this to our present instructions?

====

--

[.offset]
+++[+++Mary Capper appears to have returned home in the fourth month, whence she writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Fourth month 30th, 1830.

Express my affectionate remembrance to A. F. To her this is a mournful bereavement;
but what can we do better for ourselves and others, in the day of trouble,
than in the exercise of humble, though firm confidence in prayer, to cherish hope!
O! had we been a rightly praying people,
surely so much declension had not spread among us.
May there be, through a rising generation, a revival of true spiritual mindedness.

My long confinement, at Coventry, under the kindest possible care,
has left me somewhat reduced; but, through all, I was passive like a weaned child,
and even cheerful and thankful.
Ah! dear M. this was nature subdued; and now, at a lengthened out day,
my heart`'s most earnest desire is to live near to
the subjecting power by which this is effected;
the power, if I understand aright, of the cross of Christ.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Birmingham, Fifth month 25th, 1830.

[.salutation]
Dear J. and C,

This is a day and time of important serious interest, yet I do not,--as a poor,
short-sighted individual,
measurably quickened and made alive as I humbly hope
by Divine grace,--I dare not cherish dark,
gloomy, dismaying views, though I hear sad tidings of pernicious principles,
and I am well aware of bad practices.
Alas! for the poor hearts,
that are not changed,--sanctified by a new and spiritual birth in Christ Jesus,
the Light, the saving Life in man!
If we can feel pity and compassion one for another, oh! how short,
how imperfect our comprehension of that love,
that tendering mercy which brought a Saviour down
to suffer for sin and sinners,--`'tis a glorious,
marvellous theme! and sometimes put to silence, solemn silence,
all that would rise in judgment within me, either as to the dead or the living.
My solemn interest is to know more fully than I yet know, Christ my Redeemer,
as my perfect reconciler to God the Father, being cleansed from the guilt of all sin,
by the atoning sacrifice of the Son of God, as testified in the Scriptures,
and opened to the understanding of my humbled praying spirit,
I never felt these Divine truths more consolingly than in the time of
a late reduction of bodily strength and deep humiliation of mind,
wherein I had no high or luminous thoughts; but as a poor dependent child,
my views of a Saviour`'s compassion and power, were very, very sweet, calming every fear,
and putting to silence doubt.

I have scribbled this whilst an inmate in thy father`'s house--as I was left alone,
and a clothing of peaceful serenity around me, it came into my mind to acknowledge,
that your conjoint messages of affectionate remembrance are cordially accepted.

May lowly peace in the love of a reconciled God through Christ Jesus our Redeemer,
be the blessed portion of you, of your children,
and of all those who are near and dear unto you,
is the unfeigned affectionate desire of your Christian probationer and friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Seventh month 26th, 1830.

[.salutation]
My very dear Friend,

Do accept a short but grateful acknowledgement of thy friendly communication,
with the instructive memoir accompanying it.
O! that I may die the death of the faithful, and that my end may be like his;
may my close be calm, lowly and peaceful;
but even this it is best to leave to a faithful, just and wise Creator.
Death has not always been disarmed of terrors, even to the upright,
and I wish to leave it to the Lord; to whom I desire to resign soul and body,
with all that I have and all that I am.
Lowly obedience has consolations in this life,
and the bright beams of hope sometimes break forth out of darkness;
so the safe path is perseverance.
Dear John Pumphrey called this morning; he is a pleasant picture of old age.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Ninth month 14th, 1830.

In these places there has been great stripping;
elders and standard-bearers have been taken from this scene of trial and probation;
some of their successors have turned from the narrow path,
and by imprudent marriages and other deviations, have defrauded their own souls,
and mingled their cup of life with many bitters; added to which,
I consider it a serious wrong to children`'s children.

If the Good Shepherd were not enduringly merciful, what indeed should we do?
but when the sorrowing heart is humbled,
in the house of sore bondage and in the land of captivity,
where the cruel enemy of all good has carried them,
then if they cry unto the Lord like captive Israel, O! then, in pity,
heavenly mercy delivereth them out of their distresses.
Some circumstances have very seriously affected me;
for although my view of mercy is large,
yet it bows down my soul to see mercies received and lightly esteemed.
But let me turn to a brighter prospect.
There are, I hope, not a few, within the borders of our own religious Society,
who prize their privileges, and who have the heart-humbling,
tendering belief of the forgiveness of sins, and sanctification from sin,
through the mercy of God in Christ Jesus.
These, with my own soul, watch unto prayer, enduring hardship,
as soldiers engaged in combat.

[.signed-section-signature]
Mary Capper,

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Second month 14th, 1831.

My much-loved niece! perhaps never being in more sweet union than at this day;
having our senses exercised to discern good and evil,
through that measure of mercy which has not left us to perish
in ignorance or unbelief Since I last wrote to thee,
I have been almost a prisoner, from debility and loss of appetite.
I was nearly ready to conclude that the remaining
springs of natural life were gently wearing away;
but a childlike, cheerful confidence kept my spirit calm and undisturbed.
O! what shall I say of the free mercy that thus sustains me in lively faith and hope;
not for any dedication or faithfulness in me.
Ah! no; I am a poor weak child, an unprofitable servant,
if ever I have done ought of service in our holy Saviour`'s house.
Mercy is my only plea for favour here, and for acceptance hereafter.
Again my bodily vigour is a little revived; it is the great Creator`'s will,
so may it be to his gracious purpose.
I dare not foster a will of my own, knowing that I am weak and blind.
The religious prospect of your kinsman James Backhouse, his affectionate mother,
his dear bereft children, are subjects of much interest;
but all centers in the will of God.
We may rest in gospel promises,
whatever is given up for the sake of fulfilling this requiring;
but what could be the happiness of a Christian in disobedience,
though possessed of houses, lands and kindred; yea, of all that this world could give?

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Coventry, Tenth month, 1831.

My oft remembered friends and tenderly beloved members
of kind and dear connections round about me,
whose kindness is of so long continuance from parents and children,
that it is no marvel that I feel some affectionate
interest in the well-being of children`'s children,
which seem to multiply and spread as in my own family like olive branches;
and though a young scion is sometimes taken off`", in its early tender state,
to ripen and mature in a better clime,
sheltered from every possible blight or chilling blast, may we be grateful,
and acknowledge the gracious Power that cultivates the yet live branches, watering,
pruning, fitting these to bring forth good fruit in due season.

I am now permitted to enjoy the fine fresh breezes of this pleasant autumnal season,
congenial to invigorate with the gratifying society of long known friends.

To you dear friends, what can I say more than I have in time past expressed.
May uprightness and integrity guide you and all yours;
may the balmy breath of a Saviour`'s peace be the
clothing of our spirits in time and in eternity,
in life and in death!
So craves the heart of your fellow probationer and affectionate interested friend,

[.signed-section-signature]
Mary Capper.

[.postscript]
====

Old England preferred with all her faults and commotions.
Nations, kingdoms, tongues and people, will have an end,
but heavenly power and mercy endure forever and forever.

====

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Fourth month 7th, 1832.

On the eleventh of this month, if my life be lengthened to that morning,
I shall have seen the end of seventy seven years.
I still feel as a child, depending upon a tender Father`'s daily mercies;
upon Him who has taken my earthly parents to Himself, I assuredly believe.
O! the goodness and mercy that follows their children, yea,
I doubt not their children`'s children.
My dear mother was a woman of prayer, private prayer;
the remembrance is precious to this day;
in my early days her influence led me to bow at the footstool of mercy,
at least often to retire in secret; and in some favoured seasons,
I had to shed sweet tears of tenderness, arising from the desire to be good,
for I was aware of evil in my heart.
Who can set forth the compassion which has followed me, and does yet help,
teach and comfort me! that has united me to a people whose genuine
religious principles satisfy every faculty of my soul,
and are my strong consolation, with hope in a Redeemer`'s love and power;
even that He will complete his glorious work, and own me among his ransomed ones.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Fifth month 25th, 1832.

[.salutation]
Dear John and Sarah Grubb,

The salutation of an old friend, if in any sort it may be in the newness of life,
I seem constrained to believe, you will not reject.
Many years and many events have passed, dear Sarah,
since our personal intercourse with each other, and with dear friends in this place,
now gathered to their rest;
the remembrance arises in liveliness before me--no bitterness mingled therewith.
Thou wast then engaged with dear, faithful, lowly-minded Ann Baker.
In my little measure I loved you then; and I cherish the hope that,
in the school of experience, my best love increases,
with the increase of my union and fellowship with the long-tried, faithful labourers,
in the present day of sifting, and of deep plunges, even as in the pit of darkness,
tumult and dismay.
Well, dear John and Sarah Grubb, is it not a marvellous mercy, that, as a people,
we are not forsaken!
Prophets and prophetesses are yet raised up among us.
May these go on in the strength of the Lord.
Accept this my poor offering of affection in the seventy-eighth year of my pilgrimage,
and permit me to add, that with reverence and heart-contriting thankfulness,
I acknowledge the mercy that united me to a religious people,
whose genuine principles of faith in Christ Jesus, as a Mediator, a sacrifice for sin,
and reconciler to God the Father, through justification and sanctification,
is fully satisfying to every faculty of my soul, as the glad tidings of salvation.

[.signed-section-closing]
Farewell, friends beloved in the fellowship of the Gospel,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Sixth month 7th, 1832.

[.salutation]
My kind Friend,

How inexpressible is the privilege of a retired apartment,
in the very midst of contention; how privileged we, as a Society are,
if we keep within the limits of our religious profession.

I think that "`Hancock`'s Principles of Peace,`"
exemplified in the conduct of the Society in Ireland,
in 1798, cannot be too attentively and generally read.
Whatever may be the result of the unsettled state of nations, kings and kingdoms,
there is a ruling Power, above every other power.
May this be our help and our shield.
Poor devoted Paris! after the destructive pestilence,
follows the more destructive desolation of sword and bloodshed.
O! for an interceding, praying spirit, for ourselves and for others,
that a sure place of refuge may be known.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Eighth month 16th, 1832.

I attended our quarterly meeting held at Shipstone;
we were favoured with the company of some choice, ministering friends;
John Dymond and wife, etc. etc. Shipstone is a small meeting;
I profess myself a lover of society, and I think there is an advantage,
especially to the young, in living more in a body together;
though no earthly situation is secure from the venom of sin;
nor is there a solitude which excludes a Saviour`'s redeeming love.
I was absent longer than I had anticipated, as I felt a little bound, if I may so say,
to attend the meeting still annually held at Armscot, a village not far from Tredington.
I accompanied dear Sarah Lamley;
she is well-known and highly esteemed among the villagers thereaway;
and she seems peculiarly qualified to preach in plain, searching language to them.
A very large crowded meeting there was.
I was also at the small meetings at Camden, Brails, etc.
The overshadowing of mercy is to be experienced everywhere.
O! how it would flow, did every heart watch and pray.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To C. C.

[.signed-section-context-open]
Birmingham, Tenth month 2nd, 1832.

[.salutation]
My dear Friend,

I am concerned to hear that thou art suffering,
and I believe it will interest thy affectionate feelings, to learn,
that I am again in the school of reduction, I hope not in displeasure,
but for my profit and purification.
What can we do better, my precious friend, than resign body,
soul and spirit to the Power that formed us,
and who best knows how to fit and prepare us for a glorious inheritance.

Cloudy days and an oppressive atmosphere may be our portion, in our pilgrimage journey,
and I was thinking that we may even look for boisterous gales at times; but in our case,
they may only be permitted, I trust, to sweep away the chaff,
leaving the substantial grain to be gathered in security.

[.signed-section-closing]
Accept the unfeigned love of,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel H.

[.signed-section-context-open]
Twelfth month 18th, 1832.

[.salutation]
Dear S. H.

Thou art very often in my affectionate thoughts; and this morning more especially,
as my heart was tendered before the Lord, I thought of thee,
with something like the interest of a Christian mother.
It is obvious that thy health is precarious,
a consideration that must be trying to a young man, in the opening day of human life,
with the prospect of a settlement, as to a maintenance.
But, dear Samuel, the Power that mars these prospects, can provide better things,
for his children and people, though seen through a glass darkly.
Bear in mind, that however kind, and even amiable, any may be by nature,
there must be a change of heart experienced, termed in Scripture a new birth,
or new spiritual creation, through the secret operation of Divine Grace in the soul.
My measure of experience disposes me to feel tenderly
for those in whom this work is begun,
because I am aware that it must be carried forward through
humiliations and close provings and searchings of heart.
Nature has her strong holds;
but be not discouraged though the triumph of Grace be a great work.
The Divine Power is above every other power,
and can complete as well as begin that which is our sanctification.
I know there are times when our faith is so weak that we
can scarcely read and understand the Scriptures;
this is no new thing; our prayers too may seem unavailing,
and clouds of thick darkness may appear to envelope us; but we must persevere in earnest,
wrestling prayer, though it may only be with sighs, and conflict unutterable.
And dear Samuel, I would say, enter into no disputations.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Twelfth month 26th. 1832.

I seem gratefully constrained to acknowledge thy cordial Christian salutation;
how inexpressibly precious is Christian fellowship! it is a feeling which has no fellow.
My heart was tendered in reading thy lines, at a time when the pure life was low,
though I may thankfully say it is yet preserved.
No marvel if there is a secret sense of sorrow for
the too general prevalence of spiritual deadness,
and for our own imperfect views of heavenly things,
the ways of our God being past our finding out.

But when the redeemed, sanctified soul shall be unclothed of the frail body,
then shall we know as we are known, of Him who purchased salvation for us.
Great and glorious is the new and living way which
he has cast up for faithful believers to walk in.
When pondering these things,
all that is spiritually alive within me seems to be humbled and contrited,
under a sense of the infinite condescension that
has turned my feet into this blessed way.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Fourth month 4th, 1833.

I do not say short and evil have been the days of my sojourn,
though ignorance and folly have had their share therein.
Never did I view heavenly mercy, free and pardoning Grace,
brought to light by our Redeemer and Saviour, more clearly, more consolingly,
than in these times of stripping, when self has not a rag to clothe itself with.
I believe that those are not our most favoured moments
wherein the subtlety of self can take a part;
but that when the good leaven is deeply hidden, it works the designed end.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Fifth month 24th, 1833.

[.salutation]
My dear Christian Friends,

Contenders for the faith, or the Truth, as it is in Jesus!
Still ye are called to labour, the end not being yet,
when the faithful shall receive their full hire.
At this time of renewed exercise, you are again fresh in my remembrance;
there is fellowship in the lowly valley of humiliation,
however differing in degree and circumstances.

In my solitude, may I say it with reverence,
a spark of spiritual life is mercifully kept from total obscurity,
though death and darkness seem, at times, to hover round me.
O! the mercy that glimmers, or arises out of darkness.
Surely our Heavenly Father deals gently with the feeble of the flock.
I can bear my testimony to his protecting power, the internal evidence,
manifested in the soul.
O! how it checks, how it teaches, how it guides from childhood to the oldest age,
just according to our state,
obedience opening the way to an enlargement of spiritual understanding.
Marvellous are the Lord`'s dealings with his humbled, patient, believing children.
O! that there was a believing heart in every child of man;
there would be no need to puzzle and bewilder the mind, in things too high for us;
secret things would be left to the Lord.
I am set much as a solitary one, though in the bosom of kind friends.
Shall I be presumptuous if I record, with feelings of great seriousness,
that my prevailing exercise in this my latter day, is secret, wrestling prayer,
oft on the bended knees, in my quiet, secluded chamber.
My spirit craves for more evident marks of godly simplicity among the Quakers, so called.
I am one of those who mark the boasted "`march of intellect`" with a jealous fear.
The refinements of our day seem, in my view,
to draw the mind from under the cross of Christ.
According to my observation, we are not the plain, unfashionable people that,
if faithful,
we should be we are too generally intermingled with the manners and maxims of the times.
Everlasting Mercy can yet turn and overturn, and settle a faithful people.

[.signed-section-closing]
Farewell, dear friends, subjoins,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To C. B. C.

[.signed-section-context-open]
Birmingham, Fifth month 31st, 1833.

[.salutation]
My kindly affectionate Friend,

As I sit solitary, and contemplate the close of time,
the mind being measurably free from care as to this life (which with thankfulness I
may record is mercifully my allotment) the thoughts of the heart take a wide range,
and I think of my fellow-probationers, in their diversified circumstances.
If there were not a heavenly pilot, through storms and clouds, what should we do?
The most skilful human mariner could not steer the vessel aright, nor save her from wreck.

I think, with tender sympathy of thee, and of thy dear parents in their suffering;
but there is the consoling evidence of the building being on the sure foundation,
the Rock of Salvation, that cannot fail; though the body be dissolved,
the redeemed soul will return to God, as a glorified spirit.
There is strong consolation for the humble believer,
in the unalterable mercies which are in Christ Jesus; though bereavements are permitted,
and we are left to mourn, but not without hope, nor even without, at seasons,
a transient view, as it were,
of the glorious mansions prepared for those who have held
fast their confidence in redeeming love and power,
unto the end of the Christian warfare.
Accept the grateful acknowledgement of the love of

[.signed-section-closing]
Thy oft-obliged friend,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Sarah Grubb to Mary Capper.

[.signed-section-context-open]
Stoke Newington, Sixth month 10th, 1833.

[.salutation]
My dear Friend,

Thy salutation of love by letter is precious to us,
as the long-continued friendship thou hast evinced has always been.
How encouraging it is to see those who made many sacrifices in early life,
for the Truth`'s sake,
not satisfied to rest in past experience even of the Lord`'s goodness,
but as those who remember that "`He that thinketh he knoweth anything,
knoweth nothing yet as he ought to know;`" and even in old age,
are concerned to go on learning of Him who said, "`I am meek and lowly in heart.`"
I am glad that thou canst so fully subscribe to the "`Anointing,
which is truth and no lie;`" the Unction from the Holy One, as an internal evidence,
manifested in the soul.
What shall we do if we suffer ourselves to be drawn
from this blessed Spirit of the Saviour of men,
or from the measure thereof, which is given to all for our profit!
Where, but within our own hearts shall we find the Comforter and the safe Guide?
Surely the Holy Scriptures direct us to Christ! Surely
the holy Scriptures direct us to Christ within,
the hope of glory; but now we are told, that in looking for inward direction,
we subject ourselves to error; and that the Gospel is to be found in the scriptures,
where there is "`clear, comprehensible truth,`" and "`a direct message from God.`"
True, the Scriptures came by inspiration of God; yet, in my view,
the same inspiration must be with us,
to give us to comprehend their spiritual meaning and application;
because the natural man, by all his head knowledge and finite capacity,
even though he may compare scripture with scripture, and acknowledge to their harmony,
is, nevertheless, the natural or unregenerate man still,
without the operations of the Spirit in his soul;
even that which is the Divine gift to all men, and which, I conceive,
brings all who adhere to it, into a converted state,
whether they be favored with the inspired writings,
which tell of the blessed and holy Redeemer, or whether they be ignorant of them.
Must it not be our experience,
in order to partake of the benefit of the death and sufferings of Christ,
to be brought into obedience unto righteousness?
And what can do this for us, but the power of God, or name of Jesus,
which is immediately made known to us by inward revelation thereof?

In short, my dear friend, I feel alarmed in seeing that we, as a community,
are in great danger of leaning to the understanding of man,
in this day of the truly surprising "`march of intellect;`" and that,
for want of trusting in the Lord with all the heart,
we are going off greatly from first principles;
intermingling indeed with that which is not distinguished by gospel simplicity,
but which has a tendency to bring us to be satisfied with many things, out of which,
as a people, we were brought by a strong hand and a stretched out arm,
which delivered from the iron hand of cruel persecution,
as well as from all false dependence in religion.
All will not, however, thus return, either to the maxims and customs of the world,
or to the beggarly elements, to be again brought into bondage; a precious seed remaineth,
and will remain, however hidden,
in which the real life of the crucified Immanuel will be found;
and who will by and by come forth, and shine as the children of Him who is light,
and in whom is no darkness at all.
Yea, I believe it shall yet be the earnest inquiry,
relative to such as abide in the truth through all,
"`Who is she that looketh forth as the morning; fair as the moon, clear as the sun,
and terrible as an army with banners?`"

Ah!
My long loved friend, I am persuaded that thou dost know what thou professest;
and the possession of the truth as it is in Jesus,
has been thy primary concern in the different stages of life: thou hast now, at times,
the certain evidence of having been kept from following "`cunningly
devised fables;`" and I humbly trust that the saying of Him who
enabled thee to separate thyself unto Him,
from all that is found in the apostacy, will be realized to thee-- "`Lo,
I am with you alway, even unto the end of the world.`"
Amen, saith thy ever affectionate friend,

[.signed-section-signature]
Sarah Grubb.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Seventh month 5th. 1833.

[.salutation]
My dear Friends,

I seem constrained to acknowledge
the receipt of your interesting communication.
My feeble faith still holds out, that the Lord`'s own works will praise Him.
O! He has done wonders, in generations that were before our days;
that passed through the sea and through the cloud, and the Rock followed them,
which Rock is Christ, revealed in the soul, believed and cherished,
as a Leader and Teacher, made known to the simple, faithful humbled heart.
Happy, they who cherish this belief,
and truly desire to know the Lord to be their Teacher; for He leadeth gently along.
He careth for the lambs, and He feedeth his own sheep,
in pastures convenient for their growth; the herbage may be mingled with bitters,
but this may prove a strengthening portion.

To you, my much-loved friends, I need not scribble thus;
but allow me to say, do not be over much cast down;
`'tis the child-like hint of simple child-like love.
It is among the Lord`'s merciful dealings,
that this poor tabernacle has stood the wear and tear of seventy-seven years,
without violent disease, though often shattered and reduced.
Through all,
redeeming love and mercy lifts up a standard against the enemies of the soul,
and my spirits are mostly cheerful.
All the sacrifices made in obedience to gentle requirings,
in the early part of my spiritual warfare of faith, O! they have been abundantly repaid;
yea, seven fold! though it was to the giving up of father, mother and my father`'s house;
with even the man I loved!
I record not this to boast; O! no, but, if it might be so,
I would encourage a rising generation to obey the "`still small voice`" manifested within,
the Word nigh in the heart.

[.signed-section-closing]
Accept my love, affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Seventh month 9th, 1833.

I was gratified with the short visit of my nephew and niece;
their appearance and manners indicating that they are learners in the school of Christ,
the good old way.
O! it comforteth me.
I think I am not quite ignorantly prejudiced against intellectual progress;
but I am jealous lest any should depart from under the yoke and cross of Christ;
for what would then be the final event!
I long for Christian believers, in and out of our own Society,
to be more spiritually minded, bound together in true unity,
and in the peaceable fellowship of the gospel, in the holy Head.
Every sacrifice of self-love and self-will, of the unsanctified part in us,
will have an abundant reward.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend in America.

[.signed-section-context-open]
Birmingham, Seventh month, 1833.

A fresh spring of tenderness and Christian love seems to flow from the fount new and old,
towards the offspring and descendants of those dear well-known kind friends,
thy father and mother,
who were in kindness as nursing parents in my early
entrance into the field of Christian faith,
as in that day many sacrifices were called for, and my mental conflicts were not small.
With reverence let me record the mercies that have followed me hitherto,
and crown my present declining years with a childlike peaceful simplicity.
Go on, dear friends, ye rising generation; mind not the lo! here, or lo! there;
continue humble learners in the school of Christ, the highest, best academy.

Oh, how sweet is the unity of the Spirit of Jesus, in the bond of universal peace,
or love without guile!

[.signed-section-signature]
Mary Capper.

[.signed-section-context-close]
In the 79th year of her pilgrimage.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Tenth month 14th, 1833.

[.salutation]
My partial Friend,

I am not what I was, previous to the late severe attack,
nor do I anticipate full restoration; surely my views rise upward,
I hope not presumptuously, but with entire trust, reverent,
humble confidence in redeeming mercy, in the atoning sacrifice for sin,
whereby the believing heart cries, Abba! my reconciled Father!
Ah! my beloved friends, what is there so consoling?
And it is sweet to love our fellow-pilgrims through this our wilderness journey;
but how far beyond our present feeble conceptions is the view,
that when unclothed of these mortal bodies,
we shall be translated to the kingdom of our Lord Jesus Christ,
and join the church triumphant!

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Lamley, Jr.

[.signed-section-context-open]
Birmingham, Third month 30th, 1834.

[.salutation]
Dear Sarah,

You are all often in my thoughts,
with the recollection of events and of years passed by,
as one of the first interesting "`Quaker`" families, with whom I was familiar.
I have a lively remembrance of early impressions, and my spirit longs, at this day,
for a more prevailing sense of what I then felt;
but dear S. we must be willing to walk by faith and not by sight,
that patience may have her perfect work, I have satisfactory information from Worcester;
dear Candia and Sarah Burlingham submit with Christian
resignation to their loss of a dear sister.
Maria was meek and lowly; a patient, silent sufferer from early years;
the close exceedingly sudden, and so calm as to be almost unperceived.
I was particularly interested in the long confinement of Dr. +++_______+++.
I believe his views of salvation in Jesus were correct;
but O! how a deathbed view, with eternity before us, shows the wood,
hay and stubble which must be consumed by fire--the fiery baptism of the Holy Ghost!

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fourth month 18th, 1834.

I do very tenderly sympathize with your deeply-tried relative,
but there is one unfailing remedy,
viz. resignation to whatever a God of mercy and compassion pleases to lay upon us.
Surely it is unavailing to struggle with ourselves about sins that we cannot blot out.
We should rather bear the condemnation, and sit at the footstool of mercy,
with our mouths in the dust.
O! this entire, this silent resignation; I believe the evil spirit opposes it,
and self-will opposes it, because it proceeds from simple,
pure naked faith in the redeeming power of Jesus, the friend and Saviour of sinners,
who gave his life a ransom for us, to deliver us from sin.
Here the vilest sinner may take refuge, and be safe.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Sarah Grubb.

[.signed-section-context-open]
Birmingham, Fifth month 18th, 1834.

[.salutation]
Dear Friends,

Be not dismayed; the spiritual Head of his own church worketh,
and will work, in a way that human wisdom and foresight knoweth not;
He will bring his own glorious work to pass,
though He leads his faithful servants in a way they know not.
You, dear friends, are again entering the field of Christian warfare;
bear in mind you are one year nearer the end that crowns all,
than you were twelve months gone by.
Let not go the right shield, and the battle axe.
Everlasting mercy and help is on the side of the humble and devoted,
though they have to pass through many tribulations.

As far as condescending favour has led me to discern
the work of Divine Grace in the soul,
the internal evidences of Christ revealed as the true Light, the Life,
the Way to God the Father, O! I dare not enter into doubtful disputation.
Often in the day my prayer is to be kept lowly, simple, dependent as a helpless child.
My old age, now in my eightieth year, is calm, with abundant cause to be content; yea,
very thankful, for innumerable blessings.
I lack no earthly accommodation.

Ye dear labourers who have yet to bear the heat and burden of the day,
surely your rest will be glorious!
This is the view rising before me.

[.signed-section-closing]
Affectionately,

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Grubb to M. Capper.

[.signed-section-context-open]
London, Fifth month 27th, 1834.

[.salutation]
Dear And Precious Friend,

Thy lively communication, received a few days since, has done me good.
How sweet is the sympathy of a mind regulated by the pure
principle of Divine grace placed in our hearts!
Few letters that come to my hand are fraught with so much encouragement as thine;
so genuine is the desire breathed by thy expressions for our preservation every way,
and that the good cause may prosper in, by, and through us; and so evident is it,
that He who was thy morning light is now thy evening song;
as well as that He remains to be like dew which keeps thee fresh and fruitful still.

Yes, thy address to my dear husband and me seems to invite
us forward in the race set before us,
while we often feel far from either swift or strong.
Sometimes I cannot run, only wade through difficulty and much impediment;
yet so far my poor mind can acknowledge that they
who wait upon the Lord renew their strength;
that herein ability is received to mount upward too at seasons,
even with wings as eagles; to run, and not be weary; to walk, and not utterly faint.
The present is a time peculiarly calculated to depress some of our souls; for yet,
within the borders of our religious Society,
we find there is too generally a sliding from that situation in
which Infinite Wisdom and Power placed our early predecessors;
when their light shone as from the hill of the Lord, and men, seeing their good works,
were induced to glorify our Heavenly Father.
Oh! we are indeed sadly mingled as with the crowd,
and it looks as if this might be more the case.

We have heard a great deal of preaching already during this Yearly Meeting,
but really we can select but little that has been like the old sort;
even as an Apostle spoke of the true gospel ministry, when he said,
"`Not with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power.`"

I could say much more in a plaintive strain,
but forbear--let me watch well over my own heart.
Besides there is room, amidst all our occasions of sadness,
to be humbly thankful that the sure foundation is kept to by a living remnant,
and also that a little, yet firm faith is vouchsafed,
that the ancient testimonies of the immutable truth
will continue to be upheld by at least a few,
and the standard raised in its own dignity and simplicity;
for let the great and the learned among us say what they will,
of further light being manifested to them on gospel truths,
than was known in former days, surely,
as there is nothing beyond the meridian brightness of the Gospel,
and that it was long since proved the sons of the morning of our day as a people,
were brought to this, that which has stood the test of ages will stand through all,
being truth and righteousness unfailingly;
and it requires not the torch of human reason to search it out.

I remain, I trust in that which knows no change,

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Sarah Grubb.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James Backhouse, then in Australia.

[.signed-section-context-open]
Birmingham, Fifth month 30th, 1834.

[.salutation]
My valued Friend J. B.,

I have sometimes been privileged to see extracts from thy letters to thy dear relatives, etc.

The Good Shepherd knoweth the right time and place, when and how,
to feed the scattered flock.
He goeth before, and leadeth the blind in a way they knew not, but of his own preparing.

All this, and much more, is well known to thee; I may add to you, dear dedicated servants!
I am personally a stranger to thy companion George W. Walker,
but I feel no separation in the best desires of my heart,
that the universal Father of mankind,
to whom we are reconciled through faith in Jesus Christ, the atonement for sin,
the Saviour of the poor contrite sinner, who has no other hope of salvation,
may continue to bless you.
May He increase our true faith, so that we may avoid all doubts and vain wranglings;
simple obedience seems to me much wanting among religious professors.

It is very gratifying that thou rememberest me in the bond of Christian affection; often,
very often, do I think of thee, especially in my solitary sitting, in my own apartment.
When I call to mind thy report of your favoured retirements,
I seem in some imperfect measure, gathered by the One, eternal Power,
to the same footstool of Mercy where you are so eminently
favoured and comforted,--brought as it were,
into the bosom of your own dear absent friends,--pouring forth the spirit of prayer,
renewing your spiritual confidence, and afresh resigning all!
This is the Lord`'s doing, and He is greatly to be praised.

I cannot but smile, my Christian brother,
when thou designates me "`The ancient friend;`" though it is true
I have lived days and years not a few (fourscore years!),
yet, believe me, I feel myself a very child; having to learn a new lesson every day,
and to be thankful if the evening bring no condemnation for wilful omission,
or any other cause; also that the morning light again arises with renewed mercies.

My health, though never robust, is sufficient for the exertions required;
my spirits cheerful; all my wants supplied, and crowned with calm content.
What can a Christian, drawing to the close of time, desire more; save to press forward,
to the mark for the prize at the end of the race!
Accept the simple, sincere love of

[.signed-section-signature]
Mary Capper.

[.signed-section-context-close]
In Old England; loved, though not faultless.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To M. S.

[.signed-section-context-open]
Birmingham, Sixth month 22nd, 1834.

Thy affectionate partiality will peruse what is now sent with indulgence.
I have not made any particular remark respecting joining the Society unto
which I at this day consider it an unspeakable favour to be united.
The religious principles professed by us, in their purity,
as set forth in the Scriptures, which testify of Jesus, born of a virgin, as foretold,
to bruise the head of the serpent, yea, manifested in the flesh,
and dying to redeem the fallen race of Adam,
and to cast up a new and holy way of access to God
the Father--these principles have been,
and are still from time to time, so far opened to my spiritual understanding,
that my heart is at rest.
As to the result of what conviction has wrought in my life and manners,
since united in your favoured fellowship, my familiar friends must testify.
I can only add,
that I am bound in gratitude to acknowledge the gentle
hand of Mercy that has guided me hitherto,
and joined me in strong affection to the Society,
and satisfied my seeking mind as to the genuine gospel principles of salvation.

[.signed-section-signature]
Mary Capper.

--

+++[+++It is probably the following series of reflections
to which Mary Capper alludes in the foregoing letter;
as they bear date about this time.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Birmingham, Sixth month, 1834.

After a considerable lapse of time, now in the eightieth year of my age,
yet a sojourner and a pilgrim,
pressing forward as not having attained all that my soul longeth after,
I have this testimony to bear.
Being lively, active and volatile in my early years,
I account it not one of the least of many mercies that my natural frame was feeble,
and that sometimes I was much reduced by sickness.
At these seasons, O! marvellous mercy!
I was favoured with much tenderness of spirit, and shed secret, soothing, precious tears,
in an indescribable sense that God was very good, and that He saw me;
and I think I did breathe the prayer that I might not be left to my own guidance.

When sin and sinfulness were set before me, in the times of my folly,
and I felt not the sweet, gentle balm of our Heavenly Father`'s favour,
I did inwardly mourn, and did ignorantly, if not sinfully,
wish that I had never been born.
For many years, under a variety of outward changes or events, the secret,
progressive work (may I not say,
the genuine power of pure religion) was preparing the way
for clearer views respecting the soul`'s salvation.
In these babe-like days,
whatever I found to obstruct daily prayer--lowly supplication at the throne of mercy,
seemed in my view sinful, and must be overcome.
Verily I have found it, and I do still find it, a wrestling warfare!
The new birth is a marvellous work; a complete spiritual creation, with all things new,
is not wrought by the reasoning powers of the natural man.
God the Father reveals the Son in us, as the Light, the Life and the Way;
and gives us power to believe in Him also as the atoning sacrifice for sin,
whereby we have access to a reconciled God and universal Father.
This spiritual view of salvation, as set forth in the Scriptures,
and abundantly testified by the faithful of former generations,--this atoning Sacrifice,
this Way of redemption, (begun,
carried on and perfected for me and in me,) is the rock and ground of my Christian faith,
and of my hope of acceptance, when this mortal shall put on immortality.

My simple, yet reverent testimony is to the marvellous love of God, in Christ Jesus,
as the guide of youth, and the staff of lengthened years,
to those who acknowledge Him in all their ways.
My heart rests in the belief that these will not be left to perish through ignorance.
Obedience is the test of our sincerity.
Acknowledge God in all thy ways, and He will direct thy steps aright,
from youth to old age.

[.signed-section-signature]
Mary Capper.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Katharine Backhouse

[.signed-section-context-open]
Birmingham, Eighth month 27th, 1834.

[.salutation]
My much loved Niece and Relatives.

Shall I meet you with this letter,
in the favoured shades of a father`'s planting! as I have understood that
your annual retreat is among tress cultivated by a parent`'s hand.
Whether this may reach you there or not, something alive within me,
better than naughty self, seems as it were to unite with your contrited spirits.
The Saviour`'s gentle, sweet, marvellously kind,
and feeling language of invitation to his faithful followers, presents,
as so beautifully applicable, encouraging and consoling, that I think I must refer to it,
namely, "`Come ye yourselves apart into a desert place, and rest awhile!`"
I can hardly forbear to copy a few lines from a beautiful comment on these words;

[verse]
____
Gladly we catch the tender sound,
Which bids us come and rest awhile;
Come, breathe with me the desert air!
Come, breathe to God the secret prayer!
We come! we come!--the harassed soul
Longs to escape this war of words,
The clouds of care which round us roll,
And rest with thee, thou Lord of lords!
And once again, the bark refit.
Ere we the quiet haven quit!
____

My own "`dear little home,`" as thou so justly termest it,
is a prepared place of rest for me.
No human contrivance or foresight could have so provided for my ease and accommodation;
no anxious cares, no daily solicitudes, which press with even lawful weight,
in many situations; and what shall I say?
reverence and humbling contrition clothe my spirit.
Language would fail me to tell of the lowly calm,
wherein my thoughts are fixed on the mercy which
has followed me from my childhood to this day.
In my lowest estate I have the anchor of hope, and dare not cherish unbelief,
nor unprofitably dwell on things too high for my present comprehension.
Even my very weakness proves an exercise of faith and patience.
These things I write, not so much for your instruction,
as to signify that we are fellow-contenders for the
end of our faith--the salvation of our souls.

I mark thy observation on the too frequent and familiar
mention of the name of the blessed Saviour,
both in public and private.
Through faith in this name, my belief is that we shall be saved;
but the solemn admonition sometimes rises before me,
"`Let every one that nameth the name of Christ depart from iniquity.`"
O! I long to depart from all iniquity;
this is a marvellous work of the Lord`'s beginning, carrying on, and perfecting.

[.signed-section-signature]
Mary Capper.

--
