== Chapter XIV.

Extracts from, her last letters,
and from some of those of her friends respecting her.--Last illness.--Death.

To J. and Katharine Backhouse

Birlingham, First month 21st, 1839.

My very dear Relatives,

From day to day I think of your kindness toward me,
and my spirit is bowed before the Source from whence
all our reciprocal Christian good-will must flow.
Something like a glance of a precious future union seems to enliven the present moment,
as I pen this, though my body and mind are in a weak state;
but I think it is ungrateful to intrude my infirmities on your tender sympathy; rather,
with reverence, may I acknowledge a sustaining Power,
that keeps the spirit of prayer alive through all.
There is much to humble us, and to mourn over;
yet there is encouragement for the faithful.
Press forward!

To T. and M. S.

Dale End, Third month 6th, 1839.

My very kind Friends,

I cannot rest satisfied without attempting some acknowledgment
of my grateful acceptance of a gift,
so instructively interesting as the life of your truly valuable relative Thomas Shillitoe,
with whom I was favoured to be somewhat familiarly acquainted,
in the early days of my attachment to a religious Society, unto which,
after upwards of fifty years experience, I am still conscientiously bound;
not as having attained, but as earnestly pressing after the mark,
for the prize of our high calling.
I am well aware that consistency with our profession leads to much self-humiliation,
and may emphatically be designated the strait and narrow way;
but my faith encourages me to believe that it will be crowned with enduring peace,
when the redeemed spirit shall enter that undefiled
rest which is prepared for the prepared soul.

Accept, dear friends, my affectionate goodwill,
with my best desires for your present and eternal blessedness,
in the path of obedience to the sanctifying power of a Saviour.
With a very grateful sense of your liberality towards me, I subscribe, Mary Capper.

To Katharine Backhouse

Birmingham, Tenth month 4th, 1839.

I have just parted with my endeared niece.
I cherish the hope that we have been favoured to encourage each other,
in our desire to be submissive learners in the school of the Redeemer,
and to possess an increase of that availing faith
which is the root of holiness in all its branches,
working by love, to the purifying of the heart.
I hope I do not presumptuously express my thoughts on this important subject,
or on that of prayer.
I have pondered it much, and this morning it has opened in my view,
that to manifest by consistency of conduct, that we live in the spirit of prayer,
may have an influence on those around us, which we are not conscious of,
though our family and connections may not see us on our knees,
nor witness our supplications in secret, when the door being shut, we bow low,
at the feet of the Redeemer.

With regard to thy last communication, I have thought,
when manifested duties succeed each other,
how unspeakably great is the mercy that gives the willing mind in the day of power!
In this the subjugated heart has nothing to boast, but may persevere, in lowly obedience,
whether secret conflict be the allotted portion, or a chastened joy be permitted,
in the promotion of the Gospel of peace and salvation.
I am daily conscious of diminishing powers, but continue to wrestle for patience;
and in unison with, or in answer to, the desires and prayers of my endeared relations,
I experience the Comforter to be my help and my shield.

Mary Capper.

To C. B. C.

Eleventh month 3rd, 1839.

My very dear Friend,

There is a little, all-important word of four letters,
that when stamped on the tablet of the heart, is not easily effaced.
This is love.
This sweet token of union I believe we do gratefully
accept and cherish as a precious boon,
from the Author of all pure fellowship,
I am aware of divers obstacles to our personal intercourse, and I consider,
with much tender feeling, thy domestic occupations,
which claim the sacrifice of some gratifications;
but the place of duty is the place of safety, and will be blessed; so, my dear friend,
we must not disturb ourselves, but rather be thankful.
In much affection,

Mary Capper.

To Katharine Backhouse

Birmingham, Twelfth month 10th, 1839.

My very dear Niece,

Thy letters bring a grateful sweetness with them;
it would be gratifying could I diffuse the same; but length of days, with natural decay,
now claims a continuance of that affection which
can yet discern a little life in the root.
I think we may cherish the belief that a good work
is begun in the heart of our dear kinsman;
and I do believe there is also a willingness wrought by the same Power,
that redeeming love and mercy may perfect the will of our Heavenly Father.
As fellow-probationers, we have learned, in some measure, to sympathize with,
and it may be in favoured seasons, to pray for one another;
knowing that there are many lively enemies, seeking to mar the good work;
many a strong hold to be pulled down, and many a dark and cloudy day,
ere we obtain the blessing in store for those who hold out to the end.

My dear brother George`'s greeting, in my own apartment, was almost overwhelming,
as I had no previous information of his visit;
but we were soon affectionately clasped in each other`'s arms.
I hope he is seriously disposed to look beyond the present scene.
He visited the receptacle of the dead, where the bodies of our parents,
etc. are deposited in a vault;
but I have no desire that my poor body should be laid there.
My soul rather aspires to be fitted to join the ransomed of the Lord in heaven.

I apprehend that B. S.`'s labours among us are drawing to a conclusion;
we have much bestowed upon us, in instruction, reproof, warning and encouragement.
I am afraid of taking up a rest in consolations,
as suffering seems the allotment of the present day;
and I do petition for patient submission to whatever may be brought upon me,
either by the conscious increase of mental and bodily weakness,
or in a measure of Christian sympathy with my fellow travellers Zionward.

Mary Capper.

To the Same.

Birmingham, First month 18th, 1840.

My affectionately kind Niece,

I do desire gratefully to acknowledge the mercy that
produces so much interest in what concerns my welfare.
It is marvellous in my view; and in my present weak estate,
I cleave to the Power that thus condescends to uphold me,
and to spread the feeling of sympathy far and wide
My bodily frame is in a very debilitated state;
but when the cheering sun-beams break through the mist, I almost long to be in the air,
and again to be privileged to meet my fellow-Christian professors,
and unite in waiting upon the Lord.

Mary Capper.

+++[+++Mary Capper did not again rise much out of the state of feebleness which she here describes;
but she continued to enjoy, during the remaining years of her protracted life,
a comfortable degree of health, and was capable, to the last,
of enjoying the Society of her friends,
to whom she ever continued to be affectionately attached.
Some of her relations, who visited her in the spring of 1840,
among whom was the editor of this volume,
found her in a strikingly happy and holy state of mind,--a
state which seems best described by the word,
heavenly.
She retained the power of epistolary correspondence for some time after this period,
and continued to manifest her interest in the welfare of others,
as the following extracts from her letters will testify.
She thus addressed her niece Katharine Backhouse during the yearly meeting:]

Birmingham.
Fifth month 22nd, 1840.

My endeared Niece,

My thoughts, with some of the best desires that I am favoured to feel in my solitude,
seem to bring into mental view, the dear dedicated Friends, now sitting together;
in reverence and lowliness of mind, waiting for a renewal of strength to press on,
toward the unpolluted rest, prepared for the redeemed, sanctified soul;
patience having her perfect work.
Though my present ability is small, it is gratifying to myself, even thus imperfectly,
to greet thee by the way.
I hear thy dear brother is liberated to return home
after his arduous engagement in the environs of London.
I think it a privilege to feel tender sympathy with such labourers.

To the Same.

Birmingham, Eleventh month 28th. 1840.

My affectionate Niece,

In reply to thy kind inquiries, my general health is better than it was,
and I am favoured to have some relish for my food, and ability for calm repose,
when I retire to my comfortable bed; favours indeed reverently to be acknowledged!
Yet I mourn the low estate of my mental and spiritual powers,
and I long to be more patient and resigned, trusting in the Rock of my salvation.

I take my little rambles must days, though we have fogs and rain.
I am not so painfully sensible of the state of the atmosphere as some afflicted individuals,
who find great difficulty in breathing.
O! what tender dealings towards me, a poor helpless creature.

To the Same.

Birmingham, First month 9th, 1841.

My beloved Niece,

Mercy sees fit to add another opening year to my long life.
O! may the refining process go on, to perfect that which is still wanting.
I crept out to meeting on first-day morning,
and was not so faithful as I possibly ought to have been; not from actual unwillingness,
but from very weakness; but with gratitude may I express it,
enduring Goodness clothed my spirit with a lowly calm.
What condescending tenderness and compassion!

To the Same.

Birmingham, Seventh month 20th, 1841.

My dear Niece and Relations,

I would convey as impressively as I can, my affectionate thoughts toward you,
in this time of anticipating a personal separation, mutually and deeply felt,
though under circumstances the most favourable,
sanctioned by deliberate consideration and prayer.
I trust it is a movement under Divine direction.
In this belief, may sweet peace clothe your spirits, and enduring Mercy crown all!
This, in my enfeebled state, is the secret breathing of my soul for you.
I feel an affectionate interest in your dear daughter`'s present and future prospects;
with the consoling belief that He who has been her
help and shield will continue so to be.

To the Same.

Birmingham, Ninth month 14th, 1841.

My beloved Niece,

The affecting intelligence of my dear nephew`'s sudden illness is deeply impressive,
though thy few lines are relieving.
O! what a crown, on all the blessings and favours received, is it,
when in the hour of deep affliction, every murmuring thought is subdued,
and the accuser rebuked.

I think of you, my endeared relatives, as under the humbling hand of sorrow;
and I endeavour to cherish the sustaining hope that thus the good
Shepherd of the sheep is extending the crook of his love,
to gather, and to prepare the immortal spirit for a place in the heavenly kingdom,
to be forever with the Lord.

With sincere affection, I subscribe,

Mary Capper.

From James Backhouse to J. and Katharine Backhouse

York, Second month 18th, 1842

My dear Cousins,

I do not recollect, that in my last, I mentioned your aged relative Mary Capper,
who appeared to me much enfeebled.
She spoke of the approach of her end,
as feeling an earnest desire to depart and be with her Saviour,
but said that she could nevertheless say, "`Not my will,
but Thine be done,`" and that she had many comforts to be thankful for,
of the least of which she was unworthy.
She feelingly expressed her sense of helplessness, and of dependence on Divine support;
and her heart seemed overflowing with love to her friends.
She is an encouraging example of the power of religion in old age;
and while her heart expands in Christian love towards all,
she retains a clear and strong attachment to those views, or rather,
I might more properly say,
to those experiences of Christianity to which true Friends through faith have attained.
I thought this little notice of your honourable relation was due to you;
and should I see her no more, to her memory.

Your affectionate cousin,

James Backhouse.

On a subsequent occasion, James Backhouse, in writing of a call made on Mary Capper,
soon after his return from his labours abroad, makes the following observations:]

"`In the course of conversation, she informed me,
that she had adopted the principles of total abstinence as regards intoxicating liquors;
that, though on the first mention of the subject, she had doubted its propriety,
yet on reflecting upon it, and considering the numbers led away into inebriety,
and that all these began their course of drunkenness by taking
intoxicating liquors in what had been thought to be moderation,
she came to the resolution,
that no one should be able to plead her example for taking them at all.
At the time she left them off, she was upwards of eighty years of age,
and in the practice of taking a single glass of wine daily with her dinner;
and having been for many years unable to take animal food,
this glass of wine had been thought almost essential to her existence,
especially as she had been accustomed to it from an early period of her life.
She told me that she expected to have something to suffer, in making this change,
and that she might probably have to endure a greater
sense of feebleness during the remainder of her days;
but the welfare of those by whom she was surrounded,
and on whom her example might have some influence,
she considered to be of much greater importance.
On making the trial, she was however agreeably disappointed;
for though she felt some languor for a few days,
she soon became sensible of an increase of strength,
and was more vigorous without the wine than she had been with it;
so that she had cause to commemorate the goodness by which
she had been enabled to make this little sacrifice.
And I believe that her example in this respect,
as well as her Christian practice exhibited in a great variety of other points,
had a beneficial influence on many.

+++[+++Mary Capper, about this time, began to feel almost unequal to use her pen,
in order to cheer and animate her friends to persevere in their Christian race;
so that while her interest in the best welfare of all continued unabated,
she could no longer testify it by her lively epistles.
The following is believed to be one of the last that she was able to write;
it was addressed:

To her Niece Katharine Backhouse

Birmingham, Ninth month 16th, 1842.

My beloved Niece,

Gratitude constrains me again to attempt to acknowledge
the welcome reception of thy encouraging communication.
It is an unspeakable favour that a time of rest is granted.
My bodily health is measurably restored,
yet increasing infirmities keep me much confined, though I do creep out a little,
but have not, of late, ventured to attend our meetings for worship,
which is a real trial; though I know I am not alone in trial, as you, my dear relations,
can testify, in your deep sorrows.
Your affectionate aunt,

Mary Capper.

+++[+++From this time to the end of her days, she was most affectionately cared for,
as she had long been, by the family of Richard Cadbury,
to all of whom she was strongly attached, and who, in her enfeebled state,
added to their former kindnesses, that of keeping her relations informed of her health, etc.
A few extracts from these letters and from those of some
other friends who visited her in her declining days,
will give a better idea of the manner in which the remainder of her life glided away,
than any other outline could do, and will doubtless be acceptable to the reader,
who may have, thus far, traced her steps.]

From E. Cadbury to Katharine Backhouse

Edgbaston, Fourth month 20th, 1843.

I have Still to give thee as favourable an account of thy dear aunt,
as at her time of life, can be expected.
Last week was our monthly meeting, the whole of which she sat,
and seemed less fatigued than some of her younger sisters.
She felt a lively interest in the answers to the queries,
and spoke feelingly upon several subjects.

Thy letter deeply interested her, respecting the proceedings of some dear friends;
she truly rejoices in the enlargement of Zion`'s borders,
and in the prosperity of her helpers.

From R. F. to Katharine Backhouse

York, Eighth month 9th. 1843.

My dear Cousin,

We called upon thy dear aunt, who appeared feeble, but in comfortable health;
and what gratified us most, was the sweetness and liveliness of her spirit.
Her mind seemed clothed with love to all,
and I thought I had seldom seen a more encouraging
or animating example of a peaceful old age.
She said that she felt herself to he a poor unworthy creature,
and often wondered how it was that she was so mercifully dealt with and cared for;
that she was endeavouring patiently to wait her appointed time; and that,
when her Master called, she thought she should thankfully receive the summons.
It was an interview that we shall long remember.

E+++.+++ Cadbury to Katharine Backhouse

Edgbaston, Second month 5th, 1844.

My dear Cousin,--Thy dear aunt was at meeting yesterday morning, also on fourth-day,
when she particularly wished to sit with those who
had not gone to our quarterly meeting at Coventry;
her company was very acceptable, and she expressed a few words,
full of love to her Heavenly Father, and to all the human family.
She is often favoured with ability to say a little to the dear children,
of whom we have a large number in this place;
and her affectionate kindness to them is such,
that I think there is scarcely a child but will remember her as long as they live.
As she was about to leave my son`'s yesterday,
the three little ones followed her for the parting kiss, pulling her gown,
as described by Goldsmith, "`To share the good man`'s smile.`"
Her servant continues as attentive as ever, and I believe she has every comfort.

+++[+++Mary Capper continued much in the same state during the remaining months of the year,
and bore the winter`'s cold quite as well as her friends had anticipated,
as she was now in her ninetieth year.
In the fifth month, 1845, she had a troublesome cough, yet she continued to get out,
and was able to attend meetings,
in which she sometimes addressed her friends in encouraging language; and on first-day,
the 18th, she especially noticed the dear children in her ministry.
The next day her medical attendant requested that she would remain in bed,
with which she reluctantly complied.
In deed, so unconscious was she of the extent of her own feebleness,
that on the 21st she wished to be allowed to rise and to go to meeting,
that she might sit with the few who were gathered,
many being absent at the yearly meeting.
On the 22nd, fever increased, and her breathing became much affected,
so as to alarm the kind friends who surrounded her; but, as one of them remarks,
"`She seemed peculiarly peaceful, and full of love and gratitude.
The exclamation, '`Goodness, mercy and power!`' was frequently on her lips.
In the evening she took leave of the person under whose roof she resided,
evidently under the idea that it might be a last farewell,
expressing her desire that a blessing might attend the family for their kindness.`"

Previous to settling for the night,
she requested her faithful attendant to read in the Scriptures to her, as usual.
The 14th chapter of John came in course, which was very congenial to her feelings,
and she said that she could not have heard a more beautiful chapter, exclaiming,
'`O! how beautiful! to go to a mansion prepared for us!`' and afterwards
she appeared to be fervently engaged in silent prayer.
She then spoke of her unworthiness; that she had no merit of her own,
but that it was all of the Lord`'s mercy.

During the night she was much engaged in prayer,
and the words '`O! Father!`' often escaped her lips.
She remarked to her servant, that she would be rewarded,
for her affectionate kindness to her, both here and in heaven.

About eight o`'clock in the morning of the 23rd, she proposed having her knitting,
and endeavoured to put on her spectacles,
but the powers of the frail tabernacle were failing,
and she speedily and gently passed away; to enter, as we reverently believe,
into that mansion prepared for her by the Saviour; where,
clothed in the spotless robe of his righteousness,
we humbly trust she is uttering the anthem of praise.

To her last moments, love was the covering of her spirit,
and she continued to recognize her friends, and to manifest it to them.
A feeling of great solemnity was over those who were privileged to be
present at the close of the life of this devoted servant of the Lord,
which took place about eleven o`'clock in the forenoon.
Having done her day`'s work in the day time,
she was ready to accept the gracious invitation, and to enter into the joy of her Lord.

Several of the poor to whom she had long been kind,
desired to be allowed to visit the remains; and one of her great nephews,
who was on the spot, and who had long been an attentive and kind helper to her, remarks,
that the feeling shewn by these poor neighbours proved
that she had been a Dorcas among them.

The interment took place on the 1st of the sixth month, 1845,
and was a very solemn and instructive time.

In reviewing the long life of this dear friend,
the mind is powerfully impressed with the truth of the Scripture declaration,
"`Him that honoureth me I will honour;`" for how
do we see it verified in every stage of her life!
She sought to honour her Lord in all things,
and He dignified her with his gifts and graces,
and enabled her to glorify Him while on earth; preparing her,
through his redeeming love and mercy to celebrate his praise forever in Heaven.]
