== A Testimony of Warwickshire North monthly meeting, concerning Mary Capper, deceased.

Our late dear and valued friend Mary Capper was born in 1755, at Rugely, Staffordshire,
In a letter written to a relation in 1835,
from which most of the subsequent extracts have been taken,
she commemorates the Divine grace by which she was
preserved throughout the course of a long life,
in the following language:
"`In the present day it seems as if all was swallowed up in mercy,
and in the marvellous watchful care which kept me in the
days of my ignorance from wandering far in the broad way,
and has brought me hitherto, through a wilderness of pits and snares, and above all,
has settled my heart in a calm, peaceful, lowly state,
no more tossed with floating opinions, but watching, waiting,
and praying yet to be perfected and fitted for the kingdom of Heaven.`"
Her parents were members of the national establishment,
and brought her up in the strict observance of its rites and ceremonies:
she says "`My dear and valued parents accustomed their children to read the Scriptures,
my beloved mother especially, to whom I often read,
and asked questions relative to some passages when I was about eight or ten years old.`"
Whilst quite young she spent a considerable time at Macclesfield,
under the care of an aunt,
where she was allowed to accompany her young companions to the theatre,
and other places of amusement,
nor was she at that time sensible of the evil tendency of such practices.
The first impression of a contrary nature distinctly remembered,
appears to have been during a residence at Birmingham,
which she says "`was whilst on my knees at my accustomed evening prayers:
my thoughts being confused and dissipated, I lay down comfortless,
believing that whatever distracted or hindered prayer must be wrong;
this impression rested with me,
and from time to time led to deep reflection and secret conflict;
the witness for truth left me not, and as little sacrifices,
such as declining gay parties, seemed to yield a peaceful calm,
I was favoured with resolution to persevere.`"
She also says, "`I was at times, and many times, in earlier life,
very thoughtful as to the genuine effect of religion on the mind;
my constitution was weak,
which I have considered a favour (amongst others,) as my nature was volatile,
and I was much left as to outward restraints.`"
She gradually became increasingly serious,
but for several years made little alteration in her manners or personal appearance.

In 1776 she went to France, on account of the precarious state of her health,
and that she might be qualified by education to obtain for herself, if needful,
a respectable maintenance.
Whilst there she was much exposed to dissipating company,
but appears to have been remarkably preserved:
soon after her return an obvious change took place in her religious views,
and she remarks:
"`In process of time I could not conform to what
I had been taught as being necessary to salvation;
I kept much retired without attending any place of worship, or having a view to any,
although I think I had been at a Friends`' meeting for worship at Birmingham,
but do not call to mind any particular impression, saving a tenderness of spirit,
I think to tears.`"
It appeal`'s, however, from a manuscript journal kept by our dear friend,
that whilst making a short stay in London on her way to France,
she was introduced to several members of our Society,
from whom she received considerable information relative to our principles,
and in whose company she attended a meeting for worship in Gracechurch-street.
She resided for some time with her brother,
who was a minister of the Episcopal establishment: whilst under his roof,
she was brought into very close exercise of mind
respecting taking what is termed the sacrament,
which she says "`was administered by my brother with much solemnity;`" but she adds,
"`The best of teachers was pleased to calm and quiet my mind on a subject so important,
that I no more repeated the ceremony.`"

About the year 1784 she went to reside with one of her brothers in London,
and became a regular attender of our religious meetings.
She says, "`On my decidedly going to Friends`' meetings, my dear father,
no doubt in faithfulness to his own religious views,
and the desire to rescue a poor child from apprehended error,
desired not my return to the parental roof,
unless I could be satisfied with the religious education he had conscientiously given me;
this, with a tender heart-piercing remonstrance from my dear mother,
was far more deeply felt than I can describe, and marvellous in my view,
even to this day, was the settled, firm belief,
that I must follow on to know the soul`'s salvation for myself, truly in a way,
that I knew not.`"

Mary Capper was settled within the compass of Peel monthly meeting,
and was admitted into membership by that meeting about the year 1788.
Whilst residing in London she believed herself called
upon to express a few words in our meetings for worship,
which she thus describes.
"`I have no distinct recollection as to any serious
thoughts of speaking in a religious meeting;
it sometimes arose in my view,
that possibly I might have to tell unto others how I had
been taught and kept from the broad way of destruction,
but a few words arising in my mind with something of unusual power,
I think at the Peel meeting, I stood up and spoke them, and was very quiet,
nor did I anticipate or foresee that such a thing might ever be again,
and thus was I led on from time to time, not knowing but each time might be the last.`"

Our dear friend removed to Birmingham in 1789,
and in 1794 she was recommended to the meeting of ministers and elders;
in reference to which she remarks,
"`I know not that I ever questioned the propriety of such a step, yet really so simple,
so like a childlike learner to this day, I know not that I can claim the awful,
important character of a gospel minister.`"
Her travels in the work of the ministry were a good deal
confined to her own and the neighbouring quarterly meetings;
in many of her religious visits she united with her friend, Mary Beesley, of Worcester.

In addition to several journeys nearer home, they visited in 1798,
Friends of Bristol and Somersetshire,
and in 1800 they united in a visit to the meetings and families of Friends in Oxfordshire.
In 1803 she was liberated to unite with the same friend, then Mary Lewis,
in a visit to Hampshire, Somersetshire, and Devonshire.

In 1811 Mary Capper removed to Leominster,
and was recommended from thence back to Birmingham in 1816,
where she resided until her death.
In 1823 she was liberated for service in and about London,
and in 1826 she visited the meetings and families of Friends in Derbyshire,
Nottinghamshire, and part of Leicestershire,
which appears to have been her last engagement of this nature away from home.

Her ministry was sound and of a spiritual character;
having herself largely partaken of the conflict between flesh and spirit,
she was often concerned to encourage the sincere-hearted
patiently to submit to these proving seasons,
looking for effectual help to the light and power of our Lord Jesus Christ,
and frequently whilst suffering from a sense of the low state of things amongst us,
as a religious Society,
she looked forward with encouragement and hope towards a brighter period.
She was accustomed, both in her ministry and in conversation,
to express the great objection she felt to a disputatious spirit,
particularly when exercised in matters relating to doctrine,
recommending her young friends, who were anxiously inquiring after truth,
to wait for the unfoldings of Divine light,
which in due time would make known all that was needful for their salvation,
if they were faithful to that which was already manifested to them;
and stating her belief that such would never be suffered to perish for lack of knowledge.

Our dear friend was very exemplary in the attendance
of our meetings for worship and discipline,
even in the latter part of her life, when her bodily powers were much weakened.
She felt a lively interest in the spiritual and temporal welfare of her friends,
was ever ready to afford advice or assistance to those who stood in need of it,
and with very limited means was an example of contentment, and liberality to the poor.
Her correspondence, until within a few years of her death, was extensive,
and many of her letters were addressed to those who were in affliction,
or who she thought in some way needed her affectionate remembrance or sympathy;
and for usefulness in this way she appeared peculiarly qualified.

The natural cheerfulness of her disposition, and her uniform kindness and courtesy,
endeared her to all who were acquainted with her,
and rendered her society both pleasant and instructive.
She was firmly attached to the principles of our religious Society,
believing them to be in full accordance with the New Testament,
but largely cherished Christian love and charity
to all those who conscientiously differed from her.
In a letter written to a friend in the eightieth year of her age, she says,
"`I am bound in gratitude to acknowledge the gentle
hand of mercy which has guided me hitherto,
and joined me in strong affection to the Society,
and satisfied my seeking mind as to the genuine gospel principles of salvation.`"
In a memorandum made about the same time,
after referring to the earlier part of her Christian experience, she proceeds:
"`The sinfulness of sin in all its subtleties is not discovered all at once,
neither is the efficacy of Divine grace manifested in its fulness, but as we can bear it,
obedience keeping pace in deep abasement and humiliation with the
Spirit revealed,--God the Father revealing the Son in us,
the Light, the Life, the Way, wherein we come to a view, though yet faint and imperfect,
of the atoning sacrifice for sin,
with the new and living way cast up for the redeemed to walk in,
and whereby we have access to a reconciled God and universal Father.
My simple, yet reverent testimony is to the love, the marvellous love of God,
as the guide of our youth, and the staff of lengthened years,
to those who acknowledge Him in all their ways.`"

Our dear friend was at meeting on the morning of the first-day previous to her decease,
and was enabled to address her friends in encouraging language,
and spoke particularly to the dear children.
The day following she was so unwell that it was thought
desirable to send for her medical attendant,
and on fourth-day morning,
being hardly aware that her weakness rendered it impracticable,
she wished to be dressed that she might go to meeting,
remarking that many friends were absent attending the yearly meeting,
and she wished to assemble with those who remained.
To a friend who called upon her after meeting she said,
she hoped she should not be cast off in her old age; the friend replied,
she believed she would not, that she had done her work in the day.
"`Ah!`" she remarked, addressing herself to those about her,
"`You will feel a comfort in such a day as this,
that you have been engaged in His service.`"

On fifth-day she became much worse, several friends called to see her,
with whom she conversed very cheerfully,
and although she did not appear aware that she should see them no more,
she parted from them very affectionately.
Previous to settling for the night, she said to her attendant,
"`I think thou hast not read to me in the Bible today,`"
and expressed a wish to hear a portion of it;
the chapter in course was the 14th of John,
beginning "`Let not your heart be troubled,`" which seemed very consoling to her;
as the reading proceeded she responded to it, and spoke of the boundless goodness, mercy,
and power of God, saying, "`How beautiful to go to a mansion ready prepared for us,
and if such should be my happy experience it will indeed be all of mercy,
unmerited mercy.`"
She appeared to be much engaged in prayer during the night.
In the morning her bodily powers were evidently fast failing;
after this she spoke but little,
and about eleven o`'clock in the forenoon her purified spirit gently passed away,
exchanging, we doubt not,
through the mercy and mediation of our Lord and Saviour Jesus Christ,
an earthly for a heavenly habitation.

She died on the 23rd of the fifth month, 1845, in the ninety-first year of her age,
a minister about fifty-five years.
